// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package fts5secure5

import (
"github.com/pijalu/frigolite"
"github.com/pijalu/frigolite/internal/vtab"
"os"
"strconv"
"testing"
)

func Test_fts5secure5(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	var _r string
	var _berr error
	_ = _berr // suppress unused warning
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	_ = _r   // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testprefix string
	_ = testprefix // pre-declared from TCL source
	var i string
	_ = i // pre-declared from TCL source

	// return_if_no_fts5 (unsupported command, not transpiled)
	vtab.TclVarSet("testprefix", "", "fts5secure5")
	testprefix = "fts5secure5" // TCL namespace variable
	_ = testprefix // suppress unused warning
	// return_if_no_fts5 (unsupported command, not transpiled)
	// proc definition (not transpiled)
	{ // "1.0"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE ft1 USING fts5(a, detail=none);\n  INSERT INTO ft1(ft1, rank) VALUES('secure-delete', 1);\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft1 USING fts5(a, detail=none);\n  INSERT INTO ft1(ft1, rank) VALUES('secure-delete', 1);\n")
		}
	}
	{ // "1.1"
		_res = db.Exec("\n  BEGIN;\n    INSERT INTO ft1(rowid, a) VALUES(1, 'abcd');\n    INSERT INTO ft1(rowid, a) VALUES(2, 'abcd');\n    INSERT INTO ft1(rowid, a) VALUES(3, 'abcd');\n  COMMIT;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  BEGIN;\n    INSERT INTO ft1(rowid, a) VALUES(1, 'abcd');\n    INSERT INTO ft1(rowid, a) VALUES(2, 'abcd');\n    INSERT INTO ft1(rowid, a) VALUES(3, 'abcd');\n  COMMIT;\n")
		}
	}
	{ // "1.2"
		_res = db.Exec("\n  DELETE FROM ft1 WHERE rowid=1;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  DELETE FROM ft1 WHERE rowid=1;\n")
		}
	}
	{ // "1.3"
		_res = db.Exec("\n  INSERT INTO ft1(ft1) VALUES('integrity-check');\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  INSERT INTO ft1(ft1) VALUES('integrity-check');\n")
		}
	}
	{ // "1.4"
		_res = db.Exec("\n  DELETE FROM ft1 WHERE rowid=3;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  DELETE FROM ft1 WHERE rowid=3;\n")
		}
	}
	{ // "1.5"
		_res = db.Exec("\n  INSERT INTO ft1(ft1) VALUES('integrity-check');\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  INSERT INTO ft1(ft1) VALUES('integrity-check');\n")
		}
	}
	{ // "1.6"
		_res = db.Exec("\n  DELETE FROM ft1 WHERE rowid=3;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  DELETE FROM ft1 WHERE rowid=3;\n")
		}
	}
	{ // "1.7"
		_res = db.Exec("\n  INSERT INTO ft1(ft1) VALUES('integrity-check');\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  INSERT INTO ft1(ft1) VALUES('integrity-check');\n")
		}
	}
	db.Close()
	os.Remove("test.db")
	os.Remove("test.db-journal")
	os.Remove("test.db-wal")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	tcl_nullvalue = "{}" // fresh connection resets nullvalue
	{ // "2.0"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE ft1 USING fts5(a, detail=none);\n  INSERT INTO ft1(ft1, rank) VALUES('secure-delete', 1);\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft1 USING fts5(a, detail=none);\n  INSERT INTO ft1(ft1, rank) VALUES('secure-delete', 1);\n")
		}
	}
	{ // "2.1"
		_res = db.Exec("\n  BEGIN;\n    INSERT INTO ft1(rowid, a) VALUES(1, 'abcd one');\n    INSERT INTO ft1(rowid, a) VALUES(2, 'abcd two');\n    INSERT INTO ft1(rowid, a) VALUES(3, 'abcd two');\n    INSERT INTO ft1(rowid, a) VALUES(4, 'abcd two');\n    INSERT INTO ft1(rowid, a) VALUES(5, 'abcd three');\n  COMMIT;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  BEGIN;\n    INSERT INTO ft1(rowid, a) VALUES(1, 'abcd one');\n    INSERT INTO ft1(rowid, a) VALUES(2, 'abcd two');\n    INSERT INTO ft1(rowid, a) VALUES(3, 'abcd two');\n    INSERT INTO ft1(rowid, a) VALUES(4, 'abcd two');\n    INSERT INTO ft1(rowid, a) VALUES(5, 'abcd three');\n  COMMIT;\n")
		}
	}
	{ // "2.2a"
		_res = db.Exec("\n  DELETE FROM ft1 WHERE rowid=3;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  DELETE FROM ft1 WHERE rowid=3;\n")
		}
	}
	{ // "2.2b"
		_res = db.Exec("\n  INSERT INTO ft1(ft1) VALUES('integrity-check');\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  INSERT INTO ft1(ft1) VALUES('integrity-check');\n")
		}
	}
	{ // "2.3a"
		_res = db.Exec("\n  DELETE FROM ft1 WHERE rowid=2;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  DELETE FROM ft1 WHERE rowid=2;\n")
		}
	}
	{ // "2.3b"
		_res = db.Exec("\n  INSERT INTO ft1(ft1) VALUES('integrity-check');\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  INSERT INTO ft1(ft1) VALUES('integrity-check');\n")
		}
	}
	{ // "2.4a"
		_res = db.Exec("\n  DELETE FROM ft1 WHERE rowid=4;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  DELETE FROM ft1 WHERE rowid=4;\n")
		}
	}
	{ // "2.4b"
		_res = db.Exec("\n  INSERT INTO ft1(ft1) VALUES('integrity-check');\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  INSERT INTO ft1(ft1) VALUES('integrity-check');\n")
		}
	}
	db.Close()
	os.Remove("test.db")
	os.Remove("test.db-journal")
	os.Remove("test.db-wal")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	tcl_nullvalue = "{}" // fresh connection resets nullvalue
	{ // "3.0"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE ft1 USING fts5(a, detail=none, prefix=1);\n  INSERT INTO ft1(ft1, rank) VALUES('secure-delete', 1);\n  INSERT INTO ft1(ft1, rank) VALUES('pgsz', 64);\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft1 USING fts5(a, detail=none, prefix=1);\n  INSERT INTO ft1(ft1, rank) VALUES('secure-delete', 1);\n  INSERT INTO ft1(ft1, rank) VALUES('pgsz', 64);\n")
		}
	}
	{ // "3.1"
		_res = db.Exec("\n  BEGIN;\n    INSERT INTO ft1(a) VALUES('c');\n  COMMIT;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  BEGIN;\n    INSERT INTO ft1(a) VALUES('c');\n  COMMIT;\n")
		}
	}
	{ // "3.2"
		_res = db.Exec("\n  DELETE FROM ft1 WHERE rowid IN (1);\n  INSERT INTO ft1(ft1) VALUES('integrity-check');\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  DELETE FROM ft1 WHERE rowid IN (1);\n  INSERT INTO ft1(ft1) VALUES('integrity-check');\n")
		}
	}
	db.Close()
	os.Remove("test.db")
	os.Remove("test.db-journal")
	os.Remove("test.db-wal")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	tcl_nullvalue = "{}" // fresh connection resets nullvalue
	{ // "4.0"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE ft1 USING fts5(a, detail=none);\n  INSERT INTO ft1(ft1, rank) VALUES('secure-delete', 1);\n  INSERT INTO ft1(ft1, rank) VALUES('pgsz', 64);\n\n  WITH s(i) AS (\n    SELECT 1 UNION ALL SELECT i+1 FROM s WHERE i<500\n  )\n  INSERT INTO ft1 SELECT 'abcdefg' FROM s;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft1 USING fts5(a, detail=none);\n  INSERT INTO ft1(ft1, rank) VALUES('secure-delete', 1);\n  INSERT INTO ft1(ft1, rank) VALUES('pgsz', 64);\n\n  WITH s(i) AS (\n    SELECT 1 UNION ALL SELECT i+1 FROM s WHERE i<500\n  )\n  INSERT INTO ft1 SELECT 'abcdefg' FROM s;\n")
		}
	}
	{ // do_test "4.1"
		vtab.TclVarSet("i", "", "500")
		i = "500"
		_ = i // suppress unused warning
		for func() bool { i_n, _i_e := strconv.Atoi(i); if _i_e != nil { return false }; return i_n > 0 }() {
			_res = db.Exec(" DELETE FROM ft1 WHERE rowid=" + sqlLiteral(i) + " ")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, " DELETE FROM ft1 WHERE rowid=" + sqlLiteral(i) + " ")
			}
			_res = db.Exec(" INSERT INTO ft1(ft1) VALUES('integrity-check') ")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO ft1(ft1) VALUES('integrity-check') ")
			}
			// incr i -1
			{
				_n, _err := strconv.Atoi(i)
				if _err == nil {
					i = strconv.Itoa(_n + -1)
				}
			}
		}
	}
}
