// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package unique

import (
"github.com/pijalu/frigolite"
"strings"
"testing"
)

func Test_unique2(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var id string
	_ = id // pre-declared from TCL source
	var sql string
	_ = sql // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	// foreach {id sql} "\n   1 {CREATE TABLE t1(x TEXT PRIMARY KEY, y NOT NULL) WITHOUT ROWID}\n   2 {CREATE TABLE t1(x TEXT PRIMARY KEY, y NOT NULL)}\n   3 {CREATE TABLE t1(x TEXT PRIMARY KEY, y) WITHOUT ROWID}\n   4 {CREATE TABLE t1(x TEXT PRIMARY KEY, y)}\n"
	_items0 := tclSplitList("\n   1 {CREATE TABLE t1(x TEXT PRIMARY KEY, y NOT NULL) WITHOUT ROWID}\n   2 {CREATE TABLE t1(x TEXT PRIMARY KEY, y NOT NULL)}\n   3 {CREATE TABLE t1(x TEXT PRIMARY KEY, y) WITHOUT ROWID}\n   4 {CREATE TABLE t1(x TEXT PRIMARY KEY, y)}\n")
	for _idx0 := 0; _idx0+2 <= len(_items0); _idx0 += 2 {
		id := _items0[_idx0+0]
		_ = id // suppress unused warning
		sql := _items0[_idx0+1]
		_ = sql // suppress unused warning
		_ = _idx0
			{ // do_test id + ".1"
				_res = db.Exec("DROP TABLE IF EXISTS t1")
				if _res.Error != nil {
					t.Errorf("exec error: %v\n  sql: %s", _res.Error, "DROP TABLE IF EXISTS t1")
				}
				_res = db.Exec(sql)
				if _res.Error != nil {
					t.Errorf("exec error: %v\n  sql: %s", _res.Error, sql)
				}
				_res = db.Exec("INSERT INTO t1(x,y) VALUES(1,1),(2,2),(3,2),(4,3)")
				if _res.Error != nil {
					t.Errorf("exec error: %v\n  sql: %s", _res.Error, "INSERT INTO t1(x,y) VALUES(1,1),(2,2),(3,2),(4,3)")
				}
			}
			{ // do_test id + ".2"
				_res = db.Exec("CREATE UNIQUE INDEX t1y ON t1(y)")
				_ = _res // catchsql
			}
		}
		// foreach {id sql} "\n   5 {CREATE TABLE t1(w,x,y NOT NULL,z NOT NULL,PRIMARY KEY(w,x)) WITHOUT ROWID}\n   6 {CREATE TABLE t1(w,x,y NOT NULL,z NOT NULL,PRIMARY KEY(w,x))}\n   7 {CREATE TABLE t1(w,x,y NOT NULL,z,PRIMARY KEY(w,x)) WITHOUT ROWID}\n   8 {CREATE TABLE t1(w,x,y NOT NULL,z,PRIMARY KEY(w,x))}\n   9 {CREATE TABLE t1(w,x,y,z NOT NULL,PRIMARY KEY(w,x)) WITHOUT ROWID}\n  10 {CREATE TABLE t1(w,x,y,z NOT NULL,PRIMARY KEY(w,x))}\n  11 {CREATE TABLE t1(w,x,y,z,PRIMARY KEY(w,x)) WITHOUT ROWID}\n  12 {CREATE TABLE t1(w,x,y,z,PRIMARY KEY(w,x))}\n"
		_items1 := tclSplitList("\n   5 {CREATE TABLE t1(w,x,y NOT NULL,z NOT NULL,PRIMARY KEY(w,x)) WITHOUT ROWID}\n   6 {CREATE TABLE t1(w,x,y NOT NULL,z NOT NULL,PRIMARY KEY(w,x))}\n   7 {CREATE TABLE t1(w,x,y NOT NULL,z,PRIMARY KEY(w,x)) WITHOUT ROWID}\n   8 {CREATE TABLE t1(w,x,y NOT NULL,z,PRIMARY KEY(w,x))}\n   9 {CREATE TABLE t1(w,x,y,z NOT NULL,PRIMARY KEY(w,x)) WITHOUT ROWID}\n  10 {CREATE TABLE t1(w,x,y,z NOT NULL,PRIMARY KEY(w,x))}\n  11 {CREATE TABLE t1(w,x,y,z,PRIMARY KEY(w,x)) WITHOUT ROWID}\n  12 {CREATE TABLE t1(w,x,y,z,PRIMARY KEY(w,x))}\n")
		for _idx1 := 0; _idx1+2 <= len(_items1); _idx1 += 2 {
			id := _items1[_idx1+0]
			_ = id // suppress unused warning
			sql := _items1[_idx1+1]
			_ = sql // suppress unused warning
			_ = _idx1
				{ // do_test id + ".1"
					_res = db.Exec("DROP TABLE IF EXISTS t1")
					if _res.Error != nil {
						t.Errorf("exec error: %v\n  sql: %s", _res.Error, "DROP TABLE IF EXISTS t1")
					}
					_res = db.Exec(sql)
					if _res.Error != nil {
						t.Errorf("exec error: %v\n  sql: %s", _res.Error, sql)
					}
					_res = db.Exec("INSERT INTO t1(w,x,y,z) VALUES(1,2,3,4),(2,3,3,4)")
					if _res.Error != nil {
						t.Errorf("exec error: %v\n  sql: %s", _res.Error, "INSERT INTO t1(w,x,y,z) VALUES(1,2,3,4),(2,3,3,4)")
					}
				}
				{ // do_test id + ".2"
					_res = db.Exec("CREATE UNIQUE INDEX t1yz ON t1(y,z)")
					_ = _res // catchsql
				}
			}
			{ // "13.1"
				_res = db.Exec("\n  CREATE TABLE err1(a,b,c,UNIQUE(rowid));\n")
				if _res.Error == nil || !strings.Contains(_res.Error.Error(), "no such column: rowid") {
					t.Errorf("expected error containing %q, got: %v\n  sql: %s", "no such column: rowid", _res.Error, "\n  CREATE TABLE err1(a,b,c,UNIQUE(rowid));\n")
				}
			}
			{ // "13.2"
				_res = db.Exec("\n  CREATE TABLE err1(a,b,c,PRIMARY KEY(rowid));\n")
				if _res.Error == nil || !strings.Contains(_res.Error.Error(), "no such column: rowid") {
					t.Errorf("expected error containing %q, got: %v\n  sql: %s", "no such column: rowid", _res.Error, "\n  CREATE TABLE err1(a,b,c,PRIMARY KEY(rowid));\n")
				}
			}
}
