// Code generated by tcl2go; DO NOT EDIT.
package memsubsys

import (
"github.com/pijalu/frigolite"
"testing"
)

func Test_memsubsys1(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	// set testdir: test directory (not used in Go test context)
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_reset_auto_extension")
	if tclBool("permutation" + " == \"memsubsys1\"") {
		return
	}
	t.Errorf("TODO: %s not implemented in frigolite", "test_set_config_pagecache 0 0")
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	var xtra_size = "290"
	_ = xtra_size // suppress unused warning
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_shutdown")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_config_lookaside 0 0")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_config_pagecache 0 0")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_initialize")
	t.Errorf("TODO: %s not implemented in frigolite", "reset_highwater_marks")
	t.Errorf("TODO: %s not implemented in frigolite", "build_test_db memsubsys1-1 {PRAGMA page_size=1024}")
	{ // do_test "memsubsys1-1.3"
		var pg_used = "lindex [sqlite3_status SQLITE_STATUS_PAGECACHE_USED 0] 2"
		_ = pg_used // suppress unused warning
	}
	{ // do_test "memsubsys1-1.4"
		var s_used = "lindex [sqlite3_status SQLITE_STATUS_SCRATCH_USED 0] 2"
		_ = s_used // suppress unused warning
	}
	var max_pagecache = "lindex [sqlite3_status SQLITE_STATUS_PAGECACHE_OVERFLOW 0] 2"
	_ = max_pagecache // suppress unused warning
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_shutdown")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_config_pagecache [expr 1024+$xtra_size] 20")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_initialize")
	t.Errorf("TODO: %s not implemented in frigolite", "reset_highwater_marks")
	t.Errorf("TODO: %s not implemented in frigolite", "build_test_db memsubsys1-2 {PRAGMA page_size=1024; PRAGMA mmap_size=0}")
	var MEMORY_MANAGEMENT = sqlite_options + "(memorymanage)"
	_ = MEMORY_MANAGEMENT // suppress unused warning
	{ // do_test "memsubsys1-2.4"
		var pg_used = "lindex [sqlite3_status SQLITE_STATUS_PAGECACHE_USED 0] 2"
		_ = pg_used // suppress unused warning
	}
	{ // do_test "memsubsys1-2.5"
		var s_used = "lindex [sqlite3_status SQLITE_STATUS_SCRATCH_USED 0] 2"
		_ = s_used // suppress unused warning
	}
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_shutdown")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_config_pagecache [expr 512+$xtra_size] 20")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_config singlethread")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_initialize")
	t.Errorf("TODO: %s not implemented in frigolite", "reset_highwater_marks")
	t.Errorf("TODO: %s not implemented in frigolite", "build_test_db memsubsys1-3.1 {PRAGMA page_size=1024}")
	{ // do_test "memsubsys1-3.1.3"
		var pg_used = "lindex [sqlite3_status SQLITE_STATUS_PAGECACHE_USED 0] 2"
		_ = pg_used // suppress unused warning
	}
	{ // do_test "memsubsys1-3.1.4"
		var overflow = "lindex [sqlite3_status SQLITE_STATUS_PAGECACHE_OVERFLOW 0] 2"
		_ = overflow // suppress unused warning
		// expr $overflow>=$max_pagecache*0.95 && $overflow<=$max_pagecache*1.05 → "$overflow>=$max_pagecache*0.95 && $overflow<=$max_pagecache*1.05"
	}
	{ // do_test "memsubsys1-3.1.5"
		var s_used = "lindex [sqlite3_status SQLITE_STATUS_SCRATCH_USED 0] 2"
		_ = s_used // suppress unused warning
	}
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_shutdown")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_config_pagecache [expr 2048+$xtra_size] 20")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_initialize")
	t.Errorf("TODO: %s not implemented in frigolite", "reset_highwater_marks")
	t.Errorf("TODO: %s not implemented in frigolite", "build_test_db memsubsys1-3.2 {PRAGMA page_size=2048}")
	{ // do_test "memsubsys1-3.2.3"
		_res = db.Exec("PRAGMA page_size")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "PRAGMA page_size")
		}
	}
	{ // do_test "memsubsys1-3.2.4"
		var pg_used = "lindex [sqlite3_status SQLITE_STATUS_PAGECACHE_USED 0] 2"
		_ = pg_used // suppress unused warning
	}
	{ // do_test "memsubsys1-3.2.5"
		var s_used = "lindex [sqlite3_status SQLITE_STATUS_SCRATCH_USED 0] 2"
		_ = s_used // suppress unused warning
	}
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_shutdown")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_config_pagecache [expr 1024+$xtra_size] 50")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_initialize")
	t.Errorf("TODO: %s not implemented in frigolite", "reset_highwater_marks")
	t.Errorf("TODO: %s not implemented in frigolite", "build_test_db memsubsys1-4 {PRAGMA page_size=1024}")
	{ // do_test "memsubsys1-4.3"
		var pg_used = "lindex [sqlite3_status SQLITE_STATUS_PAGECACHE_USED 0] 2"
		_ = pg_used // suppress unused warning
		// expr $pg_used>=45 && $pg_used<=50 → "$pg_used>=45 && $pg_used<=50"
	}
	{ // do_test "memsubsys1-4.4"
		var pg_ovfl = "lindex [sqlite3_status SQLITE_STATUS_PAGECACHE_OVERFLOW 0] 2"
		_ = pg_ovfl // suppress unused warning
	}
	{ // do_test "memsubsys1-4.5"
		var maxreq = "lindex [sqlite3_status SQLITE_STATUS_MALLOC_SIZE 0] 2"
		_ = maxreq // suppress unused warning
		// expr $maxreq<9000 → "$maxreq<9000"
	}
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_shutdown")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_config_memstatus 1")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_config_lookaside 100 500")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_config serialized")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_initialize")
	t.Errorf("TODO: %s not implemented in frigolite", "autoinstall_test_functions")
	t.Errorf("TODO: %s not implemented in frigolite", "test_restore_config_pagecache")
}
