// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package like

import (
"github.com/pijalu/frigolite"
"os"
"testing"
)

func Test_like3(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	var _r string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	_ = _r   // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var enc string
	_ = enc // pre-declared from TCL source
	var tn string
	_ = tn // pre-declared from TCL source
	var expr string
	_ = expr // pre-declared from TCL source
	var x string
	_ = x // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	{ // "like3-1.1"
		r = db.Query("\n  PRAGMA encoding=UTF8;\n  CREATE TABLE t1(a,b TEXT COLLATE nocase);\n  INSERT INTO t1(a,b)\n     VALUES(1,'abc'),\n           (2,'ABX'),\n           (3,'BCD'),\n           (4,x'616263'),\n           (5,x'414258'),\n           (6,x'424344');\n  CREATE INDEX t1ba ON t1(b,a);\n\n  SELECT a, b FROM t1 WHERE b LIKE 'aB%' ORDER BY +a;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  PRAGMA encoding=UTF8;\n  CREATE TABLE t1(a,b TEXT COLLATE nocase);\n  INSERT INTO t1(a,b)\n     VALUES(1,'abc'),\n           (2,'ABX'),\n           (3,'BCD'),\n           (4,x'616263'),\n           (5,x'414258'),\n           (6,x'424344');\n  CREATE INDEX t1ba ON t1(b,a);\n\n  SELECT a, b FROM t1 WHERE b LIKE 'aB%' ORDER BY +a;\n")
			return
		}
		got := flatten(r)
		want := "1 abc 2 ABX 4 abc 5 ABX"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-1.2"
		r = db.Query("\n  SELECT a, b FROM t1 WHERE +b LIKE 'aB%' ORDER BY +a;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT a, b FROM t1 WHERE +b LIKE 'aB%' ORDER BY +a;\n")
			return
		}
		got := flatten(r)
		want := "1 abc 2 ABX 4 abc 5 ABX"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-2.0"
		r = db.Query("\n  CREATE TABLE t2(a, b TEXT);\n  INSERT INTO t2 SELECT a, b FROM t1;\n  CREATE INDEX t2ba ON t2(b,a);\n  SELECT a, b FROM t2 WHERE b GLOB 'ab*' ORDER BY +a;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  CREATE TABLE t2(a, b TEXT);\n  INSERT INTO t2 SELECT a, b FROM t1;\n  CREATE INDEX t2ba ON t2(b,a);\n  SELECT a, b FROM t2 WHERE b GLOB 'ab*' ORDER BY +a;\n")
			return
		}
		got := flatten(r)
		want := "1 abc 4 abc"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-2.1"
		r = db.Query("\n  SELECT a, b FROM t2 WHERE +b GLOB 'ab*' ORDER BY +a;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT a, b FROM t2 WHERE +b GLOB 'ab*' ORDER BY +a;\n")
			return
		}
		got := flatten(r)
		want := "1 abc 4 abc"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-2.2"
		r = db.Query("\n  SELECT a, b FROM t2 WHERE b>=x'6162' AND b GLOB 'ab*'\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT a, b FROM t2 WHERE b>=x'6162' AND b GLOB 'ab*'\n")
			return
		}
		got := flatten(r)
		want := "4 abc"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-2.3"
		r = db.Query("\n  SELECT a, b FROM t2 WHERE +b>=x'6162' AND +b GLOB 'ab*'\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT a, b FROM t2 WHERE +b>=x'6162' AND +b GLOB 'ab*'\n")
			return
		}
		got := flatten(r)
		want := "4 abc"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-2.4"
		r = db.Query("\n  SELECT a, b FROM t2 WHERE b GLOB 'ab*' AND b>=x'6162'\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT a, b FROM t2 WHERE b GLOB 'ab*' AND b>=x'6162'\n")
			return
		}
		got := flatten(r)
		want := "4 abc"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-2.5"
		r = db.Query("\n  SELECT a, b FROM t2 WHERE +b GLOB 'ab*' AND +b>=x'6162'\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT a, b FROM t2 WHERE +b GLOB 'ab*' AND +b>=x'6162'\n")
			return
		}
		got := flatten(r)
		want := "4 abc"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-3.0"
		r = db.Query("\n  CREATE TABLE t3(x TEXT PRIMARY KEY COLLATE nocase);\n  INSERT INTO t3(x) VALUES('aaa'),('abc'),('abd'),('abe'),('acz');\n  INSERT INTO t3(x) SELECT CAST(x AS blob) FROM t3;\n  SELECT quote(x) FROM t3 WHERE x LIKE 'ab%' ORDER BY x;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  CREATE TABLE t3(x TEXT PRIMARY KEY COLLATE nocase);\n  INSERT INTO t3(x) VALUES('aaa'),('abc'),('abd'),('abe'),('acz');\n  INSERT INTO t3(x) SELECT CAST(x AS blob) FROM t3;\n  SELECT quote(x) FROM t3 WHERE x LIKE 'ab%' ORDER BY x;\n")
			return
		}
		got := flatten(r)
		want := "'abc' 'abd' 'abe' X'616263' X'616264' X'616265'"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-3.1"
		r = db.Query("\n  SELECT quote(x) FROM t3 WHERE x LIKE 'ab%' ORDER BY x DESC;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT quote(x) FROM t3 WHERE x LIKE 'ab%' ORDER BY x DESC;\n")
			return
		}
		got := flatten(r)
		want := "X'616265' X'616264' X'616263' 'abe' 'abd' 'abc'"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-3.1ck"
		r = db.Query("\n  SELECT quote(x) FROM t3 WHERE x LIKE 'ab%' ORDER BY +x DESC;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT quote(x) FROM t3 WHERE x LIKE 'ab%' ORDER BY +x DESC;\n")
			return
		}
		got := flatten(r)
		want := "X'616265' X'616264' X'616263' 'abe' 'abd' 'abc'"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-3.2"
		r = db.Query("\n  SELECT quote(x) FROM t3 WHERE x LIKE 'ab%' ORDER BY x ASC;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT quote(x) FROM t3 WHERE x LIKE 'ab%' ORDER BY x ASC;\n")
			return
		}
		got := flatten(r)
		want := "'abc' 'abd' 'abe' X'616263' X'616264' X'616265'"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-3.2ck"
		r = db.Query("\n  SELECT quote(x) FROM t3 WHERE x LIKE 'ab%' ORDER BY +x ASC;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT quote(x) FROM t3 WHERE x LIKE 'ab%' ORDER BY +x ASC;\n")
			return
		}
		got := flatten(r)
		want := "'abc' 'abd' 'abe' X'616263' X'616264' X'616265'"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-4.0"
		r = db.Query("\n  CREATE TABLE t4(x TEXT COLLATE nocase);\n  CREATE INDEX t4x ON t4(x DESC);\n  INSERT INTO t4(x) SELECT x FROM t3;\n  SELECT quote(x) FROM t4 WHERE x LIKE 'ab%' ORDER BY x;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  CREATE TABLE t4(x TEXT COLLATE nocase);\n  CREATE INDEX t4x ON t4(x DESC);\n  INSERT INTO t4(x) SELECT x FROM t3;\n  SELECT quote(x) FROM t4 WHERE x LIKE 'ab%' ORDER BY x;\n")
			return
		}
		got := flatten(r)
		want := "'abc' 'abd' 'abe' X'616263' X'616264' X'616265'"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-4.1"
		r = db.Query("\n  SELECT quote(x) FROM t4 WHERE x LIKE 'ab%' ORDER BY x DESC;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT quote(x) FROM t4 WHERE x LIKE 'ab%' ORDER BY x DESC;\n")
			return
		}
		got := flatten(r)
		want := "X'616265' X'616264' X'616263' 'abe' 'abd' 'abc'"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-4.1ck"
		r = db.Query("\n  SELECT quote(x) FROM t4 WHERE x LIKE 'ab%' ORDER BY +x DESC;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT quote(x) FROM t4 WHERE x LIKE 'ab%' ORDER BY +x DESC;\n")
			return
		}
		got := flatten(r)
		want := "X'616265' X'616264' X'616263' 'abe' 'abd' 'abc'"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-4.2"
		r = db.Query("\n  SELECT quote(x) FROM t4 WHERE x LIKE 'ab%' ORDER BY x ASC;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT quote(x) FROM t4 WHERE x LIKE 'ab%' ORDER BY x ASC;\n")
			return
		}
		got := flatten(r)
		want := "'abc' 'abd' 'abe' X'616263' X'616264' X'616265'"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-4.2ck"
		r = db.Query("\n  SELECT quote(x) FROM t4 WHERE x LIKE 'ab%' ORDER BY +x ASC;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT quote(x) FROM t4 WHERE x LIKE 'ab%' ORDER BY +x ASC;\n")
			return
		}
		got := flatten(r)
		want := "'abc' 'abd' 'abe' X'616263' X'616264' X'616265'"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-5.100"
		r = db.Query("\n  CREATE TABLE t5a(x INT UNIQUE COLLATE nocase);\n  INSERT INTO t5a(x) VALUES('/abc'),(123),(-234);\n  SELECT x FROM t5a WHERE x LIKE '/%';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  CREATE TABLE t5a(x INT UNIQUE COLLATE nocase);\n  INSERT INTO t5a(x) VALUES('/abc'),(123),(-234);\n  SELECT x FROM t5a WHERE x LIKE '/%';\n")
			return
		}
		got := flatten(r)
		want := "/abc"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-5.101"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT x FROM t5a WHERE x LIKE '/%';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT x FROM t5a WHERE x LIKE '/%';\n")
		}
	}
	{ // "like3-5.110"
		r = db.Query("\n  SELECT x FROM t5a WHERE x LIKE '/a%';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT x FROM t5a WHERE x LIKE '/a%';\n")
			return
		}
		got := flatten(r)
		want := "/abc"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-5.111"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT x FROM t5a WHERE x LIKE '/a%';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT x FROM t5a WHERE x LIKE '/a%';\n")
		}
	}
	{ // "like3-5.120"
		r = db.Query("\n  SELECT x FROM t5a WHERE x LIKE '^12%' ESCAPE '^';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT x FROM t5a WHERE x LIKE '^12%' ESCAPE '^';\n")
			return
		}
		got := flatten(r)
		want := "123"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-5.121"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT x FROM t5a WHERE x LIKE '^12%' ESCAPE '^';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT x FROM t5a WHERE x LIKE '^12%' ESCAPE '^';\n")
		}
	}
	{ // "like3-5.122"
		r = db.Query("\n  SELECT x FROM t5a WHERE x LIKE '^-2%' ESCAPE '^';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT x FROM t5a WHERE x LIKE '^-2%' ESCAPE '^';\n")
			return
		}
		got := flatten(r)
		want := "-234"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-5.123"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT x FROM t5a WHERE x LIKE '^12%' ESCAPE '^';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT x FROM t5a WHERE x LIKE '^12%' ESCAPE '^';\n")
		}
	}
	{ // "like3-5.200"
		r = db.Query("\n  CREATE TABLE t5b(x INT UNIQUE COLLATE binary);\n  INSERT INTO t5b(x) VALUES('/abc'),(123),(-234);\n  SELECT x FROM t5b WHERE x GLOB '/*';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  CREATE TABLE t5b(x INT UNIQUE COLLATE binary);\n  INSERT INTO t5b(x) VALUES('/abc'),(123),(-234);\n  SELECT x FROM t5b WHERE x GLOB '/*';\n")
			return
		}
		got := flatten(r)
		want := "/abc"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-5.201"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT x FROM t5b WHERE x GLOB '/*';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT x FROM t5b WHERE x GLOB '/*';\n")
		}
	}
	{ // "like3-5.210"
		r = db.Query("\n  SELECT x FROM t5b WHERE x GLOB '/a*';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT x FROM t5b WHERE x GLOB '/a*';\n")
			return
		}
		got := flatten(r)
		want := "/abc"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-5.211"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT x FROM t5b WHERE x GLOB '/a*';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT x FROM t5b WHERE x GLOB '/a*';\n")
		}
	}
	{ // "like3-5.300"
		r = db.Query("\n  CREATE TABLE t5c (c0 REAL);\n  CREATE INDEX t5c_0 ON t5c(c0 COLLATE NOCASE);\n  INSERT INTO t5c(rowid, c0) VALUES (99,'+/');\n  SELECT * FROM t5c WHERE (c0 LIKE '+/');\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  CREATE TABLE t5c (c0 REAL);\n  CREATE INDEX t5c_0 ON t5c(c0 COLLATE NOCASE);\n  INSERT INTO t5c(rowid, c0) VALUES (99,'+/');\n  SELECT * FROM t5c WHERE (c0 LIKE '+/');\n")
			return
		}
		got := flatten(r)
		want := "+/"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-5.400"
		r = db.Query("\n  DROP TABLE IF EXISTS t0;\n  CREATE TABLE t0(c0 INT UNIQUE COLLATE NOCASE);\n  INSERT INTO t0(c0) VALUES ('./');\n  SELECT * FROM t0 WHERE t0.c0 LIKE './';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  DROP TABLE IF EXISTS t0;\n  CREATE TABLE t0(c0 INT UNIQUE COLLATE NOCASE);\n  INSERT INTO t0(c0) VALUES ('./');\n  SELECT * FROM t0 WHERE t0.c0 LIKE './';\n")
			return
		}
		got := flatten(r)
		want := "./"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-5.410"
		r = db.Query("\n  DROP TABLE IF EXISTS t0;\n  CREATE TABLE t0(c0 INT UNIQUE COLLATE NOCASE);\n  INSERT INTO t0(c0) VALUES ('.1%');\n  SELECT * FROM t0 WHERE t0.c0 LIKE '.1%';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  DROP TABLE IF EXISTS t0;\n  CREATE TABLE t0(c0 INT UNIQUE COLLATE NOCASE);\n  INSERT INTO t0(c0) VALUES ('.1%');\n  SELECT * FROM t0 WHERE t0.c0 LIKE '.1%';\n")
			return
		}
		got := flatten(r)
		want := ".1%"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-5.420"
		r = db.Query("\n  DROP TABLE IF EXISTS t0;\n  CREATE TABLE t0(c0 UNIQUE);\n  INSERT INTO t0(c0) VALUES(-1);\n  SELECT * FROM t0 WHERE t0.c0 GLOB '-*';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  DROP TABLE IF EXISTS t0;\n  CREATE TABLE t0(c0 UNIQUE);\n  INSERT INTO t0(c0) VALUES(-1);\n  SELECT * FROM t0 WHERE t0.c0 GLOB '-*';\n")
			return
		}
		got := flatten(r)
		want := "-1"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-5.421"
		r = db.Query("\n  SELECT t0.c0 GLOB '-*' FROM t0;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT t0.c0 GLOB '-*' FROM t0;\n")
			return
		}
		got := flatten(r)
		want := "1"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-6.100"
		_res = db.Exec("\n  DROP TABLE IF EXISTS t1;\n  CREATE TABLE t1(path TEXT COLLATE nocase PRIMARY KEY,a,b,c) WITHOUT ROWID;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  DROP TABLE IF EXISTS t1;\n  CREATE TABLE t1(path TEXT COLLATE nocase PRIMARY KEY,a,b,c) WITHOUT ROWID;\n")
		}
	}
	{ // "like3-6.110"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM t1 WHERE path LIKE 'a%';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM t1 WHERE path LIKE 'a%';\n")
		}
	}
	{ // "like3-6.120"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM t1 WHERE path LIKE 'a%' ESCAPE 'x';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM t1 WHERE path LIKE 'a%' ESCAPE 'x';\n")
		}
	}
	{ // "like3-6.200"
		_res = db.Exec("\n  DROP TABLE IF EXISTS t2;\n  CREATE TABLE t2(path TEXT,x,y,z);\n  CREATE INDEX t2path ON t2(path COLLATE nocase);\n  CREATE INDEX t2path2 ON t2(path);\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  DROP TABLE IF EXISTS t2;\n  CREATE TABLE t2(path TEXT,x,y,z);\n  CREATE INDEX t2path ON t2(path COLLATE nocase);\n  CREATE INDEX t2path2 ON t2(path);\n")
		}
	}
	{ // "like3-6.210"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM t2 WHERE path LIKE 'a%';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM t2 WHERE path LIKE 'a%';\n")
		}
	}
	{ // "like3-6.220"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM t2 WHERE path LIKE 'a%' ESCAPE '\\';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM t2 WHERE path LIKE 'a%' ESCAPE '\\';\n")
		}
	}
	_res = db.Exec("PRAGMA case_sensitive_like=ON")
	if _res.Error != nil {
		t.Errorf("exec error: %v\n  sql: %s", _res.Error, "PRAGMA case_sensitive_like=ON")
	}
	{ // "like3-6.230"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM t2 WHERE path LIKE 'a%';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM t2 WHERE path LIKE 'a%';\n")
		}
	}
	{ // "like3-6.240"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM t2 WHERE path LIKE 'a%' ESCAPE '\\';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM t2 WHERE path LIKE 'a%' ESCAPE '\\';\n")
		}
	}
	db.Close()
	os.Remove("test.db")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	tcl_nullvalue = "{}" // fresh connection resets nullvalue
	{ // "like3-7.0"
		r = db.Query("\n    PRAGMA encoding = 'UTF-16be';\n  \n    CREATE TABLE Example(word TEXT NOT NULL);\n    CREATE INDEX Example_word on Example(word);\n  \n    INSERT INTO Example VALUES(char(0x307F));\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    PRAGMA encoding = 'UTF-16be';\n  \n    CREATE TABLE Example(word TEXT NOT NULL);\n    CREATE INDEX Example_word on Example(word);\n  \n    INSERT INTO Example VALUES(char(0x307F));\n  ")
		}
	}
	{ // "like3-7.1"
		r = db.Query("\n    SELECT char(0x307F)=='み';\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT char(0x307F)=='み';\n  ")
			return
		}
		got := flatten(r)
		want := "1"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-7.1"
		r = db.Query("\n    SELECT * FROM Example WHERE word GLOB 'み*'\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT * FROM Example WHERE word GLOB 'み*'\n  ")
			return
		}
		got := flatten(r)
		want := "み"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "like3-7.2"
		r = db.Query("\n    SELECT * FROM Example WHERE word >= char(0x307F) AND word < char(0x3080);\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT * FROM Example WHERE word >= char(0x307F) AND word < char(0x3080);\n  ")
			return
		}
		got := flatten(r)
		want := "み"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	db.Close()
	os.Remove("test.db")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	tcl_nullvalue = "{}" // fresh connection resets nullvalue
	for _, enc := range tclSplitList("UTF-8\n  UTF-16le \n  UTF-16be") {
	_ = enc // suppress unused warning
		// foreach {tn expr} "1 \"CAST (X'FF' AS TEXT)\"\n    2 \"CAST (X'FFBF' AS TEXT)\"\n    3 \"CAST (X'FFBFBF' AS TEXT)\"\n    4 \"CAST (X'FFBFBFBF' AS TEXT)\"\n\n    5 \"'abc' || CAST (X'FF' AS TEXT)\"\n    6 \"'def' || CAST (X'FFBF' AS TEXT)\"\n    7 \"'ghi' || CAST (X'FFBFBF' AS TEXT)\"\n    8 \"'jkl' || CAST (X'FFBFBFBF' AS TEXT)\""
		_items0 := tclSplitList("1 \"CAST (X'FF' AS TEXT)\"\n    2 \"CAST (X'FFBF' AS TEXT)\"\n    3 \"CAST (X'FFBFBF' AS TEXT)\"\n    4 \"CAST (X'FFBFBFBF' AS TEXT)\"\n\n    5 \"'abc' || CAST (X'FF' AS TEXT)\"\n    6 \"'def' || CAST (X'FFBF' AS TEXT)\"\n    7 \"'ghi' || CAST (X'FFBFBF' AS TEXT)\"\n    8 \"'jkl' || CAST (X'FFBFBFBF' AS TEXT)\"")
		for _idx0 := 0; _idx0+2 <= len(_items0); _idx0 += 2 {
			tn := _items0[_idx0+0]
			_ = tn // suppress unused warning
			expr := _items0[_idx0+1]
			_ = expr // suppress unused warning
			_ = _idx0
				db.Close()
				os.Remove("test.db")
				db, err = frigolite.Open("test.db")
				if err != nil { t.Fatal(err) }
				tcl_nullvalue = "{}" // fresh connection resets nullvalue
				r = db.Query("PRAGMA encoding = '" + enc + "'")
				if r.Error != nil {
					t.Errorf("query error: %v\n  sql: %s", r.Error, "PRAGMA encoding = '" + enc + "'")
				}
				tn = "utf" + tclStringRange(enc, "4", "end") + "." + tn
				_ = tn // suppress unused warning
				{ // "like3-8." + tn + ".1"
					_res = db.Exec("\n      CREATE TABLE t1(x);\n    ")
					if _res.Error != nil {
						t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      CREATE TABLE t1(x);\n    ")
					}
				}
				{ // "like3-8." + tn + ".2"
					r = db.Query("\n      PRAGMA encoding\n    ")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n      PRAGMA encoding\n    ")
						return
					}
					got := flatten(r)
					want := tclListFlatten(enc)
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				{ // "like3-8." + tn + ".3"
					_res = db.Exec("\n      INSERT INTO t1 VALUES( " + expr + " )\n    ")
					if _res.Error != nil {
						t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      INSERT INTO t1 VALUES( " + expr + " )\n    ")
					}
				}
				{ // "like3-8." + tn + ".4"
					r = db.Query("\n      SELECT typeof(x) FROM t1\n    ")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n      SELECT typeof(x) FROM t1\n    ")
						return
					}
					got := flatten(r)
					want := "text"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				_dbone1 := tclExecSQL(db, "{SELECT x || '%' FROM t1}")
				x = _dbone1
				_ = x // suppress unused warning
				{ // "like3-8." + tn + ".5"
					r = db.Query("\n      SELECT rowid FROM t1 WHERE x LIKE " + sqlLiteral(x) + "\n    ")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n      SELECT rowid FROM t1 WHERE x LIKE " + sqlLiteral(x) + "\n    ")
						return
					}
					got := flatten(r)
					want := "1"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				{ // "like3-8." + tn + ".6"
					_res = db.Exec("\n      CREATE INDEX i1 ON t1(x);\n    ")
					if _res.Error != nil {
						t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      CREATE INDEX i1 ON t1(x);\n    ")
					}
				}
				{ // "like3-8." + tn + ".7"
					r = db.Query("\n      SELECT rowid FROM t1 WHERE x LIKE " + sqlLiteral(x) + "\n    ")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n      SELECT rowid FROM t1 WHERE x LIKE " + sqlLiteral(x) + "\n    ")
						return
					}
					got := flatten(r)
					want := "1"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
			}
		}
}
