// Code generated by tcl2go; DO NOT EDIT.
package tkt_313723c

import (
"github.com/pijalu/frigolite"
"testing"
)

func Test_tkt_313723c356(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	// set testdir: test directory (not used in Go test context)
	if tclBool("!" + "wal_is_capable") {
		return
	}
	{ // "tkt-313723c356.1"
		_res = db.Exec("\n  PRAGMA page_size = 1024;\n  PRAGMA journal_mode = WAL;\n  CREATE TABLE t1(a, b);\n  CREATE INDEX i1 ON t1(a, b);\n  INSERT INTO t1 VALUES(randomblob(400), randomblob(400));\n  INSERT INTO t1 SELECT randomblob(400), randomblob(400) FROM t1;\n  INSERT INTO t1 SELECT randomblob(400), randomblob(400) FROM t1;\n  INSERT INTO t1 SELECT randomblob(400), randomblob(400) FROM t1;\n  INSERT INTO t1 SELECT randomblob(400), randomblob(400) FROM t1;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  PRAGMA page_size = 1024;\n  PRAGMA journal_mode = WAL;\n  CREATE TABLE t1(a, b);\n  CREATE INDEX i1 ON t1(a, b);\n  INSERT INTO t1 VALUES(randomblob(400), randomblob(400));\n  INSERT INTO t1 SELECT randomblob(400), randomblob(400) FROM t1;\n  INSERT INTO t1 SELECT randomblob(400), randomblob(400) FROM t1;\n  INSERT INTO t1 SELECT randomblob(400), randomblob(400) FROM t1;\n  INSERT INTO t1 SELECT randomblob(400), randomblob(400) FROM t1;\n")
		}
	}
	t.Errorf("TODO: %s not implemented in frigolite", "faultsim_save_and_close")
	t.Errorf("TODO: %s not implemented in frigolite", "do_faultsim_test tkt-313723c356.2 -faults shmerr* -prep {\n  faultsim_restore_and_reopen\n  sqlite3 db2 test....} -body {\n  # At this point, the cache contains all of tabl...} -test {\n  faultsim_test_result {0 1}\n  faultsim_integrity...}")
}
