// Code generated by tcl2go; DO NOT EDIT.
package capi

import (
"github.com/pijalu/frigolite"
"os"
"strconv"
"testing"
)

func Test_capi3(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var testprefix string
	_ = testprefix // pre-declared from TCL source
	var _r string
	_ = _r // pre-declared from TCL source
	var str string
	_ = str // pre-declared from TCL source
	var DB string
	_ = DB // pre-declared from TCL source
	var STMT string
	_ = STMT // pre-declared from TCL source
	var sql string
	_ = sql // pre-declared from TCL source
	var sql16 string
	_ = sql16 // pre-declared from TCL source
	var capi3_errno string
	_ = capi3_errno // pre-declared from TCL source
	var idxlist string
	_ = idxlist // pre-declared from TCL source
	var numcols string
	_ = numcols // pre-declared from TCL source
	var i string
	_ = i // pre-declared from TCL source
	var cnamelist string
	_ = cnamelist // pre-declared from TCL source
	var types string
	_ = types // pre-declared from TCL source
	var x string
	_ = x // pre-declared from TCL source
	var ints string
	_ = ints // pre-declared from TCL source
	var lens string
	_ = lens // pre-declared from TCL source
	var bytes string
	_ = bytes // pre-declared from TCL source
	var utf8 string
	_ = utf8 // pre-declared from TCL source
	var ENC string
	_ = ENC // pre-declared from TCL source
	var schemacookie string
	_ = schemacookie // pre-declared from TCL source
	var code2english string
	_ = code2english // pre-declared from TCL source
	var test_number string
	_ = test_number // pre-declared from TCL source
	var code string
	_ = code // pre-declared from TCL source
	var english string
	_ = english // pre-declared from TCL source
	var ms string
	_ = ms // pre-declared from TCL source
	var rc string
	_ = rc // pre-declared from TCL source
	var nbytes string
	_ = nbytes // pre-declared from TCL source
	var v1 string
	_ = v1 // pre-declared from TCL source
	var stmt string
	_ = stmt // pre-declared from TCL source
	var Id_ string
	_ = Id_ // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source
	var nt string
	_ = nt // pre-declared from TCL source
	var vals string
	_ = vals // pre-declared from TCL source
	var fname string
	_ = fname // pre-declared from TCL source
	var options string
	_ = options // pre-declared from TCL source
	var test string
	_ = test // pre-declared from TCL source
	var names string
	_ = names // pre-declared from TCL source
	var decltypes string
	_ = decltypes // pre-declared from TCL source
	var dbs string
	_ = dbs // pre-declared from TCL source
	var tables string
	_ = tables // pre-declared from TCL source
	var cols string
	_ = cols // pre-declared from TCL source
	var doubles string
	_ = doubles // pre-declared from TCL source
	var strings string
	_ = strings // pre-declared from TCL source
	var newval string
	_ = newval // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	testprefix = "capi3" // TCL namespace variable
	_ = testprefix // suppress unused warning
	// do_not_use_codec (unsupported command, not transpiled)
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	DB = "sqlite3_connection_pointer db"
	_ = DB // suppress unused warning
	{ // do_test "capi3-1.0"
		// sqlite3_get_autocommit $DB (unsupported command, not transpiled)
	}
	{ // do_test "capi3-1.1"
		STMT = "sqlite3_prepare $DB {SELECT name FROM sqlite_master} -1 TAIL"
		_ = STMT // suppress unused warning
		// sqlite3_finalize $STMT (unsupported command, not transpiled)
	}
	{ // do_test "capi3-1.2.1"
		// sqlite3_errcode $DB (unsupported command, not transpiled)
	}
	{ // do_test "capi3-1.2.2"
		// sqlite3_extended_errcode $DB (unsupported command, not transpiled)
	}
	{ // do_test "capi3-1.3"
		// sqlite3_errmsg $DB (unsupported command, not transpiled)
	}
	{ // do_test "capi3-1.4"
		sql = "SELECT name FROM sqlite_master;SELECT 10"
		_ = sql // suppress unused warning
		STMT = "sqlite3_prepare $DB $sql -1 TAIL"
		_ = STMT // suppress unused warning
		// sqlite3_finalize $STMT (unsupported command, not transpiled)
	}
	{ // do_test "capi3-1.5"
		sql = "SELECT name FROM sqlite_master;SELECT 10"
		_ = sql // suppress unused warning
		STMT = "sqlite3_prepare $DB $sql [string length $sql] TAIL"
		_ = STMT // suppress unused warning
		// sqlite3_finalize $STMT (unsupported command, not transpiled)
	}
	{ // do_test "capi3-1.6"
		sql = "SELECT name FROM sqlite_master;SELECT 10"
		_ = sql // suppress unused warning
		STMT = "sqlite3_prepare $DB $sql [expr [string length $sql]+1] TAIL"
		_ = STMT // suppress unused warning
		// sqlite3_finalize $STMT (unsupported command, not transpiled)
	}
	{ // do_test "capi3-1.7"
		sql = "SELECT namex FROM sqlite_master"
		_ = sql // suppress unused warning
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			STMT = "sqlite3_prepare $DB $sql -1 TAIL"
			_ = STMT // suppress unused warning
		}
	}
	{ // do_test "capi3-1.8.1"
		// sqlite3_errcode $DB (unsupported command, not transpiled)
	}
	{ // do_test "capi3-1.8.2"
		// sqlite3_extended_errcode $DB (unsupported command, not transpiled)
	}
	{ // do_test "capi3-1.9"
		// sqlite3_errmsg $DB (unsupported command, not transpiled)
	}
	{ // do_test "capi3-2.1"
		sql16 = "utf16 {SELECT name FROM sqlite_master}"
		_ = sql16 // suppress unused warning
		STMT = "sqlite3_prepare16 $DB $sql16 -1 ::TAIL"
		_ = STMT // suppress unused warning
		// sqlite3_finalize $STMT (unsupported command, not transpiled)
		// utf8 $::TAIL (unsupported command, not transpiled)
	}
	{ // do_test "capi3-2.2"
		sql = "utf16 {SELECT name FROM sqlite_master;SELECT 10}"
		_ = sql // suppress unused warning
		STMT = "sqlite3_prepare16 $DB $sql -1 TAIL"
		_ = STMT // suppress unused warning
		// sqlite3_finalize $STMT (unsupported command, not transpiled)
		// utf8 $TAIL (unsupported command, not transpiled)
	}
	{ // do_test "capi3-2.3"
		sql = "utf16 {SELECT namex FROM sqlite_master}"
		_ = sql // suppress unused warning
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			STMT = "sqlite3_prepare16 $DB $sql -1"
			_ = STMT // suppress unused warning
		}
	}
	{ // do_test "capi3-2.4.1"
		// sqlite3_errcode $DB (unsupported command, not transpiled)
	}
	{ // do_test "capi3-2.4.2"
		// sqlite3_extended_errcode $DB (unsupported command, not transpiled)
	}
	{ // do_test "capi3-2.5"
		// sqlite3_errmsg $DB (unsupported command, not transpiled)
	}
	{ // do_test "capi3-2.6"
		_res = db.Exec("CREATE TABLE tablename(x)")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "CREATE TABLE tablename(x)")
		}
		sql16 = "utf16 {PRAGMA table_info(\"TableName\"); --excess text}"
		_ = sql16 // suppress unused warning
		STMT = "sqlite3_prepare16 $DB $sql16 -1"
		_ = STMT // suppress unused warning
		// sqlite3_step $STMT (unsupported command, not transpiled)
	}
	{ // do_test "capi3-2.7"
		// sqlite3_step $STMT (unsupported command, not transpiled)
	}
	{ // do_test "capi3-2.8"
		// sqlite3_finalize $STMT (unsupported command, not transpiled)
	}
	{ // do_test "capi3-3.1"
		// set db2 [sqlite3_open ...] (skipped, DB connection)
		// sqlite3_errcode $db2 (unsupported command, not transpiled)
	}
	{ // do_test "capi3-3.2"
		// sqlite3_close $db2 (unsupported command, not transpiled)
	}
	{ // do_test "capi3-3.3"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			// set db2 [sqlite3_open ...] (skipped, DB connection)
		}
		capi3_errno = "sqlite3_system_errno $db2" // TCL namespace variable
		_ = capi3_errno // suppress unused warning
		_list := tclList([]string{"sqlite3_extended_errcode $db2", tclExpr("$::capi3_errno!=0")})
		_ = _list
	}
	{ // do_test "capi3-3.4"
		// sqlite3_errmsg $db2 (unsupported command, not transpiled)
	}
	{ // do_test "capi3-3.5"
		_list := tclList([]string{"sqlite3_system_errno $db2", "sqlite3_close $db2"})
		_ = _list
	}
	if tclBool("clang_sanitize_address" + "==0 && 0") {
		{ // do_test "capi3-3.6.1-misuse"
			// sqlite3_close $db2 (unsupported command, not transpiled)
		}
		{ // do_test "capi3-3.6.2-misuse"
			// sqlite3_errmsg $db2 (unsupported command, not transpiled)
		}
		{ // do_test "capi3-3.6.3-misuse"
			// utf8 [sqlite3_errmsg16 $db2] (unsupported command, not transpiled)
		}
	}
	{ // do_test "capi3-3.7"
		// set db2 [sqlite3_open ...] (skipped, DB connection)
		// sqlite3_errcode $db2 (unsupported command, not transpiled)
	}
	{ // do_test "capi3-3.8"
		// sqlite3_close $db2 (unsupported command, not transpiled)
	}
	{ // do_test "capi3-4.1"
		// set db2 [sqlite3_open ...] (skipped, DB connection)
		// sqlite3_errcode $db2 (unsupported command, not transpiled)
	}
	{ // do_test "capi3-4.2"
		// sqlite3_close $db2 (unsupported command, not transpiled)
	}
	{ // do_test "capi3-4.3"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			// set db2 [sqlite3_open ...] (skipped, DB connection)
		}
		// sqlite3_errcode $db2 (unsupported command, not transpiled)
	}
	{ // do_test "capi3-4.4"
		// utf8 [sqlite3_errmsg16 $db2] (unsupported command, not transpiled)
	}
	{ // do_test "capi3-4.5"
		// sqlite3_close $db2 (unsupported command, not transpiled)
	}
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	return
	{ // do_test "capi3-5.0"
		_res = db.Exec("\n    CREATE TABLE t1(a VARINT, b BLOB, c VARCHAR(16));\n    INSERT INTO t1 VALUES(1, 2, 3);\n    INSERT INTO t1 VALUES('one', 'two', NULL);\n    INSERT INTO t1 VALUES(1.2, 1.3, 1.4);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE TABLE t1(a VARINT, b BLOB, c VARCHAR(16));\n    INSERT INTO t1 VALUES(1, 2, 3);\n    INSERT INTO t1 VALUES('one', 'two', NULL);\n    INSERT INTO t1 VALUES(1.2, 1.3, 1.4);\n  ")
		}
		sql = "SELECT * FROM t1"
		_ = sql // suppress unused warning
		STMT = "sqlite3_prepare $DB $sql -1 TAIL"
		_ = STMT // suppress unused warning
		// sqlite3_column_count $STMT (unsupported command, not transpiled)
	}
	// check_header $STMT capi3-5.1 {a b c} {VARINT BLOB VARCHAR(16)} (unsupported command, not transpiled)
	// check_origin_header $STMT capi3-5.1 {main main main} {t1 t1 t1} {a b c} (unsupported command, not transpiled)
	{ // do_test "capi3-5.2"
		// sqlite3_step $STMT (unsupported command, not transpiled)
	}
	// check_header $STMT capi3-5.3 {a b c} {VARINT BLOB VARCHAR(16)} (unsupported command, not transpiled)
	// check_origin_header $STMT capi3-5.3 {main main main} {t1 t1 t1} {a b c} (unsupported command, not transpiled)
	// check_data $STMT capi3-5.4 {INTEGER INTEGER TEXT} {1 2 3} {1.0 2.0 3.0} {1 2 3} (unsupported command, not transpiled)
	{ // do_test "capi3-5.5"
		// sqlite3_step $STMT (unsupported command, not transpiled)
	}
	// check_header $STMT capi3-5.6 {a b c} {VARINT BLOB VARCHAR(16)} (unsupported command, not transpiled)
	// check_origin_header $STMT capi3-5.6 {main main main} {t1 t1 t1} {a b c} (unsupported command, not transpiled)
	// check_data $STMT capi3-5.7 {TEXT TEXT NULL} {0 0 0} {0.0 0.0 0.0} {one two {}} (unsupported command, not transpiled)
	{ // do_test "capi3-5.8"
		// sqlite3_step $STMT (unsupported command, not transpiled)
	}
	// check_header $STMT capi3-5.9 {a b c} {VARINT BLOB VARCHAR(16)} (unsupported command, not transpiled)
	// check_origin_header $STMT capi3-5.9 {main main main} {t1 t1 t1} {a b c} (unsupported command, not transpiled)
	// check_data $STMT capi3-5.10 {FLOAT FLOAT TEXT} {1 1 1} {1.2 1.3 1.4} {1.2 1.3 1.4} (unsupported command, not transpiled)
	{ // do_test "capi3-5.11"
		// sqlite3_step $STMT (unsupported command, not transpiled)
	}
	{ // do_test "capi3-5.12"
		// sqlite3_finalize $STMT (unsupported command, not transpiled)
	}
	{ // do_test "capi3-5.20"
		sql = "SELECT a, sum(b), max(c) FROM t1 GROUP BY a"
		_ = sql // suppress unused warning
		STMT = "sqlite3_prepare $DB $sql -1 TAIL"
		_ = STMT // suppress unused warning
		// sqlite3_column_count $STMT (unsupported command, not transpiled)
	}
	// check_header $STMT capi3-5.21 {a sum(b) max(c)} {VARINT {} {}} (unsupported command, not transpiled)
	// check_origin_header $STMT capi3-5.22 {main {} {}} {t1 {} {}} {a {} {}} (unsupported command, not transpiled)
	{ // do_test "capi3-5.23"
		// sqlite3_finalize $STMT (unsupported command, not transpiled)
	}
	{ // do_test "capi3-5.30"
		sql = "SELECT a AS x, sum(b) AS y, max(c) AS z FROM t1 AS m GROUP BY x"
		_ = sql // suppress unused warning
		STMT = "sqlite3_prepare $DB $sql -1 TAIL"
		_ = STMT // suppress unused warning
		// sqlite3_column_count $STMT (unsupported command, not transpiled)
	}
	// check_header $STMT capi3-5.31 {x y z} {VARINT {} {}} (unsupported command, not transpiled)
	// check_origin_header $STMT capi3-5.32 {main {} {}} {t1 {} {}} {a {} {}} (unsupported command, not transpiled)
	{ // do_test "capi3-5.33"
		// sqlite3_finalize $STMT (unsupported command, not transpiled)
	}
	{ // do_test "capi3-5.34"
		STMT = "sqlite3_prepare $DB {SELECT :a, :b} -1 TAIL"
		_ = STMT // suppress unused warning
		// sqlite3_column_count $STMT (unsupported command, not transpiled)
	}
	// check_header $STMT capi-5.35 {:a :b} {{} {}} (unsupported command, not transpiled)
	// sqlite3_finalize $STMT (unsupported command, not transpiled)
	ENC = "execsql {pragma encoding}" // TCL namespace variable
	_ = ENC // suppress unused warning
	{ // do_test "capi3-6.0"
		_dbtmp0, err := frigolite.Open("test.db")
		_ = _dbtmp0 // sqlite3 db connection
		if err != nil { t.Fatal(err) }
		DB = "sqlite3_connection_pointer db"
		_ = DB // suppress unused warning
		if tclBool("sqlite3 -has-codec" + "==0") {
			// sqlite3_key $DB xyzzy (unsupported command, not transpiled)
		}
		sql = "SELECT a FROM t1 order by rowid"
		_ = sql // suppress unused warning
		STMT = "sqlite3_prepare $DB $sql -1 TAIL"
		_ = STMT // suppress unused warning
		// expr 0 → "0"
	}
	{ // do_test "capi3-6.1"
		// sqlite3_close $DB (unsupported command, not transpiled)
	}
	{ // do_test "capi3-6.2"
		// sqlite3_step $STMT (unsupported command, not transpiled)
	}
	{ // do_test "capi3-6.3"
		// sqlite3_finalize $STMT (unsupported command, not transpiled)
	}
	if tclBool("0 && " + "clang_sanitize_address" + "==0") {
		{ // do_test "capi3-6.4-misuse"
			// sqlite3_close $DB (unsupported command, not transpiled)
		}
	}
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	if tclBool("!" + "sqlite3 -has-codec") {
		{ // do_test "capi3-7.1"
			// set_file_format 5 (unsupported command, not transpiled)
		}
		{ // do_test "capi3-7.2"
			{
				var _catchErr error
				_ = _catchErr // suppress unused warning
				_dbtmp0, err := frigolite.Open("test.db")
				_ = _dbtmp0 // sqlite3 db connection
				if err != nil { t.Fatal(err) }
			}
			_res = db.Exec("\n      SELECT * FROM sqlite_master;\n    ")
			_ = _res // catchsql
		}
	}
	if tclBool("!" + "sqlite3 -has-codec") {
		{ // do_test "capi3-8.1"
			os.Remove("test.db")
			_dbtmp0, err := frigolite.Open("test.db")
			_ = _dbtmp0 // sqlite3 db connection
			if err != nil { t.Fatal(err) }
			_res = db.Exec("\n      CREATE TABLE t1(a);\n    ")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      CREATE TABLE t1(a);\n    ")
			}
		}
		{ // do_test "capi3-8.2"
			_dbtmp1, err := frigolite.Open("test.db")
			_ = _dbtmp1 // sqlite3 db connection
			if err != nil { t.Fatal(err) }
			// sqlite3_db_config db DEFENSIVE 0 (unsupported command, not transpiled)
			_res = db.Exec("\n      PRAGMA writable_schema=ON;\n      INSERT INTO sqlite_master VALUES(NULL,NULL,NULL,NULL,NULL);\n    ")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      PRAGMA writable_schema=ON;\n      INSERT INTO sqlite_master VALUES(NULL,NULL,NULL,NULL,NULL);\n    ")
			}
		}
		{ // do_test "capi3-8.3"
			{
				var _catchErr error
				_ = _catchErr // suppress unused warning
				_dbtmp0, err := frigolite.Open("test.db")
				_ = _dbtmp0 // sqlite3 db connection
				if err != nil { t.Fatal(err) }
			}
			_res = db.Exec("\n      SELECT * FROM sqlite_master;\n    ")
			_ = _res // catchsql
		}
		{ // do_test "capi3-8.4"
			os.Remove("test.db")
			_dbtmp2, err := frigolite.Open("test.db")
			_ = _dbtmp2 // sqlite3 db connection
			if err != nil { t.Fatal(err) }
			// sqlite3_db_config db DEFENSIVE 0 (unsupported command, not transpiled)
			_res = db.Exec("\n      CREATE TABLE t1(a);\n      PRAGMA writable_schema=ON;\n      INSERT INTO sqlite_master VALUES('table',NULL,NULL,NULL,NULL);\n    ")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      CREATE TABLE t1(a);\n      PRAGMA writable_schema=ON;\n      INSERT INTO sqlite_master VALUES('table',NULL,NULL,NULL,NULL);\n    ")
			}
		}
		{ // do_test "capi3-8.5"
			{
				var _catchErr error
				_ = _catchErr // suppress unused warning
				_dbtmp0, err := frigolite.Open("test.db")
				_ = _dbtmp0 // sqlite3 db connection
				if err != nil { t.Fatal(err) }
			}
			_res = db.Exec("\n      SELECT * FROM sqlite_master;\n    ")
			_ = _res // catchsql
		}
	}
	os.Remove("test.db")
	os.Remove("test.db-journal")
	code2english = "list \\\nSQLITE_OK         {not an error} \\\nSQLITE_ERROR      {SQL logic error} \\\nSQLITE_PERM       {access permission denied} \\\nSQLITE_ABORT      {query aborted} \\\nSQLITE_BUSY       {database is locked} \\\nSQLITE_LOCKED     {database table is locked} \\\nSQLITE_NOMEM      {out of memory} \\\nSQLITE_READONLY   {attempt to write a readonly database} \\\nSQLITE_INTERRUPT  {interrupted} \\\nSQLITE_IOERR      {disk I/O error} \\\nSQLITE_CORRUPT    {database disk image is malformed} \\\nSQLITE_FULL       {database or disk is full} \\\nSQLITE_CANTOPEN   {unable to open database file} \\\nSQLITE_SCHEMA     {database schema has changed} \\\nSQLITE_CONSTRAINT {constraint failed} \\\nSQLITE_MISMATCH   {datatype mismatch} \\\nSQLITE_MISUSE     {bad parameter or other API misuse} \\\nSQLITE_AUTH       {authorization denied} \\\nSQLITE_RANGE      {column index out of range} \\\nSQLITE_NOTADB     {file is not a database} \\\nunknownerror      {unknown error} \\"
	_ = code2english // suppress unused warning
	test_number = "1"
	_ = test_number // suppress unused warning
	// foreach {code english} code2english
	_items1 := tclSplitList(code2english)
	for _idx1 := 0; _idx1+2 <= len(_items1); _idx1 += 2 {
		code := _items1[_idx1+0]
		_ = code // suppress unused warning
		english := _items1[_idx1+1]
		_ = english // suppress unused warning
		_ = _idx1
			{ // do_test "capi3-9." + test_number
				_res = db.Exec("sqlite3_test_errstr " + code)
				if _res.Error != nil {
					t.Errorf("exec error: %v\n  sql: %s", _res.Error, "sqlite3_test_errstr " + code)
				}
			}
			// incr test_number 1
			{
				_n, _err := strconv.Atoi(test_number)
				if _err == nil {
					test_number = strconv.Itoa(_n + 1)
				}
			}
		}
		if tclBool("permutation" + " != \"nofaultsim\"") {
			{ // do_test "capi3-10-1"
				_dbtmp0, err := frigolite.Open("test.db")
				_ = _dbtmp0 // sqlite3 db connection
				if err != nil { t.Fatal(err) }
				DB = "sqlite3_connection_pointer db"
				_ = DB // suppress unused warning
				// sqlite3_memdebug_fail 1 (unsupported command, not transpiled)
				_res = db.Exec("\n      select * from sqlite_master;\n    ")
				_ = _res // catchsql
			}
			{ // do_test "capi3-10-2"
				// sqlite3_errmsg $::DB (unsupported command, not transpiled)
			}
			{ // do_test "capi3-10-3"
				// utf8 [sqlite3_errmsg16 $::DB] (unsupported command, not transpiled)
			}
			// sqlite3_memdebug_fail -1 (unsupported command, not transpiled)
			{ // do_test "capi3-10-4"
				_dbtmp1, err := frigolite.Open("test.db")
				_ = _dbtmp1 // sqlite3 db connection
				if err != nil { t.Fatal(err) }
				DB = "sqlite3_connection_pointer db"
				_ = DB // suppress unused warning
				// sqlite3_memdebug_fail 1 (unsupported command, not transpiled)
				_res = db.Exec("\n      select * from sqlite_master where rowid>5;\n    ")
				_ = _res // catchsql
			}
			{ // do_test "capi3-10-5"
				// sqlite3_errmsg $::DB (unsupported command, not transpiled)
			}
			{ // do_test "capi3-10-6"
				// utf8 [sqlite3_errmsg16 $::DB] (unsupported command, not transpiled)
			}
			// sqlite3_memdebug_fail -1 (unsupported command, not transpiled)
		}
		_dbtmp2, err := frigolite.Open("test.db")
		_ = _dbtmp2 // sqlite3 db connection
		if err != nil { t.Fatal(err) }
		DB = "sqlite3_connection_pointer db"
		_ = DB // suppress unused warning
		// sqlite_register_test_function $DB func (unsupported command, not transpiled)
		{ // do_test "capi3-11.1"
			_res = db.Exec("\n    BEGIN;\n    CREATE TABLE t1(a, b);\n    INSERT INTO t1 VALUES(1, 'int');\n    INSERT INTO t1 VALUES(2, 'notatype');\n  ")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    BEGIN;\n    CREATE TABLE t1(a, b);\n    INSERT INTO t1 VALUES(1, 'int');\n    INSERT INTO t1 VALUES(2, 'notatype');\n  ")
			}
		}
		{ // do_test "capi3-11.1.1"
			// sqlite3_get_autocommit $DB (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.2"
			STMT = "sqlite3_prepare $DB \"SELECT func(b, a) FROM t1\" -1 TAIL"
			_ = STMT // suppress unused warning
			// sqlite3_step $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.3.1"
			_res = db.Exec("\n    COMMIT;\n  ")
			_ = _res // catchsql
		}
		{ // do_test "capi3-11.3.2"
			// sqlite3_extended_errcode $DB (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.3.3"
			// sqlite3_get_autocommit $DB (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.3.4"
			_res = db.Exec("PRAGMA lock_status")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "PRAGMA lock_status")
			}
		}
		{ // do_test "capi3-11.4"
			// sqlite3_step $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.5"
			// sqlite3_finalize $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.6"
			_res = db.Exec("\n    SELECT * FROM t1;\n  ")
			_ = _res // catchsql
		}
		{ // do_test "capi3-11.7"
			// sqlite3_get_autocommit $DB (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.8"
			_res = db.Exec("\n    CREATE TABLE t2(a);\n    INSERT INTO t2 VALUES(1);\n    INSERT INTO t2 VALUES(2);\n    BEGIN;\n    INSERT INTO t2 VALUES(3);\n  ")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE TABLE t2(a);\n    INSERT INTO t2 VALUES(1);\n    INSERT INTO t2 VALUES(2);\n    BEGIN;\n    INSERT INTO t2 VALUES(3);\n  ")
			}
		}
		{ // do_test "capi3-11.8.1"
			// sqlite3_get_autocommit $DB (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.9"
			STMT = "sqlite3_prepare $DB \"SELECT a FROM t2\" -1 TAIL"
			_ = STMT // suppress unused warning
			// sqlite3_step $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.9.1"
			// sqlite3_get_autocommit $DB (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.9.2"
			_res = db.Exec("\n    ROLLBACK;\n  ")
			_ = _res // catchsql
		}
		{ // do_test "capi3-11.9.3"
			// sqlite3_get_autocommit $DB (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.10"
			// sqlite3_step $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.11"
			// sqlite3_step $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.12armor"
			// sqlite3_step $STMT (unsupported command, not transpiled)
			// sqlite3_step $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.13"
			// sqlite3_finalize $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.14"
			r = db.Query("\n    SELECT a FROM t2;\n  ")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT a FROM t2;\n  ")
			}
		}
		{ // do_test "capi3-11.14.1"
			// sqlite3_get_autocommit $DB (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.15"
			_res = db.Exec("\n    ROLLBACK;\n  ")
			_ = _res // catchsql
		}
		{ // do_test "capi3-11.15.1"
			// sqlite3_get_autocommit $DB (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.16"
			r = db.Query("\n    SELECT a FROM t2;\n  ")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT a FROM t2;\n  ")
			}
		}
		{ // do_test "capi3-11.17"
			_res = db.Exec("\n    BEGIN;\n  ")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    BEGIN;\n  ")
			}
		}
		{ // do_test "capi3-11.18"
			STMT = "sqlite3_prepare $DB \"SELECT a FROM t1\" -1 TAIL"
			_ = STMT // suppress unused warning
			_res = db.Exec("\n    COMMIT;\n  ")
			_ = _res // catchsql
		}
		{ // do_test "capi3-11.19"
			// sqlite3_step $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-11.20"
			_res = db.Exec("\n    BEGIN;\n    COMMIT;\n  ")
			_ = _res // catchsql
		}
		{ // do_test "capi3-11.20"
			// sqlite3_reset $STMT (unsupported command, not transpiled)
			_res = db.Exec("\n    COMMIT;\n  ")
			_ = _res // catchsql
		}
		{ // do_test "capi3-11.21"
			// sqlite3_finalize $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-12.1"
			STMT = "sqlite3_prepare $DB \"SELECT a FROM t2\" -1 TAIL"
			_ = STMT // suppress unused warning
			// sqlite3_step $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-12.2"
			_res = db.Exec("\n    INSERT INTO t1 VALUES(3, NULL);\n  ")
			_ = _res // catchsql
		}
		{ // do_test "capi3-12.3"
			_res = db.Exec("\n    INSERT INTO t2 VALUES(4);\n  ")
			_ = _res // catchsql
		}
		{ // do_test "capi3-12.4"
			_res = db.Exec("\n    BEGIN;\n    INSERT INTO t1 VALUES(4, NULL);\n  ")
			_ = _res // catchsql
		}
		{ // do_test "capi3-12.5"
			// sqlite3_step $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-12.5.1"
			// sqlite3_step $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-12.6"
			// sqlite3_step $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-12.7"
			// sqlite3_finalize $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-12.8"
			r = db.Query("\n    COMMIT;\n    SELECT a FROM t1;\n  ")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    COMMIT;\n    SELECT a FROM t1;\n  ")
			}
		}
		if tclBool("llength [info commands sqlite3_clear_bindings]" + ">0") {
			{ // do_test "capi3-13.1"
				_res = db.Exec("\n      DELETE FROM t1;\n    ")
				if _res.Error != nil {
					t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      DELETE FROM t1;\n    ")
				}
				STMT = "sqlite3_prepare $DB \"INSERT INTO t1 VALUES(?, ?)\" -1 TAIL"
				_ = STMT // suppress unused warning
				// sqlite3_step $STMT (unsupported command, not transpiled)
			}
			{ // do_test "capi3-13.2"
				// sqlite3_reset $STMT (unsupported command, not transpiled)
				// sqlite3_bind_text $STMT 1 hello 5 (unsupported command, not transpiled)
				// sqlite3_bind_text $STMT 2 world 5 (unsupported command, not transpiled)
				// sqlite3_step $STMT (unsupported command, not transpiled)
			}
			{ // do_test "capi3-13.3"
				// sqlite3_reset $STMT (unsupported command, not transpiled)
				// sqlite3_clear_bindings $STMT (unsupported command, not transpiled)
				// sqlite3_step $STMT (unsupported command, not transpiled)
			}
			{ // do_test "capi3-13-4"
				// sqlite3_finalize $STMT (unsupported command, not transpiled)
				r = db.Query("\n      SELECT * FROM t1;\n    ")
				if r.Error != nil {
					t.Errorf("query error: %v\n  sql: %s", r.Error, "\n      SELECT * FROM t1;\n    ")
				}
			}
		}
		if tclBool("llength [info commands sqlite3_sleep]" + ">0") {
			{ // do_test "capi3-13-5"
				ms = "sqlite3_sleep 80"
				_ = ms // suppress unused warning
				// expr $ms==80 || $ms==1000 (not evaluated)
			}
		}
		if tclBool("clang_sanitize_address" + "==0") {
			{ // do_test "capi3-14.1-misuse"
	_ = rc // suppress unused warning
	_ = msg // suppress unused warning
				{ // catch block
					var _catchErr error
					// sqlite3_bind_text 0 1 hello 5 (unsupported command, not transpiled)
					if _catchErr != nil {
						rc = "1"
						msg = _catchErr.Error()
					} else {
						rc = "0"
						msg = ""
					}
				}
				rc = tclListAppend(rc, msg)
			}
		}
		{ // do_test "capi3-15.1"
			sql = "SELECT * FROM t2"
			_ = sql // suppress unused warning
			nbytes = strconv.Itoa(len(sql))
			_ = nbytes // suppress unused warning
			sql += " WHERE a==1"
			STMT = "sqlite3_prepare $DB $sql $nbytes TAIL"
			_ = STMT // suppress unused warning
			// sqlite3_step $STMT (unsupported command, not transpiled)
			// sqlite3_column_int $STMT 0 (unsupported command, not transpiled)
		}
		{ // do_test "capi3-15.2"
			// sqlite3_step $STMT (unsupported command, not transpiled)
			// sqlite3_column_int $STMT 0 (unsupported command, not transpiled)
		}
		{ // do_test "capi3-15.3"
			// sqlite3_finalize $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-15.4"
			sql = "SELECT 1234567890"
			_ = sql // suppress unused warning
			STMT = "sqlite3_prepare $DB $sql 8 TAIL"
			_ = STMT // suppress unused warning
			// sqlite3_step $STMT (unsupported command, not transpiled)
			v1 = "0"
			_ = v1 // suppress unused warning
			// sqlite3_finalize $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-15.5"
			sql = "SELECT 1234567890"
			_ = sql // suppress unused warning
			STMT = "sqlite3_prepare $DB $sql 9 TAIL"
			_ = STMT // suppress unused warning
			// sqlite3_step $STMT (unsupported command, not transpiled)
			v1 = "0"
			_ = v1 // suppress unused warning
			// sqlite3_finalize $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-15.6"
			sql = "SELECT 1234567890"
			_ = sql // suppress unused warning
			STMT = "sqlite3_prepare $DB $sql 12 TAIL"
			_ = STMT // suppress unused warning
			// sqlite3_step $STMT (unsupported command, not transpiled)
			v1 = "0"
			_ = v1 // suppress unused warning
			// sqlite3_finalize $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-15.7"
			sql = "SELECT 12.34567890"
			_ = sql // suppress unused warning
			STMT = "sqlite3_prepare $DB $sql 12 TAIL"
			_ = STMT // suppress unused warning
			// sqlite3_step $STMT (unsupported command, not transpiled)
			v1 = "sqlite3_column_double $STMT 0"
			_ = v1 // suppress unused warning
			// sqlite3_finalize $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-15.8"
			sql = "SELECT 12.34567890"
			_ = sql // suppress unused warning
			STMT = "sqlite3_prepare $DB $sql 14 TAIL"
			_ = STMT // suppress unused warning
			// sqlite3_step $STMT (unsupported command, not transpiled)
			v1 = "sqlite3_column_double $STMT 0"
			_ = v1 // suppress unused warning
			// sqlite3_finalize $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-16.1"
			sql = "DROP TABLE IF EXISTS t3"
			_ = sql // suppress unused warning
			STMT = "sqlite3_prepare $DB $sql -1 TAIL"
			_ = STMT // suppress unused warning
			// sqlite3_finalize $STMT (unsupported command, not transpiled)
			// expr $STMT!="" (not evaluated)
		}
		{ // do_test "capi3-16.2"
			sql = "CREATE TABLE IF NOT EXISTS t1(x,y)"
			_ = sql // suppress unused warning
			STMT = "sqlite3_prepare $DB $sql -1 TAIL"
			_ = STMT // suppress unused warning
			// sqlite3_finalize $STMT (unsupported command, not transpiled)
			// expr $STMT!="" (not evaluated)
		}
		{ // do_test "capi3-16.3"
			STMT = "sqlite3_prepare $DB {} -1 TAIL"
			_ = STMT // suppress unused warning
			// sqlite3_finalize $STMT (unsupported command, not transpiled)
			// expr $STMT=="" (not evaluated)
		}
		{ // do_test "capi3-16.4"
			STMT = "sqlite3_prepare $DB {;} -1 TAIL"
			_ = STMT // suppress unused warning
			// sqlite3_finalize $STMT (unsupported command, not transpiled)
			// expr $STMT=="" (not evaluated)
		}
		{ // do_test "capi3-17.1"
			STMT = "sqlite3_prepare $DB {SELECT * FROM t2} -1 TAIL"
			_ = STMT // suppress unused warning
			// sqlite3_step $STMT (unsupported command, not transpiled)
			// sqlite3_column_int $STMT 0 (unsupported command, not transpiled)
		}
		{ // do_test "capi3-17.2"
			// sqlite3_reset $STMT (unsupported command, not transpiled)
			// sqlite3_column_int $STMT 0 (unsupported command, not transpiled)
		}
		{ // do_test "capi3-17.3"
			// sqlite3_finalize $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-18.1"
			STMT = "sqlite3_prepare db {SELECT * FROM t2} -1 TAIL"
			_ = STMT // suppress unused warning
			db2, err = frigolite.Open("test.db")
			if err != nil { t.Fatal(err) }
			db2.Exec("CREATE TABLE t3(x)")
			if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
			db2.Close()
			// sqlite3_step $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-18.2"
			// sqlite3_reset $STMT (unsupported command, not transpiled)
			// sqlite3_errcode db (unsupported command, not transpiled)
		}
		{ // do_test "capi3-18.3"
			// sqlite3_errmsg db (unsupported command, not transpiled)
		}
		{ // do_test "capi3-18.4"
			// sqlite3_step $STMT (unsupported command, not transpiled)
		}
		{ // do_test "capi3-18.5"
			// sqlite3_reset $STMT (unsupported command, not transpiled)
			// sqlite3_errcode db (unsupported command, not transpiled)
		}
		{ // do_test "capi3-18.6"
			// sqlite3_errmsg db (unsupported command, not transpiled)
		}
		// sqlite3_finalize $STMT (unsupported command, not transpiled)
		{ // do_test "capi3-19.1"
			// sqlite3_prepare_tkt3134 db (unsupported command, not transpiled)
		}
		{ // "20.1"
			_res = db.Exec("\n  CREATE TABLE t4(x);\n  INSERT INTO t4 VALUES('abcdefghij');\n")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE t4(x);\n  INSERT INTO t4 VALUES('abcdefghij');\n")
			}
		}
		{ // do_test "20.2"
			stmt = "sqlite3_prepare db \"SELECT * FROM t4\" -1 dummy"
			_ = stmt // suppress unused warning
			// sqlite3_step $stmt (unsupported command, not transpiled)
		}
		{ // do_test "20.3"
			// sqlite3_column_type $stmt 0 (unsupported command, not transpiled)
		}
		{ // do_test "20.4"
			// sqlite3_column_blob $stmt 0 (unsupported command, not transpiled)
		}
		{ // do_test "20.5"
			// sqlite3_column_type $stmt 0 (unsupported command, not transpiled)
		}
		{ // do_test "20.6"
			// sqlite3_finalize $stmt (unsupported command, not transpiled)
		}
		if tclBool("!" + "info exists tester_do_binarylog") {
			// vfs_unregister_all (unsupported command, not transpiled)
			{ // do_test "capi3-20.1"
				// sqlite3_sleep 100 (unsupported command, not transpiled)
			}
			// vfs_reregister_all (unsupported command, not transpiled)
		}
}
