// Code generated by tcl2go; DO NOT EDIT.
package tkt_f67b41381

import (
"github.com/pijalu/frigolite"
"testing"
)

func Test_tkt_f67b41381a(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning

	// set testdir: test directory (not used in Go test context)
	var testprefix = "tkt-f67b41381a"
	_ = testprefix // suppress unused warning
	{ // "1.0"
		r = db.Query("\n  CREATE TABLE t1(a);\n  INSERT INTO t1 VALUES(1);\n  ALTER TABLE t1 ADD COLUMN b DEFAULT 2;\n  CREATE TABLE t2(a, b);\n  INSERT INTO t2 SELECT * FROM t1;\n  SELECT * FROM t2;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  CREATE TABLE t1(a);\n  INSERT INTO t1 VALUES(1);\n  ALTER TABLE t1 ADD COLUMN b DEFAULT 2;\n  CREATE TABLE t2(a, b);\n  INSERT INTO t2 SELECT * FROM t1;\n  SELECT * FROM t2;\n")
			return
		}
		got := flatten(r)
		want := "1 2"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	// foreach {tn tbls xfer} "\n  1 { CREATE TABLE t1(a, b); CREATE TABLE t2(a, b)             }             1\n  2 { CREATE TABLE t1(a, b DEFAULT 'x'); CREATE TABLE t2(a, b) }             0\n  3 { CREATE TABLE t1(a, b DEFAULT 'x'); CREATE TABLE t2(a, b DEFAULT 'x') } 1\n  4 { CREATE TABLE t1(a, b DEFAULT NULL); CREATE TABLE t2(a, b) }            0\n  5 { CREATE TABLE t1(a DEFAULT 2, b); CREATE TABLE t2(a DEFAULT 1, b) }     1\n  6 { CREATE TABLE t1(a DEFAULT 1, b); CREATE TABLE t2(a DEFAULT 1, b) }     1\n  7 { CREATE TABLE t1(a DEFAULT 1, b DEFAULT 1);\n      CREATE TABLE t2(a DEFAULT 3, b DEFAULT 1) }                            1\n  8 { CREATE TABLE t1(a DEFAULT 1, b DEFAULT 1);\n      CREATE TABLE t2(a DEFAULT 3, b DEFAULT 3) }                            0\n\n"
	_items := tclSplitList("\n  1 { CREATE TABLE t1(a, b); CREATE TABLE t2(a, b)             }             1\n  2 { CREATE TABLE t1(a, b DEFAULT 'x'); CREATE TABLE t2(a, b) }             0\n  3 { CREATE TABLE t1(a, b DEFAULT 'x'); CREATE TABLE t2(a, b DEFAULT 'x') } 1\n  4 { CREATE TABLE t1(a, b DEFAULT NULL); CREATE TABLE t2(a, b) }            0\n  5 { CREATE TABLE t1(a DEFAULT 2, b); CREATE TABLE t2(a DEFAULT 1, b) }     1\n  6 { CREATE TABLE t1(a DEFAULT 1, b); CREATE TABLE t2(a DEFAULT 1, b) }     1\n  7 { CREATE TABLE t1(a DEFAULT 1, b DEFAULT 1);\n      CREATE TABLE t2(a DEFAULT 3, b DEFAULT 1) }                            1\n  8 { CREATE TABLE t1(a DEFAULT 1, b DEFAULT 1);\n      CREATE TABLE t2(a DEFAULT 3, b DEFAULT 3) }                            0\n\n")
	for _idx := 0; _idx+3 <= len(_items); _idx += 3 {
		tn := _items[_idx+0]
		_ = tn // suppress unused warning
		tbls := _items[_idx+1]
		_ = tbls // suppress unused warning
		xfer := _items[_idx+2]
		_ = xfer // suppress unused warning
		_ = _idx
			_res = db.Exec(" DROP TABLE t1; DROP TABLE t2 ")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, " DROP TABLE t1; DROP TABLE t2 ")
			}
			_res = db.Exec(tbls)
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, tbls)
			}
			var res = "1"
			_ = res // suppress unused warning
			_res = db.Exec(" EXPLAIN INSERT INTO t1 SELECT * FROM t2 ")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, " EXPLAIN INSERT INTO t1 SELECT * FROM t2 ")
			}
			{ // do_test "2." + tn
				_res = db.Exec("list set res")
				if _res.Error != nil {
					t.Errorf("exec error: %v\n  sql: %s", _res.Error, "list set res")
				}
			}
		}
}
