// Code generated by tcl2go; DO NOT EDIT.
package alter

import (
"github.com/pijalu/frigolite"
"testing"
)

func Test_alter2(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	// set testdir: test directory (not used in Go test context)
	t.Errorf("TODO: %s not implemented in frigolite", "do_not_use_codec")
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	{ // do_test "alter2-1.0"
		_res = db.Exec("SELECT substr('abcdefg',1,3)")
		_ = _res // catchsql
	}
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_db_config db DEFENSIVE 0")
	{ // do_test "alter2-1.1"
		_res = db.Exec("\n    CREATE TABLE abc(a, b);\n    INSERT INTO abc VALUES(1, 2);\n    INSERT INTO abc VALUES(3, 4);\n    INSERT INTO abc VALUES(5, 6);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE TABLE abc(a, b);\n    INSERT INTO abc VALUES(1, 2);\n    INSERT INTO abc VALUES(3, 4);\n    INSERT INTO abc VALUES(5, 6);\n  ")
		}
	}
	{ // do_test "alter2-1.2"
		t.Errorf("TODO: %s not implemented in frigolite", "alter_table abc {CREATE TABLE abc(a, b, c);}")
	}
	{ // do_test "alter2-1.3"
		r = db.Query("\n    SELECT * FROM abc;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT * FROM abc;\n  ")
		}
	}
	{ // do_test "alter2-1.4"
		r = db.Query("\n    UPDATE abc SET c = 10 WHERE a = 1;\n    SELECT * FROM abc;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    UPDATE abc SET c = 10 WHERE a = 1;\n    SELECT * FROM abc;\n  ")
		}
	}
	{ // do_test "alter2-1.5"
		_res = db.Exec("\n    CREATE INDEX abc_i ON abc(c);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE INDEX abc_i ON abc(c);\n  ")
		}
	}
	{ // do_test "alter2-1.6"
		r = db.Query("\n    SELECT c FROM abc ORDER BY c;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT c FROM abc ORDER BY c;\n  ")
		}
	}
	{ // do_test "alter2-1.7"
		r = db.Query("\n    SELECT * FROM abc WHERE c = 10;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT * FROM abc WHERE c = 10;\n  ")
		}
	}
	{ // do_test "alter2-1.8"
		r = db.Query("\n    SELECT sum(a), c FROM abc GROUP BY c;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT sum(a), c FROM abc GROUP BY c;\n  ")
		}
	}
	{ // do_test "alter2-1.9"
		t.Errorf("TODO: %s not implemented in frigolite", "alter_table abc {CREATE TABLE abc(a, b, c, d);}")
		if tclBool("permutation" + " == \"prepare\"") {
		}
		r = db.Query(" SELECT * FROM abc; ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM abc; ")
		}
		r = db.Query("\n    UPDATE abc SET d = 11 WHERE c IS NULL AND a<4;\n    SELECT * FROM abc;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    UPDATE abc SET d = 11 WHERE c IS NULL AND a<4;\n    SELECT * FROM abc;\n  ")
		}
	}
	{ // do_test "alter2-1.10"
		r = db.Query("\n    SELECT typeof(d) FROM abc;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT typeof(d) FROM abc;\n  ")
		}
	}
	{ // do_test "alter2-1.99"
		_res = db.Exec("\n    DROP TABLE abc;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    DROP TABLE abc;\n  ")
		}
	}
	{ // do_test "alter2-4.1"
		t.Errorf("TODO: %s not implemented in frigolite", "set_file_format 5")
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			db, err := frigolite.Open("test.db")
			defer db.Close()
			if err != nil { t.Fatal(err) }
		}
		var _unnamed_var = ""
		_ = _unnamed_var // suppress unused warning
	}
	{ // do_test "alter2-4.2"
		_res = db.Exec(" SELECT * FROM sqlite_master; ")
		_ = _res // catchsql
		_res = db.Exec(" SELECT * FROM sqlite_master; ")
		_ = _res // catchsql
	}
	{ // do_test "alter2-4.3"
		t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_errcode db")
	}
	{ // do_test "alter2-4.4"
		var _DB = "sqlite3_connection_pointer db" // TCL namespace variable
		_ = _DB // suppress unused warning
		_res = db.Exec("\n    SELECT * FROM sqlite_master;\n  ")
		_ = _res // catchsql
	}
	{ // do_test "alter2-4.5"
		t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_errcode db")
	}
	var default_file_format = "$SQLITE_DEFAULT_FILE_FORMAT==4 ? 4 : 1"
	_ = default_file_format // suppress unused warning
	{ // do_test "alter2-6.1"
		t.Errorf("TODO: %s not implemented in frigolite", "set_file_format 2")
		db, err := frigolite.Open("test.db")
		defer db.Close()
		if err != nil { t.Fatal(err) }
		t.Errorf("TODO: %s not implemented in frigolite", "get_file_format")
	}
	{ // do_test "alter2-6.3"
		_res = db.Exec("\n    CREATE TABLE t1(a, b);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE TABLE t1(a, b);\n  ")
		}
		t.Errorf("TODO: %s not implemented in frigolite", "get_file_format")
	}
	{ // do_test "alter2-7.1"
		r = db.Query("\n    DROP TABLE t1;\n    CREATE TABLE t1(a);\n    INSERT INTO t1 VALUES(1);\n    INSERT INTO t1 VALUES(2);\n    INSERT INTO t1 VALUES(3);\n    INSERT INTO t1 VALUES(4);\n    SELECT * FROM t1;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    DROP TABLE t1;\n    CREATE TABLE t1(a);\n    INSERT INTO t1 VALUES(1);\n    INSERT INTO t1 VALUES(2);\n    INSERT INTO t1 VALUES(3);\n    INSERT INTO t1 VALUES(4);\n    SELECT * FROM t1;\n  ")
		}
	}
	{ // do_test "alter2-7.2"
		var sql = "CREATE TABLE t1(a, b DEFAULT '123', c INTEGER DEFAULT '123')"
		_ = sql // suppress unused warning
		t.Errorf("TODO: %s not implemented in frigolite", "alter_table t1 $sql 3")
		r = db.Query("\n    SELECT * FROM t1 LIMIT 1;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT * FROM t1 LIMIT 1;\n  ")
		}
	}
	{ // do_test "alter2-7.3"
		r = db.Query("\n    SELECT a, typeof(a), b, typeof(b), c, typeof(c) FROM t1 LIMIT 1;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT a, typeof(a), b, typeof(b), c, typeof(c) FROM t1 LIMIT 1;\n  ")
		}
	}
	{ // do_test "alter2-7.4"
		r = db.Query("\n    SELECT a, typeof(a), b, typeof(b), c, typeof(c) FROM t1 LIMIT 1;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT a, typeof(a), b, typeof(b), c, typeof(c) FROM t1 LIMIT 1;\n  ")
		}
	}
	{ // do_test "alter2-7.5"
		var sql = "CREATE TABLE t1(a, b DEFAULT -123.0, c VARCHAR(10) default 5)"
		_ = sql // suppress unused warning
		t.Errorf("TODO: %s not implemented in frigolite", "alter_table t1 $sql 3")
		r = db.Query("\n    SELECT a, typeof(a), b, typeof(b), c, typeof(c) FROM t1 LIMIT 1;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT a, typeof(a), b, typeof(b), c, typeof(c) FROM t1 LIMIT 1;\n  ")
		}
	}
	{ // do_test "alter2-8.2"
		r = db.Query("\n    UPDATE t1 SET c = 10 WHERE a = 1;\n    SELECT a, typeof(a), b, typeof(b), c, typeof(c) FROM t1 LIMIT 1;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    UPDATE t1 SET c = 10 WHERE a = 1;\n    SELECT a, typeof(a), b, typeof(b), c, typeof(c) FROM t1 LIMIT 1;\n  ")
		}
	}
}
