// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package queryonly

import (
"github.com/pijalu/frigolite"
"os"
"testing"
)

func Test_queryonly(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	{ // "queryonly-1.1"
		r = db.Query("\n  CREATE TABLE t1(a);\n  INSERT INTO t1 VALUES(123),(456);\n  SELECT a FROM t1 ORDER BY a;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  CREATE TABLE t1(a);\n  INSERT INTO t1 VALUES(123),(456);\n  SELECT a FROM t1 ORDER BY a;\n")
			return
		}
		got := flatten(r)
		want := "123 456"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "queryonly-1.2"
		r = db.Query("\n  PRAGMA query_only;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  PRAGMA query_only;\n")
			return
		}
		got := flatten(r)
		want := "0"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "queryonly-1.3"
		r = db.Query("\n  PRAGMA query_only=ON;\n  PRAGMA query_only;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  PRAGMA query_only=ON;\n  PRAGMA query_only;\n")
			return
		}
		got := flatten(r)
		want := "1"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // do_test "queryonly-1.4"
		_res = db.Exec("INSERT INTO t1 VALUES(789);")
		_ = _res // catchsql
	}
	{ // do_test "queryonly-1.5"
		_res = db.Exec("DELETE FROM t1;")
		_ = _res // catchsql
	}
	{ // do_test "queryonly-1.6"
		_res = db.Exec("UPDATE t1 SET a=a+1;")
		_ = _res // catchsql
	}
	{ // do_test "queryonly-1.7"
		_res = db.Exec("CREATE TABLE t2(b);")
		_ = _res // catchsql
	}
	{ // do_test "queryonly-1.8"
		_res = db.Exec("CREATE INDEX t1a ON t1(a);")
		_ = _res // catchsql
	}
	{ // do_test "queryonly-1.9"
		_res = db.Exec("DROP TABLE t1;")
		_ = _res // catchsql
	}
	{ // do_test "queryonly-1.10"
		_res = db.Exec("ANALYZE;")
		_ = _res // catchsql
	}
	{ // "queryonly-1.11"
		r = db.Query("\n  SELECT a FROM t1 ORDER BY a;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT a FROM t1 ORDER BY a;\n")
			return
		}
		got := flatten(r)
		want := "123 456"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "queryonly-2.2"
		r = db.Query("\n  PRAGMA query_only;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  PRAGMA query_only;\n")
			return
		}
		got := flatten(r)
		want := "1"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "queryonly-2.3"
		r = db.Query("\n  PRAGMA query_only=OFF;\n  PRAGMA query_only;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  PRAGMA query_only=OFF;\n  PRAGMA query_only;\n")
			return
		}
		got := flatten(r)
		want := "0"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "queryonly-2.4"
		r = db.Query("\n  INSERT INTO t1 VALUES(789);\n  SELECT a FROM t1 ORDER BY a;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  INSERT INTO t1 VALUES(789);\n  SELECT a FROM t1 ORDER BY a;\n")
			return
		}
		got := flatten(r)
		want := "123 456 789"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "queryonly-2.5"
		r = db.Query("\n  UPDATE t1 SET a=a+1;\n  SELECT a FROM t1 ORDER BY a;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  UPDATE t1 SET a=a+1;\n  SELECT a FROM t1 ORDER BY a;\n")
			return
		}
		got := flatten(r)
		want := "124 457 790"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
}
