// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package tkt_99378177930f87bd

import (
"testing"
)

func Test_tkt_99378177930f87bd(t *testing.T) {}
// skipped: JSON operators (->>) not implemented N-A
