// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package walprotocol

import (
"github.com/pijalu/frigolite"
"os"
"testing"
)

func Test_walprotocol(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var testprefix string
	_ = testprefix // pre-declared from TCL source
	var locks string
	_ = locks // pre-declared from TCL source
	var _r string
	_ = _r // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source
	var lock string
	_ = lock // pre-declared from TCL source
	var spec string
	_ = spec // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	testprefix = "walprotocol"
	_ = testprefix // suppress unused warning
	{ // "1.0"
		r = db.Query("\n  PRAGMA journal_mode = wal;\n  CREATE TABLE x(y);\n  INSERT INTO x VALUES('z');\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  PRAGMA journal_mode = wal;\n  CREATE TABLE x(y);\n  INSERT INTO x VALUES('z');\n")
			return
		}
		got := flatten(r)
		want := "wal"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	// proc definition (not transpiled)
	{ // do_test "1.1"
		// testvfs T (unsupported command, not transpiled)
		// T filter xShmLock (unsupported command, not transpiled)
		// T script lock_callback (unsupported command, not transpiled)
		locks = "" // TCL namespace variable
		_ = locks // suppress unused warning
		_dbtmp0, err := frigolite.Open("test.db")
		_ = _dbtmp0 // sqlite3 db connection
		if err != nil { t.Fatal(err) }
		r = db.Query(" SELECT * FROM x ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM x ")
		}
		_ = tclLRange(locks, "0", "11") // lrange result
	}
	{ // do_test "1.2"
		db.Close()
		locks = "" // TCL namespace variable
		_ = locks // suppress unused warning
		db, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		r = db.Query(" SELECT * FROM x ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM x ")
		}
		_ = tclLRange(locks, "0", "11") // lrange result
	}
	// proc definition (not transpiled)
	_putsMsg := "# Warning: This next test case causes SQLite to call xSleep(1) 100 times."
	_ = _putsMsg
	_putsMsg = "# Normally this equates to a delay of roughly 10 seconds, but if SQLite"
	_ = _putsMsg
	_putsMsg = "# is built on unix without HAVE_USLEEP defined, it may be much longer."
	_ = _putsMsg
	{ // do_test "1.3"
		db.Close()
		locks = "" // TCL namespace variable
		_ = locks // suppress unused warning
		db, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		_res = db.Exec(" SELECT * FROM x ")
		_ = _res // catchsql
	}
	_putsMsg = "# Warning: Same again!"
	_ = _putsMsg
	// proc definition (not transpiled)
	{ // do_test "1.4"
		db.Close()
		locks = "" // TCL namespace variable
		_ = locks // suppress unused warning
		db, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		_res = db.Exec(" SELECT * FROM x ")
		_ = _res // catchsql
	}
	_putsMsg = "# Warning: Third time!"
	_ = _putsMsg
	// proc definition (not transpiled)
	{ // do_test "1.5"
		db.Close()
		locks = "" // TCL namespace variable
		_ = locks // suppress unused warning
		db, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		_res = db.Exec(" SELECT * FROM x ")
		_ = _res // catchsql
	}
	db.Close()
	// T delete (unsupported command, not transpiled)
	{ // do_test "2.1"
		os.Remove("test.db")
		db, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		db2 = db // sqlite3 db2 test.db: alias to main in-memory db
		_ = db2
		r = db.Query("\n    PRAGMA auto_vacuum = off;\n    PRAGMA journal_mode = WAL;\n    CREATE TABLE b(c);\n    INSERT INTO b VALUES('Tehran');\n    INSERT INTO b VALUES('Qom');\n    INSERT INTO b VALUES('Markazi');\n    PRAGMA wal_checkpoint;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    PRAGMA auto_vacuum = off;\n    PRAGMA journal_mode = WAL;\n    CREATE TABLE b(c);\n    INSERT INTO b VALUES('Tehran');\n    INSERT INTO b VALUES('Qom');\n    INSERT INTO b VALUES('Markazi');\n    PRAGMA wal_checkpoint;\n  ")
		}
	}
	{ // do_test "2.2"
		r = db.Query(" SELECT * FROM b ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM b ")
		}
	}
	{ // do_test "2.3"
		_res = db.Exec(" SELECT * FROM b ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " SELECT * FROM b ")
		}
	}
	{ // do_test "2.4"
		_res = db.Exec("\n    INSERT INTO b VALUES('Gilan');\n    INSERT INTO b VALUES('Ardabil');\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    INSERT INTO b VALUES('Gilan');\n    INSERT INTO b VALUES('Ardabil');\n  ")
		}
	}
	_ = db2 // close db2: aliased to db, no-op
	// faultsim_save_and_close (unsupported command, not transpiled)
	// testvfs T -default 1 (unsupported command, not transpiled)
	// faultsim_restore_and_reopen (unsupported command, not transpiled)
	// T filter xShmLock (unsupported command, not transpiled)
	// T script lock_callback (unsupported command, not transpiled)
	// proc definition (not transpiled)
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	db2 = db // sqlite3 db2 test.db: alias to main in-memory db
	_ = db2
	_putsMsg = "# Warning: Another slow test!"
	_ = _putsMsg
	{ // do_test "2.5"
		r = db.Query(" SELECT * FROM b ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM b ")
		}
	}
	{ // do_test "2.6"
		_ = _r // TCL namespace variable (query)
	}
	db.Close()
	_ = db2 // close db2: aliased to db, no-op
	// faultsim_restore_and_reopen (unsupported command, not transpiled)
	db2 = db // sqlite3 db2 test.db: alias to main in-memory db
	_ = db2
	// T filter xShmLock (unsupported command, not transpiled)
	// T script lock_callback (unsupported command, not transpiled)
	// proc definition (not transpiled)
	_putsMsg = "# Warning: Last one!"
	_ = _putsMsg
	{ // do_test "2.7"
		r = db.Query(" SELECT * FROM b ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM b ")
		}
	}
	{ // do_test "2.8"
		_ = _r // TCL namespace variable (query)
	}
	db.Close()
	_ = db2 // close db2: aliased to db, no-op
	// T delete (unsupported command, not transpiled)
}
