// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package pagerfault3

import (
"testing"
)

func Test_pagerfault3(t *testing.T) {}
// skipped: VFS/fault-injection harness N-A
