// Code generated by tcl2go; DO NOT EDIT.
package tkt

import (
"github.com/pijalu/frigolite"
"os"
"testing"
)

func Test_tkt2820(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning

	// set testdir: test directory (not used in Go test context)
	// proc definition (not transpiled)
	t.Skipf("TODO: %s not implemented in frigolite", "test_schema_change 1 {\n  CREATE TABLE t1(a);\n} {\n  DROP TABLE t1\n} {t1}")
	t.Skipf("TODO: %s not implemented in frigolite", "test_schema_change 2 {\n  CREATE TABLE t1(a);\n  CREATE TABLE t2(b);\n} {\n  DROP TABLE t2\n} {t1 t2}")
	t.Skipf("TODO: %s not implemented in frigolite", "test_schema_change 3 {\n  CREATE TABLE t1(a);\n  CREATE INDEX i1 ON t1(a);...} {\n  DROP INDEX i1\n} {i1 t1}")
	{ // do_test "tkt2820-4.1"
		os.Remove("test.db")
		db, err := frigolite.Open("test.db")
		defer db.Close()
		if err != nil { t.Fatal(err) }
		_res = db.Exec("\n    CREATE TABLE t1(a INTEGER PRIMARY KEY);\n    INSERT INTO t1 VALUES(1);\n    INSERT INTO t1 VALUES(2);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE TABLE t1(a INTEGER PRIMARY KEY);\n    INSERT INTO t1 VALUES(1);\n    INSERT INTO t1 VALUES(2);\n  ")
		}
		_res = db.Exec("SELECT name FROM sqlite_master")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "SELECT name FROM sqlite_master")
		}
		_res = db.Exec("SELECT a FROM t1 ORDER BY a")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "SELECT a FROM t1 ORDER BY a")
		}
	}
}
