// Code generated by tcl2go; DO NOT EDIT.
package tkt

import (
"github.com/pijalu/frigolite"
"strconv"
"testing"
)

func Test_tkt2565(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning

	// set testdir: test directory (not used in Go test context)
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_shutdown")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_config_alt_pcache 1 100 0 1")
	// proc definition (not transpiled)
	{ // do_test "tkt2565-1.0"
		t.Errorf("TODO: %s not implemented in frigolite", "reopen_database")
		_res = db.Exec(" CREATE TABLE A(Id INTEGER, Name TEXT) ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " CREATE TABLE A(Id INTEGER, Name TEXT) ")
		}
	}
	var iFail = "1"
	_ = iFail // suppress unused warning
	for func() bool { iFail_n, _iFail_e := strconv.Atoi(iFail); if _iFail_e != nil { return false }; return iFail_n < 200 }() {
		t.Errorf("TODO: %s not implemented in frigolite", "reopen_database")
		r = db.Query(" pragma locking_mode=exclusive ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " pragma locking_mode=exclusive ")
		}
		var nRow = "db one {SELECT count(*) FROM a}"
		_ = nRow // suppress unused warning
		{ // do_test "tkt2565-1." + iFail + ".1"
			_res = db.Exec("\n      BEGIN EXCLUSIVE;\n      INSERT INTO a VALUES(1, 'ABCDEFGHIJKLMNOP');\n    ")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      BEGIN EXCLUSIVE;\n      INSERT INTO a VALUES(1, 'ABCDEFGHIJKLMNOP');\n    ")
			}
		}
		var _sqlite_io_error_persist = "1" // TCL namespace variable
		_ = _sqlite_io_error_persist // suppress unused warning
		var _sqlite_io_error_pending = iFail // TCL namespace variable
		_ = _sqlite_io_error_pending // suppress unused warning
		{ // do_test "tkt2565-1." + iFail + ".2"
			var rc = "catchsql {COMMIT}"
			_ = rc // suppress unused warning
		}
		var _sqlite_io_error_persist = "0" // TCL namespace variable
		_ = _sqlite_io_error_persist // suppress unused warning
		var _sqlite_io_error_pending = "0" // TCL namespace variable
		_ = _sqlite_io_error_pending // suppress unused warning
		if tclBool("!" + _sqlite_io_error_hit) {
		}
		var _sqlite_io_error_hit = "0" // TCL namespace variable
		_ = _sqlite_io_error_hit // suppress unused warning
		// incr iFail 1
		{
			_n, _err := strconv.Atoi(iFail)
			if _err == nil {
				iFail = strconv.Itoa(_n + 1)
			}
		}
	}
	{ // do_test "tkt2565-1.X"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
		}
	}
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_shutdown")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_config_alt_pcache 0")
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_initialize")
	t.Errorf("TODO: %s not implemented in frigolite", "autoinstall_test_functions")
}
