// Code generated by tcl2go; DO NOT EDIT.
package tkt

import (
"github.com/pijalu/frigolite"
"testing"
)

func Test_tkt2285(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	// set testdir: test directory (not used in Go test context)
	{ // do_test "tkt2285-1.1"
		r = db.Query("\n    PRAGMA locking_mode = EXCLUSIVE;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    PRAGMA locking_mode = EXCLUSIVE;\n  ")
		}
		_res = db.Exec("\n    BEGIN;\n    CREATE TABLE abc(a, b, c);\n    ROLLBACK;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    BEGIN;\n    CREATE TABLE abc(a, b, c);\n    ROLLBACK;\n  ")
		}
	}
	{ // do_test "tkt2285-1.2"
		r = db.Query("\n    SELECT * FROM sqlite_master;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT * FROM sqlite_master;\n  ")
		}
	}
}
