// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package tkt

import (
"github.com/pijalu/frigolite"
"testing"
)

func Test_tkt3879(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var Id_ string
	_ = Id_ // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	{ // do_test "tkt3879.1.1"
		_res = db.Exec("\n    CREATE TABLE t1 (a PRIMARY KEY, b);\n    INSERT INTO t1 VALUES ('w',  1);\n    INSERT INTO t1 VALUES ('z', -1);\n  \n    CREATE TABLE t2 (m INTEGER PRIMARY KEY, n, a, p);\n    INSERT INTO t2 VALUES (25, 13, 'w', 1);\n    INSERT INTO t2 VALUES (26, 25, 'z', 153);\n    INSERT INTO t2 VALUES (27, 25, 'z', 68);\n\n    CREATE TABLE t3 (m);\n    INSERT INTO t3 VALUES (25);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE TABLE t1 (a PRIMARY KEY, b);\n    INSERT INTO t1 VALUES ('w',  1);\n    INSERT INTO t1 VALUES ('z', -1);\n  \n    CREATE TABLE t2 (m INTEGER PRIMARY KEY, n, a, p);\n    INSERT INTO t2 VALUES (25, 13, 'w', 1);\n    INSERT INTO t2 VALUES (26, 25, 'z', 153);\n    INSERT INTO t2 VALUES (27, 25, 'z', 68);\n\n    CREATE TABLE t3 (m);\n    INSERT INTO t3 VALUES (25);\n  ")
		}
	}
	{ // do_test "tkt3879.1.2"
		r = db.Query("\n    SELECT 111, t1.b*123\n    FROM t3, t2 AS j0, t2 AS j1, t1\n    WHERE j0.m=t3.m AND t1.a=j0.a AND j1.n=j0.m;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT 111, t1.b*123\n    FROM t3, t2 AS j0, t2 AS j1, t1\n    WHERE j0.m=t3.m AND t1.a=j0.a AND j1.n=j0.m;\n  ")
		}
	}
	{ // do_test "tkt3879.1.3"
		r = db.Query("\n    SELECT 222, t1.b*123\n    FROM t3, t2 AS j0, t2 AS j1, t1\n    WHERE j0.m=t3.m AND t1.a=j0.a AND j1.n=j0.m\n    ORDER BY t1.b;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT 222, t1.b*123\n    FROM t3, t2 AS j0, t2 AS j1, t1\n    WHERE j0.m=t3.m AND t1.a=j0.a AND j1.n=j0.m\n    ORDER BY t1.b;\n  ")
		}
	}
}
