// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package io

import (
"github.com/pijalu/frigolite"
"os"
"strconv"
"strings"
"testing"
)

func Test_io(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	var _r string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	_ = _r   // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var testprefix string
	_ = testprefix // pre-declared from TCL source
	var nWrite string
	_ = nWrite // pre-declared from TCL source
	var bt string
	_ = bt // pre-declared from TCL source
	var res string
	_ = res // pre-declared from TCL source
	var nSync string
	_ = nSync // pre-declared from TCL source
	var ret string
	_ = ret // pre-declared from TCL source
	var expected_sync_count string
	_ = expected_sync_count // pre-declared from TCL source
	var tn string
	_ = tn // pre-declared from TCL source
	var char string
	_ = char // pre-declared from TCL source
	var sectorsize string
	_ = sectorsize // pre-declared from TCL source
	var pgsize string
	_ = pgsize // pre-declared from TCL source
	var sql string
	_ = sql // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source
	var stats_write string
	_ = stats_write // pre-declared from TCL source
	var sqlite_sync_count string
	_ = sqlite_sync_count // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	testprefix = "io" // TCL namespace variable
	_ = testprefix // suppress unused warning
	db.Close()
	// sqlite3_simulate_device (unsupported command, not transpiled)
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	nWrite = "0" // TCL namespace variable
	_ = nWrite // suppress unused warning
	// proc definition (not transpiled)
	nSync = "0" // TCL namespace variable
	_ = nSync // suppress unused warning
	// proc definition (not transpiled)
	{ // do_test "io-1.1"
		r = db.Query("\n    PRAGMA auto_vacuum = OFF;\n    PRAGMA page_size = 1024;\n    CREATE TABLE abc(a,b);\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    PRAGMA auto_vacuum = OFF;\n    PRAGMA page_size = 1024;\n    CREATE TABLE abc(a,b);\n  ")
		}
		// nWrite db (unsupported command, not transpiled)
	}
	{ // do_test "io-1.2"
		ret = ""
		_ = ret // suppress unused warning
		_res = db.Exec(" INSERT INTO abc VALUES(1,randstr(230,230)); ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO abc VALUES(1,randstr(230,230)); ")
		}
		ret = tclListAppend(ret, "nWrite db")
		_res = db.Exec(" INSERT INTO abc VALUES(2,randstr(230,230)); ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO abc VALUES(2,randstr(230,230)); ")
		}
		ret = tclListAppend(ret, "nWrite db")
		_res = db.Exec(" INSERT INTO abc VALUES(3,randstr(230,230)); ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO abc VALUES(3,randstr(230,230)); ")
		}
		ret = tclListAppend(ret, "nWrite db")
		_res = db.Exec(" INSERT INTO abc VALUES(4,randstr(230,230)); ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO abc VALUES(4,randstr(230,230)); ")
		}
		ret = tclListAppend(ret, "nWrite db")
	}
	{ // do_test "io-1.3"
		_res = db.Exec(" INSERT INTO abc VALUES(5,randstr(230,230)); ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO abc VALUES(5,randstr(230,230)); ")
		}
		// nWrite db (unsupported command, not transpiled)
	}
	{ // do_test "io-1.4"
		ret = ""
		_ = ret // suppress unused warning
		_res = db.Exec(" INSERT INTO abc VALUES(6,randstr(230,230)); ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO abc VALUES(6,randstr(230,230)); ")
		}
		ret = tclListAppend(ret, "nWrite db")
		_res = db.Exec(" INSERT INTO abc VALUES(7,randstr(230,230)); ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO abc VALUES(7,randstr(230,230)); ")
		}
		ret = tclListAppend(ret, "nWrite db")
		_res = db.Exec(" INSERT INTO abc VALUES(8,randstr(230,230)); ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO abc VALUES(8,randstr(230,230)); ")
		}
		ret = tclListAppend(ret, "nWrite db")
	}
	{ // do_test "io-1.5"
		_res = db.Exec(" INSERT INTO abc VALUES(9,randstr(230,230)); ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO abc VALUES(9,randstr(230,230)); ")
		}
		// nWrite db (unsupported command, not transpiled)
	}
	{ // do_test "io-2.1"
		_res = db.Exec(" DELETE FROM abc; VACUUM; ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " DELETE FROM abc; VACUUM; ")
		}
	}
	// nWrite db (unsupported command, not transpiled)
	// nSync (unsupported command, not transpiled)
	{ // do_test "io-2.2"
		_res = db.Exec(" INSERT INTO abc VALUES(1, 2) ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO abc VALUES(1, 2) ")
		}
		_list := tclList([]string{"nWrite db", "nSync"})
		_ = _list
	}
	// sqlite3_simulate_device -char atomic (unsupported command, not transpiled)
	{ // do_test "io-2.3"
		_res = db.Exec(" INSERT INTO abc VALUES(3, 4) ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO abc VALUES(3, 4) ")
		}
		_list := tclList([]string{"nWrite db", "nSync"})
		_ = _list
	}
	{ // do_test "io-2.4.1"
		_res = db.Exec("\n    BEGIN;\n    INSERT INTO abc VALUES(5, 6);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    BEGIN;\n    INSERT INTO abc VALUES(5, 6);\n  ")
		}
		db2, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		r = db2.Query(" SELECT * FROM abc ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM abc ")
		}
	}
	{ // do_test "io-2.4.2"
		// file exists "test.db-journal"
	}
	{ // do_test "io-2.4.3"
		_res = db.Exec(" COMMIT ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " COMMIT ")
		}
		r = db2.Query(" SELECT * FROM abc ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM abc ")
		}
	}
	db2.Close()
	{ // do_test "io-2.5.1"
		_res = db.Exec(" CREATE TABLE def(d, e) ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " CREATE TABLE def(d, e) ")
		}
		// nWrite db (unsupported command, not transpiled)
		// nSync (unsupported command, not transpiled)
		_res = db.Exec("\n    BEGIN;\n    INSERT INTO abc VALUES(7, 8);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    BEGIN;\n    INSERT INTO abc VALUES(7, 8);\n  ")
		}
		// file exists "test.db-journal"
	}
	{ // do_test "io-2.5.2"
		_res = db.Exec(" INSERT INTO def VALUES('a', 'b'); ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO def VALUES('a', 'b'); ")
		}
		// file exists "test.db-journal"
	}
	{ // do_test "io-2.5.3"
		_res = db.Exec(" COMMIT ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " COMMIT ")
		}
		_list := tclList([]string{"nWrite db", "nSync"})
		_ = _list
	}
	{ // do_test "io-2.6.1"
		_res = db.Exec("\n    BEGIN IMMEDIATE;\n    -- INSERT INTO abc VALUES(9, randstr(1000,1000));\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    BEGIN IMMEDIATE;\n    -- INSERT INTO abc VALUES(9, randstr(1000,1000));\n  ")
		}
		// file exists "test.db-journal"
	}
	{ // do_test "io-2.6.2"
		// file mkdir test.db-journal
		_res = db.Exec("\n    INSERT INTO abc VALUES(9, randstr(1000,1000));\n    COMMIT\n  ")
		_ = _res // catchsql
	}
	{ // do_test "io-2.6.3"
		os.Remove("test.db-journal")
		_res = db.Exec(" COMMIT ")
		_ = _res // catchsql
	}
	{ // do_test "io-2.6.4"
		r = db.Query(" SELECT * FROM abc ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM abc ")
		}
	}
	os.Remove("test2.db")
	{ // do_test "io-2.7.1"
		r = db.Query("\n      ATTACH 'test2.db' AS aux;\n      PRAGMA aux.page_size = 1024;\n      CREATE TABLE aux.abc2(a, b);\n      BEGIN;\n      INSERT INTO abc VALUES(9, 10);\n    ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n      ATTACH 'test2.db' AS aux;\n      PRAGMA aux.page_size = 1024;\n      CREATE TABLE aux.abc2(a, b);\n      BEGIN;\n      INSERT INTO abc VALUES(9, 10);\n    ")
		}
		// file exists "test.db-journal"
	}
	{ // do_test "io-2.7.2"
		_res = db.Exec(" INSERT INTO abc2 SELECT * FROM abc ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO abc2 SELECT * FROM abc ")
		}
		// file exists "test2.db-journal"
	}
	{ // do_test "io-2.7.3"
		r = db.Query(" SELECT * FROM abc UNION ALL SELECT * FROM abc2 ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM abc UNION ALL SELECT * FROM abc2 ")
		}
	}
	{ // do_test "io-2.7.4"
		// file mkdir test2.db-journal
		_res = db.Exec(" COMMIT ")
		_ = _res // catchsql
	}
	{ // do_test "io-2.7.5"
		os.Remove("test2.db-journal")
		_res = db.Exec(" COMMIT ")
		_ = _res // catchsql
	}
	{ // do_test "io-2.7.6"
		r = db.Query(" SELECT * FROM abc UNION ALL SELECT * FROM abc2 ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM abc UNION ALL SELECT * FROM abc2 ")
		}
	}
	{ // do_test "io-2.8.1"
		_res = db.Exec("\n    BEGIN;\n    DELETE FROM abc;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    BEGIN;\n    DELETE FROM abc;\n  ")
		}
		// file exists "test.db-journal"
	}
	{ // do_test "io-2.8.2"
		r = db.Query(" SELECT * FROM abc ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM abc ")
		}
	}
	{ // do_test "io-2.8.3"
		r = db.Query("\n    ROLLBACK;\n    SELECT * FROM abc;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    ROLLBACK;\n    SELECT * FROM abc;\n  ")
		}
	}
	{ // do_test "io-2.9.1"
		db.Close()
		db, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		// sqlite3_simulate_device -char atomic -sectorsize 2048 (unsupported command, not transpiled)
		_res = db.Exec("\n    BEGIN;\n    INSERT INTO abc VALUES(9, 10);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    BEGIN;\n    INSERT INTO abc VALUES(9, 10);\n  ")
		}
		// file exists "test.db-journal"
	}
	{ // do_test "io-2.9.2"
		_res = db.Exec(" ROLLBACK; ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " ROLLBACK; ")
		}
		db.Close()
		os.Remove("test.db")
		db, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		r = db.Query("\n    PRAGMA auto_vacuum = OFF;\n    PRAGMA page_size = 2048;\n    CREATE TABLE abc(a, b);\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    PRAGMA auto_vacuum = OFF;\n    PRAGMA page_size = 2048;\n    CREATE TABLE abc(a, b);\n  ")
		}
		_res = db.Exec("\n    BEGIN;\n    INSERT INTO abc VALUES(9, 10);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    BEGIN;\n    INSERT INTO abc VALUES(9, 10);\n  ")
		}
		// file exists "test.db-journal"
	}
	{ // do_test "io-2.9.3"
		_res = db.Exec(" COMMIT ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " COMMIT ")
		}
	}
	{ // do_test "io-2.10.1"
		// sqlite3_simulate_device -char atomic1k (unsupported command, not transpiled)
		_res = db.Exec("\n    BEGIN;\n    INSERT INTO abc VALUES(11, 12);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    BEGIN;\n    INSERT INTO abc VALUES(11, 12);\n  ")
		}
		// file exists "test.db-journal"
	}
	{ // do_test "io-2.10.2"
		_res = db.Exec(" ROLLBACK ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " ROLLBACK ")
		}
		// sqlite3_simulate_device -char atomic2k (unsupported command, not transpiled)
		_res = db.Exec("\n    BEGIN;\n    INSERT INTO abc VALUES(11, 12);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    BEGIN;\n    INSERT INTO abc VALUES(11, 12);\n  ")
		}
		// file exists "test.db-journal"
	}
	{ // do_test "io-2.10.3"
		_res = db.Exec(" ROLLBACK ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " ROLLBACK ")
		}
	}
	{ // do_test "io-2.11.0"
		r = db.Query(" \n    PRAGMA locking_mode = exclusive;\n    PRAGMA locking_mode;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " \n    PRAGMA locking_mode = exclusive;\n    PRAGMA locking_mode;\n  ")
		}
	}
	{ // do_test "io-2.11.1"
		_res = db.Exec(" \n    INSERT INTO abc VALUES(11, 12);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " \n    INSERT INTO abc VALUES(11, 12);\n  ")
		}
		// file exists "test.db-journal"
	}
	{ // do_test "io-2.11.2"
		r = db.Query(" \n    PRAGMA locking_mode = normal;\n    INSERT INTO abc VALUES(13, 14);\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " \n    PRAGMA locking_mode = normal;\n    INSERT INTO abc VALUES(13, 14);\n  ")
		}
		// file exists "test.db-journal"
	}
	// sqlite3_simulate_device -char sequential -sectorsize 0 (unsupported command, not transpiled)
	{ // do_test "io-3.1"
		db.Close()
		os.Remove("test.db")
		db, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		_res = db.Exec("\n      PRAGMA auto_vacuum=OFF;\n    ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      PRAGMA auto_vacuum=OFF;\n    ")
		}
		// expr [file size test.db]>1 (not evaluated)
	}
	{ // do_test "io-3.2"
		_res = db.Exec(" CREATE TABLE abc(a, b) ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " CREATE TABLE abc(a, b) ")
		}
		// nSync (unsupported command, not transpiled)
		r = db.Query("\n      PRAGMA temp_store = memory;\n      PRAGMA cache_size = 10;\n      BEGIN;\n      INSERT INTO abc VALUES('hello', 'world');\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n    ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n      PRAGMA temp_store = memory;\n      PRAGMA cache_size = 10;\n      BEGIN;\n      INSERT INTO abc VALUES('hello', 'world');\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n      INSERT INTO abc SELECT * FROM abc;\n    ")
		}
		_list := tclList([]string{tclExpr("[file size test.db]>20000"), "nSync"})
		_ = _list
	}
	{ // do_test "io-3.3"
		_res = db.Exec(" COMMIT ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " COMMIT ")
		}
		_list := tclList([]string{"file size test.db", "nSync"})
		_ = _list
	}
	// sqlite3_simulate_device -char safe_append (unsupported command, not transpiled)
	expected_sync_count = "2"
	_ = expected_sync_count // suppress unused warning
	if tcl_platform_os != "Windows NT" {
		// incr expected_sync_count 1
		{
			_n, _err := strconv.Atoi(expected_sync_count)
			if _err == nil {
				expected_sync_count = strconv.Itoa(_n + 1)
			}
		}
	}
	{ // do_test "io-4.1"
		_res = db.Exec(" DELETE FROM abc ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " DELETE FROM abc ")
		}
		// nSync (unsupported command, not transpiled)
		_res = db.Exec(" INSERT INTO abc VALUES('a', 'b') ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO abc VALUES('a', 'b') ")
		}
		// nSync (unsupported command, not transpiled)
		if _res.Error == nil || !strings.Contains(_res.Error.Error(), expected_sync_count) {
			t.Errorf("expected error containing %s, got: %v\n  body: do_test %s", expected_sync_count, _res.Error, "io-4.1")
		}
	}
	{ // do_test "io-4.2.1"
		_res = db.Exec(" BEGIN ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " BEGIN ")
		}
		_res = db.Exec(" INSERT INTO abc VALUES('c', 'd') ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO abc VALUES('c', 'd') ")
		}
		// file exists "test.db-journal"
	}
	if tcl_platform_platform == "unix" {
		{ // do_test "io-4.2.2"
			// hexio_read test.db-journal 8 4 (unsupported command, not transpiled)
		}
	}
	{ // do_test "io-4.2.3"
		_res = db.Exec(" COMMIT ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " COMMIT ")
		}
		// nSync (unsupported command, not transpiled)
		if _res.Error == nil || !strings.Contains(_res.Error.Error(), expected_sync_count) {
			t.Errorf("expected error containing %s, got: %v\n  body: do_test %s", expected_sync_count, _res.Error, "io-4.2.3")
		}
	}
	// sqlite3_simulate_device -char safe_append (unsupported command, not transpiled)
	{ // do_test "io-4.3.1"
		_res = db.Exec("\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n    INSERT INTO abc SELECT * FROM abc;\n  ")
		}
		// expr [file size test.db]/1024 (not evaluated)
	}
	{ // do_test "io-4.3.2"
		r = db.Query("\n      PRAGMA synchronous = full;\n      PRAGMA cache_size = 10;\n      PRAGMA synchronous;\n    ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n      PRAGMA synchronous = full;\n      PRAGMA cache_size = 10;\n      PRAGMA synchronous;\n    ")
		}
	}
	{ // do_test "io-4.3.3"
		_res = db.Exec("\n    BEGIN;\n    UPDATE abc SET a = 'x';\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    BEGIN;\n    UPDATE abc SET a = 'x';\n  ")
		}
		// file exists "test.db-journal"
	}
	if tcl_platform_platform != "symbian" {
		{ // do_test "io-4.3.4"
			// file size test.db-journal
		}
	}
	tn = "0"
	_ = tn // suppress unused warning
	// foreach {char sectorsize pgsize} "{}                     512      1024\n         {}                    1024      1024\n         {}                    2048      2048\n         {}                    8192      8192\n         {}                   16384      8192\n         {atomic}               512      8192\n         {atomic512}            512      1024\n         {atomic2K}             512      2048\n         {atomic2K}            4096      4096\n         {atomic2K atomic}      512      8192\n         {atomic64K}            512      1024"
	_items0 := tclSplitList("{}                     512      1024\n         {}                    1024      1024\n         {}                    2048      2048\n         {}                    8192      8192\n         {}                   16384      8192\n         {atomic}               512      8192\n         {atomic512}            512      1024\n         {atomic2K}             512      2048\n         {atomic2K}            4096      4096\n         {atomic2K atomic}      512      8192\n         {atomic64K}            512      1024")
	for _idx0 := 0; _idx0+3 <= len(_items0); _idx0 += 3 {
		char := _items0[_idx0+0]
		_ = char // suppress unused warning
		sectorsize := _items0[_idx0+1]
		_ = sectorsize // suppress unused warning
		pgsize := _items0[_idx0+2]
		_ = pgsize // suppress unused warning
		_ = _idx0
			// incr tn 1
			{
				_n, _err := strconv.Atoi(tn)
				if _err == nil {
					tn = strconv.Itoa(_n + 1)
				}
			}
			if func() bool { pgsize_n, _pgsize_e := strconv.Atoi(pgsize); if _pgsize_e != nil { return false }; SQLITE_MAX_PAGE_SIZE_n, _SQLITE_MAX_PAGE_SIZE_e := strconv.Atoi(SQLITE_MAX_PAGE_SIZE); if _SQLITE_MAX_PAGE_SIZE_e != nil { return false }; return pgsize_n > SQLITE_MAX_PAGE_SIZE_n }() {
				continue
			}
			db.Close()
			os.Remove("test.db")
			// sqlite3_simulate_device -char $char -sectorsize $sectorsize (unsupported command, not transpiled)
			db, err = frigolite.Open("test.db")
			if err != nil { t.Fatal(err) }
			_res = db.Exec("\n    PRAGMA auto_vacuum=OFF;\n  ")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    PRAGMA auto_vacuum=OFF;\n  ")
			}
			{ // do_test "io-5." + tn
				_res = db.Exec("\n      CREATE TABLE abc(a, b, c);\n    ")
				if _res.Error != nil {
					t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      CREATE TABLE abc(a, b, c);\n    ")
				}
				// expr [file size test.db]/2 (not evaluated)
				if _res.Error == nil || !strings.Contains(_res.Error.Error(), pgsize) {
					t.Errorf("expected error containing %s, got: %v\n  body: do_test %s", pgsize, _res.Error, "io-5." + tn)
				}
			}
		}
		{ // do_test "io-6.1"
			db.Close()
			// sqlite3_simulate_device -char atomic (unsupported command, not transpiled)
			os.Remove("test.db")
			db, err = frigolite.Open("test.db")
			if err != nil { t.Fatal(err) }
			r = db.Query("\n    PRAGMA mmap_size = 0;\n    PRAGMA page_size = 1024;\n    PRAGMA cache_size = 2000;\n    CREATE TABLE t1(x);\n    CREATE TABLE t2(x);\n    CREATE TABLE t3(x);\n    CREATE INDEX i3 ON t3(x);\n    INSERT INTO t3 VALUES(randomblob(100));\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n  ")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    PRAGMA mmap_size = 0;\n    PRAGMA page_size = 1024;\n    PRAGMA cache_size = 2000;\n    CREATE TABLE t1(x);\n    CREATE TABLE t2(x);\n    CREATE TABLE t3(x);\n    CREATE INDEX i3 ON t3(x);\n    INSERT INTO t3 VALUES(randomblob(100));\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n    INSERT INTO t3 SELECT randomblob(100) FROM t3;\n  ")
			}
			// db_save_and_close (unsupported command, not transpiled)
		}
		// foreach {tn sql} "1 { BEGIN;\n        INSERT INTO t1 VALUES('123');\n        INSERT INTO t2 VALUES('456');\n      COMMIT;\n  }\n  2 { BEGIN;\n        INSERT INTO t1 VALUES('123');\n      COMMIT;\n  }"
		_items1 := tclSplitList("1 { BEGIN;\n        INSERT INTO t1 VALUES('123');\n        INSERT INTO t2 VALUES('456');\n      COMMIT;\n  }\n  2 { BEGIN;\n        INSERT INTO t1 VALUES('123');\n      COMMIT;\n  }")
		for _idx1 := 0; _idx1+2 <= len(_items1); _idx1 += 2 {
			tn := _items1[_idx1+0]
			_ = tn // suppress unused warning
			sql := _items1[_idx1+1]
			_ = sql // suppress unused warning
			_ = _idx1
				if "" == "memsubsys1" {
					continue
				}
				// db_restore (unsupported command, not transpiled)
				_dbtmp2, err := frigolite.Open("test.db")
				_ = _dbtmp2 // sqlite3 db connection
				if err != nil { t.Fatal(err) }
				r = db.Query("\n    PRAGMA cache_size = 2000;\n    PRAGMA mmap_size = 0;\n    SELECT x FROM t3 ORDER BY rowid;\n    SELECT x FROM t3 ORDER BY x;\n  ")
				if r.Error != nil {
					t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    PRAGMA cache_size = 2000;\n    PRAGMA mmap_size = 0;\n    SELECT x FROM t3 ORDER BY rowid;\n    SELECT x FROM t3 ORDER BY x;\n  ")
				}
				{ // "6.2." + tn + ".1"
					r = db.Query(" PRAGMA integrity_check ")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, " PRAGMA integrity_check ")
						return
					}
					got := flatten(r)
					want := "ok"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				{ // "6.2." + tn + ".2"
					_res = db.Exec(sql)
					if _res.Error != nil {
						t.Errorf("exec error: %v\n  sql: %s", _res.Error, sql)
					}
				}
				// hexio_write test.db [expr 1024 * 5] [string repeat 00 2048] (unsupported command, not transpiled)
				{ // "6.2." + tn + ".3"
					r = db.Query(" PRAGMA integrity_check ")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, " PRAGMA integrity_check ")
						return
					}
					got := flatten(r)
					want := "ok"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				db.Close()
			}
			// sqlite3_simulate_device -char {} -sectorsize 0 (unsupported command, not transpiled)
			// unregister_devsim (unsupported command, not transpiled)
}
