// Code generated by tcl2go; DO NOT EDIT.
package corrupt

import (
"github.com/pijalu/frigolite"
"strconv"
"strings"
"testing"
)

func Test_corrupt4(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning

	// set testdir: test directory (not used in Go test context)
	var testprefix = "corrupt4"
	_ = testprefix // suppress unused warning
	if tclBool("nonzero_reserved_bytes") {
		return
	}
	t.Errorf("TODO: %s not implemented in frigolite", "database_may_be_corrupt")
	{ // do_test "corrupt4-1.1"
		var bigstring = "0123456789 200"
		_ = bigstring // suppress unused warning
		_res = db.Exec("\n    PRAGMA auto_vacuum=OFF;\n    PRAGMA page_size=1024;\n    CREATE TABLE t1(x);\n    INSERT INTO t1 VALUES($bigstring);\n    CREATE TABLE t2(y);\n    INSERT INTO t2 VALUES(1);\n    DROP TABLE t1;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    PRAGMA auto_vacuum=OFF;\n    PRAGMA page_size=1024;\n    CREATE TABLE t1(x);\n    INSERT INTO t1 VALUES($bigstring);\n    CREATE TABLE t2(y);\n    INSERT INTO t2 VALUES(1);\n    DROP TABLE t1;\n  ")
		}
		// file size test.db
	}
	{ // do_test "corrupt4-1.2"
		r = db.Query("PRAGMA freelist_count")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "PRAGMA freelist_count")
		}
	}
	var trunkpgno = "hexio_get_int [hexio_read test.db 32 4]"
	_ = trunkpgno // suppress unused warning
	baseaddr := "($trunkpgno-1)*1024"
	_ = baseaddr // suppress unused warning
	{ // do_test "corrupt4-1.3"
		t.Errorf("TODO: %s not implemented in frigolite", "hexio_get_int [hexio_read test.db [expr {$::baseaddr+4}] 4]")
	}
	{ // do_test "corrupt4-1.4"
		t.Errorf("TODO: %s not implemented in frigolite", "hexio_write test.db [expr {$::baseaddr+4}] [hexio_render_int32 -100000000]")
		db, err := frigolite.Open("test.db")
		defer db.Close()
		if err != nil { t.Fatal(err) }
		_res = db.Exec("\n    DROP TABLE t2\n  ")
		_ = _res // catchsql
	}
	db.Close()
	db, err = frigolite.Open("")
	if err != nil { t.Fatal(err) }
	{ // "2.0"
		_res = db.Exec("\n  PRAGMA page_size = 512;\n  CREATE TABLE t1(a, b, c);\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  PRAGMA page_size = 512;\n  CREATE TABLE t1(a, b, c);\n")
		}
	}
	var nView = "1000"
	_ = nView // suppress unused warning
	{ // do_test "2.1"
		_res = db.Exec("BEGIN")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "BEGIN")
		}
		var ii = "0"
		_ = ii // suppress unused warning
		for func() bool { ii_n, _ii_e := strconv.Atoi(ii); if _ii_e != nil { return false }; nView_n, _nView_e := strconv.Atoi(nView); if _nView_e != nil { return false }; return ii_n < nView_n }() {
			_res = db.Exec(" CREATE VIEW v" + ii + " AS SELECT a, b, c FROM t1 ")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, " CREATE VIEW v" + ii + " AS SELECT a, b, c FROM t1 ")
			}
			// incr ii 1
			{
				_n, _err := strconv.Atoi(ii)
				if _err == nil {
					ii = strconv.Itoa(_n + 1)
				}
			}
		}
		_res = db.Exec("COMMIT")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "COMMIT")
		}
	}
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	var fd = "open test.db r+"
	_ = fd // suppress unused warning
	t.Errorf("TODO: %s not implemented in frigolite", "fconfigure $fd -translation binary")
	var nChild = "get2byte $fd 103"
	_ = nChild // suppress unused warning
	var offChild = "get2byte $fd [expr 100+12+($nChild-2)*2]"
	_ = offChild // suppress unused warning
	var pgnoChild = "get4byte $fd $offChild"
	_ = pgnoChild // suppress unused warning
	t.Errorf("TODO: %s not implemented in frigolite", "put4byte $fd $offChild 1")
	// close $fd
	if tclBool("!" + "info exists ::G(perm:presql)") {
		db, err := frigolite.Open("test.db")
		defer db.Close()
		if err != nil { t.Fatal(err) }
		{ // "2.2"
			_res = db.Exec("\n    PRAGMA writable_schema = 1;\n    SELECT * FROM sqlite_schema;\n  ")
			if _res.Error == nil || !strings.Contains(_res.Error.Error(), "database disk image is malformed") {
				t.Errorf("expected error containing %q, got: %v\n  sql: %s", "database disk image is malformed", _res.Error, "\n    PRAGMA writable_schema = 1;\n    SELECT * FROM sqlite_schema;\n  ")
			}
		}
		{ // do_test "2.3"
			_list := tclList([]string{"0", msg})
			_ = _list
		}
	}
}
