// Code generated by tcl2go; DO NOT EDIT.
package capi3

import (
"github.com/pijalu/frigolite"
"testing"
)

func Test_capi3b(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning

	// set testdir: test directory (not used in Go test context)
	t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_soft_heap_limit 0")
	var DB = "sqlite3_connection_pointer db"
	_ = DB // suppress unused warning
	db2, err := frigolite.Open("test.db")
	defer db2.Close()
	if err != nil { t.Fatal(err) }
	var DB2 = "sqlite3_connection_pointer db2"
	_ = DB2 // suppress unused warning
	{ // do_test "capi3b-1.1"
		r = db.Query("\n    CREATE TABLE t1(x);\n    INSERT INTO t1 VALUES(1);\n    INSERT INTO t1 VALUES(2);\n    SELECT * FROM t1\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    CREATE TABLE t1(x);\n    INSERT INTO t1 VALUES(1);\n    INSERT INTO t1 VALUES(2);\n    SELECT * FROM t1\n  ")
		}
	}
	{ // do_test "capi3b-1.2"
		r = db.Query("\n    SELECT * FROM t1\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT * FROM t1\n  ")
		}
	}
	{ // do_test "capi3b-1.3"
		r = db.Query("\n    BEGIN;\n    SELECT * FROM t1;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    BEGIN;\n    SELECT * FROM t1;\n  ")
		}
	}
	{ // do_test "capi3b-1.4"
		var VM = "sqlite3_prepare $DB2 {INSERT INTO t1 VALUES(3)} -1 TAIL"
		_ = VM // suppress unused warning
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_step $VM")
	}
	{ // do_test "capi3b-1.5.1"
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_step $VM")
	}
	{ // do_test "capi3b-1.5.2"
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_step $VM")
	}
	{ // do_test "capi3b-1.6"
		_res = db.Exec("COMMIT")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "COMMIT")
		}
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_step $VM")
	}
	{ // do_test "capi3b-1.7"
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_finalize $VM")
	}
	{ // do_test "capi3b-1.8"
		r = db.Query("SELECT * FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT * FROM t1")
		}
	}
	{ // do_test "capi3b-1.9"
		r = db.Query("SELECT * FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT * FROM t1")
		}
	}
	{ // do_test "capi3b-2.1"
		var VM1 = "sqlite3_prepare $DB {SELECT * FROM t1} -1 TAIL"
		_ = VM1 // suppress unused warning
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_step $VM1")
	}
	{ // do_test "capi3b-2.2"
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_column_text $VM1 0")
	}
	{ // do_test "capi3b-2.3"
		var VM2 = "sqlite3_prepare $DB2 {INSERT INTO t1 VALUES(4)} -1 TAIL"
		_ = VM2 // suppress unused warning
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_step $VM2")
	}
	{ // do_test "capi3b-2.4"
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_step $VM1")
	}
	{ // do_test "capi3b-2.5"
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_column_text $VM1 0")
	}
	{ // do_test "capi3b-2.6"
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_step $VM2")
	}
	{ // do_test "capi3b-2.7"
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_step $VM1")
	}
	{ // do_test "capi3b-2.8"
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_column_text $VM1 0")
	}
	{ // do_test "capi3b-2.9"
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_step $VM2")
	}
	{ // do_test "capi3b-2.10"
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_step $VM1")
	}
	{ // do_test "capi3b-2.11"
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_step $VM2")
	}
	{ // do_test "capi3b-2.12"
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_finalize $VM1")
		t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_finalize $VM2")
		r = db.Query("SELECT * FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT * FROM t1")
		}
	}
	{
		var _catchErr error
		_ = _catchErr // suppress unused warning
		db2.Close()
	}
	t.Skipf("TODO: %s not implemented in frigolite", "sqlite3_soft_heap_limit $cmdlinearg(soft-heap-limit)")
}
