// Code generated by tcl2go; DO NOT EDIT.
package tkt_5e10420e8

import (
"github.com/pijalu/frigolite"
"testing"
)

func Test_tkt_5e10420e8d(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning

	// set testdir: test directory (not used in Go test context)
	{ // "tkt-5e10420e8d.1"
		_res = db.Exec("\n  PRAGMA page_size = 1024;\n  PRAGMA auto_vacuum = incremental;\n\n  CREATE TABLE t1(x);\n  CREATE TABLE t2(x);\n  CREATE TABLE t3(x);\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  PRAGMA page_size = 1024;\n  PRAGMA auto_vacuum = incremental;\n\n  CREATE TABLE t1(x);\n  CREATE TABLE t2(x);\n  CREATE TABLE t3(x);\n")
		}
	}
	{ // "tkt-5e10420e8d.2"
		_res = db.Exec("\n  INSERT INTO t3 VALUES(randomblob(500 + 1024*248));\n  INSERT INTO t1 VALUES(randomblob(1500));\n  INSERT INTO t2 VALUES(randomblob(500 + 1024*248));\n\n  DELETE FROM t3;\n  DELETE FROM t2;\n  DELETE FROM t1;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  INSERT INTO t3 VALUES(randomblob(500 + 1024*248));\n  INSERT INTO t1 VALUES(randomblob(1500));\n  INSERT INTO t2 VALUES(randomblob(500 + 1024*248));\n\n  DELETE FROM t3;\n  DELETE FROM t2;\n  DELETE FROM t1;\n")
		}
	}
	{ // "tkt-5e10420e8d.3"
		r = db.Query("\n  PRAGMA incremental_vacuum(248)\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  PRAGMA incremental_vacuum(248)\n")
		}
	}
	{ // "tkt-5e10420e8d.4"
		r = db.Query("\n  PRAGMA incremental_vacuum(1)\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  PRAGMA incremental_vacuum(1)\n")
		}
	}
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	{ // "tkt-5e10420e8d.5"
		r = db.Query("\n  PRAGMA integrity_check;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  PRAGMA integrity_check;\n")
			return
		}
		got := flatten(r)
		want := "ok"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
}
