// Code generated by tcl2go; DO NOT EDIT.
package pcache

import (
"github.com/pijalu/frigolite"
"testing"
)

func Test_pcache(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result

	// set testdir: test directory (not used in Go test context)
	t.Skipf("TODO: %s not implemented in frigolite", "do_not_use_codec")
	{ // do_test "pcache-1.1"
		t.Skipf("TODO: %s not implemented in frigolite", "pcache_stats")
	}
	{ // do_test "pcache-1.2"
		db, err := frigolite.Open("test.db")
		defer db.Close()
		if err != nil { t.Fatal(err) }
		r = db.Query("\n    PRAGMA cache_size=12;\n    PRAGMA auto_vacuum=0;\n    PRAGMA mmap_size=0;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    PRAGMA cache_size=12;\n    PRAGMA auto_vacuum=0;\n    PRAGMA mmap_size=0;\n  ")
		}
		t.Skipf("TODO: %s not implemented in frigolite", "pcache_stats")
	}
	{ // do_test "pcache-1.3"
		_res = db.Exec("\n    BEGIN;\n    CREATE TABLE t1(a, b, c);\n    CREATE TABLE t2(a, b, c);\n    CREATE TABLE t3(a, b, c);\n    CREATE TABLE t4(a, b, c);\n    CREATE TABLE t5(a, b, c);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    BEGIN;\n    CREATE TABLE t1(a, b, c);\n    CREATE TABLE t2(a, b, c);\n    CREATE TABLE t3(a, b, c);\n    CREATE TABLE t4(a, b, c);\n    CREATE TABLE t5(a, b, c);\n  ")
		}
		t.Skipf("TODO: %s not implemented in frigolite", "pcache_stats")
	}
	{ // do_test "pcache-1.4"
		_res = db.Exec("\n    CREATE TABLE t6(a, b, c);\n    CREATE TABLE t7(a, b, c);\n    CREATE TABLE t8(a, b, c);\n    CREATE TABLE t9(a, b, c);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE TABLE t6(a, b, c);\n    CREATE TABLE t7(a, b, c);\n    CREATE TABLE t8(a, b, c);\n    CREATE TABLE t9(a, b, c);\n  ")
		}
		t.Skipf("TODO: %s not implemented in frigolite", "pcache_stats")
	}
	{ // do_test "pcache-1.5"
		db2, err := frigolite.Open("test.db")
		defer db2.Close()
		if err != nil { t.Fatal(err) }
		r = db.Query("PRAGMA cache_size; PRAGMA cache_size=10")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "PRAGMA cache_size; PRAGMA cache_size=10")
		}
		t.Skipf("TODO: %s not implemented in frigolite", "pcache_stats")
	}
	{ // do_test "pcache-1.6.1"
		r = db.Query("\n    BEGIN;\n    SELECT * FROM sqlite_master;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    BEGIN;\n    SELECT * FROM sqlite_master;\n  ")
		}
		t.Skipf("TODO: %s not implemented in frigolite", "pcache_stats")
	}
	{ // do_test "pcache-1.6.2"
		_res = db.Exec("\n    CREATE INDEX i1 ON t1(a, b);\n    CREATE INDEX i2 ON t2(a, b);\n    CREATE INDEX i3 ON t3(a, b);\n    CREATE INDEX i4 ON t4(a, b);\n    CREATE INDEX i5 ON t5(a, b);\n    CREATE INDEX i6 ON t6(a, b);\n    CREATE INDEX i7 ON t7(a, b);\n    CREATE INDEX i8 ON t8(a, b);\n    CREATE INDEX i9 ON t9(a, b);\n    CREATE INDEX i10 ON t9(a, b);\n    CREATE INDEX i11 ON t9(a, b);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE INDEX i1 ON t1(a, b);\n    CREATE INDEX i2 ON t2(a, b);\n    CREATE INDEX i3 ON t3(a, b);\n    CREATE INDEX i4 ON t4(a, b);\n    CREATE INDEX i5 ON t5(a, b);\n    CREATE INDEX i6 ON t6(a, b);\n    CREATE INDEX i7 ON t7(a, b);\n    CREATE INDEX i8 ON t8(a, b);\n    CREATE INDEX i9 ON t9(a, b);\n    CREATE INDEX i10 ON t9(a, b);\n    CREATE INDEX i11 ON t9(a, b);\n  ")
		}
		t.Skipf("TODO: %s not implemented in frigolite", "pcache_stats")
	}
	{ // do_test "pcache-1.7"
		_res = db.Exec("\n    CREATE TABLE t10(a, b, c);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE TABLE t10(a, b, c);\n  ")
		}
		t.Skipf("TODO: %s not implemented in frigolite", "pcache_stats")
	}
	{ // do_test "pcache-1.8"
		_res = db.Exec("ROLLBACK")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "ROLLBACK")
		}
		t.Skipf("TODO: %s not implemented in frigolite", "pcache_stats")
	}
	{ // do_test "pcache-1.9"
		_res = db.Exec("COMMIT")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "COMMIT")
		}
		t.Skipf("TODO: %s not implemented in frigolite", "pcache_stats")
	}
	{ // do_test "pcache-1.10"
		db2.Close()
		t.Skipf("TODO: %s not implemented in frigolite", "pcache_stats")
	}
	{ // do_test "pcache-1.11"
		r = db.Query(" PRAGMA cache_size = 20 ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " PRAGMA cache_size = 20 ")
		}
		t.Skipf("TODO: %s not implemented in frigolite", "pcache_stats")
	}
	{ // do_test "pcache-1.12"
		r = db.Query(" \n    SELECT * FROM t1 ORDER BY a; SELECT * FROM t1;\n    SELECT * FROM t2 ORDER BY a; SELECT * FROM t2;\n    SELECT * FROM t3 ORDER BY a; SELECT * FROM t3;\n    SELECT * FROM t4 ORDER BY a; SELECT * FROM t4;\n    SELECT * FROM t5 ORDER BY a; SELECT * FROM t5;\n    SELECT * FROM t6 ORDER BY a; SELECT * FROM t6;\n    SELECT * FROM t7 ORDER BY a; SELECT * FROM t7;\n    SELECT * FROM t8 ORDER BY a; SELECT * FROM t8;\n    SELECT * FROM t9 ORDER BY a; SELECT * FROM t9;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " \n    SELECT * FROM t1 ORDER BY a; SELECT * FROM t1;\n    SELECT * FROM t2 ORDER BY a; SELECT * FROM t2;\n    SELECT * FROM t3 ORDER BY a; SELECT * FROM t3;\n    SELECT * FROM t4 ORDER BY a; SELECT * FROM t4;\n    SELECT * FROM t5 ORDER BY a; SELECT * FROM t5;\n    SELECT * FROM t6 ORDER BY a; SELECT * FROM t6;\n    SELECT * FROM t7 ORDER BY a; SELECT * FROM t7;\n    SELECT * FROM t8 ORDER BY a; SELECT * FROM t8;\n    SELECT * FROM t9 ORDER BY a; SELECT * FROM t9;\n  ")
		}
		t.Skipf("TODO: %s not implemented in frigolite", "pcache_stats")
	}
	{ // do_test "pcache-1.13"
		r = db.Query(" PRAGMA cache_size = 15 ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " PRAGMA cache_size = 15 ")
		}
		t.Skipf("TODO: %s not implemented in frigolite", "pcache_stats")
	}
	{ // do_test "pcache-1.14"
		t.Skipf("TODO: %s not implemented in frigolite", "hexio_write test.db 24 [hexio_render_int32 1000]")
		r = db.Query(" SELECT * FROM sqlite_master ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM sqlite_master ")
		}
		t.Skipf("TODO: %s not implemented in frigolite", "pcache_stats")
	}
	{ // do_test "pcache-1.15"
		r = db.Query(" \n    SELECT * FROM t1 ORDER BY a; SELECT * FROM t1;\n    SELECT * FROM t2 ORDER BY a; SELECT * FROM t2;\n    SELECT * FROM t3 ORDER BY a; SELECT * FROM t3;\n    SELECT * FROM t4 ORDER BY a; SELECT * FROM t4;\n    SELECT * FROM t5 ORDER BY a; SELECT * FROM t5;\n    SELECT * FROM t6 ORDER BY a; SELECT * FROM t6;\n    SELECT * FROM t7 ORDER BY a; SELECT * FROM t7;\n    SELECT * FROM t8 ORDER BY a; SELECT * FROM t8;\n    SELECT * FROM t9 ORDER BY a; SELECT * FROM t9;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " \n    SELECT * FROM t1 ORDER BY a; SELECT * FROM t1;\n    SELECT * FROM t2 ORDER BY a; SELECT * FROM t2;\n    SELECT * FROM t3 ORDER BY a; SELECT * FROM t3;\n    SELECT * FROM t4 ORDER BY a; SELECT * FROM t4;\n    SELECT * FROM t5 ORDER BY a; SELECT * FROM t5;\n    SELECT * FROM t6 ORDER BY a; SELECT * FROM t6;\n    SELECT * FROM t7 ORDER BY a; SELECT * FROM t7;\n    SELECT * FROM t8 ORDER BY a; SELECT * FROM t8;\n    SELECT * FROM t9 ORDER BY a; SELECT * FROM t9;\n  ")
		}
		t.Skipf("TODO: %s not implemented in frigolite", "pcache_stats")
	}
}
