// Code generated by tcl2go; DO NOT EDIT.
package alterdropcol

import (
"github.com/pijalu/frigolite"
"strings"
"testing"
)

func Test_alterdropcol2(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var testprefix string
	_ = testprefix // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source
	var schema string
	_ = schema // pre-declared from TCL source
	var tn string
	_ = tn // pre-declared from TCL source
	var atdc string
	_ = atdc // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	testprefix = "alterdropcol2"
	_ = testprefix // suppress unused warning
	{ // "1.0"
		_res = db.Exec("\n  CREATE TABLE t1(c, b, a, PRIMARY KEY(b, a)) WITHOUT ROWID;\n  INSERT INTO t1 VALUES(1, 2, 3), (4, 5, 6);\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE t1(c, b, a, PRIMARY KEY(b, a)) WITHOUT ROWID;\n  INSERT INTO t1 VALUES(1, 2, 3), (4, 5, 6);\n")
		}
	}
	{ // "1.1"
		_res = db.Exec("\n  ALTER TABLE t1 DROP c;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  ALTER TABLE t1 DROP c;\n")
		}
	}
	{ // "1.2.1"
		r = db.Query("\n  SELECT * FROM t1;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT * FROM t1;\n")
			return
		}
		got := flatten(r)
		want := "2 3   5 6"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "1.2.2"
		r = db.Query("\n  SELECT sql FROM sqlite_schema;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT sql FROM sqlite_schema;\n")
			return
		}
		got := flatten(r)
		want := "\n  {CREATE TABLE t1(b, a, PRIMARY KEY(b, a)) WITHOUT ROWID}\n"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	// proc definition (not transpiled)
	// do_atdc_error_test 2.1.1 {
  CREATE TABLE x1(a PRIMARY KEY, b, c);
} { 
  ALTER TABLE x1 DROP COLUMN a 
} {
  cannot drop PRIMARY KEY column: "a"
} (unsupported command, not transpiled)
	// do_atdc_error_test 2.1.2 {
  CREATE TABLE x1(a,b,c,d,e, PRIMARY KEY(b,c,d));...} { 
  ALTER TABLE x1 DROP COLUMN c
} {
  cannot drop PRIMARY KEY column: "c"
} (unsupported command, not transpiled)
	// do_atdc_error_test 2.2.1 {
  CREATE TABLE x1(a PRIMARY KEY, b, c UNIQUE);
} { 
  ALTER TABLE x1 DROP COLUMN c 
} {
  cannot drop UNIQUE column: "c"
} (unsupported command, not transpiled)
	// do_atdc_error_test 2.2.2 {
  CREATE TABLE x1(a PRIMARY KEY, b, c, UNIQUE(b, ...} { 
  ALTER TABLE x1 DROP COLUMN c 
} {
  error in table x1 after drop column: no such co...} (unsupported command, not transpiled)
	// do_atdc_error_test 2.3.1 {
  CREATE TABLE 'one two'('x y', 'z 1', 'a b');
  ...} { 
  ALTER TABLE 'one two' DROP COLUMN 'z 1' 
} {
  error in index idx after drop column: no such c...} (unsupported command, not transpiled)
	// do_atdc_error_test 2.3.2 {
  CREATE TABLE x1(a, b, c);
  CREATE INDEX idx ON...} { 
  ALTER TABLE x1 DROP COLUMN a;
} {
  error in index idx after drop column: no such c...} (unsupported command, not transpiled)
	// do_atdc_error_test 2.4.1 {
  CREATE TABLE x1234(a, b, c PRIMARY KEY) WITHOUT...} { 
  ALTER TABLE x1234 DROP a
} {
  error in index i1 after drop column: no such co...} (unsupported command, not transpiled)
	// do_atdc_error_test 2.5.1 {
  CREATE TABLE x1234(a, b, c PRIMARY KEY, CHECK((...} { 
  ALTER TABLE x1234 DROP a
} {
  error in table x1234 after drop column: no such...} (unsupported command, not transpiled)
	// do_atdc_error_test 2.6.1 {
  CREATE TABLE p1(x, y UNIQUE);
  CREATE TABLE c1...} { 
  ALTER TABLE c1 DROP v
} {
  error in table c1 after drop column: unknown co...} (unsupported command, not transpiled)
	// do_atdc_error_test 2.7.1 {
  CREATE TABLE c1(u, v, w AS (u+v));
} { 
  ALTER TABLE c1 DROP v
} {
  error in table c1 after drop column: no such co...} (unsupported command, not transpiled)
	// do_atdc_error_test 2.7.2 {
  CREATE TABLE c1(u, v, w AS (u+v) STORED);
} { 
  ALTER TABLE c1 DROP u
} {
  error in table c1 after drop column: no such co...} (unsupported command, not transpiled)
	// do_atdc_error_test 2.8.1 {
  CREATE TABLE log(l);
  CREATE TABLE c1(u, v, w)...} { 
  ALTER TABLE c1 DROP w
} {
  error in trigger tr1 after drop column: no such...} (unsupported command, not transpiled)
	// do_atdc_error_test 2.8.2 {
  CREATE TABLE c1(u, v, w);
  CREATE VIEW v1 AS S...} { 
  ALTER TABLE c1 DROP w
} {
  error in view v1 after drop column: no such col...} (unsupported command, not transpiled)
	// do_atdc_error_test 2.8.3 {
  CREATE TABLE c1(u, v, w);
  CREATE VIEW v1 AS S...} { 
  ALTER TABLE c1 DROP w
} {
  error in view v1 after drop column: no such col...} (unsupported command, not transpiled)
	{ // "3.0"
		_res = db.Exec("\n  CREATE TABLE yyy(q, w, e CHECK (e > 0), r);\n  INSERT INTO yyy VALUES(1,1,1,1), (2,2,2,2);\n\n  CREATE TABLE zzz(q, w, e, r, CHECK (e > 0));\n  INSERT INTO zzz VALUES(1,1,1,1), (2,2,2,2);\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE yyy(q, w, e CHECK (e > 0), r);\n  INSERT INTO yyy VALUES(1,1,1,1), (2,2,2,2);\n\n  CREATE TABLE zzz(q, w, e, r, CHECK (e > 0));\n  INSERT INTO zzz VALUES(1,1,1,1), (2,2,2,2);\n")
		}
	}
	{ // "3.1.1"
		_res = db.Exec("\n  INSERT INTO yyy VALUES(0,0,0,0);\n")
		if _res.Error == nil || !strings.Contains(_res.Error.Error(), "CHECK constraint failed: e > 0") {
			t.Errorf("expected error containing %q, got: %v\n  sql: %s", "CHECK constraint failed: e > 0", _res.Error, "\n  INSERT INTO yyy VALUES(0,0,0,0);\n")
		}
	}
	{ // "3.1.2"
		_res = db.Exec("\n  INSERT INTO yyy VALUES(0,0,0,0);\n")
		if _res.Error == nil || !strings.Contains(_res.Error.Error(), "CHECK constraint failed: e > 0") {
			t.Errorf("expected error containing %q, got: %v\n  sql: %s", "CHECK constraint failed: e > 0", _res.Error, "\n  INSERT INTO yyy VALUES(0,0,0,0);\n")
		}
	}
	{ // "3.2.1"
		_res = db.Exec("\n  ALTER TABLE yyy DROP e;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  ALTER TABLE yyy DROP e;\n")
		}
	}
	{ // "3.2.2"
		_res = db.Exec("\n  ALTER TABLE zzz DROP e;\n")
		if _res.Error == nil || !strings.Contains(_res.Error.Error(), "error in table zzz after drop column: no such column: e") {
			t.Errorf("expected error containing %q, got: %v\n  sql: %s", "error in table zzz after drop column: no such column: e", _res.Error, "\n  ALTER TABLE zzz DROP e;\n")
		}
	}
}
