// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package fts5limits

import (
"github.com/pijalu/frigolite"
"github.com/pijalu/frigolite/internal/vtab"
"os"
"strings"
"testing"
)

func Test_fts5limits(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	var _r string
	var _berr error
	_ = _berr // suppress unused warning
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	_ = _r   // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testprefix string
	_ = testprefix // pre-declared from TCL source
	var tn string
	_ = tn // pre-declared from TCL source
	var nRepeat string
	_ = nRepeat // pre-declared from TCL source
	var op string
	_ = op // pre-declared from TCL source
	var bErr string
	_ = bErr // pre-declared from TCL source
	var L string
	_ = L // pre-declared from TCL source
	var Q string
	_ = Q // pre-declared from TCL source
	var res string
	_ = res // pre-declared from TCL source

	vtab.TclVarSet("testprefix", "", "fts5limits")
	testprefix = "fts5limits"
	_ = testprefix // suppress unused warning
	// return_if_no_fts5 (unsupported command, not transpiled)
	{ // "1.0"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE ft USING fts5(x);\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft USING fts5(x);\n")
		}
	}
	// foreach {tn nRepeat op bErr} "1  200  AND  0\n  2  200  NOT  0\n  3  200  OR   0\n\n  4  260  AND  0\n  5  260  NOT  1\n  6  260  OR   0"
	_items0 := tclSplitList("1  200  AND  0\n  2  200  NOT  0\n  3  200  OR   0\n\n  4  260  AND  0\n  5  260  NOT  1\n  6  260  OR   0")
	for _idx0 := 0; _idx0+4 <= len(_items0); _idx0 += 4 {
		tn := _items0[_idx0+0]
		_ = tn // suppress unused warning
		nRepeat := _items0[_idx0+1]
		_ = nRepeat // suppress unused warning
		op := _items0[_idx0+2]
		_ = op // suppress unused warning
		bErr := _items0[_idx0+3]
		_ = bErr // suppress unused warning
		_ = _idx0
			L = tclStringRepeat("abc ", nRepeat)
			_ = L // suppress unused warning
			Q = strings.Join(tclSplitList(L), " " + op + " ")
			_ = Q // suppress unused warning
			vtab.TclVarSet("res", "", "0 {}")
			res = "0 {}"
			_ = res // suppress unused warning
			if tclBool(bErr) {
				vtab.TclVarSet("res", "", "1 {fts5 expression tree is too large (maximum depth 256)}")
				res = "1 {fts5 expression tree is too large (maximum depth 256)}"
				_ = res // suppress unused warning
			}
			{ // "1." + tn
				_res = db.Exec("\n    SELECT * FROM ft(" + sqlLiteral(Q) + ")\n  ")
				if !tclCatchsqlMatches(_res, res) {
					t.Errorf("catchsql mismatch\n  got:  [%v]\n  want: [%s]\n  sql: %s", resErrString(_res), res, "\n    SELECT * FROM ft(" + sqlLiteral(Q) + ")\n  ")
				}
			}
		}
}
