// Code generated by tcl2go; DO NOT EDIT.
package altermalloc

import (
"github.com/pijalu/frigolite"
"testing"
)

func Test_altermalloc(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var rc string
	_ = rc // pre-declared from TCL source
	var Id_ string
	_ = Id_ // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	return
	// do_malloc_test altermalloc-1 -tclprep {\n  db close\n} -tclbody {\n  if {[catch {sqlite3 db test.db}]} {\n    error...} -sqlbody {\n  CREATE TABLE t1(a int);\n  ALTER TABLE t1 ADD ...} (unsupported command, not transpiled)
	// do_malloc_test altermalloc-vtab -tclprep {\n    sqlite3 db2 test.db \n    sqlite3_db_config_...} -tclbody {\n    set rc [catch {db eval { ALTER TABLE t1echo ...} (unsupported command, not transpiled)
}
