// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package bestindexG

import (
"github.com/pijalu/frigolite"
"os"
"testing"
)

func Test_bestindexG(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	var _r string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	_ = _r   // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var testprefix string
	_ = testprefix // pre-declared from TCL source
	var hdl string
	_ = hdl // pre-declared from TCL source
	var conslist string
	_ = conslist // pre-declared from TCL source
	var ret string
	_ = ret // pre-declared from TCL source
	var idxnum string
	_ = idxnum // pre-declared from TCL source
	var iCons string
	_ = iCons // pre-declared from TCL source
	var cons string
	_ = cons // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source
	var method string
	_ = method // pre-declared from TCL source
	var args string
	_ = args // pre-declared from TCL source
	var c_usable string
	_ = c_usable // pre-declared from TCL source
	var c_op string
	_ = c_op // pre-declared from TCL source
	var c_column string
	_ = c_column // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	testprefix = "bestindexF"
	_ = testprefix // suppress unused warning
	// proc definition (not transpiled)
	// register_tcl_module db (unsupported command, not transpiled)
	{ // "1.0"
		_res = db.Exec("\n  CREATE TABLE t1(rowid INTEGER PRIMARY KEY, id, k);\n  INSERT INTO t1 VALUES(1, 1, 1);\n  INSERT INTO t1 VALUES(2, 2, 2);\n  INSERT INTO t1 VALUES(3, 3, 3);\n  INSERT INTO t1 VALUES(4, 4, 4);\n\n  INSERT INTO t1 VALUES(5, 1, 11);\n  INSERT INTO t1 VALUES(6, 2, 22);\n  INSERT INTO t1 VALUES(7, 3, 33);\n  INSERT INTO t1 VALUES(8, 4, 44);\n\n  CREATE VIRTUAL TABLE tt USING tcl(vtab_command)\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE t1(rowid INTEGER PRIMARY KEY, id, k);\n  INSERT INTO t1 VALUES(1, 1, 1);\n  INSERT INTO t1 VALUES(2, 2, 2);\n  INSERT INTO t1 VALUES(3, 3, 3);\n  INSERT INTO t1 VALUES(4, 4, 4);\n\n  INSERT INTO t1 VALUES(5, 1, 11);\n  INSERT INTO t1 VALUES(6, 2, 22);\n  INSERT INTO t1 VALUES(7, 3, 33);\n  INSERT INTO t1 VALUES(8, 4, 44);\n\n  CREATE VIRTUAL TABLE tt USING tcl(vtab_command)\n")
		}
	}
	{ // "1.1"
		_res = db.Exec("\n  CREATE TABLE probe(id);\n  CREATE TABLE pr(id, k);\n  CREATE TABLE sl(id, dk);\n\n  INSERT INTO probe VALUES(3), (44);\n\n  INSERT INTO pr VALUES(3, 3);\n  INSERT INTO sl VALUES(3, 3);\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE probe(id);\n  CREATE TABLE pr(id, k);\n  CREATE TABLE sl(id, dk);\n\n  INSERT INTO probe VALUES(3), (44);\n\n  INSERT INTO pr VALUES(3, 3);\n  INSERT INTO sl VALUES(3, 3);\n")
		}
	}
	{ // "1.2"
		r = db.Query("\n  with v as (\n      select sl.id as id\n      from tt\n      left join pr on pr.k = tt.k\n      join sl on sl.dk = tt.id\n  )\n  select count(*) from probe join v on v.id = probe.id;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  with v as (\n      select sl.id as id\n      from tt\n      left join pr on pr.k = tt.k\n      join sl on sl.dk = tt.id\n  )\n  select count(*) from probe join v on v.id = probe.id;\n")
			return
		}
		got := flatten(r)
		want := "2"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
}
