// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package temptable

import (
"github.com/pijalu/frigolite"
"os"
"testing"
)

func Test_temptable(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var dummy string
	_ = dummy // pre-declared from TCL source
	var _r string
	_ = _r // pre-declared from TCL source
	var Id_ string
	_ = Id_ // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	return
	{ // do_test "temptable-1.0"
		db2, err = frigolite.Open("./test.db")
		if err != nil { t.Fatal(err) }
		dummy = ""
		_ = dummy // suppress unused warning
	}
	{ // do_test "temptable-1.1"
		_res = db.Exec("CREATE TABLE t1(a,b,c);")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "CREATE TABLE t1(a,b,c);")
		}
		_res = db.Exec("INSERT INTO t1 VALUES(1,2,3);")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "INSERT INTO t1 VALUES(1,2,3);")
		}
		r = db.Query("SELECT * FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT * FROM t1")
		}
	}
	{ // do_test "temptable-1.2"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			db2.Exec("SELECT * FROM sqlite_master")
			if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
		}
		db2.Exec("SELECT * FROM t1")
		if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
	}
	{ // do_test "temptable-1.3"
		r = db.Query("SELECT name FROM sqlite_master")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT name FROM sqlite_master")
		}
	}
	{ // do_test "temptable-1.4"
		db2.Exec("SELECT name FROM sqlite_master")
		if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
	}
	{ // do_test "temptable-1.5"
		db2.Exec("\n    CREATE TEMP TABLE t2(x,y,z);\n    INSERT INTO t2 VALUES(4,5,6);\n  ")
		if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
		db2.Exec("SELECT * FROM t2")
		if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
	}
	{ // do_test "temptable-1.6"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			r = db.Query("SELECT * FROM sqlite_master")
			if r.Error != nil { _catchErr = r.Error }
		}
		_res = db.Exec("SELECT * FROM t2")
		_ = _res // catchsql
	}
	{ // do_test "temptable-1.7"
		_res = db.Exec("INSERT INTO t2 VALUES(8,9,0);")
		_ = _res // catchsql
	}
	{ // do_test "temptable-1.8"
		db2.Exec("INSERT INTO t2 VALUES(8,9,0);")
		if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
		db2.Exec("SELECT * FROM t2 ORDER BY x")
		if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
	}
	{ // do_test "temptable-1.9"
		db2.Exec("DELETE FROM t2 WHERE x==8")
		if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
		db2.Exec("SELECT * FROM t2 ORDER BY x")
		if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
	}
	{ // do_test "temptable-1.10"
		db2.Exec("DELETE FROM t2")
		if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
		db2.Exec("SELECT * FROM t2")
		if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
	}
	{ // do_test "temptable-1.11"
		db2.Exec("\n     INSERT INTO t2 VALUES(7,6,5);\n     INSERT INTO t2 VALUES(4,3,2);\n     SELECT * FROM t2 ORDER BY x;\n  ")
		if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
	}
	{ // do_test "temptable-1.12"
		db2.Exec("DROP TABLE t2;")
		if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
	_ = _r // suppress unused warning
	_ = msg // suppress unused warning
		{ // catch block
			var _catchErr error
			db2.Exec("SELECT * FROM t2")
			if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
			if _catchErr != nil {
				_r = "1"
				msg = _catchErr.Error()
			} else {
				_r = "0"
				msg = ""
			}
		}
		_r = tclListAppend(_r, msg)
	}
	{ // do_test "temptable-2.1"
		r = db.Query("\n    BEGIN TRANSACTION;\n    CREATE TEMPORARY TABLE t2(x,y);\n    INSERT INTO t2 VALUES(1,2);\n    SELECT * FROM t2;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    BEGIN TRANSACTION;\n    CREATE TEMPORARY TABLE t2(x,y);\n    INSERT INTO t2 VALUES(1,2);\n    SELECT * FROM t2;\n  ")
		}
	}
	{ // do_test "temptable-2.2"
		_res = db.Exec("ROLLBACK")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "ROLLBACK")
		}
		_res = db.Exec("SELECT * FROM t2")
		_ = _res // catchsql
	}
	{ // do_test "temptable-2.3"
		r = db.Query("\n    BEGIN TRANSACTION;\n    CREATE TEMPORARY TABLE t2(x,y);\n    INSERT INTO t2 VALUES(1,2);\n    SELECT * FROM t2;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    BEGIN TRANSACTION;\n    CREATE TEMPORARY TABLE t2(x,y);\n    INSERT INTO t2 VALUES(1,2);\n    SELECT * FROM t2;\n  ")
		}
	}
	{ // do_test "temptable-2.4"
		_res = db.Exec("COMMIT")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "COMMIT")
		}
		_res = db.Exec("SELECT * FROM t2")
		_ = _res // catchsql
	}
	{ // do_test "temptable-2.5"
	_ = _r // suppress unused warning
	_ = msg // suppress unused warning
		{ // catch block
			var _catchErr error
			db2.Exec("SELECT * FROM t2")
			if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
			if _catchErr != nil {
				_r = "1"
				msg = _catchErr.Error()
			} else {
				_r = "0"
				msg = ""
			}
		}
		_r = tclListAppend(_r, msg)
	}
	{ // do_test "temptable-3.1"
		r = db.Query("\n    CREATE INDEX i2 ON t2(x);\n    SELECT name FROM sqlite_master WHERE type='index';\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    CREATE INDEX i2 ON t2(x);\n    SELECT name FROM sqlite_master WHERE type='index';\n  ")
		}
	}
	{ // do_test "temptable-3.2"
		r = db.Query("\n    SELECT y FROM t2 WHERE x=1;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT y FROM t2 WHERE x=1;\n  ")
		}
	}
	{ // do_test "temptable-3.3"
		r = db.Query("\n    DROP INDEX i2;\n    SELECT y FROM t2 WHERE x=1;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    DROP INDEX i2;\n    SELECT y FROM t2 WHERE x=1;\n  ")
		}
	}
	{ // do_test "temptable-3.4"
		_res = db.Exec("\n    CREATE INDEX i2 ON t2(x);\n    DROP TABLE t2;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE INDEX i2 ON t2(x);\n    DROP TABLE t2;\n  ")
		}
		_res = db.Exec("DROP INDEX i2")
		_ = _res // catchsql
	}
	{ // do_test "temptable-4.1"
		r = db.Query("\n    CREATE TEMP TABLE t2(x,y);\n    INSERT INTO t2 VALUES(10,20);\n    SELECT * FROM t2;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    CREATE TEMP TABLE t2(x,y);\n    INSERT INTO t2 VALUES(10,20);\n    SELECT * FROM t2;\n  ")
		}
	}
	{ // do_test "temptable-4.2"
		r = db.Query("\n    CREATE TABLE t2(x,y,z);\n    INSERT INTO t2 VALUES(9,8,7);\n    SELECT * FROM t2;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    CREATE TABLE t2(x,y,z);\n    INSERT INTO t2 VALUES(9,8,7);\n    SELECT * FROM t2;\n  ")
		}
	}
	{ // do_test "temptable-4.3"
		_res = db.Exec("\n    SELECT * FROM t2;\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-4.4.1"
		_res = db.Exec("\n    SELECT * FROM temp.t2;\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-4.4.2"
		_res = db.Exec("\n    SELECT * FROM main.t2;\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-4.4.4"
		_res = db.Exec("\n    SELECT name FROM main.sqlite_master WHERE type='table';\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-4.4.5"
		_res = db.Exec("\n    SELECT * FROM main.t2;\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-4.4.6"
		_res = db.Exec("\n    SELECT * FROM t2;\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-4.5"
		_res = db.Exec("\n    DROP TABLE t2;     -- should drop TEMP\n    SELECT * FROM t2;  -- data should be from MAIN\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-4.6"
		db2.Close()
		db2, err = frigolite.Open("./test.db")
		if err != nil { t.Fatal(err) }
		_res = db.Exec("\n    SELECT * FROM t2;\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-4.7"
		_res = db.Exec("\n    DROP TABLE t2;\n    SELECT * FROM t2;\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-4.8"
		db2.Close()
		db2, err = frigolite.Open("./test.db")
		if err != nil { t.Fatal(err) }
		r = db.Query("\n    CREATE TEMP TABLE t2(x unique,y);\n    INSERT INTO t2 VALUES(1,2);\n    SELECT * FROM t2;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    CREATE TEMP TABLE t2(x unique,y);\n    INSERT INTO t2 VALUES(1,2);\n    SELECT * FROM t2;\n  ")
		}
	}
	{ // do_test "temptable-4.9"
		r = db.Query("\n    CREATE TABLE t2(x unique, y);\n    INSERT INTO t2 VALUES(3,4);\n    SELECT * FROM t2;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    CREATE TABLE t2(x unique, y);\n    INSERT INTO t2 VALUES(3,4);\n    SELECT * FROM t2;\n  ")
		}
	}
	{ // do_test "temptable-4.10.1"
		_res = db.Exec("\n    SELECT * FROM t2;\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-4.10.3"
		_res = db.Exec("\n    SELECT name FROM sqlite_master WHERE type='table'\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-4.11"
		r = db.Query("\n    SELECT * FROM t2;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT * FROM t2;\n  ")
		}
	}
	{ // do_test "temptable-4.12"
		r = db.Query("\n    SELECT * FROM t2;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT * FROM t2;\n  ")
		}
	}
	{ // do_test "temptable-4.13"
		_res = db.Exec("\n    DROP TABLE t2;     -- drops TEMP.T2\n    SELECT * FROM t2;  -- uses MAIN.T2\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-4.14"
		r = db.Query("\n    SELECT * FROM t2;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT * FROM t2;\n  ")
		}
	}
	{ // do_test "temptable-4.15"
		db2.Close()
		db2, err = frigolite.Open("./test.db")
		if err != nil { t.Fatal(err) }
		r = db.Query("\n    SELECT * FROM t2;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT * FROM t2;\n  ")
		}
	}
	{ // do_test "temptable-5.1"
		_res = db.Exec("\n    CREATE TEMP TABLE mask(a,b,c)\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE TEMP TABLE mask(a,b,c)\n  ")
		}
		if tclBool("permutation" + "==\"prepare\"") {
		}
		r = db.Query("\n    CREATE INDEX mask ON t2(x);\n    SELECT * FROM t2;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    CREATE INDEX mask ON t2(x);\n    SELECT * FROM t2;\n  ")
		}
	}
	{ // do_test "temptable-5.3"
		_res = db.Exec("\n    SELECT * FROM t2;\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-5.4"
		r = db.Query("\n    SELECT y FROM t2 WHERE x=3\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT y FROM t2 WHERE x=3\n  ")
		}
	}
	{ // do_test "temptable-5.5"
		r = db.Query("\n    SELECT y FROM t2 WHERE x=3\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT y FROM t2 WHERE x=3\n  ")
		}
	}
	{ // do_test "temptable-5.6"
		r = db.Query("\n    INSERT INTO t2 VALUES(1,2);\n    SELECT y FROM t2 WHERE x=1;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    INSERT INTO t2 VALUES(1,2);\n    SELECT y FROM t2 WHERE x=1;\n  ")
		}
	}
	{ // do_test "temptable-5.7"
		r = db.Query("\n    SELECT y FROM t2 WHERE x=3\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT y FROM t2 WHERE x=3\n  ")
		}
	}
	{ // do_test "temptable-5.8"
		r = db.Query("\n    SELECT y FROM t2 WHERE x=1;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT y FROM t2 WHERE x=1;\n  ")
		}
	}
	{ // do_test "temptable-5.9"
		r = db.Query("\n    SELECT y FROM t2 WHERE x=3\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT y FROM t2 WHERE x=3\n  ")
		}
	}
	db2.Close()
	{ // do_test "temptable-6.1"
		r = db.Query("\n    CREATE TABLE t8(x);\n    INSERT INTO t8 VALUES('xyzzy');\n    SELECT * FROM t8;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    CREATE TABLE t8(x);\n    INSERT INTO t8 VALUES('xyzzy');\n    SELECT * FROM t8;\n  ")
		}
	}
	{ // do_test "temptable-6.2"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			// file attributes test.db -permissions 0444
		}
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			// file attributes test.db -readonly 1
		}
		_dbtmp0, err := frigolite.Open("test.db")
		_ = _dbtmp0 // sqlite3 db connection
		if err != nil { t.Fatal(err) }
		if tclBool("file writable test.db") {
			t.Errorf("TCL error: %s", "Unable to make the database file test.db readonly - rerun this test as an unprivileged user")
		}
		r = db.Query("\n    SELECT * FROM t8;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT * FROM t8;\n  ")
		}
	}
	{ // do_test "temptable-6.3"
		if tclBool("file writable test.db") {
			t.Errorf("TCL error: %s", "Unable to make the database file test.db readonly - rerun this test as an unprivileged user")
		}
		_res = db.Exec("\n    CREATE TABLE t9(x,y);\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-6.4"
		_res = db.Exec("\n    CREATE TEMP TABLE t9(x,y);\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-6.5"
		_res = db.Exec("\n    INSERT INTO t9 VALUES(1,2);\n    SELECT * FROM t9;\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-6.6"
		if tclBool("file writable test.db") {
			t.Errorf("TCL error: %s", "Unable to make the database file test.db readonly - rerun this test as an unprivileged user")
		}
		_res = db.Exec("\n    INSERT INTO t8 VALUES('hello');\n    SELECT * FROM t8;\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-6.7"
		_res = db.Exec("\n    SELECT * FROM t8,t9;\n  ")
		_ = _res // catchsql
	}
	{ // do_test "temptable-6.8"
		_dbtmp1, err := frigolite.Open("test.db")
		_ = _dbtmp1 // sqlite3 db connection
		if err != nil { t.Fatal(err) }
		_res = db.Exec("\n    SELECT * FROM t8,t9;\n  ")
		_ = _res // catchsql
	}
	os.Remove("test2.db")
	{ // do_test "temptable-7.1"
		_res = db.Exec("\n      ATTACH 'test2.db' AS two;\n      CREATE TEMP TABLE two.abc(x,y);\n    ")
		_ = _res // catchsql
	}
	{
		var _catchErr error
		_ = _catchErr // suppress unused warning
		// file attributes test.db -readonly 0
	}
	{ // do_test "temptable-8.0"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			os.Remove("test.db")
		}
		_dbtmp2, err := frigolite.Open("test.db")
		_ = _dbtmp2 // sqlite3 db connection
		if err != nil { t.Fatal(err) }
	}
	{ // do_test "temptable-8.1"
		_res = db.Exec(" CREATE TEMP TABLE tbl2(a, b); ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " CREATE TEMP TABLE tbl2(a, b); ")
		}
		_res = db.Exec("\n    CREATE TABLE tbl(a, b);\n    INSERT INTO tbl VALUES(1, 2);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE TABLE tbl(a, b);\n    INSERT INTO tbl VALUES(1, 2);\n  ")
		}
		r = db.Query("SELECT * FROM tbl")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT * FROM tbl")
		}
	}
	{ // do_test "temptable-8.2"
		_res = db.Exec(" CREATE TEMP TABLE tbl(a, b); ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " CREATE TEMP TABLE tbl(a, b); ")
		}
		r = db.Query("SELECT * FROM tbl")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT * FROM tbl")
		}
	}
}
