// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package bind

import (
"github.com/pijalu/frigolite"
"github.com/pijalu/frigolite/internal/vtab"
"os"
"strconv"
"strings"
"testing"
)

func Test_bind(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	var _r string
	var _berr error
	_ = _berr // suppress unused warning
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	_ = _r   // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9
	var TAIL string
	_ = TAIL // prepared-statement tail var

	var testdir string
	_ = testdir // pre-declared from TCL source
	var vals string
	_ = vals // pre-declared from TCL source
	var cols string
	_ = cols // pre-declared from TCL source
	var rc string
	_ = rc // pre-declared from TCL source
	var i string
	_ = i // pre-declared from TCL source
	var DB string
	_ = DB // pre-declared from TCL source
	var VM string
	_ = VM // pre-declared from TCL source
	var sqlite_static_bind_value string
	_ = sqlite_static_bind_value // pre-declared from TCL source
	var TX string
	_ = TX // pre-declared from TCL source
	var v1 string
	_ = v1 // pre-declared from TCL source
	var v2 string
	_ = v2 // pre-declared from TCL source
	var v3 string
	_ = v3 // pre-declared from TCL source
	var x string
	_ = x // pre-declared from TCL source
	var y string
	_ = y // pre-declared from TCL source
	var enc string
	_ = enc // pre-declared from TCL source
	var Unknown_database_encoding___enc string
	_ = Unknown_database_encoding___enc // pre-declared from TCL source
	var iMaxVar string
	_ = iMaxVar // pre-declared from TCL source
	var zError string
	_ = zError // pre-declared from TCL source
	var ret string
	_ = ret // pre-declared from TCL source
	var ii string
	_ = ii // pre-declared from TCL source
	var Id_ string
	_ = Id_ // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source
	var stmt string
	_ = stmt // pre-declared from TCL source
	var abc_123 string
	_ = abc_123 // pre-declared from TCL source
	var _var string
	_ = _var // pre-declared from TCL source
	var one string
	_ = one // pre-declared from TCL source
	var two string
	_ = two // pre-declared from TCL source
	var x__z_ string
	_ = x__z_ // pre-declared from TCL source
	var abc string
	_ = abc // pre-declared from TCL source
	var ab string
	_ = ab // pre-declared from TCL source
	var zSql string
	_ = zSql // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	// proc definition (not transpiled)
	{ // do_test "bind-1.1"
		DB = "db"
		_ = DB // suppress unused warning
		_res = db.Exec("CREATE TABLE t1(a,b,c);")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "CREATE TABLE t1(a,b,c);")
		}
		_r = tclPrepareStmt(db, "VM", "INSERT INTO t1 VALUES(:1,?,:abc)", -1)
		// prepared VM: INSERT INTO t1 VALUES(:1,?,:abc) (bind/step emulation)
		TAIL = tclSqlTail("INSERT INTO t1 VALUES(:1,?,:abc)")
		_ = TAIL // suppress unused warning
		_ = VM // prepared statement handle
		got := tclListFlattenCollapse(TAIL)
		want := tclListFlattenCollapse("")
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", got, want, "bind-1.1")
		}
	}
	{ // do_test "bind-1.1.1"
		_r = strconv.Itoa(tclParamCountOf("VM"))
	}
	{ // do_test "bind-1.1.2"
		_r = tclParamNameOf("VM", 1)
	}
	{ // do_test "bind-1.1.3"
		_r = tclParamNameOf("VM", 2)
	}
	{ // do_test "bind-1.1.4"
		_r = tclParamNameOf("VM", 3)
	}
	{ // do_test "bind-1.2"
		_r = tclStepStmt(db, "VM")
	}
	{ // do_test "bind-1.3"
		r = db.Query("SELECT rowid, * FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT rowid, * FROM t1")
		}
	}
	{ // do_test "bind-1.4"
		_r = tclResetStmtCode("VM")
		_r = tclBindStmt(db, "VM", 1, "text", "test value 1", -1)
		_r = tclStepStmt(db, "VM")
	}
	{ // do_test "bind-1.5"
		r = db.Query("SELECT rowid, * FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT rowid, * FROM t1")
		}
	}
	{ // do_test "bind-1.6"
		_r = tclResetStmtCode("VM")
		_r = tclBindStmt(db, "VM", 3, "text", "'test value 2'", -1)
		_r = tclStepStmt(db, "VM")
	}
	{ // do_test "bind-1.7"
		r = db.Query("SELECT rowid, * FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT rowid, * FROM t1")
		}
	}
	{ // do_test "bind-1.8"
		_r = tclResetStmtCode("VM")
		vtab.TclVarSet("sqlite_static_bind_value", "", "123")
		sqlite_static_bind_value = "123"
		_ = sqlite_static_bind_value // suppress unused warning
		_r = tclBindStmt(db, "VM", 1, "text", sqlite_static_bind_value, -1)
		_r = tclBindStmt(db, "VM", 2, "text", "abcdefg", -1)
		_r = tclBindStmt(db, "VM", 3, "null", "", -1)
		_res = db.Exec("DELETE FROM t1")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "DELETE FROM t1")
		}
		_r = tclStepStmt(db, "VM")
		r = db.Query("SELECT rowid, * FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT rowid, * FROM t1")
		}
	}
	{ // do_test "bind-1.9"
		_r = tclResetStmtCode("VM")
		_r = tclBindStmt(db, "VM", 1, "text", "456", -1)
		_r = tclStepStmt(db, "VM")
		r = db.Query("SELECT rowid, * FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT rowid, * FROM t1")
		}
	}
	{ // do_test "bind-1.10"
	_ = rc // suppress unused warning
	_ = msg // suppress unused warning
		{ // catch block
			var _catchErr error
			// sqlite3_prepare (standalone prepare; not emulated)
			if _catchErr != nil {
				rc = "1"
				msg = _catchErr.Error()
			} else {
				rc = "0"
				msg = ""
			}
		}
		rc = tclListAppend(rc, msg)
	}
	{ // do_test "bind-1.11"
	_ = rc // suppress unused warning
	_ = msg // suppress unused warning
		{ // catch block
			var _catchErr error
			// sqlite3_prepare (standalone prepare; not emulated)
			if _catchErr != nil {
				rc = "1"
				msg = _catchErr.Error()
			} else {
				rc = "0"
				msg = ""
			}
		}
		rc = tclListAppend(rc, msg)
	}
	{ // do_test "bind-1.99"
		_r = tclFinalizeStmt(db, "VM")
	}
	{ // do_test "bind-2.1"
		_res = db.Exec("\n      DELETE FROM t1;\n    ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      DELETE FROM t1;\n    ")
		}
		_r = tclPrepareStmt(db, "VM", "INSERT INTO t1 VALUES($one,$::two,$x(-z-))", -1)
		// prepared VM: INSERT INTO t1 VALUES($one,$::two,$x(-z-)) (bind/step emulation)
		TX = tclSqlTail("INSERT INTO t1 VALUES($one,$::two,$x(-z-))")
		_ = TX // suppress unused warning
		_ = VM // prepared statement handle
		got := tclListFlatten(TX)
		want := tclListFlatten("")
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", got, want, "bind-2.1")
		}
	}
	vtab.TclVarSet("v1", "", one)
	v1 = one
	_ = v1 // suppress unused warning
	vtab.TclVarSet("v2", "", two)
	v2 = two
	_ = v2 // suppress unused warning
	vtab.TclVarSet("v3", "", x__z_)
	v3 = x__z_
	_ = v3 // suppress unused warning
	{ // do_test "bind-2.1.1"
		_r = strconv.Itoa(tclParamCountOf("VM"))
	}
	{ // do_test "bind-2.1.2"
		_r = tclParamNameOf("VM", 1)
		if _r != v1 {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", _r, v1, "bind-2.1.2")
		}
	}
	{ // do_test "bind-2.1.3"
		_r = tclParamNameOf("VM", 2)
		if _r != v2 {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", _r, v2, "bind-2.1.3")
		}
	}
	{ // do_test "bind-2.1.4"
		_r = tclParamNameOf("VM", 3)
		if _r != v3 {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", _r, v3, "bind-2.1.4")
		}
	}
	{ // do_test "bind-2.1.5"
		_r = strconv.Itoa(tclParamIndexOf("VM", v1))
	}
	{ // do_test "bind-2.1.6"
		_r = strconv.Itoa(tclParamIndexOf("VM", v2))
	}
	{ // do_test "bind-2.1.7"
		_r = strconv.Itoa(tclParamIndexOf("VM", v3))
	}
	{ // do_test "bind-2.1.8"
		_r = strconv.Itoa(tclParamIndexOf("VM", ":hi"))
	}
	{ // do_test "bind-2.2"
		_r = tclBindStmt(db, "VM", 1, "int", "123", -1)
		_r = tclBindStmt(db, "VM", 2, "int", "456", -1)
		_r = tclBindStmt(db, "VM", 3, "int", "789", -1)
		_r = tclStepStmt(db, "VM")
		_r = tclResetStmtCode("VM")
		r = db.Query("SELECT rowid, * FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT rowid, * FROM t1")
		}
	}
	{ // do_test "bind-2.3"
		_r = tclBindStmt(db, "VM", 2, "int", "-2000000000", -1)
		_r = tclBindStmt(db, "VM", 3, "int", "2000000000", -1)
		_r = tclStepStmt(db, "VM")
		_r = tclResetStmtCode("VM")
		r = db.Query("SELECT rowid, * FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT rowid, * FROM t1")
		}
	}
	{ // do_test "bind-2.4"
		r = db.Query("SELECT typeof(a), typeof(b), typeof(c) FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT typeof(a), typeof(b), typeof(c) FROM t1")
		}
	}
	{ // do_test "bind-2.5"
		_res = db.Exec("\n    DELETE FROM t1;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    DELETE FROM t1;\n  ")
		}
	}
	{ // do_test "bind-3.1"
		_r = tclBindStmt(db, "VM", 1, "int", "32", -1)
		_r = tclBindStmt(db, "VM", 2, "int", "-2000000000000", -1)
		_r = tclBindStmt(db, "VM", 3, "int", "2000000000000", -1)
		_r = tclStepStmt(db, "VM")
		_r = tclResetStmtCode("VM")
		r = db.Query("SELECT rowid, * FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT rowid, * FROM t1")
		}
	}
	{ // do_test "bind-3.2"
		r = db.Query("SELECT typeof(a), typeof(b), typeof(c) FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT typeof(a), typeof(b), typeof(c) FROM t1")
		}
	}
	{ // do_test "bind-3.3"
		_res = db.Exec("\n    DELETE FROM t1;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    DELETE FROM t1;\n  ")
		}
	}
	{ // do_test "bind-4.1"
		_r = tclBindStmt(db, "VM", 1, "double", "1234.1234", -1)
		_r = tclBindStmt(db, "VM", 2, "double", "0.00001", -1)
		_r = tclBindStmt(db, "VM", 3, "double", "123456789", -1)
		_r = tclStepStmt(db, "VM")
		_r = tclResetStmtCode("VM")
		x = tclExecSQL(db, "SELECT rowid, * FROM t1")
		_ = x // suppress unused warning
		y = tclRegsub("1e-005", x, "1e-05")
		_ = y // suppress unused warning
		got := tclListFlatten(y)
		want := tclListFlatten("1 1234.1234 1e-05 123456789.0")
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", got, want, "bind-4.1")
		}
	}
	{ // do_test "bind-4.2"
		r = db.Query("SELECT typeof(a), typeof(b), typeof(c) FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT typeof(a), typeof(b), typeof(c) FROM t1")
		}
	}
	{ // do_test "bind-4.3"
		_res = db.Exec("\n    DELETE FROM t1;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    DELETE FROM t1;\n  ")
		}
	}
	{ // do_test "bind-4.4"
		_r = tclBindStmt(db, "VM", 1, "double", "NaN", -1)
		_r = tclBindStmt(db, "VM", 2, "double", "1e300", -1)
		_r = tclBindStmt(db, "VM", 3, "double", "-1e-300", -1)
		_r = tclStepStmt(db, "VM")
		_r = tclResetStmtCode("VM")
		x = tclExecSQL(db, "SELECT rowid, * FROM t1")
		_ = x // suppress unused warning
		y = tclRegsub("1e-005", x, "1e-05")
		_ = y // suppress unused warning
		got := tclListFlatten(y)
		want := tclListFlatten("1 {} 1e+300 -1e-300")
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", got, want, "bind-4.4")
		}
	}
	{ // do_test "bind-4.5"
		r = db.Query("SELECT typeof(a), typeof(b), typeof(c) FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT typeof(a), typeof(b), typeof(c) FROM t1")
		}
	}
	{ // do_test "bind-4.6"
		_res = db.Exec("\n    DELETE FROM t1;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    DELETE FROM t1;\n  ")
		}
	}
	{ // do_test "bind-5.1"
		_r = tclBindStmt(db, "VM", 1, "null", "", -1)
		_r = tclBindStmt(db, "VM", 2, "null", "", -1)
		_r = tclBindStmt(db, "VM", 3, "null", "", -1)
		_r = tclStepStmt(db, "VM")
		_r = tclResetStmtCode("VM")
		r = db.Query("SELECT rowid, * FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT rowid, * FROM t1")
		}
	}
	{ // do_test "bind-5.2"
		r = db.Query("SELECT typeof(a), typeof(b), typeof(c) FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT typeof(a), typeof(b), typeof(c) FROM t1")
		}
	}
	{ // do_test "bind-5.3"
		_res = db.Exec("\n    DELETE FROM t1;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    DELETE FROM t1;\n  ")
		}
	}
	{ // do_test "bind-6.1"
		_r = tclBindStmt(db, "VM", 1, "text", "hellothere", 5)
		_r = tclBindStmt(db, "VM", 2, "text", "..", 1)
		_r = tclBindStmt(db, "VM", 3, "text", "world\\000", -1)
		_r = tclStepStmt(db, "VM")
		_r = tclResetStmtCode("VM")
		r = db.Query("SELECT rowid, * FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT rowid, * FROM t1")
		}
	}
	{ // do_test "bind-6.2"
		r = db.Query("SELECT typeof(a), typeof(b), typeof(c) FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT typeof(a), typeof(b), typeof(c) FROM t1")
		}
	}
	{ // do_test "bind-6.3"
		_res = db.Exec("\n    DELETE FROM t1;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    DELETE FROM t1;\n  ")
		}
	}
	{ // do_test "bind-6.4"
		_res = db.Exec("DELETE FROM t1")
		_r = tclBindStmt(db, "VM", 1, "text", "hello\\000there\\000", 12)
		_r = tclBindStmt(db, "VM", 2, "text", "hello\\000there\\000", 11)
		_r = tclBindStmt(db, "VM", 3, "text", "hello\\000there\\000", -1)
		_r = tclStepStmt(db, "VM")
		_r = tclResetStmtCode("VM")
		r = db.Query("SELECT * FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT * FROM t1")
		}
	}
	_dbeval0 := tclExecSQL(db, "PRAGMA encoding")
	enc = _dbeval0
	_ = enc // suppress unused warning
	if tclBool(enc + "==\"UTF-8\" || " + enc + "==\"\"") {
		{ // do_test "bind-6.5"
			r = db.Query("SELECT  hex(a), hex(b), hex(c) FROM t1")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT  hex(a), hex(b), hex(c) FROM t1")
			}
		}
	} else if enc == "UTF-16le" {
		{ // do_test "bind-6.5"
			r = db.Query("SELECT  hex(a), hex(b), hex(c) FROM t1")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT  hex(a), hex(b), hex(c) FROM t1")
			}
		}
	} else if enc == "UTF-16be" {
		{ // do_test "bind-6.5"
			r = db.Query("SELECT  hex(a), hex(b), hex(c) FROM t1")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT  hex(a), hex(b), hex(c) FROM t1")
			}
		}
	} else {
		{ // do_test "bind-6.5"
			got := tclListFlatten(Unknown_database_encoding___enc)
			want := tclListFlatten("")
			if got != want {
				t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", got, want, "bind-6.5")
			}
		}
	}
	{ // do_test "bind-6.6"
		r = db.Query("SELECT typeof(a), typeof(b), typeof(c) FROM t1")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT typeof(a), typeof(b), typeof(c) FROM t1")
		}
	}
	{ // do_test "bind-6.7"
		_res = db.Exec("\n    DELETE FROM t1;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    DELETE FROM t1;\n  ")
		}
	}
	{ // do_test "bind-7.99"
		_res = db.Exec("DELETE FROM t1;")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "DELETE FROM t1;")
		}
	}
	{ // do_test "bind-8.1"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			_r = tclBindStmt(db, "VM", 0, "null", "", -1)
		}
	}
	{ // do_test "bind-8.2"
		_r = tclErrMsg(db)
		if _r != "column index out of range" {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", _r, "column index out of range", "bind-8.2")
		}
	}
	{ // do_test "bind-8.4"
		_r = tclBindStmt(db, "VM", 1, "null", "", -1)
		_r = tclErrMsg(db)
		if _r != "not an error" {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", _r, "not an error", "bind-8.4")
		}
	}
	{ // do_test "bind-8.5"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			_r = tclBindStmt(db, "VM", 4, "null", "", -1)
		}
	}
	{ // do_test "bind-8.6"
		_r = tclErrMsg(db)
		if _r != "column index out of range" {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", _r, "column index out of range", "bind-8.6")
		}
	}
	{ // do_test "bind-8.8"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			_r = tclBindStmt(db, "VM", 0, "blob", "abc", -1)
		}
	}
	{ // do_test "bind-8.9"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			_r = tclBindStmt(db, "VM", 4, "blob", "abc", -1)
		}
	}
	{ // do_test "bind-8.10"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			_r = tclBindStmt(db, "VM", 0, "text", "abc", 3)
		}
	}
	{ // do_test "bind-8.12"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			_r = tclBindStmt(db, "VM", 0, "int", "5", -1)
		}
	}
	{ // do_test "bind-8.13"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			_r = tclBindStmt(db, "VM", 4, "int", "5", -1)
		}
	}
	{ // do_test "bind-8.14"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			_r = tclBindStmt(db, "VM", 0, "double", "5.0", -1)
		}
	}
	{ // do_test "bind-8.15"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			_r = tclBindStmt(db, "VM", 4, "double", "6.0", -1)
		}
	}
	{ // do_test "bind-8.99"
		_r = tclFinalizeStmt(db, "VM")
	}
	vtab.TclVarSet("iMaxVar", "", SQLITE_MAX_VARIABLE_NUMBER)
	iMaxVar = SQLITE_MAX_VARIABLE_NUMBER
	_ = iMaxVar // suppress unused warning
	vtab.TclVarSet("zError", "", "(1) variable number must be between ?1 and ?" + iMaxVar)
	zError = "(1) variable number must be between ?1 and ?" + iMaxVar
	_ = zError // suppress unused warning
	{ // do_test "bind-9.1"
		_res = db.Exec("\n    CREATE TABLE t2(a,b,c,d,e,f);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE TABLE t2(a,b,c,d,e,f);\n  ")
		}
	_ = rc // suppress unused warning
	_ = msg // suppress unused warning
		{ // catch block
			var _catchErr error
			// sqlite3_prepare (standalone prepare; not emulated)
			if _catchErr != nil {
				rc = "1"
				msg = _catchErr.Error()
			} else {
				rc = "0"
				msg = ""
			}
		}
		rc = tclListAppend(rc, msg)
	}
	{ // do_test "bind-9.2"
	_ = rc // suppress unused warning
	_ = msg // suppress unused warning
		{ // catch block
			var _catchErr error
			// sqlite3_prepare (standalone prepare; not emulated)
			if _catchErr != nil {
				rc = "1"
				msg = _catchErr.Error()
			} else {
				rc = "0"
				msg = ""
			}
		}
		rc = tclListAppend(rc, msg)
	}
	{ // do_test "bind-9.3.1"
		_r = tclPrepareStmt(db, "VM", "INSERT INTO t2(a,b) VALUES(?1,?" + iMaxVar + ")", -1)
		// prepared VM: INSERT INTO t2(a,b) VALUES(?1,?$iMaxVar) (bind/step emulation)
		TAIL = tclSqlTail("INSERT INTO t2(a,b) VALUES(?1,?$iMaxVar)")
		_ = TAIL // suppress unused warning
		_ = VM // prepared statement handle
		_r = strconv.Itoa(tclParamCountOf("VM"))
		if _r != iMaxVar {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", _r, iMaxVar, "bind-9.3.1")
		}
	}
	{
		var _catchErr error
		_ = _catchErr // suppress unused warning
		_r = tclFinalizeStmt(db, "VM")
	}
	{ // do_test "bind-9.3.2"
		_r = tclPrepareStmt(db, "VM", "INSERT INTO t2(a,b) VALUES(?2,?" + tclExprWith("$iMaxVar - 1", map[string]string{"iMaxVar": iMaxVar}) + ")", -1)
		// prepared VM: INSERT INTO t2(a,b) VALUES(?2,?[expr $iMaxVar - 1]) (bind/step emulation)
		TAIL = tclSqlTail("INSERT INTO t2(a,b) VALUES(?2,?[expr $iMaxVar - 1])")
		_ = TAIL // suppress unused warning
		_ = VM // prepared statement handle
		_r = strconv.Itoa(tclParamCountOf("VM"))
	}
	{
		var _catchErr error
		_ = _catchErr // suppress unused warning
		_r = tclFinalizeStmt(db, "VM")
	}
	{ // do_test "bind-9.4"
		_r = tclPrepareStmt(db, "VM", "INSERT INTO t2(a,b,c,d) VALUES(?1,?" + tclExprWith("$iMaxVar - 2", map[string]string{"iMaxVar": iMaxVar}) + ",?,?)", -1)
		// prepared VM: INSERT INTO t2(a,b,c,d) VALUES(?1,?[expr $iMaxVar - 2],?,?) (bind/step emulation)
		TAIL = tclSqlTail("INSERT INTO t2(a,b,c,d) VALUES(?1,?[expr $iMaxVar - 2],?,?)")
		_ = TAIL // suppress unused warning
		_ = VM // prepared statement handle
		_r = strconv.Itoa(tclParamCountOf("VM"))
		if _r != iMaxVar {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", _r, iMaxVar, "bind-9.4")
		}
	}
	{ // do_test "bind-9.5"
		_r = tclBindStmt(db, "VM", 1, "int", "1", -1)
		// sqlite3_bind_int $VM [expr $iMaxVar - 2] (non-numeric bind index)
		// sqlite3_bind_int $VM [expr $iMaxVar - 1] (non-numeric bind index)
		// sqlite3_bind_int $VM $iMaxVar (non-numeric bind index)
		_r = tclStepStmt(db, "VM")
	}
	{ // do_test "bind-9.6"
		_r = tclFinalizeStmt(db, "VM")
	}
	{ // do_test "bind-9.7"
		r = db.Query("SELECT * FROM t2")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT * FROM t2")
		}
	}
	{ // do_test "bind-10.1"
		_r = tclPrepareStmt(db, "VM", "INSERT INTO t2(a,b,c,d,e,f) VALUES(:abc,$abc,:abc,$ab,$abc,:abc)", -1)
		// prepared VM: INSERT INTO t2(a,b,c,d,e,f) VALUES(:abc,$abc,:abc,$ab,$abc,:abc) (bind/step emulation)
		TAIL = tclSqlTail("INSERT INTO t2(a,b,c,d,e,f) VALUES(:abc,$abc,:abc,$ab,$abc,:abc)")
		_ = TAIL // suppress unused warning
		_ = VM // prepared statement handle
		_r = strconv.Itoa(tclParamCountOf("VM"))
	}
	vtab.TclVarSet("v1", "", abc)
	v1 = abc
	_ = v1 // suppress unused warning
	vtab.TclVarSet("v2", "", ab)
	v2 = ab
	_ = v2 // suppress unused warning
	{ // do_test "bind-10.2"
		_r = strconv.Itoa(tclParamIndexOf("VM", ":abc"))
	}
	{ // do_test "bind-10.3"
		_r = strconv.Itoa(tclParamIndexOf("VM", v1))
	}
	{ // do_test "bind-10.4"
		_r = strconv.Itoa(tclParamIndexOf("VM", v2))
	}
	{ // do_test "bind-10.5"
		_r = tclParamNameOf("VM", 1)
	}
	{ // do_test "bind-10.6"
		_r = tclParamNameOf("VM", 2)
		if _r != v1 {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", _r, v1, "bind-10.6")
		}
	}
	{ // do_test "bind-10.7"
		_r = tclParamNameOf("VM", 3)
		if _r != v2 {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", _r, v2, "bind-10.7")
		}
	}
	{ // do_test "bind-10.7.1"
		_r = tclParamNameOf("v_0", 1)
	}
	{ // do_test "bind-10.7.2"
		_r = tclParamNameOf("VM", 0)
	}
	{ // do_test "bind-10.7.3"
		_r = tclParamNameOf("VM", 4)
	}
	{ // do_test "bind-10.8"
		_r = tclBindStmt(db, "VM", 1, "int", "1", -1)
		_r = tclBindStmt(db, "VM", 2, "int", "2", -1)
		_r = tclBindStmt(db, "VM", 3, "int", "3", -1)
		_r = tclStepStmt(db, "VM")
	}
	{ // do_test "bind-10.8.1"
	_ = rc // suppress unused warning
	_ = msg // suppress unused warning
		{ // catch block
			var _catchErr error
			_r = tclBindStmt(db, "VM", 1, "int", "1", -1)
			if _catchErr != nil {
				rc = "1"
				msg = _catchErr.Error()
			} else {
				rc = "0"
				msg = ""
			}
		}
		rc = tclListAppend(rc, msg)
	}
	{ // do_test "bind-10.9"
		_r = tclFinalizeStmt(db, "VM")
	}
	{ // do_test "bind-10.10"
		r = db.Query("SELECT * FROM t2")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT * FROM t2")
		}
	}
	{ // do_test "bind-10.11"
		_r = tclPrepareStmt(db, "VM", "INSERT INTO t2(a,b,c,d,e,f) VALUES(:abc,?,?4,:pqr,:abc,?4)", -1)
		// prepared VM: INSERT INTO t2(a,b,c,d,e,f) VALUES(:abc,?,?4,:pqr,:abc,?4) (bind/step emulation)
		TAIL = tclSqlTail("INSERT INTO t2(a,b,c,d,e,f) VALUES(:abc,?,?4,:pqr,:abc,?4)")
		_ = TAIL // suppress unused warning
		_ = VM // prepared statement handle
		_r = strconv.Itoa(tclParamCountOf("VM"))
	}
	{ // do_test "bind-10.11.1"
		_r = strconv.Itoa(tclParamIndexOf("v_0", ":xyz"))
	}
	{ // do_test "bind-10.12"
		_r = strconv.Itoa(tclParamIndexOf("VM", ":xyz"))
	}
	{ // do_test "bind-10.13"
		_r = strconv.Itoa(tclParamIndexOf("VM", ""))
	}
	{ // do_test "bind-10.14"
		_r = strconv.Itoa(tclParamIndexOf("VM", ":pqr"))
	}
	{ // do_test "bind-10.15"
		_r = strconv.Itoa(tclParamIndexOf("VM", "?4"))
	}
	{ // do_test "bind-10.16"
		_r = tclParamNameOf("VM", 1)
	}
	{ // do_test "bind-10.17"
		_r = tclParamNameOf("VM", 2)
	}
	{ // do_test "bind-10.18"
		_r = tclParamNameOf("VM", 3)
	}
	{ // do_test "bind-10.19"
		_r = tclParamNameOf("VM", 4)
	}
	{ // do_test "bind-10.20"
		_r = tclParamNameOf("VM", 5)
	}
	{
		var _catchErr error
		_ = _catchErr // suppress unused warning
		_r = tclFinalizeStmt(db, "VM")
	}
	{ // do_test "bind-11.1"
		_res = db.Exec("SELECT * FROM sqlite_master WHERE name=$abc(123 and sql NOT NULL;")
		if _res.Error == nil || !strings.Contains(_res.Error.Error(), "unrecognized token: \"$abc(123\"") {
			t.Errorf("expected error containing %q, got: %v\n  sql: %s", "unrecognized token: \"$abc(123\"", _res.Error, "SELECT * FROM sqlite_master WHERE name=$abc(123 and sql NOT NULL;")
		}
	}
	if tclExecSQL(db, "pragma encoding") == "UTF-8" {
		{ // do_test "bind-12.1"
			_res = db.Exec("\n      CREATE TABLE t3(x BLOB);\n    ")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      CREATE TABLE t3(x BLOB);\n    ")
			}
			_r = tclPrepareStmt(db, "VM", "INSERT INTO t3 VALUES(?)", -1)
			// prepared VM: INSERT INTO t3 VALUES(?) (bind/step emulation)
			TAIL = tclSqlTail("INSERT INTO t3 VALUES(?)")
			_ = TAIL // suppress unused warning
			_ = VM // prepared statement handle
			_r = tclBindStmt(db, "VM", 1, "blob10", "not-used", 10)
			_r = tclStepStmt(db, "VM")
			_r = tclFinalizeStmt(db, "VM")
			r = db.Query("\n      SELECT typeof(x), length(x), quote(x),\n             length(cast(x AS BLOB)), quote(cast(x AS BLOB)) FROM t3\n    ")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "\n      SELECT typeof(x), length(x), quote(x),\n             length(cast(x AS BLOB)), quote(cast(x AS BLOB)) FROM t3\n    ")
			}
		}
		{ // do_test "bind-12.2"
			db.RegisterFunction("x_coalesce", func(a []interface{}) (interface{}, error) {
				for _, v := range a { if v != nil { return v, nil } }
				return nil, nil
			}, 1, -1)
			r = db.Query("\n      SELECT quote(cast(x_coalesce(x) AS blob)) FROM t3\n    ")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "\n      SELECT quote(cast(x_coalesce(x) AS blob)) FROM t3\n    ")
			}
		}
	}
	{ // do_test "bind-13.1"
		_r = tclPrepareStmt(db, "VM", "SELECT ?,?,?", -1)
		// prepared VM: SELECT ?,?,? (bind/step emulation)
		TAIL = tclSqlTail("SELECT ?,?,?")
		_ = TAIL // suppress unused warning
		_ = VM // prepared statement handle
		_r = tclStepStmt(db, "VM")
		_list := tclList([]string{"sqlite3_column_type $VM 0", "sqlite3_column_type $VM 1", "sqlite3_column_type $VM 2"})
		_ = _list
		_r = _list
	}
	{ // do_test "bind-13.2"
		_r = tclResetStmtCode("VM")
		_r = tclBindStmt(db, "VM", 1, "int", "1", -1)
		_r = tclBindStmt(db, "VM", 2, "int", "2", -1)
		_r = tclBindStmt(db, "VM", 3, "int", "3", -1)
		_r = tclStepStmt(db, "VM")
		_list := tclList([]string{"sqlite3_column_type $VM 0", "sqlite3_column_type $VM 1", "sqlite3_column_type $VM 2"})
		_ = _list
		_r = _list
	}
	{ // do_test "bind-13.3"
		_r = tclResetStmtCode("VM")
		_r = tclStepStmt(db, "VM")
		_list := tclList([]string{"sqlite3_column_type $VM 0", "sqlite3_column_type $VM 1", "sqlite3_column_type $VM 2"})
		_ = _list
		_r = _list
	}
	{ // do_test "bind-13.4"
		_r = tclResetStmtCode("VM")
		_r = tclClearBindingsStmt("VM")
		_r = tclStepStmt(db, "VM")
		_list := tclList([]string{"sqlite3_column_type $VM 0", "sqlite3_column_type $VM 1", "sqlite3_column_type $VM 2"})
		_ = _list
		_r = _list
	}
	_r = tclFinalizeStmt(db, "VM")
	// proc definition (not transpiled)
	{ // do_test "bind-14.1"
		// param_names db { SELECT @a, @b } (unsupported command, not transpiled)
	}
	{ // do_test "bind-14.2"
		// param_names db { SELECT NULL FROM (SELECT NULL) WHERE @a = @b } (unsupported command, not transpiled)
	}
	{ // do_test "bind-14.3"
		// param_names db { SELECT @a FROM (SELECT NULL) WHERE 1 = @b } (unsupported command, not transpiled)
	}
	{ // do_test "bind-14.4"
		// param_names db { SELECT @a, @b FROM (SELECT NULL) } (unsupported command, not transpiled)
	}
	{ // do_test "bind-15.1"
		_res = db.Exec("CREATE TABLE t4(a,b,c,d,e,f,g,h);")
		_r = tclPrepareStmt(db, "VM", "INSERT INTO t4(a,b,c,d,f,g,h,e) VALUES(?,?,?,?,?,?,?,?)", -1)
		// prepared VM: INSERT INTO t4(a,b,c,d,f,g,h,e) VALUES(?,?,?,?,?,?,?,?) (bind/step emulation)
		TAIL = tclSqlTail("INSERT INTO t4(a,b,c,d,f,g,h,e) VALUES(?,?,?,?,?,?,?,?)")
		_ = TAIL // suppress unused warning
		_ = VM // prepared statement handle
		_r = tclBindStmt(db, "VM", 1, "int", "1", -1)
		_r = tclBindStmt(db, "VM", 2, "int", "2", -1)
		_r = tclBindStmt(db, "VM", 3, "int", "3", -1)
		_r = tclBindStmt(db, "VM", 4, "int", "4", -1)
		_r = tclBindStmt(db, "VM", 5, "int", "5", -1)
		_r = tclBindStmt(db, "VM", 6, "int", "6", -1)
		_r = tclBindStmt(db, "VM", 7, "int", "7", -1)
		_r = tclBindStmt(db, "VM", 8, "int", "8", -1)
		_r = tclStepStmt(db, "VM")
		_r = tclFinalizeStmt(db, "VM")
		_res = db.Exec("SELECT * FROM t4")
	}
	{ // do_test "bind-15.2"
		_res = db.Exec("DELETE FROM t4")
		_r = tclPrepareStmt(db, "VM", "INSERT INTO t4(a,b,c,d,e,f,g,h) VALUES(?,?,?,?,?,?,?,?)", -1)
		// prepared VM: INSERT INTO t4(a,b,c,d,e,f,g,h) VALUES(?,?,?,?,?,?,?,?) (bind/step emulation)
		TAIL = tclSqlTail("INSERT INTO t4(a,b,c,d,e,f,g,h) VALUES(?,?,?,?,?,?,?,?)")
		_ = TAIL // suppress unused warning
		_ = VM // prepared statement handle
		_r = tclBindStmt(db, "VM", 1, "int", "1", -1)
		_r = tclBindStmt(db, "VM", 2, "int", "2", -1)
		_r = tclBindStmt(db, "VM", 3, "int", "3", -1)
		_r = tclBindStmt(db, "VM", 4, "int", "4", -1)
		_r = tclBindStmt(db, "VM", 5, "int", "5", -1)
		_r = tclBindStmt(db, "VM", 6, "int", "6", -1)
		_r = tclBindStmt(db, "VM", 7, "int", "7", -1)
		_r = tclBindStmt(db, "VM", 8, "int", "8", -1)
		_r = tclStepStmt(db, "VM")
		_r = tclFinalizeStmt(db, "VM")
		_res = db.Exec("SELECT * FROM t4")
	}
	{ // do_test "bind-15.3"
		_res = db.Exec("DELETE FROM t4")
		_r = tclPrepareStmt(db, "VM", "INSERT INTO t4(h,g,f,e,d,c,b,a) VALUES(?,?,?,?,?,?,?,?)", -1)
		// prepared VM: INSERT INTO t4(h,g,f,e,d,c,b,a) VALUES(?,?,?,?,?,?,?,?) (bind/step emulation)
		TAIL = tclSqlTail("INSERT INTO t4(h,g,f,e,d,c,b,a) VALUES(?,?,?,?,?,?,?,?)")
		_ = TAIL // suppress unused warning
		_ = VM // prepared statement handle
		_r = tclBindStmt(db, "VM", 1, "int", "1", -1)
		_r = tclBindStmt(db, "VM", 2, "int", "2", -1)
		_r = tclBindStmt(db, "VM", 3, "int", "3", -1)
		_r = tclBindStmt(db, "VM", 4, "int", "4", -1)
		_r = tclBindStmt(db, "VM", 5, "int", "5", -1)
		_r = tclBindStmt(db, "VM", 6, "int", "6", -1)
		_r = tclBindStmt(db, "VM", 7, "int", "7", -1)
		_r = tclBindStmt(db, "VM", 8, "int", "8", -1)
		_r = tclStepStmt(db, "VM")
		_r = tclFinalizeStmt(db, "VM")
		_res = db.Exec("SELECT * FROM t4")
	}
	{ // do_test "bind-15.4"
		_res = db.Exec("DELETE FROM t4")
		_r = tclPrepareStmt(db, "VM", "INSERT INTO t4(a,b,c,d,e,f,g,h) VALUES(?,?,?,?4,?,?6,?,?)", -1)
		// prepared VM: INSERT INTO t4(a,b,c,d,e,f,g,h) VALUES(?,?,?,?4,?,?6,?,?) (bind/step emulation)
		TAIL = tclSqlTail("INSERT INTO t4(a,b,c,d,e,f,g,h) VALUES(?,?,?,?4,?,?6,?,?)")
		_ = TAIL // suppress unused warning
		_ = VM // prepared statement handle
		_r = tclBindStmt(db, "VM", 1, "int", "1", -1)
		_r = tclBindStmt(db, "VM", 2, "int", "2", -1)
		_r = tclBindStmt(db, "VM", 3, "int", "3", -1)
		_r = tclBindStmt(db, "VM", 4, "int", "4", -1)
		_r = tclBindStmt(db, "VM", 5, "int", "5", -1)
		_r = tclBindStmt(db, "VM", 6, "int", "6", -1)
		_r = tclBindStmt(db, "VM", 7, "int", "7", -1)
		_r = tclBindStmt(db, "VM", 8, "int", "8", -1)
		_r = tclStepStmt(db, "VM")
		_r = tclFinalizeStmt(db, "VM")
		_res = db.Exec("SELECT * FROM t4")
	}
}
