// Code generated by tcl2go; DO NOT EDIT.
package sharedB

import (
"github.com/pijalu/frigolite"
"strconv"
"testing"
)

func Test_sharedB(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	// set testdir: test directory (not used in Go test context)
	if tclBool("run_thread_tests" + "==0") {
		return
	}
	var _testprefix = "sharedB" // TCL namespace variable
	_ = _testprefix // suppress unused warning
	var _enable_shared_cache = "sqlite3_enable_shared_cache 1" // TCL namespace variable
	_ = _enable_shared_cache // suppress unused warning
	{ // do_test "1.1"
		db1, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		db2, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		db1.Exec("\n    CREATE TABLE t1(x,y TEXT COLLATE nocase);\n    WITH RECURSIVE\n      c(i) AS (VALUES(1) UNION ALL SELECT i+1 FROM c WHERE i<100)\n    INSERT INTO t1(x,y) SELECT i, printf('x%03dy',i) FROM c;\n    CREATE INDEX t1yx ON t1(y,x);\n  ")
		if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
		db2.Exec("\n    SELECT x FROM t1 WHERE y='X014Y';\n  ")
		if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
	}
	var j = "1"
	_ = j // suppress unused warning
	for func() bool { j_n, _j_e := strconv.Atoi(j); if _j_e != nil { return false }; return j_n <= 100 }() {
		{ // do_test "1.2." + j
			db2.Close()
			db2, err = frigolite.Open("test.db")
			if err != nil { t.Fatal(err) }
			db2.Exec("\n      SELECT x FROM t1 WHERE y='X014Y';\n    ")
			if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
		}
		// incr j 1
		{
			_n, _err := strconv.Atoi(j)
			if _err == nil {
				j = strconv.Itoa(_n + 1)
			}
		}
	}
	db1.Close()
	db2.Close()
	t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_enable_shared_cache $::enable_shared_cache")
}
