// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package func6

import (
"github.com/pijalu/frigolite"
"os"
"strings"
"testing"
)

func Test_func6(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	var _r string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	_ = _r   // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var bNullTrim string
	_ = bNullTrim // pre-declared from TCL source
	var fd string
	_ = fd // pre-declared from TCL source
	var data string
	_ = data // pre-declared from TCL source
	var hdr string
	_ = hdr // pre-declared from TCL source
	var body string
	_ = body // pre-declared from TCL source
	var args string
	_ = args // pre-declared from TCL source
	var x string
	_ = x // pre-declared from TCL source
	var n string
	_ = n // pre-declared from TCL source
	var res string
	_ = res // pre-declared from TCL source
	var off string
	_ = off // pre-declared from TCL source
	var offset string
	_ = offset // pre-declared from TCL source
	var rec string
	_ = rec // pre-declared from TCL source
	var F string
	_ = F // pre-declared from TCL source
	var z100 string
	_ = z100 // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source
	var file string
	_ = file // pre-declared from TCL source
	var hexdb string
	_ = hexdb // pre-declared from TCL source
	var hexrec string
	_ = hexrec // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	bNullTrim = "0"
	_ = bNullTrim // suppress unused warning
	bNullTrim = "1"
	_ = bNullTrim // suppress unused warning
	{ // "func6-100"
		r = db.Query("\n  PRAGMA page_size=4096;\n  PRAGMA auto_vacuum=NONE;\n  CREATE TABLE t1(a,b,c,d);\n  WITH RECURSIVE c(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM c WHERE x<100)\n   INSERT INTO t1(a,b,c,d) SELECT printf('abc%03x',x), x, 1000-x, NULL FROM c;\n  CREATE INDEX t1a ON t1(a);\n  CREATE INDEX t1bc ON t1(b,c);\n  CREATE TABLE t2(x TEXT PRIMARY KEY, y) WITHOUT ROWID;\n  INSERT INTO t2(x,y) SELECT a, b FROM t1;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  PRAGMA page_size=4096;\n  PRAGMA auto_vacuum=NONE;\n  CREATE TABLE t1(a,b,c,d);\n  WITH RECURSIVE c(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM c WHERE x<100)\n   INSERT INTO t1(a,b,c,d) SELECT printf('abc%03x',x), x, 1000-x, NULL FROM c;\n  CREATE INDEX t1a ON t1(a);\n  CREATE INDEX t1bc ON t1(b,c);\n  CREATE TABLE t2(x TEXT PRIMARY KEY, y) WITHOUT ROWID;\n  INSERT INTO t2(x,y) SELECT a, b FROM t1;\n")
		}
	}
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	F = "loadhex test.db"
	_ = F // suppress unused warning
	// db function offrec (variable-reader, inlined)
	if tclBool(bNullTrim) {
		offset = "8180"
		_ = offset // suppress unused warning
	} else {
		offset = "8179"
		_ = offset // suppress unused warning
	}
	{ // "func6-105" — skipped: sqlite_offset file-layout offsets (implementation-specific)
	}
	{ // "func6-106" — skipped: sqlite_offset file-layout offsets (implementation-specific)
	}
	z100 = strings.TrimSpace(tclStringRepeat("0 ", "100"))
	_ = z100 // suppress unused warning
	{ // "func6-110" — skipped: sqlite_offset file-layout offsets (implementation-specific)
	}
	{ // "func6-120" — skipped: sqlite_offset file-layout offsets (implementation-specific)
	}
	{ // "func6-130" — skipped: sqlite_offset file-layout offsets (implementation-specific)
	}
	{ // "func6-140" — skipped: sqlite_offset file-layout offsets (implementation-specific)
	}
	{ // "func6-150" — skipped: sqlite_offset file-layout offsets (implementation-specific)
	}
	{ // "func6-160" — skipped: sqlite_offset file-layout offsets (implementation-specific)
	}
	{ // "func6-200" — skipped: sqlite_offset file-layout offsets (implementation-specific)
	}
	db.Close()
	os.Remove("test.db")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	tcl_nullvalue = "{}" // fresh connection resets nullvalue
	{ // "func6-300" — skipped: sqlite_offset file-layout offsets (implementation-specific)
	}
}
