// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package fts5secure2

import (
"github.com/pijalu/frigolite"
"github.com/pijalu/frigolite/internal/vtab"
"os"
"testing"
)

func Test_fts5secure2(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	var _r string
	var _berr error
	_ = _berr // suppress unused warning
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	_ = _r   // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testprefix string
	_ = testprefix // pre-declared from TCL source

	vtab.TclVarSet("testprefix", "", "fts5secure2")
	testprefix = "fts5secure2" // TCL namespace variable
	_ = testprefix // suppress unused warning
	{ // "1.0"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE ft USING fts5(col);\n  INSERT INTO ft VALUES('data for the table');\n  INSERT INTO ft VALUES('more of the same');\n  INSERT INTO ft VALUES('and extra data');\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft USING fts5(col);\n  INSERT INTO ft VALUES('data for the table');\n  INSERT INTO ft VALUES('more of the same');\n  INSERT INTO ft VALUES('and extra data');\n")
		}
	}
	{ // "1.1"
		r = db.Query("\n  SELECT * FROM ft_config\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT * FROM ft_config\n")
			return
		}
		got := flatten(r)
		want := "version 4"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "1.2"
		r = db.Query("\n  INSERT INTO ft(ft, rank) VALUES('secure-delete', 1);\n  SELECT * FROM ft_config;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  INSERT INTO ft(ft, rank) VALUES('secure-delete', 1);\n  SELECT * FROM ft_config;\n")
			return
		}
		got := flatten(r)
		want := "secure-delete 1 version 4"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "1.3"
		r = db.Query("\n  INSERT INTO ft(ft, rank) VALUES('secure-delete', 1);\n  SELECT * FROM ft_config;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  INSERT INTO ft(ft, rank) VALUES('secure-delete', 1);\n  SELECT * FROM ft_config;\n")
			return
		}
		got := flatten(r)
		want := "secure-delete 1 version 4"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "1.4"
		r = db.Query("\n  DELETE FROM ft WHERE rowid=2;\n  SELECT * FROM ft_config;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  DELETE FROM ft WHERE rowid=2;\n  SELECT * FROM ft_config;\n")
			return
		}
		got := flatten(r)
		want := "secure-delete 1 version 5"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "1.5"
		r = db.Query("\n  SELECT rowid, col FROM ft('data');\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT rowid, col FROM ft('data');\n")
			return
		}
		got := flatten(r)
		want := "1 data for the table 3 and extra data"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	db.Close()
	db, err = frigolite.Open("test.db")
	tclConnRegister("db", db)
	if err != nil { t.Fatal(err) }
	{ // "1.6"
		r = db.Query("\n  SELECT rowid, col FROM ft('data');\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT rowid, col FROM ft('data');\n")
			return
		}
		got := flatten(r)
		want := "1 data for the table 3 and extra data"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	db.Close()
	os.Remove("test.db")
	os.Remove("test.db-journal")
	os.Remove("test.db-wal")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	tcl_nullvalue = "{}" // fresh connection resets nullvalue
	{ // "2.0"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE ft USING fts5(col);\n  INSERT INTO ft VALUES('one zero one one zero');\n  INSERT INTO ft(ft, rank) VALUES('secure-delete', 1);\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft USING fts5(col);\n  INSERT INTO ft VALUES('one zero one one zero');\n  INSERT INTO ft(ft, rank) VALUES('secure-delete', 1);\n")
		}
	}
	{ // "2.1"
		r = db.Query("\n  SELECT count(*) FROM ft_data WHERE block=X'00000004';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT count(*) FROM ft_data WHERE block=X'00000004';\n")
			return
		}
		got := flatten(r)
		want := "0"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "2.2"
		_res = db.Exec("\n  UPDATE ft SET col = 'zero one zero zero one' WHERE rowid=1;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  UPDATE ft SET col = 'zero one zero zero one' WHERE rowid=1;\n")
		}
	}
	{ // "2.3"
		r = db.Query("\n  SELECT count(*) FROM ft_data WHERE block=X'00000004';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT count(*) FROM ft_data WHERE block=X'00000004';\n")
			return
		}
		got := flatten(r)
		want := "1"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "2.4"
		_res = db.Exec("\n  INSERT INTO ft VALUES('one zero zero one');\n  DELETE FROM ft WHERE rowid=1;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  INSERT INTO ft VALUES('one zero zero one');\n  DELETE FROM ft WHERE rowid=1;\n")
		}
	}
	{ // "2.5"
		r = db.Query("\n  SELECT count(*) FROM ft_data WHERE block=X'00000004';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT count(*) FROM ft_data WHERE block=X'00000004';\n")
			return
		}
		got := flatten(r)
		want := "2"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
}
