// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package trans2

import (
"github.com/pijalu/frigolite"
"github.com/pijalu/frigolite/internal/vtab"
"os"
"strconv"
"strings"
"testing"
)

func Test_trans2(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	var _r string
	var _berr error
	_ = _berr // suppress unused warning
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	_ = _r   // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var y string
	_ = y // pre-declared from TCL source
	var x string
	_ = x // pre-declared from TCL source
	var outlist string
	_ = outlist // pre-declared from TCL source
	var u string
	_ = u // pre-declared from TCL source
	var i string
	_ = i // pre-declared from TCL source
	var rec string
	_ = rec // pre-declared from TCL source
	var data string
	_ = data // pre-declared from TCL source
	var max_rowid string
	_ = max_rowid // pre-declared from TCL source
	var id string
	_ = id // pre-declared from TCL source
	var u1 string
	_ = u1 // pre-declared from TCL source
	var z string
	_ = z // pre-declared from TCL source
	var u2 string
	_ = u2 // pre-declared from TCL source
	var todel string
	_ = todel // pre-declared from TCL source
	var n string
	_ = n // pre-declared from TCL source
	var max1 string
	_ = max1 // pre-declared from TCL source
	var origres string
	_ = origres // pre-declared from TCL source
	var newdata string
	_ = newdata // pre-declared from TCL source
	var j string
	_ = j // pre-declared from TCL source
	var modsql string
	_ = modsql // pre-declared from TCL source
	var inssql string
	_ = inssql // pre-declared from TCL source
	var newres string
	_ = newres // pre-declared from TCL source
	var s string
	_ = s // pre-declared from TCL source
	var Id_ string
	_ = Id_ // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source
	var inlist string
	_ = inlist // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	registerTclUserProc("scramble", func(a []string) string { if len(a) == 0 { return "" }; return tclUserScramble(a[0]) })
	// proc definition (not transpiled)
	// expr srand(1) (not evaluated)
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	vtab.TclVarSet("data", "", "")
	data = ""
	_ = data // suppress unused warning
	vtab.TclVarSet("i", "", "0")
	i = "0"
	_ = i // suppress unused warning
	for func() bool { i_n, _i_e := strconv.Atoi(i); if _i_e != nil { return false }; return i_n < 400 }() {
		rec = i + " " + tclRandomUUID() + " " + "1000" + " " + tclRandomUUID()
		_ = rec // suppress unused warning
		data = tclListAppend(data, rec)
		// incr i 1
		{
			_n, _err := strconv.Atoi(i)
			if _err == nil {
				i = strconv.Itoa(_n + 1)
			}
		}
	}
	max_rowid = tclExprWith("$i-1", map[string]string{"i": i})
	_ = max_rowid // suppress unused warning
	{ // do_test "trans2-1.1"
		r = db.Query("\n    PRAGMA cache_size=100;\n    CREATE TABLE t1(\n      id INTEGER PRIMARY KEY,\n      u1 TEXT UNIQUE,\n      z BLOB NOT NULL,\n      u2 TEXT UNIQUE\n    );\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    PRAGMA cache_size=100;\n    CREATE TABLE t1(\n      id INTEGER PRIMARY KEY,\n      u1 TEXT UNIQUE,\n      z BLOB NOT NULL,\n      u2 TEXT UNIQUE\n    );\n  ")
		}
		for _, rec := range tclSplitList(tclScramble(data)) {
		_ = rec // suppress unused warning
			_items0 := tclSplitList(rec)
			if len(_items0) >= 4 {
				id = _items0[0]
				_ = id // suppress unused warning
				u1 = _items0[1]
				_ = u1 // suppress unused warning
				z = _items0[2]
				_ = z // suppress unused warning
				u2 = _items0[3]
				_ = u2 // suppress unused warning
			}
			_res = db.Exec("INSERT INTO t1 VALUES(" + sqlLiteral(id) + "," + sqlLiteral(u1) + ",zeroblob(" + sqlLiteral(z) + ")," + sqlLiteral(u2) + ")")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "INSERT INTO t1 VALUES(" + sqlLiteral(id) + "," + sqlLiteral(u1) + ",zeroblob(" + sqlLiteral(z) + ")," + sqlLiteral(u2) + ")")
			}
		}
		_res = db.Exec("SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
		}
	}
	vtab.TclVarSet("i", "", "2")
	i = "2"
	_ = i // suppress unused warning
	for func() bool { i_n, _i_e := strconv.Atoi(i); if _i_e != nil { return false }; return i_n <= 30 }() {
		vtab.TclVarSet("todel", "", "")
		todel = ""
		_ = todel // suppress unused warning
		n = strconv.Itoa((tclLLength(data))/10)
		_ = n // suppress unused warning
		data = callTclUserProc("scramble", data)
		_ = data // suppress unused warning
		for _, rec := range tclSplitList(tclLRange(data, "0", n)) {
		_ = rec // suppress unused warning
			todel = tclListAppend(todel, tclLIndex(rec, "0"))
		}
		data = tclLRange(data, tclExprWith("$n+1", map[string]string{"n": n}), "end")
		_ = data // suppress unused warning
		max1 = tclLIndex(tclLIndex(data, "0"), "0")
		_ = max1 // suppress unused warning
		for _, rec := range tclSplitList(data) {
		_ = rec // suppress unused warning
			id = tclLIndex(rec, "0")
			_ = id // suppress unused warning
			if func() bool { id_n, _id_e := strconv.Atoi(id); if _id_e != nil { return false }; max1_n, _max1_e := strconv.Atoi(max1); if _max1_e != nil { return false }; return id_n > max1_n }() {
				vtab.TclVarSet("max1", "", id)
				max1 = id
				_ = max1 // suppress unused warning
			}
		}
		origres = tclHashByIndex(data, 1) + " " + tclHashByIndex(data, 3)
		_ = origres // suppress unused warning
		{ // do_test "trans2-" + i + ".1"
			_res = db.Exec("DELETE FROM t1 WHERE id IN (" + strings.Join(tclSplitList(todel), ",") + ")")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "DELETE FROM t1 WHERE id IN (" + strings.Join(tclSplitList(todel), ",") + ")")
			}
			_res = db.Exec("SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			}
			r = db.Query("SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			}
			if flatten(r) != origres {
				t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", flatten(r), origres, "trans2-" + i + ".1")
			}
		}
		_res = db.Exec("PRAGMA integrity_check")
		if _res.Error != nil { t.Errorf("integrity check: %v", _res.Error) }
		vtab.TclVarSet("newdata", "", "")
		newdata = ""
		_ = newdata // suppress unused warning
		for _, id := range tclSplitList(todel) {
		_ = id // suppress unused warning
			rec = id + " " + tclRandomUUID() + "                        " + "1000" + " " + tclRandomUUID()
			_ = rec // suppress unused warning
			newdata = tclListAppend(newdata, rec)
			data = tclListAppend(data, rec)
		}
		vtab.TclVarSet("j", "", "1")
		j = "1"
		_ = j // suppress unused warning
		for func() bool { j_n, _j_e := strconv.Atoi(j); if _j_e != nil { return false }; return j_n < 50 }() {
			id = tclExprWith("$max_rowid+$j", map[string]string{"max_rowid": max_rowid, "j": j})
			_ = id // suppress unused warning
			todel = tclListAppend(todel, id)
			rec = id + " " + tclRandomUUID() + "                        " + "1000" + " " + tclRandomUUID()
			_ = rec // suppress unused warning
			newdata = tclListAppend(newdata, rec)
			data = tclListAppend(data, rec)
			// incr j 1
			{
				_n, _err := strconv.Atoi(j)
				if _err == nil {
					j = strconv.Itoa(_n + 1)
				}
			}
		}
		max_rowid = tclExprWith("$max_rowid+$j-1", map[string]string{"max_rowid": max_rowid, "j": j})
		_ = max_rowid // suppress unused warning
		vtab.TclVarSet("modsql", "", "")
		modsql = ""
		_ = modsql // suppress unused warning
		vtab.TclVarSet("inssql", "", "")
		inssql = ""
		_ = inssql // suppress unused warning
		newres = tclHashByIndex(data, 1) + " " + tclHashByIndex(data, 3)
		_ = newres // suppress unused warning
		{ // do_test "trans2-" + i + ".3"
			_res = db.Exec("BEGIN")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "BEGIN")
			}
			for _, rec := range tclSplitList(tclScramble(newdata)) {
			_ = rec // suppress unused warning
				_items1 := tclSplitList(rec)
				if len(_items1) >= 4 {
					id = _items1[0]
					_ = id // suppress unused warning
					u1 = _items1[1]
					_ = u1 // suppress unused warning
					z = _items1[2]
					_ = z // suppress unused warning
					u2 = _items1[3]
					_ = u2 // suppress unused warning
				}
				vtab.TclVarSet("s", "", "INSERT INTO t1 VALUES(" + id + ",'" + u1 + "',zeroblob(" + z + "),'" + u2 + "');")
				s = "INSERT INTO t1 VALUES(" + id + ",'" + u1 + "',zeroblob(" + z + "),'" + u2 + "');"
				_ = s // suppress unused warning
				modsql += s_n
				inssql += s_n
				_res = db.Exec(s)
				if _res.Error != nil {
					t.Errorf("exec error: %v\n  sql: %s", _res.Error, s)
				}
			}
			_res = db.Exec("SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			}
			r = db.Query("SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			}
			if flatten(r) != newres {
				t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", flatten(r), newres, "trans2-" + i + ".3")
			}
		}
		_res = db.Exec("PRAGMA integrity_check")
		if _res.Error != nil { t.Errorf("integrity check: %v", _res.Error) }
		{ // do_test "trans2-" + i + ".10"
			_res = db.Exec("\n      UPDATE t1 SET u1=u1||'x',\n          z = CASE WHEN id<" + sqlLiteral(max_rowid) + "\n                   THEN zeroblob((random()&65535)%5000 + 1000) END;\n    ")
			if _res.Error == nil || !strings.Contains(_res.Error.Error(), "NOT NULL constraint failed: t1.z") {
				t.Errorf("expected error containing %q, got: %v\n  sql: %s", "NOT NULL constraint failed: t1.z", _res.Error, "\n      UPDATE t1 SET u1=u1||'x',\n          z = CASE WHEN id<" + sqlLiteral(max_rowid) + "\n                   THEN zeroblob((random()&65535)%5000 + 1000) END;\n    ")
			}
		}
		{ // do_test "trans2-" + i + ".11"
			r = db.Query("SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
				return
			}
			got := flatten(r)
			want := tclListFlattenCollapse(newres)
			got = tclListFlattenCollapse(got)
			if got != want {
				t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
			}
		}
		{ // do_test "trans2-" + i + ".20"
			vtab.TclVarSet("s", "", "DELETE FROM t1 WHERE id IN (" + strings.Join(tclSplitList(todel), ",") + ");")
			s = "DELETE FROM t1 WHERE id IN (" + strings.Join(tclSplitList(todel), ",") + ");"
			_ = s // suppress unused warning
			modsql += s_n
			_res = db.Exec(s)
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, s)
			}
			_res = db.Exec("SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			}
			r = db.Query("SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			}
			if flatten(r) != origres {
				t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", flatten(r), origres, "trans2-" + i + ".20")
			}
		}
		{ // do_test "trans2-" + i + ".30"
			_res = db.Exec("\n      UPDATE t1 SET u1=u1||'x',\n          z = CASE WHEN id<" + sqlLiteral(max1) + "\n                   THEN zeroblob((random()&65535)%5000 + 1000) END;\n    ")
			if _res.Error == nil || !strings.Contains(_res.Error.Error(), "NOT NULL constraint failed: t1.z") {
				t.Errorf("expected error containing %q, got: %v\n  sql: %s", "NOT NULL constraint failed: t1.z", _res.Error, "\n      UPDATE t1 SET u1=u1||'x',\n          z = CASE WHEN id<" + sqlLiteral(max1) + "\n                   THEN zeroblob((random()&65535)%5000 + 1000) END;\n    ")
			}
		}
		{ // do_test "trans2-" + i + ".31"
			r = db.Query("SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
				return
			}
			got := flatten(r)
			want := tclListFlattenCollapse(origres)
			got = tclListFlattenCollapse(got)
			if got != want {
				t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
			}
		}
		{ // do_test "trans2-" + i + ".40"
			_res = db.Exec(inssql)
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, inssql)
			}
			modsql += inssql
			_res = db.Exec("SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			}
			r = db.Query("SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			}
			if flatten(r) != newres {
				t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", flatten(r), newres, "trans2-" + i + ".40")
			}
		}
		{ // do_test "trans2-" + i + ".90"
			_res = db.Exec("ROLLBACK")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "ROLLBACK")
			}
			_res = db.Exec("SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			}
			r = db.Query("SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			}
			if flatten(r) != origres {
				t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", flatten(r), origres, "trans2-" + i + ".90")
			}
		}
		_res = db.Exec("PRAGMA integrity_check")
		if _res.Error != nil { t.Errorf("integrity check: %v", _res.Error) }
		{ // do_test "trans2-" + i + ".92"
			_res = db.Exec("BEGIN")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "BEGIN")
			}
			_res = db.Exec("\n      UPDATE t1 SET u1=u1||'x',\n          z = CASE WHEN id<" + sqlLiteral(max1) + "\n                   THEN zeroblob((random()&65535)%5000 + 1000) END;\n    ")
			_ = _res // catchsql
			_res = db.Exec(modsql)
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, modsql)
			}
			_res = db.Exec("\n      UPDATE t1 SET u1=u1||'x',\n          z = CASE WHEN id<" + sqlLiteral(max1) + "\n                   THEN zeroblob((random()&65535)%5000 + 1000) END;\n    ")
			_ = _res // catchsql
			_res = db.Exec("COMMIT")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "COMMIT")
			}
			_res = db.Exec("SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			}
			r = db.Query("SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT md5sum(u1), md5sum(u2) FROM t1 ORDER BY id")
			}
			if flatten(r) != newres {
				t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", flatten(r), newres, "trans2-" + i + ".92")
			}
		}
		_res = db.Exec("PRAGMA integrity_check")
		if _res.Error != nil { t.Errorf("integrity check: %v", _res.Error) }
		// incr i 1
		{
			_n, _err := strconv.Atoi(i)
			if _err == nil {
				i = strconv.Itoa(_n + 1)
			}
		}
	}
}
