// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package walpersist

import (
"github.com/pijalu/frigolite"
"github.com/pijalu/frigolite/internal/vtab"
"os"
"strconv"
"testing"
)

func Test_walpersist(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	var _r string
	var _berr error
	_ = _berr // suppress unused warning
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	_ = _r   // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var testprefix string
	_ = testprefix // pre-declared from TCL source
	var i string
	_ = i // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	vtab.TclVarSet("testprefix", "", "walpersist")
	testprefix = "walpersist" // TCL namespace variable
	_ = testprefix // suppress unused warning
	{ // do_test "walpersist-1.0"
		_res = db.Exec("\n    PRAGMA journal_mode=WAL;\n    CREATE TABLE t1(a);\n    INSERT INTO t1 VALUES(randomblob(5000));\n  ")
		// file exists "test.db-wal"
	}
	{ // do_test "walpersist-1.1"
		// file exists "test.db-shm"
	}
	{ // do_test "walpersist-1.2"
		db.Close()
		_list := tclList([]string{"file exists test.db", "file exists test.db-wal", "file exists test.db-shm"})
		_ = _list
		_r = _list
	}
	{ // do_test "walpersist-1.3"
		db, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		_res = db.Exec("SELECT length(a) FROM t1")
	}
	{ // do_test "walpersist-1.4"
		_list := tclList([]string{"file exists test.db", "file exists test.db-wal", "file exists test.db-shm"})
		_ = _list
		_r = _list
	}
	{ // do_test "walpersist-1.5"
		// file_control_persist_wal db -1 (unsupported command, not transpiled)
	}
	{ // do_test "walpersist-1.6"
		// file_control_persist_wal db 1 (unsupported command, not transpiled)
	}
	{ // do_test "walpersist-1.7"
		// file_control_persist_wal db -1 (unsupported command, not transpiled)
	}
	{ // do_test "walpersist-1.8"
		// file_control_persist_wal db 0 (unsupported command, not transpiled)
	}
	{ // do_test "walpersist-1.9"
		// file_control_persist_wal db -1 (unsupported command, not transpiled)
	}
	{ // do_test "walpersist-1.10"
		// file_control_persist_wal db 1 (unsupported command, not transpiled)
	}
	{ // do_test "walpersist-1.11"
		db.Close()
		_list := tclList([]string{"file exists test.db", "file exists test.db-wal", "file exists test.db-shm"})
		_ = _list
		_r = _list
	}
	os.Remove("test.db")
	{ // do_test "walpersist-2.1"
		db, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		_res = db.Exec("\n    PRAGMA journal_mode=WAL;\n    PRAGMA wal_autocheckpoint=OFF;\n    PRAGMA journal_size_limit=12000;\n    CREATE TABLE t1(x);\n    INSERT INTO t1 VALUES(randomblob(50000));\n    UPDATE t1 SET x=randomblob(50000);\n  ")
		// expr [file size test.db-wal]>100000 → runtime compare
		_r = tclBool01(toInt(strconv.Itoa(tclFileSize("test.db-wal")))  >  100000)
	}
	{ // "walpersist-2.2" (prepare-step internals; SQL side effects only)
		// file_control_persist_wal db 1 (unsupported command, not transpiled)
		db.Close()
		_r_tcl := append([]string{}, tclSplitList("file exists test.db-wal")...)
		_r_tcl = append(_r_tcl, tclSplitList(strconv.Itoa(tclFileSize("test.db-wal")))...)
		_r_tcl_str := tclList(_r_tcl)
		_ = _r_tcl_str
		_ = _r_tcl
	}
	{ // do_test "walpersist-2.3"
		db, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		r = db.Query(" PRAGMA integrity_check ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " PRAGMA integrity_check ")
		}
	}
	{ // do_test "3.1"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
			db.Close()
		}
		os.Remove("test.db")
		db, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		r = db.Query("\n    PRAGMA page_size = 1024;\n    PRAGMA journal_mode = WAL;\n    PRAGMA wal_autocheckpoint=128;\n    PRAGMA journal_size_limit=16384;\n    CREATE TABLE t1(a, b, PRIMARY KEY(a, b));\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    PRAGMA page_size = 1024;\n    PRAGMA journal_mode = WAL;\n    PRAGMA wal_autocheckpoint=128;\n    PRAGMA journal_size_limit=16384;\n    CREATE TABLE t1(a, b, PRIMARY KEY(a, b));\n  ")
		}
	}
	{ // do_test "3.2"
		vtab.TclVarSet("i", "", "0")
		i = "0"
		_ = i // suppress unused warning
		for func() bool { i_n, _i_e := strconv.Atoi(i); if _i_e != nil { return false }; return i_n < 200 }() {
			_res = db.Exec(" INSERT INTO t1 VALUES(randomblob(500), randomblob(500)) ")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, " INSERT INTO t1 VALUES(randomblob(500), randomblob(500)) ")
			}
			// incr i 1
			{
				_n, _err := strconv.Atoi(i)
				if _err == nil {
					i = strconv.Itoa(_n + 1)
				}
			}
		}
		// file_control_persist_wal db 1 (unsupported command, not transpiled)
		db.Close()
	}
	{ // do_test "walpersist-3.3" (file size test.db-wal)
		got := strconv.Itoa(tclFileSize("test.db-wal"))
		if got != "0" {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", got, "0", "walpersist-3.3")
		}
	}
	{ // do_test "walpersist-3.4"
		db, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		r = db.Query(" PRAGMA integrity_check ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " PRAGMA integrity_check ")
		}
	}
	db.Close()
	os.Remove("test.db")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	tcl_nullvalue = "{}" // fresh connection resets nullvalue
	{ // do_test "4.1"
		_res = db.Exec("\n    PRAGMA journal_mode=WAL;\n    CREATE TABLE t1(x);\n  ")
		// file_control_persist_wal db 1 (unsupported command, not transpiled)
		_res = db.Exec("\n    PRAGMA journal_mode=TRUNCATE;\n    PRAGMA journal_mode=MEMORY;\n    PRAGMA journal_mode=WAL;\n    PRAGMA journal_mode=PERSIST;\n  ")
	}
}
