// Code generated by tcl2go; DO NOT EDIT.
package tkt_f3e5abed

import (
"github.com/pijalu/frigolite"
"os"
"testing"
)

func Test_tkt_f3e5abed55(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var f string
	_ = f // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source
	var file string
	_ = file // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	for _, f := range tclSplitList("glob -nocomplain test.db*mj*") {
	_ = f // suppress unused warning
		os.Remove(f)
	}
	os.Remove("test.db2")
	{ // do_test "tkt-f3e5abed55-1.1"
		_res = db.Exec("\n    ATTACH 'test.db2' AS aux;\n    CREATE TABLE main.t1(a, b);\n    CREATE TABLE aux.t2(c, d);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    ATTACH 'test.db2' AS aux;\n    CREATE TABLE main.t1(a, b);\n    CREATE TABLE aux.t2(c, d);\n  ")
		}
	}
	{ // do_test "tkt-f3e5abed55-1.2"
		tclGlob("-nocomplain")
	}
	{ // do_test "tkt-f3e5abed55-1.3"
		db2, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		r = db.Query(" BEGIN; SELECT * FROM t1 ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " BEGIN; SELECT * FROM t1 ")
		}
	}
	{ // do_test "tkt-f3e5abed55-1.4"
		_res = db.Exec("\n    BEGIN;\n      INSERT INTO t1 VALUES(1, 2);\n      INSERT INTO t2 VALUES(1, 2);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    BEGIN;\n      INSERT INTO t1 VALUES(1, 2);\n      INSERT INTO t2 VALUES(1, 2);\n  ")
		}
		_res = db.Exec("COMMIT")
		_ = _res // catchsql
	}
	{ // do_test "tkt-f3e5abed55-1.5"
		_res = db.Exec("COMMIT")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "COMMIT")
		}
		_res = db.Exec("COMMIT")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "COMMIT")
		}
	}
	{ // do_test "tkt-f3e5abed55-1.6"
		tclGlob("-nocomplain")
	}
	for _, f := range tclSplitList("glob -nocomplain test.db*mj*") {
	_ = f // suppress unused warning
		os.Remove(f)
	}
	db2.Close()
	if tclBool("permutation" + "!=\"inmemory_journal\"") {
		// testvfs tvfs -default 1 (unsupported command, not transpiled)
		// tvfs script xDelete (unsupported command, not transpiled)
		// tvfs filter xDelete (unsupported command, not transpiled)
		// proc definition (not transpiled)
		_dbtmp0, err := frigolite.Open("test.db")
		_ = _dbtmp0 // sqlite3 db connection
		if err != nil { t.Fatal(err) }
		db2, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		{ // do_test "tkt-f3e5abed55-2.1"
			_res = db.Exec("\n      ATTACH 'test.db2' AS aux;\n      BEGIN;\n        INSERT INTO t1 VALUES(3, 4);\n        INSERT INTO t2 VALUES(3, 4);\n    ")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      ATTACH 'test.db2' AS aux;\n      BEGIN;\n        INSERT INTO t1 VALUES(3, 4);\n        INSERT INTO t2 VALUES(3, 4);\n    ")
			}
		}
		{ // do_test "tkt-f3e5abed55-2.2"
			r = db.Query(" BEGIN; SELECT * FROM t1 ")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, " BEGIN; SELECT * FROM t1 ")
			}
		}
		{ // do_test "tkt-f3e5abed55-2.3"
			_res = db.Exec("COMMIT")
			_ = _res // catchsql
		}
		{ // do_test "tkt-f3e5abed55-2.4"
			_res = db.Exec("COMMIT")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "COMMIT")
			}
			r = db.Query("\n      COMMIT;\n      SELECT * FROM t1;\n      SELECT * FROM t2;\n    ")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "\n      COMMIT;\n      SELECT * FROM t1;\n      SELECT * FROM t2;\n    ")
			}
		}
		{ // do_test "tkt-f3e5abed55-2.5"
			db2.Close()
			// faultsim_restore_and_reopen (unsupported command, not transpiled)
			r = db.Query("\n      ATTACH 'test.db2' AS aux;\n      SELECT * FROM t1;\n      SELECT * FROM t2;\n    ")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "\n      ATTACH 'test.db2' AS aux;\n      SELECT * FROM t1;\n      SELECT * FROM t2;\n    ")
			}
		}
	}
}
