// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package enc

import (
"github.com/pijalu/frigolite"
"os"
"strconv"
"testing"
)

func Test_enc4(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	var _r string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	_ = _r   // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var encodings string
	_ = encodings // pre-declared from TCL source
	var inits string
	_ = inits // pre-declared from TCL source
	var vals string
	_ = vals // pre-declared from TCL source
	var i string
	_ = i // pre-declared from TCL source
	var enc string
	_ = enc // pre-declared from TCL source
	var j string
	_ = j // pre-declared from TCL source
	var init string
	_ = init // pre-declared from TCL source
	var S string
	_ = S // pre-declared from TCL source
	var k string
	_ = k // pre-declared from TCL source
	var val string
	_ = val // pre-declared from TCL source
	var x string
	_ = x // pre-declared from TCL source
	var part string
	_ = part // pre-declared from TCL source
	var Id_ string
	_ = Id_ // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	db.Close()
	encodings = "UTF-8 UTF-16le UTF-16be"
	_ = encodings // suppress unused warning
	inits = "1.0 1. 1e0"
	_ = inits // suppress unused warning
	vals = "list\"922337203685477580792233720368547758079223372036854775807\"\"100000000000000000000000000000000000000000000000000000000\"\"1.0000000000000000000000000000000000000000000000000000000\""
	_ = vals // suppress unused warning
	i = "1"
	_ = i // suppress unused warning
	for _, enc := range tclSplitList(encodings) {
	_ = enc // suppress unused warning
		os.Remove("test.db")
		db, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		_res = db.Exec("PRAGMA encoding = \"" + enc + "\"")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "PRAGMA encoding = \"" + enc + "\"")
		}
		{ // do_test "enc4-" + i + ".1"
			r = db.Query("PRAGMA encoding")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "PRAGMA encoding")
				return
			}
			got := flatten(r)
			want := tclListFlatten(enc)
			if got != want {
				t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
			}
		}
		j = "1"
		_ = j // suppress unused warning
		for _, init := range tclSplitList(inits) {
		_ = init // suppress unused warning
			{ // do_test "enc4-" + i + "." + j + ".2"
				S = ""
				_ = S // suppress unused warning
				// sqlite3_expired $S (unsupported command, not transpiled)
			}
			k = "1"
			_ = k // suppress unused warning
			for _, val := range tclSplitList(vals) {
			_ = val // suppress unused warning
				x = "1"
				_ = x // suppress unused warning
				for func() bool { x_n, _x_e := strconv.Atoi(x); if _x_e != nil { return false }; return x_n < 16 }() {
					part = tclExprWith("$init + [string range $val 0 [expr $x-1]]", map[string]string{"init": init, "val": val, "x": x})
					_ = part // suppress unused warning
					// do_realnum_test enc4-$i.$j.$k.3.$x {\n          sqlite3_reset $S\n          sqlite3_bi...} [list $part] (expr test, not transpiled)
					// do_realnum_test enc4-$i.$j.$k.4.$x {\n          sqlite3_reset $S\n          sqlite3_bi...} [list $part] (expr test, not transpiled)
					// incr x 1
					{
						_n, _err := strconv.Atoi(x)
						if _err == nil {
							x = strconv.Itoa(_n + 1)
						}
					}
				}
				// incr k 1
				{
					_n, _err := strconv.Atoi(k)
					if _err == nil {
						k = strconv.Itoa(_n + 1)
					}
				}
			}
			{ // "enc4-" + i + "." + j + ".5" (uses_stmt_journal/prepare-step internals, not transpiled)
			}
			// incr j 1
			{
				_n, _err := strconv.Atoi(j)
				if _err == nil {
					j = strconv.Itoa(_n + 1)
				}
			}
		}
		db.Close()
		// incr i 1
		{
			_n, _err := strconv.Atoi(i)
			if _err == nil {
				i = strconv.Itoa(_n + 1)
			}
		}
	}
	os.Remove("test.db")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	{ // do_test "enc4-4.1"
		r = db.Query("select 1+1.")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "select 1+1.")
			return
		}
		got := flatten(r)
		want := "2.0"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "enc4-4.2.1" (uses_stmt_journal/prepare-step internals, not transpiled)
	}
	{ // "enc4-4.2.2" (uses_stmt_journal/prepare-step internals, not transpiled)
	}
	{ // "enc4-4.3.1" (uses_stmt_journal/prepare-step internals, not transpiled)
	}
	{ // "enc4-4.3.2" (uses_stmt_journal/prepare-step internals, not transpiled)
	}
	{ // "enc4-4.4.1" (uses_stmt_journal/prepare-step internals, not transpiled)
	}
	{ // "enc4-4.4.2" (uses_stmt_journal/prepare-step internals, not transpiled)
	}
	db.Close()
}
