// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package memdb1

import (
"testing"
)

func Test_memdb1(t *testing.T) {}
// skipped: deep-engine applicable gap DEFERRED (tracked for later phase)
