// Code generated by tcl2go; DO NOT EDIT.
package aggfault

import (
"github.com/pijalu/frigolite"
"testing"
)

func Test_aggfault(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	// set testdir: test directory (not used in Go test context)
	var testprefix = "aggfault"
	_ = testprefix // suppress unused warning
	{ // "1"
		_res = db.Exec("\n  CREATE TABLE t1(x);\n  CREATE INDEX t1x ON t1(x, x=0);\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE t1(x);\n  CREATE INDEX t1x ON t1(x, x=0);\n")
		}
	}
	t.Errorf("TODO: %s not implemented in frigolite", "faultsim_save_and_close")
	t.Errorf("TODO: %s not implemented in frigolite", "do_faultsim_test 2 -faults oom* -prep {\n  faultsim_restore_and_reopen\n  execsql { SELECT ...} -body {\n  execsql {\n    SELECT * FROM t1 AS a1 WHERE (\n  ...} -test {\n  faultsim_test_result {0 {}}\n}")
}
