// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package triggerC

import (
"testing"
)

func Test_triggerC(t *testing.T) {}
// skipped: recursive trigger cascade causes hang (deep-engine applicable gap DEFERRED — needs trigger recursion/perf optimization)
