// Code generated by tcl2go; DO NOT EDIT.
package main

import (
"github.com/pijalu/frigolite"
"os"
"testing"
)

func Test_main(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result

	// set testdir: test directory (not used in Go test context)
	{ // do_test "main-1.30"
	}
	{ // do_test "main-1.31"
	}
	{ // do_test "main-1.31"
	}
	{ // do_test "main-1.32"
	}
	{ // do_test "main-1.33"
	}
	{ // do_test "main-1.34"
	}
	{ // do_test "main-1.35"
	}
	{ // do_test "main-1.36"
	}
	{ // do_test "main-1.37"
	}
	{ // do_test "main-1.38"
	}
	if tclBool("permutation" + " == \"\"") {
		{ // do_test "main-2.0"
			{
				var _catchErr error
				_ = _catchErr // suppress unused warning
			}
			os.Remove("test.db")
			var fd = "open test.db w"
			_ = fd // suppress unused warning
			t.Log(fd)
			// close $fd
			var v string
			var msg string
			_ = msg // suppress unused warning
			{ // catch block
				var _catchErr error
				db, err := frigolite.Open("test.db")
				defer db.Close()
				if err != nil { t.Fatal(err) }
				if _catchErr != nil {
					v = "1"
					msg = _catchErr.Error()
				} else {
					v = "0"
					msg = ""
				}
			}
			if tclBool(v) {
				v = tclListAppend(v, msg)
			} else if tclBool("lappend v {") {
			}
		}
	}
	{ // do_test "main-3.1"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
		}
		for _, f := range []string{"glob -nocomplain testdb/*"} {
			os.Remove(f)
		}
		os.Remove("testdb")
		db, err := frigolite.Open("testdb")
		defer db.Close()
		if err != nil { t.Fatal(err) }
		var v string
		var msg string
		_ = msg // suppress unused warning
		{ // catch block
			var _catchErr error
			r = db.Query("SELECT * from T1 where x!!5")
			if r.Error != nil { _catchErr = r.Error }
			if _catchErr != nil {
				v = "1"
				msg = _catchErr.Error()
			} else {
				v = "0"
				msg = ""
			}
		}
		v = tclListAppend(v, msg)
	}
	{ // do_test "main-3.2"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
		}
		for _, f := range []string{"glob -nocomplain testdb/*"} {
			os.Remove(f)
		}
		os.Remove("testdb")
		db, err := frigolite.Open("testdb")
		defer db.Close()
		if err != nil { t.Fatal(err) }
		var v string
		var msg string
		_ = msg // suppress unused warning
		{ // catch block
			var _catchErr error
			r = db.Query("SELECT * from T1 where ^x")
			if r.Error != nil { _catchErr = r.Error }
			if _catchErr != nil {
				v = "1"
				msg = _catchErr.Error()
			} else {
				v = "0"
				msg = ""
			}
		}
		v = tclListAppend(v, msg)
	}
	{ // do_test "main-3.2.2"
		_res = db.Exec("select 'abc")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.3"
		_res = db.Exec("select \"abc")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.4"
		_res = db.Exec("select [abc")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.5"
		_res = db.Exec("select x'4869")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.6"
		_res = db.Exec("select x'4869'")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.7"
		_res = db.Exec("select x'48695'")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.8"
		_res = db.Exec("select x'486x'")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.9"
		_res = db.Exec("select $abc(")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.10"
		_res = db.Exec("select $abc(x")
		_ = _res // catchsql
	}
	var xyz = "123"
	_ = xyz // suppress unused warning
	{ // do_test "main-3.2.11"
		_res = db.Exec("select $::xyz")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.12"
		_res = db.Exec("select $testnamespace::xyz")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.13"
		_res = db.Exec("select $(abc)")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.14"
		var hi\u1234x = "987"
		_ = hi\u1234x // suppress unused warning
		_res = db.Exec("select \\$hi\\u1234x")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "select \\$hi\\u1234x")
		}
	}
	{ // do_test "main-3.2.15"
		_res = db.Exec("select 456\\u1234")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.16"
		_res = db.Exec("select cast(3.14e+4 AS integer)")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.17"
		_res = db.Exec("select cast(3.14e+04 AS integer)")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.18"
		_res = db.Exec("select cast(3.14e+004 AS integer)")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.19"
		_res = db.Exec("select cast(3.14e4 AS integer)")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.20"
		_res = db.Exec("select cast(3.14e04 AS integer)")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.21"
		_res = db.Exec("select cast(3.14e004 AS integer)")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.16"
		_res = db.Exec("select cast(3.14E+4 AS integer)")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.17"
		_res = db.Exec("select cast(3.14E+04 AS integer)")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.18"
		_res = db.Exec("select cast(3.14E+004 AS integer)")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.19"
		_res = db.Exec("select cast(3.14E4 AS integer)")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.20"
		_res = db.Exec("select cast(3.14E04 AS integer)")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.21"
		_res = db.Exec("select cast(3.14E004 AS integer)")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.22"
		_res = db.Exec("select cast(3.14e-4 * 1e8 AS integer)")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.23"
		_res = db.Exec("select cast(3.14E-04 * 1E08 AS integer)")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.24"
		_res = db.Exec("select cast(3.14e-004 * 01.0E+8 AS integer)")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.25"
		_res = db.Exec("select 123/*abc")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.26"
		_res = db.Exec("select 123/***abc")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.27"
		_res = db.Exec("select 123/*/*2")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.28"
		_res = db.Exec("select 123/**/*2")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.29"
		_res = db.Exec("select 123/")
		_ = _res // catchsql
	}
	{ // do_test "main-3.2.30"
		_res = db.Exec("select 123--5")
		_ = _res // catchsql
	}
	{ // do_test "main-3.3"
		{
			var _catchErr error
			_ = _catchErr // suppress unused warning
		}
		for _, f := range []string{"glob -nocomplain testdb/*"} {
			os.Remove(f)
		}
		os.Remove("testdb")
		db, err := frigolite.Open("testdb")
		defer db.Close()
		if err != nil { t.Fatal(err) }
		r = db.Query("\n    create table T1(X REAL);  /* C-style comments allowed */\n    insert into T1 values(0.5);\n    insert into T1 values(0.5e2);\n    insert into T1 values(0.5e-002);\n    insert into T1 values(5e-002);\n    insert into T1 values(-5.0e-2);\n    insert into T1 values(-5.1e-2);\n    insert into T1 values(0.5e2);\n    insert into T1 values(0.5E+02);\n    insert into T1 values(5E+02);\n    insert into T1 values(5.0E+03);\n    select x*10 from T1 order by x*5;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    create table T1(X REAL);  /* C-style comments allowed */\n    insert into T1 values(0.5);\n    insert into T1 values(0.5e2);\n    insert into T1 values(0.5e-002);\n    insert into T1 values(5e-002);\n    insert into T1 values(-5.0e-2);\n    insert into T1 values(-5.1e-2);\n    insert into T1 values(0.5e2);\n    insert into T1 values(0.5E+02);\n    insert into T1 values(5E+02);\n    insert into T1 values(5.0E+03);\n    select x*10 from T1 order by x*5;\n  ")
		}
	}
	{ // do_test "main-3.4"
		var v string
		var msg string
		_ = msg // suppress unused warning
		{ // catch block
			var _catchErr error
			_res = db.Exec("create bogus")
			if _res.Error != nil { _catchErr = _res.Error }
			if _catchErr != nil {
				v = "1"
				msg = _catchErr.Error()
			} else {
				v = "0"
				msg = ""
			}
		}
		v = tclListAppend(v, msg)
	}
	{ // do_test "main-3.5"
		var v string
		var msg string
		_ = msg // suppress unused warning
		{ // catch block
			var _catchErr error
			_res = db.Exec("create")
			if _res.Error != nil { _catchErr = _res.Error }
			if _catchErr != nil {
				v = "1"
				msg = _catchErr.Error()
			} else {
				v = "0"
				msg = ""
			}
		}
		v = tclListAppend(v, msg)
	}
	{ // do_test "main-3.6"
		_res = db.Exec("SELECT 'abc' + #9")
		_ = _res // catchsql
	}
	t.Log("db one {SELECT 'VERSION: ' ||\n                  sqlite_version() || ' ' ||\n                  sqlite_source_id();}")
}
