// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package rtreeC

import (
"github.com/pijalu/frigolite"
"github.com/pijalu/frigolite/internal/vtab"
"os"
"testing"
)

func Test_rtreeC(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	var _r string
	var _berr error
	_ = _berr // suppress unused warning
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	_ = _r   // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var testprefix string
	_ = testprefix // pre-declared from TCL source
	var tn string
	_ = tn // pre-declared from TCL source
	var sql string
	_ = sql // pre-declared from TCL source
	var res1 string
	_ = res1 // pre-declared from TCL source
	var res2 string
	_ = res2 // pre-declared from TCL source

	if tclBool("!" + tclBool01(vtab.TclVarExists("testdir", ""))) {
		// set testdir: test directory (not used in Go test context)
	}
	vtab.TclVarSet("testprefix", "", "rtreeC")
	testprefix = "rtreeC"
	_ = testprefix // suppress unused warning
	{ // "1.0"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE r_tree USING rtree(id, min_x, max_x, min_y, max_y);\n  CREATE TABLE t(x, y);\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE VIRTUAL TABLE r_tree USING rtree(id, min_x, max_x, min_y, max_y);\n  CREATE TABLE t(x, y);\n")
		}
	}
	{ // "1.1"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM r_tree, t \n  WHERE t.x>=min_x AND t.x<=max_x AND t.y>=min_y AND t.x<=max_y\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM r_tree, t \n  WHERE t.x>=min_x AND t.x<=max_x AND t.y>=min_y AND t.x<=max_y\n")
		}
	}
	{ // "1.2"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM t, r_tree\n  WHERE t.x>=min_x AND t.x<=max_x AND t.y>=min_y AND t.x<=max_y\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM t, r_tree\n  WHERE t.x>=min_x AND t.x<=max_x AND t.y>=min_y AND t.x<=max_y\n")
		}
	}
	{ // "1.3"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM t, r_tree\n  WHERE t.x>=min_x AND t.x<=max_x AND t.y>=min_y AND ?<=max_y\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM t, r_tree\n  WHERE t.x>=min_x AND t.x<=max_x AND t.y>=min_y AND ?<=max_y\n")
		}
	}
	{ // "1.5"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM t, r_tree\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM t, r_tree\n")
		}
	}
	{ // "2.0"
		_res = db.Exec("\n  INSERT INTO t VALUES(0, 0);\n  INSERT INTO t VALUES(0, 1);\n  INSERT INTO t VALUES(0, 2);\n  INSERT INTO t VALUES(0, 3);\n  INSERT INTO t VALUES(0, 4);\n  INSERT INTO t VALUES(0, 5);\n  INSERT INTO t VALUES(0, 6);\n  INSERT INTO t VALUES(0, 7);\n  INSERT INTO t VALUES(0, 8);\n  INSERT INTO t VALUES(0, 9);\n\n  INSERT INTO t SELECT x+1, y FROM t;\n  INSERT INTO t SELECT x+2, y FROM t;\n  INSERT INTO t SELECT x+4, y FROM t;\n  INSERT INTO r_tree SELECT NULL, x-1, x+1, y-1, y+1 FROM t;\n  ANALYZE;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  INSERT INTO t VALUES(0, 0);\n  INSERT INTO t VALUES(0, 1);\n  INSERT INTO t VALUES(0, 2);\n  INSERT INTO t VALUES(0, 3);\n  INSERT INTO t VALUES(0, 4);\n  INSERT INTO t VALUES(0, 5);\n  INSERT INTO t VALUES(0, 6);\n  INSERT INTO t VALUES(0, 7);\n  INSERT INTO t VALUES(0, 8);\n  INSERT INTO t VALUES(0, 9);\n\n  INSERT INTO t SELECT x+1, y FROM t;\n  INSERT INTO t SELECT x+2, y FROM t;\n  INSERT INTO t SELECT x+4, y FROM t;\n  INSERT INTO r_tree SELECT NULL, x-1, x+1, y-1, y+1 FROM t;\n  ANALYZE;\n")
		}
	}
	db.Close()
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	{ // "2.1"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM r_tree, t \n  WHERE t.x>=min_x AND t.x<=max_x AND t.y>=min_y AND t.x<=max_y\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM r_tree, t \n  WHERE t.x>=min_x AND t.x<=max_x AND t.y>=min_y AND t.x<=max_y\n")
		}
	}
	{ // "2.2"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM t, r_tree\n  WHERE t.x>=min_x AND t.x<=max_x AND t.y>=min_y AND t.x<=max_y\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM t, r_tree\n  WHERE t.x>=min_x AND t.x<=max_x AND t.y>=min_y AND t.x<=max_y\n")
		}
	}
	{ // "2.3"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM t, r_tree\n  WHERE t.x>=min_x AND t.x<=max_x AND t.y>=min_y AND ?<=max_y\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM t, r_tree\n  WHERE t.x>=min_x AND t.x<=max_x AND t.y>=min_y AND ?<=max_y\n")
		}
	}
	{ // "2.5"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM t, r_tree\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM t, r_tree\n")
		}
	}
	{ // "3.1"
		_res = db.Exec("\n  CREATE TABLE t1(x);\n  CREATE TABLE t2(y);\n  CREATE VIRTUAL TABLE t3 USING rtree(z, x1,x2, y1,y2);\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE t1(x);\n  CREATE TABLE t2(y);\n  CREATE VIRTUAL TABLE t3 USING rtree(z, x1,x2, y1,y2);\n")
		}
	}
	{ // "3.2.1"
		r = db.Query("EXPLAIN QUERY PLAN " + " SELECT * FROM t1 CROSS JOIN t2 ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+" SELECT * FROM t1 CROSS JOIN t2 ")
		}
	}
	{ // "3.2.2"
		r = db.Query("EXPLAIN QUERY PLAN " + " SELECT * FROM t2 CROSS JOIN t1 ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+" SELECT * FROM t2 CROSS JOIN t1 ")
		}
	}
	{ // "3.3.1"
		r = db.Query("EXPLAIN QUERY PLAN " + " SELECT * FROM t1 CROSS JOIN t3 ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+" SELECT * FROM t1 CROSS JOIN t3 ")
		}
	}
	{ // "3.3.2"
		r = db.Query("EXPLAIN QUERY PLAN " + " SELECT * FROM t3 CROSS JOIN t1 ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+" SELECT * FROM t3 CROSS JOIN t1 ")
		}
	}
	db.Close()
	os.Remove("test.db")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	tcl_nullvalue = "{}" // fresh connection resets nullvalue
	{ // "4.1"
		_res = db.Exec("\n  CREATE TABLE t1(a);\n  CREATE VIRTUAL TABLE t2 USING rtree(b, x1,x2);\n\n  INSERT INTO t1 VALUES(1);\n  INSERT INTO t1 VALUES(2);\n\n  INSERT INTO t2 VALUES(1, 0.0, 0.1);\n  INSERT INTO t2 VALUES(3, 0.0, 0.1);\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE t1(a);\n  CREATE VIRTUAL TABLE t2 USING rtree(b, x1,x2);\n\n  INSERT INTO t1 VALUES(1);\n  INSERT INTO t1 VALUES(2);\n\n  INSERT INTO t2 VALUES(1, 0.0, 0.1);\n  INSERT INTO t2 VALUES(3, 0.0, 0.1);\n")
		}
	}
	{ // "4.2"
		r = db.Query("\n  SELECT a, b FROM t1 LEFT JOIN t2 ON (+a = +b);\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT a, b FROM t1 LEFT JOIN t2 ON (+a = +b);\n")
			return
		}
		got := flatten(r)
		want := "1 1 2 {}"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "4.3"
		r = db.Query("\n  SELECT b, a FROM t2 LEFT JOIN t1 ON (+a = +b);\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT b, a FROM t2 LEFT JOIN t1 ON (+a = +b);\n")
			return
		}
		got := flatten(r)
		want := "1 1 3 {}"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	db.Close()
	os.Remove("test.db")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	tcl_nullvalue = "{}" // fresh connection resets nullvalue
	{ // "5.1"
		_res = db.Exec("\n  CREATE TABLE t1(x INT PRIMARY KEY, y);\n  CREATE VIRTUAL TABLE rt USING rtree(id, x1, x2, +d1);\n\n  INSERT INTO t1(x) VALUES(1);\n  INSERT INTO t1(x) SELECT x+1 FROM t1;   --   2\n  INSERT INTO t1(x) SELECT x+2 FROM t1;   --   4\n  INSERT INTO t1(x) SELECT x+4 FROM t1;   --   8\n  INSERT INTO t1(x) SELECT x+8 FROM t1;   --  16\n  INSERT INTO t1(x) SELECT x+16 FROM t1;  --  32\n  INSERT INTO t1(x) SELECT x+32 FROM t1;  --  64\n  INSERT INTO t1(x) SELECT x+64 FROM t1;  -- 128\n  INSERT INTO t1(x) SELECT x+128 FROM t1; -- 256\n  INSERT INTO t1(x) SELECT x+256 FROM t1; -- 512\n  INSERT INTO t1(x) SELECT x+512 FROM t1; --1024\n\n  INSERT INTO rt SELECT x, x, x+1, printf('x%04xy',x) FROM t1 WHERE x<=5;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE t1(x INT PRIMARY KEY, y);\n  CREATE VIRTUAL TABLE rt USING rtree(id, x1, x2, +d1);\n\n  INSERT INTO t1(x) VALUES(1);\n  INSERT INTO t1(x) SELECT x+1 FROM t1;   --   2\n  INSERT INTO t1(x) SELECT x+2 FROM t1;   --   4\n  INSERT INTO t1(x) SELECT x+4 FROM t1;   --   8\n  INSERT INTO t1(x) SELECT x+8 FROM t1;   --  16\n  INSERT INTO t1(x) SELECT x+16 FROM t1;  --  32\n  INSERT INTO t1(x) SELECT x+32 FROM t1;  --  64\n  INSERT INTO t1(x) SELECT x+64 FROM t1;  -- 128\n  INSERT INTO t1(x) SELECT x+128 FROM t1; -- 256\n  INSERT INTO t1(x) SELECT x+256 FROM t1; -- 512\n  INSERT INTO t1(x) SELECT x+512 FROM t1; --1024\n\n  INSERT INTO rt SELECT x, x, x+1, printf('x%04xy',x) FROM t1 WHERE x<=5;\n")
		}
	}
	// do_rtree_integrity_test 5.1.1 rt (unsupported command, not transpiled)
	{ // "5.2"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM t1, rt WHERE x==id;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM t1, rt WHERE x==id;\n")
		}
	}
	{ // "5.3"
		_res = db.Exec("\n  ANALYZE;\n  DELETE FROM sqlite_stat1 WHERE tbl='t1';\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  ANALYZE;\n  DELETE FROM sqlite_stat1 WHERE tbl='t1';\n")
		}
	}
	db.Close()
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	{ // "5.4"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM t1, rt WHERE x==id;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM t1, rt WHERE x==id;\n")
		}
	}
	{ // "5.5"
		_res = db.Exec(" DROP TABLE sqlite_stat1; ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " DROP TABLE sqlite_stat1; ")
		}
	}
	db.Close()
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	{ // "5.6"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM t1, rt WHERE x==id;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM t1, rt WHERE x==id;\n")
		}
	}
	{ // do_test "5.7"
		var _catchErr error
		_catchErr = tclDBBackupRestore(db, "backup", "main", "test.db2")
		if _catchErr != nil { _r = "" }
		db2, err = frigolite.Open("test.db2")
		if err != nil { t.Fatal(err) }
		_res = db2.Exec("\n    ANALYZE;\n    DELETE FROM sqlite_stat1 WHERE tbl='t1';\n  ")
		if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
		if db2 != nil { db2.Close() }
		db.Close()
		db, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		_res = db.Exec(" ATTACH 'test.db2' AS aux; ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " ATTACH 'test.db2' AS aux; ")
		}
	}
	{ // "5.8"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n  SELECT * FROM t1, rt WHERE x==id;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n  SELECT * FROM t1, rt WHERE x==id;\n")
		}
	}
	db.Close()
	os.Remove("test.db")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	tcl_nullvalue = "{}" // fresh connection resets nullvalue
	{ // "6.1"
		_res = db.Exec("\n    CREATE TABLE t1(x);\n    CREATE VIRTUAL TABLE rt USING rtree(id, x1, x2);\n    INSERT INTO t1 VALUES(1);\n    INSERT INTO rt VALUES(1,2,3);\n    ANALYZE;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE TABLE t1(x);\n    CREATE VIRTUAL TABLE rt USING rtree(id, x1, x2);\n    INSERT INTO t1 VALUES(1);\n    INSERT INTO rt VALUES(1,2,3);\n    ANALYZE;\n  ")
		}
	}
	db.Close()
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	{ // "6.2"
		r = db.Query(" SELECT * FROM t1 ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM t1 ")
			return
		}
		got := flatten(r)
		want := "1"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // do_test "6.3"
		db2, err = frigolite.Open("test.db")
		if err != nil { t.Fatal(err) }
		_res = db2.Exec(" DROP TABLE sqlite_stat1 ")
		if _res.Error != nil { t.Errorf("exec error: %v", _res.Error) }
		if db2 != nil { db2.Close() }
		r = db.Query(" SELECT * FROM rt ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM rt ")
		}
	}
	db.Close()
	db.Close()
	os.Remove("test.db")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	tcl_nullvalue = "{}" // fresh connection resets nullvalue
	{ // "7.0"
		_res = db.Exec("\n  CREATE TABLE xdir(x1);\n  CREATE TABLE ydir(y1);\n  CREATE VIRTUAL TABLE rt USING rtree_i32(id, xmin, xmax, ymin, ymax);\n\n  INSERT INTO xdir VALUES(5);\n  INSERT INTO ydir VALUES(10);\n\n  INSERT INTO rt VALUES(1, 2, 7, 12, 14);      -- Not a hit\n  INSERT INTO rt VALUES(2, 2, 7, 8, 12);       -- A hit!\n  INSERT INTO rt VALUES(3, 7, 11, 8, 12);      -- Not a hit!\n  INSERT INTO rt VALUES(4, 5, 5, 10, 10);      -- A hit!\n\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE xdir(x1);\n  CREATE TABLE ydir(y1);\n  CREATE VIRTUAL TABLE rt USING rtree_i32(id, xmin, xmax, ymin, ymax);\n\n  INSERT INTO xdir VALUES(5);\n  INSERT INTO ydir VALUES(10);\n\n  INSERT INTO rt VALUES(1, 2, 7, 12, 14);      -- Not a hit\n  INSERT INTO rt VALUES(2, 2, 7, 8, 12);       -- A hit!\n  INSERT INTO rt VALUES(3, 7, 11, 8, 12);      -- Not a hit!\n  INSERT INTO rt VALUES(4, 5, 5, 10, 10);      -- A hit!\n\n")
		}
	}
	// proc definition (not transpiled)
	// do_eqp_execsql_test 7.1 {\n  SELECT id FROM xdir, rt, ydir \n  ON (y1 BETWE...} {\n  QUERY PLAN\n  |... (unsupported command, not transpiled)
	// do_eqp_execsql_test 7.2 {\n  SELECT * FROM xdir, rt LEFT JOIN ydir \n  ON (...} {\n  QUERY PLAN\n  |... (unsupported command, not transpiled)
	// do_eqp_execsql_test 7.3 {\n  SELECT id FROM xdir, rt CROSS JOIN ydir \n  ON...} {\n  QUERY PLAN\n  |... (unsupported command, not transpiled)
	// do_eqp_execsql_test 7.4 {\n  SELECT id FROM rt, xdir CROSS JOIN ydir \n  ON...} {\n  QUERY PLAN\n  |... (unsupported command, not transpiled)
}
