// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package fts5tokenizer

import (
"github.com/pijalu/frigolite"
"github.com/pijalu/frigolite/internal/vtab"
"os"
"strings"
"testing"
)

func Test_fts5tokenizer(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	var _r string
	var _berr error
	_ = _berr // suppress unused warning
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	_ = _r   // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testprefix string
	_ = testprefix // pre-declared from TCL source
	var targs string
	_ = targs // pre-declared from TCL source
	var tn string
	_ = tn // pre-declared from TCL source
	var directive string
	_ = directive // pre-declared from TCL source
	var expected string
	_ = expected // pre-declared from TCL source
	var tokenizer string
	_ = tokenizer // pre-declared from TCL source
	var T string
	_ = T // pre-declared from TCL source
	var tn2 string
	_ = tn2 // pre-declared from TCL source
	var token string
	_ = token // pre-declared from TCL source
	var res string
	_ = res // pre-declared from TCL source
	var _var string
	_ = _var // pre-declared from TCL source
	var a string
	_ = a // pre-declared from TCL source
	var b string
	_ = b // pre-declared from TCL source
	var c string
	_ = c // pre-declared from TCL source
	var flags string
	_ = flags // pre-declared from TCL source
	var w string
	_ = w // pre-declared from TCL source
	var iStart string
	_ = iStart // pre-declared from TCL source
	var iEnd string
	_ = iEnd // pre-declared from TCL source
	var args string
	_ = args // pre-declared from TCL source
	var varname string
	_ = varname // pre-declared from TCL source
	var cmd string
	_ = cmd // pre-declared from TCL source
	var tflags string
	_ = tflags // pre-declared from TCL source
	var text string
	_ = text // pre-declared from TCL source

	vtab.TclVarSet("testprefix", "", "fts5tokenizer")
	testprefix = "fts5tokenizer"
	_ = testprefix // suppress unused warning
	{ // "1.0"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE ft1 USING fts5(x, tokenize=porter);\n  DROP TABLE ft1;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft1 USING fts5(x, tokenize=porter);\n  DROP TABLE ft1;\n")
		}
	}
	{ // "1.1"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE ft1 USING fts5(x, tokenize='porter');\n  DROP TABLE ft1;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft1 USING fts5(x, tokenize='porter');\n  DROP TABLE ft1;\n")
		}
	}
	{ // "1.2"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE ft1 USING fts5(x, tokenize = porter);\n  DROP TABLE ft1;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft1 USING fts5(x, tokenize = porter);\n  DROP TABLE ft1;\n")
		}
	}
	{ // "1.3"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE ft1 USING fts5(x, tokenize = 'porter');\n  DROP TABLE ft1;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft1 USING fts5(x, tokenize = 'porter');\n  DROP TABLE ft1;\n")
		}
	}
	{ // "1.4"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE ft1 USING fts5(x, tokenize = 'porter ascii');\n  DROP TABLE ft1;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft1 USING fts5(x, tokenize = 'porter ascii');\n  DROP TABLE ft1;\n")
		}
	}
	{ // "1.5"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE ft1 USING fts5(x, tokenize = 'nosuch');\n")
		if _res.Error == nil || !strings.Contains(_res.Error.Error(), "no such tokenizer: nosuch") {
			t.Errorf("expected error containing %q, got: %v\n  sql: %s", "no such tokenizer: nosuch", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft1 USING fts5(x, tokenize = 'nosuch');\n")
		}
	}
	{ // "1.6"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE ft1 USING fts5(x, tokenize = 'porter nosuch');\n")
		if _res.Error == nil || !strings.Contains(_res.Error.Error(), "error in tokenizer constructor") {
			t.Errorf("expected error containing %q, got: %v\n  sql: %s", "error in tokenizer constructor", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft1 USING fts5(x, tokenize = 'porter nosuch');\n")
		}
	}
	{ // "2.0"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE ft1 USING fts5(x, tokenize=porter);\n  INSERT INTO ft1 VALUES('embedded databases');\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft1 USING fts5(x, tokenize=porter);\n  INSERT INTO ft1 VALUES('embedded databases');\n")
		}
	}
	{ // "2.1"
		r = db.Query(" SELECT rowid FROM ft1 WHERE ft1 MATCH 'embedding' ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT rowid FROM ft1 WHERE ft1 MATCH 'embedding' ")
			return
		}
		got := flatten(r)
		want := "1"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "2.2"
		r = db.Query(" SELECT rowid FROM ft1 WHERE ft1 MATCH 'database' ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT rowid FROM ft1 WHERE ft1 MATCH 'database' ")
			return
		}
		got := flatten(r)
		want := "1"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "2.3"
		r = db.Query(" \n  SELECT rowid FROM ft1 WHERE ft1 MATCH 'database embedding' \n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " \n  SELECT rowid FROM ft1 WHERE ft1 MATCH 'database embedding' \n")
			return
		}
		got := flatten(r)
		want := "1"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	// proc definition (not transpiled)
	// sqlite3_fts5_create_tokenizer db tcl tcl_create (unsupported command, not transpiled)
	// foreach {tn directive expected} "1 {tokenize='tcl a b c'}             {a b c}\n  2 {tokenize='tcl ''d'' ''e'' ''f'''} {d e f}\n  3 {tokenize=\"tcl 'g' 'h' 'i'\"}       {g h i}\n  4 {tokenize = tcl}                   {}"
	_items0 := tclSplitList("1 {tokenize='tcl a b c'}             {a b c}\n  2 {tokenize='tcl ''d'' ''e'' ''f'''} {d e f}\n  3 {tokenize=\"tcl 'g' 'h' 'i'\"}       {g h i}\n  4 {tokenize = tcl}                   {}")
	for _idx0 := 0; _idx0+3 <= len(_items0); _idx0 += 3 {
		tn := _items0[_idx0+0]
		_ = tn // suppress unused warning
		directive := _items0[_idx0+1]
		_ = directive // suppress unused warning
		expected := _items0[_idx0+2]
		_ = expected // suppress unused warning
		_ = _idx0
			{ // "3." + tn + ".1"
				_res = db.Exec("\n    CREATE VIRTUAL TABLE ft2 USING fts5(x, " + directive + ")\n  ")
				if _res.Error == nil || !strings.Contains(_res.Error.Error(), "error in tokenizer constructor") {
					t.Errorf("expected error containing %q, got: %v\n  sql: %s", "error in tokenizer constructor", resErrString(_res), "\n    CREATE VIRTUAL TABLE ft2 USING fts5(x, " + directive + ")\n  ")
				}
			}
			{ // do_test "3." + tn + ".2"
				_ = targs // TCL namespace variable (query)
				got := tclListFlatten(targs)
				want := tclListFlatten(expected)
				if got != want {
					t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", got, want, "3." + tn + ".2")
				}
			}
		}
		{ // "4.1"
			_res = db.Exec("\n  CREATE VIRTUAL TABLE ft2 USING fts5(x, tokenize = tcl abc);\n")
			if _res.Error == nil || !strings.Contains(_res.Error.Error(), "parse error in \"tokenize = tcl abc\"") {
				t.Errorf("expected error containing %q, got: %v\n  sql: %s", "parse error in \"tokenize = tcl abc\"", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft2 USING fts5(x, tokenize = tcl abc);\n")
			}
		}
		{ // "4.2"
			_res = db.Exec("\n  CREATE VIRTUAL TABLE ft2 USING fts5(x y)\n")
			if _res.Error == nil || !strings.Contains(_res.Error.Error(), "unrecognized column option: y") {
				t.Errorf("expected error containing %q, got: %v\n  sql: %s", "unrecognized column option: y", resErrString(_res), "\n  CREATE VIRTUAL TABLE ft2 USING fts5(x y)\n")
			}
		}
		// foreach {tn tokenizer} "1 ascii 2 unicode61"
		_items1 := tclSplitList("1 ascii 2 unicode61")
		for _idx1 := 0; _idx1+2 <= len(_items1); _idx1 += 2 {
			tn := _items1[_idx1+0]
			_ = tn // suppress unused warning
			tokenizer := _items1[_idx1+1]
			_ = tokenizer // suppress unused warning
			_ = _idx1
				db.Close()
				os.Remove("test.db")
				os.Remove("test.db-journal")
				os.Remove("test.db-wal")
				db, err = frigolite.Open("test.db")
				if err != nil { t.Fatal(err) }
				tcl_nullvalue = "{}" // fresh connection resets nullvalue
				vtab.TclVarSet("T", "", tokenizer + " tokenchars ',.:' separators 'xyz'")
				T = tokenizer + " tokenchars ',.:' separators 'xyz'"
				_ = T // suppress unused warning
				_res = db.Exec("CREATE VIRTUAL TABLE t1 USING fts5(x, tokenize = \"" + T + "\")")
				if _res.Error != nil {
					t.Errorf("exec error: %v\n  sql: %s", _res.Error, "CREATE VIRTUAL TABLE t1 USING fts5(x, tokenize = \"" + T + "\")")
				}
				{ // "5." + tn + ".1"
					_res = db.Exec("\n    INSERT INTO t1 VALUES('abcxdefyghizjkl.mno,pqr:stu/vwx+yz');\n  ")
					if _res.Error != nil {
						t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n    INSERT INTO t1 VALUES('abcxdefyghizjkl.mno,pqr:stu/vwx+yz');\n  ")
					}
				}
				// foreach {tn2 token res} "1 abc 1     2 def 1     3 ghi 1    4 jkl {}\n    5 mno {}    6 pqr {}    7 stu {}   8 jkl.mno,pqr:stu 1\n    9 vw  1"
				_items2 := tclSplitList("1 abc 1     2 def 1     3 ghi 1    4 jkl {}\n    5 mno {}    6 pqr {}    7 stu {}   8 jkl.mno,pqr:stu 1\n    9 vw  1")
				for _idx2 := 0; _idx2+3 <= len(_items2); _idx2 += 3 {
					tn2 := _items2[_idx2+0]
					_ = tn2 // suppress unused warning
					token := _items2[_idx2+1]
					_ = token // suppress unused warning
					res := _items2[_idx2+2]
					_ = res // suppress unused warning
					_ = _idx2
						{ // "5." + tn + ".2." + tn2
							r = db.Query("\n      SELECT rowid FROM t1 WHERE t1 MATCH '\"" + token + "\"'\n    ")
							if r.Error != nil {
								t.Errorf("query error: %v\n  sql: %s", r.Error, "\n      SELECT rowid FROM t1 WHERE t1 MATCH '\"" + token + "\"'\n    ")
								return
							}
							got := flatten(r)
							want := tclListFlatten(res)
							if got != want {
								t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
							}
						}
					}
				}
				{ // do_test "5.1.1"
					_res = db.Exec("\n    CREATE VIRTUAL TABLE a1 USING fts5(x, tokenize=`ascii separators 'ሴ'`);\n    INSERT INTO a1 VALUES('abcሴdef');\n  ")
					if _res.Error != nil {
						t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE VIRTUAL TABLE a1 USING fts5(x, tokenize=`ascii separators 'ሴ'`);\n    INSERT INTO a1 VALUES('abcሴdef');\n  ")
					}
					r = db.Query(" SELECT rowid FROM a1 WHERE a1 MATCH 'def' ")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT rowid FROM a1 WHERE a1 MATCH 'def' ")
					}
				}
				{ // do_test "5.1.2"
					_res = db.Exec("\n    CREATE VIRTUAL TABLE a2 USING fts5(\n        x, tokenize=`unicode61 separators 'ሴ'`);\n    INSERT INTO a2 VALUES('abcሴdef');\n  ")
					if _res.Error != nil {
						t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE VIRTUAL TABLE a2 USING fts5(\n        x, tokenize=`unicode61 separators 'ሴ'`);\n    INSERT INTO a2 VALUES('abcሴdef');\n  ")
					}
					r = db.Query(" SELECT rowid FROM a2 WHERE a2 MATCH 'def' ")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT rowid FROM a2 WHERE a2 MATCH 'def' ")
					}
				}
				{ // "5.2"
					_res = db.Exec("\n  CREATE VIRTUAL TABLE a3 USING fts5(x, y, tokenize = 'ascii tokenchars');\n")
					if _res.Error == nil || !strings.Contains(_res.Error.Error(), "error in tokenizer constructor") {
						t.Errorf("expected error containing %q, got: %v\n  sql: %s", "error in tokenizer constructor", resErrString(_res), "\n  CREATE VIRTUAL TABLE a3 USING fts5(x, y, tokenize = 'ascii tokenchars');\n")
					}
				}
				{ // "5.3"
					_res = db.Exec("\n  CREATE VIRTUAL TABLE a3 USING fts5(x, y, tokenize = 'ascii opt arg');\n")
					if _res.Error == nil || !strings.Contains(_res.Error.Error(), "error in tokenizer constructor") {
						t.Errorf("expected error containing %q, got: %v\n  sql: %s", "error in tokenizer constructor", resErrString(_res), "\n  CREATE VIRTUAL TABLE a3 USING fts5(x, y, tokenize = 'ascii opt arg');\n")
					}
				}
				// proc definition (not transpiled)
				// proc definition (not transpiled)
				// sqlite3_fts5_create_function db tokenize tokenize (unsupported command, not transpiled)
				{ // "6.0"
					r = db.Query("\n  CREATE VIRTUAL TABLE x1 USING fts5(a, tokenize=ascii);\n  INSERT INTO x1 VALUES('q w e r t y');\n  INSERT INTO x1 VALUES('y t r e w q');\n  SELECT tokenize(x1) FROM x1 WHERE x1 MATCH 'e AND r';\n")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  CREATE VIRTUAL TABLE x1 USING fts5(a, tokenize=ascii);\n  INSERT INTO x1 VALUES('q w e r t y');\n  INSERT INTO x1 VALUES('y t r e w q');\n  SELECT tokenize(x1) FROM x1 WHERE x1 MATCH 'e AND r';\n")
						return
					}
					got := flatten(r)
					want := "q w e y t r"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				{ // "6.1"
					r = db.Query("\n  CREATE VIRTUAL TABLE x2 USING fts5(a, tokenize=unicode61);\n  INSERT INTO x2 VALUES('q w e r t y');\n  INSERT INTO x2 VALUES('y t r e w q');\n  SELECT tokenize(x2) FROM x2 WHERE x2 MATCH 'e AND r';\n")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  CREATE VIRTUAL TABLE x2 USING fts5(a, tokenize=unicode61);\n  INSERT INTO x2 VALUES('q w e r t y');\n  INSERT INTO x2 VALUES('y t r e w q');\n  SELECT tokenize(x2) FROM x2 WHERE x2 MATCH 'e AND r';\n")
						return
					}
					got := flatten(r)
					want := "q w e y t r"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				{ // "6.1"
					_res = db.Exec("\n  CREATE VIRTUAL TABLE a3 USING fts5(x, y, tokenize = 'unicode61 tokenchars');\n")
					if _res.Error == nil || !strings.Contains(_res.Error.Error(), "error in tokenizer constructor") {
						t.Errorf("expected error containing %q, got: %v\n  sql: %s", "error in tokenizer constructor", resErrString(_res), "\n  CREATE VIRTUAL TABLE a3 USING fts5(x, y, tokenize = 'unicode61 tokenchars');\n")
					}
				}
				{ // "6.2"
					_res = db.Exec("\n  CREATE VIRTUAL TABLE a3 USING fts5(x, y, tokenize = 'unicode61 a b');\n")
					if _res.Error == nil || !strings.Contains(_res.Error.Error(), "error in tokenizer constructor") {
						t.Errorf("expected error containing %q, got: %v\n  sql: %s", "error in tokenizer constructor", resErrString(_res), "\n  CREATE VIRTUAL TABLE a3 USING fts5(x, y, tokenize = 'unicode61 a b');\n")
					}
				}
				{ // "6.3"
					_res = db.Exec("\n  CREATE VIRTUAL TABLE a3 USING fts5(\n    x, y, tokenize = 'unicode61 remove_diacritics 3'\n  );\n")
					if _res.Error == nil || !strings.Contains(_res.Error.Error(), "error in tokenizer constructor") {
						t.Errorf("expected error containing %q, got: %v\n  sql: %s", "error in tokenizer constructor", resErrString(_res), "\n  CREATE VIRTUAL TABLE a3 USING fts5(\n    x, y, tokenize = 'unicode61 remove_diacritics 3'\n  );\n")
					}
				}
				{ // "6.4"
					_res = db.Exec("\n  CREATE VIRTUAL TABLE a3 USING fts5(\n    x, y, tokenize = 'unicode61 remove_diacritics 10'\n  );\n")
					if _res.Error == nil || !strings.Contains(_res.Error.Error(), "error in tokenizer constructor") {
						t.Errorf("expected error containing %q, got: %v\n  sql: %s", "error in tokenizer constructor", resErrString(_res), "\n  CREATE VIRTUAL TABLE a3 USING fts5(\n    x, y, tokenize = 'unicode61 remove_diacritics 10'\n  );\n")
					}
				}
				a = tclStringRepeat("a", "100")
				_ = a // suppress unused warning
				b = tclStringRepeat("b", "500")
				_ = b // suppress unused warning
				c = tclStringRepeat("c", "1000")
				_ = c // suppress unused warning
				{ // "7.0"
					_res = db.Exec("\n  CREATE VIRTUAL TABLE e5 USING fts5(x, tokenize=porter);\n  INSERT INTO e5 VALUES(" + sqlLiteral(a) + " || ' ' || " + sqlLiteral(b) + ");\n  INSERT INTO e5 VALUES(" + sqlLiteral(b) + " || ' ' || " + sqlLiteral(c) + ");\n  INSERT INTO e5 VALUES(" + sqlLiteral(c) + " || ' ' || " + sqlLiteral(a) + ");\n")
					if _res.Error != nil {
						t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE e5 USING fts5(x, tokenize=porter);\n  INSERT INTO e5 VALUES(" + sqlLiteral(a) + " || ' ' || " + sqlLiteral(b) + ");\n  INSERT INTO e5 VALUES(" + sqlLiteral(b) + " || ' ' || " + sqlLiteral(c) + ");\n  INSERT INTO e5 VALUES(" + sqlLiteral(c) + " || ' ' || " + sqlLiteral(a) + ");\n")
					}
				}
				{ // "7.1"
					r = db.Query("SELECT rowid FROM e5 WHERE e5 MATCH " + sqlLiteral(a))
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT rowid FROM e5 WHERE e5 MATCH " + sqlLiteral(a))
						return
					}
					got := flatten(r)
					want := "1 3"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				{ // "7.2"
					r = db.Query("SELECT rowid FROM e5 WHERE e5 MATCH " + sqlLiteral(b))
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT rowid FROM e5 WHERE e5 MATCH " + sqlLiteral(b))
						return
					}
					got := flatten(r)
					want := "1 2"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				{ // "7.3"
					r = db.Query("SELECT rowid FROM e5 WHERE e5 MATCH " + sqlLiteral(c))
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "SELECT rowid FROM e5 WHERE e5 MATCH " + sqlLiteral(c))
						return
					}
					got := flatten(r)
					want := "2 3"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				{ // "8.1"
					r = db.Query("\n  BEGIN;\n  CREATE VIRTUAL TABLE e6 USING fts5(x,\n    tokenize=\"unicode61 separators ABCDEFGHIJKLMNOPQRSTUVWXYZ\"\n  );\n  INSERT INTO e6 VALUES('theAquickBbrownCfoxDjumpedWoverXtheYlazyZdog');\n  CREATE VIRTUAL TABLE e7 USING fts5vocab(e6, 'row');\n  SELECT term FROM e7;\n  ROLLBACK;\n")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  BEGIN;\n  CREATE VIRTUAL TABLE e6 USING fts5(x,\n    tokenize=\"unicode61 separators ABCDEFGHIJKLMNOPQRSTUVWXYZ\"\n  );\n  INSERT INTO e6 VALUES('theAquickBbrownCfoxDjumpedWoverXtheYlazyZdog');\n  CREATE VIRTUAL TABLE e7 USING fts5vocab(e6, 'row');\n  SELECT term FROM e7;\n  ROLLBACK;\n")
						return
					}
					got := flatten(r)
					want := "brown dog fox jumped lazy over quick the"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				{ // "8.2"
					r = db.Query("BEGIN;\n  CREATE VIRTUAL TABLE e6 USING fts5(x,\n    tokenize=\"unicode61 separators 'u0E01u0E02u0E03u0E04u0E05u0E06u0E07'\"\n  );\n  INSERT INTO e6 VALUES('theu0E01quicku0E01brownu0E01foxu0E01' \n                     || 'jumpedu0E01overu0E01theu0E01lazyu0E01dog'\n  );\n  INSERT INTO e6 VALUES('u0E08u0E07u0E09');\n  CREATE VIRTUAL TABLE e7 USING fts5vocab(e6, 'row');\n  SELECT term FROM e7;\n  ROLLBACK;")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "BEGIN;\n  CREATE VIRTUAL TABLE e6 USING fts5(x,\n    tokenize=\"unicode61 separators 'u0E01u0E02u0E03u0E04u0E05u0E06u0E07'\"\n  );\n  INSERT INTO e6 VALUES('theu0E01quicku0E01brownu0E01foxu0E01' \n                     || 'jumpedu0E01overu0E01theu0E01lazyu0E01dog'\n  );\n  INSERT INTO e6 VALUES('u0E08u0E07u0E09');\n  CREATE VIRTUAL TABLE e7 USING fts5vocab(e6, 'row');\n  SELECT term FROM e7;\n  ROLLBACK;")
						return
					}
					got := flatten(r)
					want := tclListFlattenCollapse("\n  brown dog fox jumped lazy over quick the จ ฉ\n")
					got = tclListFlattenCollapse(got)
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				{ // "8.3"
					r = db.Query("\n  BEGIN;\n  CREATE VIRTUAL TABLE e6 USING fts5(x,\n    tokenize=\"porter unicode61 separators ABCDEFGHIJKLMNOPQRSTUVWXYZ\"\n  );\n  INSERT INTO e6 VALUES('theAquickBbrownCfoxDjumpedWoverXtheYlazyZdog');\n  CREATE VIRTUAL TABLE e7 USING fts5vocab(e6, 'row');\n  SELECT term FROM e7;\n  ROLLBACK;\n")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  BEGIN;\n  CREATE VIRTUAL TABLE e6 USING fts5(x,\n    tokenize=\"porter unicode61 separators ABCDEFGHIJKLMNOPQRSTUVWXYZ\"\n  );\n  INSERT INTO e6 VALUES('theAquickBbrownCfoxDjumpedWoverXtheYlazyZdog');\n  CREATE VIRTUAL TABLE e7 USING fts5vocab(e6, 'row');\n  SELECT term FROM e7;\n  ROLLBACK;\n")
						return
					}
					got := flatten(r)
					want := "brown dog fox jump lazi over quick the"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				db.Close()
				os.Remove("test.db")
				os.Remove("test.db-journal")
				os.Remove("test.db-wal")
				db, err = frigolite.Open("test.db")
				if err != nil { t.Fatal(err) }
				tcl_nullvalue = "{}" // fresh connection resets nullvalue
				// proc definition (not transpiled)
				// sqlite3_fts5_create_tokenizer db tcl tcl_create (unsupported command, not transpiled)
				vtab.TclVarSet("flags", "", "")
				flags = "" // TCL namespace variable
				_ = flags // suppress unused warning
				// proc definition (not transpiled)
				{ // "9.1.1"
					_res = db.Exec("\n  CREATE VIRTUAL TABLE t1 USING fts5(a, tokenize=tcl);\n  INSERT INTO t1 VALUES('abc');\n  INSERT INTO t1 VALUES('xyz');\n")
					if _res.Error != nil {
						t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE t1 USING fts5(a, tokenize=tcl);\n  INSERT INTO t1 VALUES('abc');\n  INSERT INTO t1 VALUES('xyz');\n")
					}
				}
				{ // do_test "9.1.2"
					_ = flags // TCL namespace variable (query)
					got := tclListFlatten(flags)
					want := tclListFlatten("document document")
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", got, want, "9.1.2")
					}
				}
				vtab.TclVarSet("flags", "", "")
				flags = "" // TCL namespace variable
				_ = flags // suppress unused warning
				{ // "9.2.1"
					r = db.Query(" SELECT * FROM t1('abc'); ")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM t1('abc'); ")
						return
					}
					got := flatten(r)
					want := "abc"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				{ // do_test "9.2.2"
					_ = flags // TCL namespace variable (query)
					got := tclListFlatten(flags)
					want := tclListFlatten("query")
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", got, want, "9.2.2")
					}
				}
				vtab.TclVarSet("flags", "", "")
				flags = "" // TCL namespace variable
				_ = flags // suppress unused warning
				{ // "9.3.1"
					r = db.Query(" SELECT * FROM t1('ab*'); ")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM t1('ab*'); ")
						return
					}
					got := flatten(r)
					want := "abc"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				{ // do_test "9.3.2"
					_ = flags // TCL namespace variable (query)
					got := tclListFlatten(flags)
					want := tclListFlatten("prefixquery")
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", got, want, "9.3.2")
					}
				}
				vtab.TclVarSet("flags", "", "")
				flags = "" // TCL namespace variable
				_ = flags // suppress unused warning
				{ // "9.4.1"
					r = db.Query(" SELECT * FROM t1('\"abc xyz\" *'); ")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM t1('\"abc xyz\" *'); ")
					}
				}
				{ // do_test "9.4.2"
					_ = flags // TCL namespace variable (query)
					got := tclListFlatten(flags)
					want := tclListFlatten("prefixquery")
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", got, want, "9.4.2")
					}
				}
				vtab.TclVarSet("flags", "", "")
				flags = "" // TCL namespace variable
				_ = flags // suppress unused warning
				{ // "9.5.1"
					r = db.Query(" SELECT * FROM t1('\"abc xyz*\"'); ")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT * FROM t1('\"abc xyz*\"'); ")
					}
				}
				{ // do_test "9.5.2"
					_ = flags // TCL namespace variable (query)
					got := tclListFlatten(flags)
					want := tclListFlatten("query")
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]\n  body: do_test %s", got, want, "9.5.2")
					}
				}
				db.Close()
				os.Remove("test.db")
				os.Remove("test.db-journal")
				os.Remove("test.db-wal")
				db, err = frigolite.Open("test.db")
				if err != nil { t.Fatal(err) }
				tcl_nullvalue = "{}" // fresh connection resets nullvalue
				{ // "10.1"
					r = db.Query("\n  CREATE VIRTUAL TABLE x1 USING fts5(x, tokenize=unicode61);\n  PRAGMA writable_schema = 1;\n  UPDATE sqlite_schema \n  SET sql = 'CREATE VIRTUAL TABLE x1 USING fts5(x, tokenize=\"unicode61 error\");'\n  WHERE name = 'x1';\n")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  CREATE VIRTUAL TABLE x1 USING fts5(x, tokenize=unicode61);\n  PRAGMA writable_schema = 1;\n  UPDATE sqlite_schema \n  SET sql = 'CREATE VIRTUAL TABLE x1 USING fts5(x, tokenize=\"unicode61 error\");'\n  WHERE name = 'x1';\n")
					}
				}
				db.Close()
				db, err = frigolite.Open("test.db")
				tclConnRegister("db", db)
				if err != nil { t.Fatal(err) }
				{ // "10.2"
					_res = db.Exec("\n  SELECT * FROM x1('abc');\n")
					if _res.Error == nil || !strings.Contains(_res.Error.Error(), "error in tokenizer constructor") {
						t.Errorf("expected error containing %q, got: %v\n  sql: %s", "error in tokenizer constructor", resErrString(_res), "\n  SELECT * FROM x1('abc');\n")
					}
				}
				{ // "10.3"
					_res = db.Exec("\n  INSERT INTO x1 VALUES('abc');\n")
					if _res.Error == nil || !strings.Contains(_res.Error.Error(), "error in tokenizer constructor") {
						t.Errorf("expected error containing %q, got: %v\n  sql: %s", "error in tokenizer constructor", resErrString(_res), "\n  INSERT INTO x1 VALUES('abc');\n")
					}
				}
				{ // "10.4"
					r = db.Query("\n  PRAGMA writable_schema = 1;\n  UPDATE sqlite_schema \n  SET sql = 'CREATE VIRTUAL TABLE x1 USING fts5(x, tokenize=\"nosuch error\");'\n  WHERE name = 'x1';\n")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  PRAGMA writable_schema = 1;\n  UPDATE sqlite_schema \n  SET sql = 'CREATE VIRTUAL TABLE x1 USING fts5(x, tokenize=\"nosuch error\");'\n  WHERE name = 'x1';\n")
					}
				}
				db.Close()
				db, err = frigolite.Open("test.db")
				tclConnRegister("db", db)
				if err != nil { t.Fatal(err) }
				{ // "10.5"
					_res = db.Exec("\n  SELECT * FROM x1('abc');\n")
					if _res.Error == nil || !strings.Contains(_res.Error.Error(), "no such tokenizer: nosuch") {
						t.Errorf("expected error containing %q, got: %v\n  sql: %s", "no such tokenizer: nosuch", resErrString(_res), "\n  SELECT * FROM x1('abc');\n")
					}
				}
				{ // "10.6"
					_res = db.Exec("\n  INSERT INTO x1 VALUES('abc');\n")
					if _res.Error == nil || !strings.Contains(_res.Error.Error(), "no such tokenizer: nosuch") {
						t.Errorf("expected error containing %q, got: %v\n  sql: %s", "no such tokenizer: nosuch", resErrString(_res), "\n  INSERT INTO x1 VALUES('abc');\n")
					}
				}
				{ // "10.7"
					r = db.Query("\n  DROP TABLE x1;\n  SELECT * FROM sqlite_schema;\n")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  DROP TABLE x1;\n  SELECT * FROM sqlite_schema;\n")
					}
				}
				db.Close()
				os.Remove("test.db")
				os.Remove("test.db-journal")
				os.Remove("test.db-wal")
				db, err = frigolite.Open("test.db")
				if err != nil { t.Fatal(err) }
				tcl_nullvalue = "{}" // fresh connection resets nullvalue
				{ // "10.8"
					r = db.Query("\n  CREATE VIRTUAL TABLE x1 USING fts5(x, tokenize=unicode61);\n  INSERT INTO x1 VALUES('a b c'), ('d e f'), ('a b c');\n  CREATE VIRTUAL TABLE x1v USING fts5vocab(x1, row);\n\n  PRAGMA writable_schema = 1;\n  UPDATE sqlite_schema \n  SET sql = 'CREATE VIRTUAL TABLE x1 USING fts5(x, tokenize=simplify);'\n  WHERE name = 'x1';\n")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  CREATE VIRTUAL TABLE x1 USING fts5(x, tokenize=unicode61);\n  INSERT INTO x1 VALUES('a b c'), ('d e f'), ('a b c');\n  CREATE VIRTUAL TABLE x1v USING fts5vocab(x1, row);\n\n  PRAGMA writable_schema = 1;\n  UPDATE sqlite_schema \n  SET sql = 'CREATE VIRTUAL TABLE x1 USING fts5(x, tokenize=simplify);'\n  WHERE name = 'x1';\n")
					}
				}
				{ // "10.9"
					r = db.Query("\n  SELECT * FROM x1v\n")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT * FROM x1v\n")
						return
					}
					got := flatten(r)
					want := "a 2 2 b 2 2 c 2 2 d 1 1 e 1 1 f 1 1"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				db.Close()
				db, err = frigolite.Open("test.db")
				tclConnRegister("db", db)
				if err != nil { t.Fatal(err) }
				{ // "10.10"
					r = db.Query("\n  SELECT * FROM x1v\n")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  SELECT * FROM x1v\n")
						return
					}
					got := flatten(r)
					want := "a 2 2 b 2 2 c 2 2 d 1 1 e 1 1 f 1 1"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
}
