// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package fts5fault7

import (
"github.com/pijalu/frigolite"
"github.com/pijalu/frigolite/internal/vtab"
"os"
"testing"
)

func Test_fts5fault7(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	var _r string
	var _berr error
	_ = _berr // suppress unused warning
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	_ = _r   // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testprefix string
	_ = testprefix // pre-declared from TCL source
	var testdir string
	_ = testdir // pre-declared from TCL source

	vtab.TclVarSet("testprefix", "", "fts5fault7")
	testprefix = "fts5fault7"
	_ = testprefix // suppress unused warning
	if true {
		{ // "1.0"
			_res = db.Exec("\n  CREATE VIRTUAL TABLE t1 USING fts5(x, columnsize=0);\n  INSERT INTO t1 VALUES('a b c d e f g');\n  INSERT INTO t1 VALUES('a b c d');\n  INSERT INTO t1 VALUES('a b c d e f g h i j');\n")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE t1 USING fts5(x, columnsize=0);\n  INSERT INTO t1 VALUES('a b c d e f g');\n  INSERT INTO t1 VALUES('a b c d');\n  INSERT INTO t1 VALUES('a b c d e f g h i j');\n")
			}
		}
		// fts5_aux_test_functions db (unsupported command, not transpiled)
		// do_faultsim_test 1 -faults oom* -body {\n  execsql { SELECT fts5_test_columnsize(t1) FROM...} -te... (unsupported command, not transpiled)
	}
	{ // "1.0"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE t2 USING fts5(a);\n  INSERT INTO t2(t2, rank) VALUES('automerge', 0);\n  INSERT INTO t2(t2, rank) VALUES('crisismerge', 4);\n  INSERT INTO t2(t2, rank) VALUES('pgsz', 40);\n\n  INSERT INTO t2 VALUES('a b c');\n  INSERT INTO t2 VALUES('d e f');\n  INSERT INTO t2 VALUES('f e d');\n  INSERT INTO t2 VALUES('c b a');\n\n  INSERT INTO t2 VALUES('a b c');\n  INSERT INTO t2 VALUES('d e f');\n  INSERT INTO t2 VALUES('f e d');\n  INSERT INTO t2 VALUES('c b a');\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE t2 USING fts5(a);\n  INSERT INTO t2(t2, rank) VALUES('automerge', 0);\n  INSERT INTO t2(t2, rank) VALUES('crisismerge', 4);\n  INSERT INTO t2(t2, rank) VALUES('pgsz', 40);\n\n  INSERT INTO t2 VALUES('a b c');\n  INSERT INTO t2 VALUES('d e f');\n  INSERT INTO t2 VALUES('f e d');\n  INSERT INTO t2 VALUES('c b a');\n\n  INSERT INTO t2 VALUES('a b c');\n  INSERT INTO t2 VALUES('d e f');\n  INSERT INTO t2 VALUES('f e d');\n  INSERT INTO t2 VALUES('c b a');\n")
		}
	}
	// db_save_and_close: snapshot test.db* under sv_ prefix
	for _, _sf := range tclSplitList(tclGlob("test.db*")) {
		tclFileCopy(_sf, "sv_"+_sf)
	}
	db.Close()
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	tcl_nullvalue = "{}" // fresh connection resets nullvalue
	// do_faultsim_test 1 -faults oom-t* -prep {\n  faultsim_restore_and_reopen\n  db eval {\n    ...} -... (unsupported command, not transpiled)
	db.Close()
	os.Remove("test.db")
	os.Remove("test.db-journal")
	os.Remove("test.db-wal")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	tcl_nullvalue = "{}" // fresh connection resets nullvalue
	{ // "2.0"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE xy USING fts5(x);\n  INSERT INTO xy(rowid, x) VALUES(1, '1 2 3');\n  INSERT INTO xy(rowid, x) VALUES(2, '2 3 4');\n  INSERT INTO xy(rowid, x) VALUES(3, '3 4 5');\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", resErrString(_res), "\n  CREATE VIRTUAL TABLE xy USING fts5(x);\n  INSERT INTO xy(rowid, x) VALUES(1, '1 2 3');\n  INSERT INTO xy(rowid, x) VALUES(2, '2 3 4');\n  INSERT INTO xy(rowid, x) VALUES(3, '3 4 5');\n")
		}
	}
	// db_save_and_close: snapshot test.db* under sv_ prefix
	for _, _sf := range tclSplitList(tclGlob("test.db*")) {
		tclFileCopy(_sf, "sv_"+_sf)
	}
	db.Close()
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	tcl_nullvalue = "{}" // fresh connection resets nullvalue
	// do_faultsim_test 2.1 -faults oom-* -prep {\n  faultsim_restore_and_reopen\n} -body {\n  db eval {... (unsupported command, not transpiled)
	// do_faultsim_test 2.2 -faults oom-* -body {\n  db eval { SELECT * FROM xy('""') }\n} -test {\n  fa... (unsupported command, not transpiled)
}
