// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package mallocK

import (
"github.com/pijalu/frigolite"
"strconv"
"testing"
)

func Test_mallocK(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var testprefix string
	_ = testprefix // pre-declared from TCL source
	var sql string
	_ = sql // pre-declared from TCL source
	var x string
	_ = x // pre-declared from TCL source
	var term string
	_ = term // pre-declared from TCL source
	var y string
	_ = y // pre-declared from TCL source
	var Id_ string
	_ = Id_ // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source
	var i string
	_ = i // pre-declared from TCL source
	var a string
	_ = a // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	testprefix = "mallocK"
	_ = testprefix // suppress unused warning
	sql = "SELECT * FROM t1, t2 WHERE (a=1 OR a=2)"
	_ = sql // suppress unused warning
	x = "1"
	_ = x // suppress unused warning
	for func() bool { x_n, _x_e := strconv.Atoi(x); if _x_e != nil { return false }; return x_n < 5 }() {
		sql += " AND b=y"
		// do_malloc_test mallocK-1.$x -sqlbody $sql -sqlprep {\n    CREATE TABLE t1(a,b);\n    CREATE TAB... (unsupported command, not transpiled)
		// incr x 1
		{
			_n, _err := strconv.Atoi(x)
			if _err == nil {
				x = strconv.Itoa(_n + 1)
			}
		}
	}
	sql = "SELECT * FROM t1 WHERE a GLOB 'xyz*' AND (a=1 OR a=2)"
	_ = sql // suppress unused warning
	x = "1"
	_ = x // suppress unused warning
	for func() bool { x_n, _x_e := strconv.Atoi(x); if _x_e != nil { return false }; return x_n < 5 }() {
		sql += " AND b!=" + x
		// do_malloc_test mallocK-2.$x -sqlbody $sql -sqlprep {\n    CREATE TABLE t1(a,b);\n  } (unsupported command, not transpiled)
		// incr x 1
		{
			_n, _err := strconv.Atoi(x)
			if _err == nil {
				x = strconv.Itoa(_n + 1)
			}
		}
	}
	sql = "SELECT * FROM t1 WHERE a BETWEEN 5 AND 10"
	_ = sql // suppress unused warning
	x = "1"
	_ = x // suppress unused warning
	for func() bool { x_n, _x_e := strconv.Atoi(x); if _x_e != nil { return false }; return x_n < 5 }() {
		sql += " AND b=" + x
		// do_malloc_test mallocK-3.$x -sqlbody $sql -sqlprep {\n    CREATE TABLE t1(a,b);\n  } (unsupported command, not transpiled)
		// incr x 1
		{
			_n, _err := strconv.Atoi(x)
			if _err == nil {
				x = strconv.Itoa(_n + 1)
			}
		}
	}
	sql = "SELECT * FROM t1 WHERE b=0"
	_ = sql // suppress unused warning
	x = "1"
	_ = x // suppress unused warning
	for func() bool { x_n, _x_e := strconv.Atoi(x); if _x_e != nil { return false }; return x_n < 5 }() {
		term = "(b=" + x
		_ = term // suppress unused warning
		y = "0"
		_ = y // suppress unused warning
		for func() bool { y_n, _y_e := strconv.Atoi(y); if _y_e != nil { return false }; x_n, _x_e := strconv.Atoi(x); if _x_e != nil { return false }; return y_n < x_n }() {
			term += " AND a!=" + y
			// incr y 1
			{
				_n, _err := strconv.Atoi(y)
				if _err == nil {
					y = strconv.Itoa(_n + 1)
				}
			}
		}
		sql += " OR " + term + ")"
		// do_malloc_test mallocK-4.$x -sqlbody $sql -sqlprep {\n    CREATE TABLE t1(a,b);\n  } (unsupported command, not transpiled)
		// incr x 1
		{
			_n, _err := strconv.Atoi(x)
			if _err == nil {
				x = strconv.Itoa(_n + 1)
			}
		}
	}
	sql = "SELECT * FROM t2 WHERE a MATCH 'xyz'"
	_ = sql // suppress unused warning
	x = "1"
	_ = x // suppress unused warning
	for func() bool { x_n, _x_e := strconv.Atoi(x); if _x_e != nil { return false }; return x_n < 5 }() {
		sql += " AND b!=" + x
		// do_malloc_test mallocK-5.$x -sqlbody $sql -tclprep {\n      register_echo_module [sqlite3_conne... (unsupported command, not transpiled)
		// incr x 1
		{
			_n, _err := strconv.Atoi(x)
			if _err == nil {
				x = strconv.Itoa(_n + 1)
			}
		}
	}
	// add_alignment_test_collations db (unsupported command, not transpiled)
	{ // "6.0"
		r = db.Query("\n  CREATE TABLE t3(a TEXT, b TEXT COLLATE utf16_aligned, c);\n  INSERT INTO t3 VALUES('one', '.....', 0);\n  INSERT INTO t3 VALUES('one', '....x', 1);\n  INSERT INTO t3 VALUES('one', '...x.', 2);\n  INSERT INTO t3 VALUES('one', '...xx', 3);\n  INSERT INTO t3 VALUES('one', '..x..', 4);\n  INSERT INTO t3 VALUES('one', '..x.x', 5);\n  INSERT INTO t3 VALUES('one', '..xx.', 6);\n  INSERT INTO t3 VALUES('one', '..xxx', 7);\n  INSERT INTO t3 VALUES('one', '.x...', 8);\n  INSERT INTO t3 VALUES('one', '.x..x', 9);\n  INSERT INTO t3 VALUES('one', '.x.x.', 10);\n  INSERT INTO t3 VALUES('one', '.x.xx', 11);\n  INSERT INTO t3 VALUES('one', '.xx..', 12);\n  INSERT INTO t3 VALUES('one', '.xx.x', 13);\n  INSERT INTO t3 VALUES('one', '.xxx.', 14);\n  INSERT INTO t3 VALUES('one', '.xxxx', 15);\n\n  INSERT INTO t3 VALUES('two', 'x....', 16);\n  INSERT INTO t3 VALUES('two', 'x...x', 17);\n  INSERT INTO t3 VALUES('two', 'x..x.', 18);\n  INSERT INTO t3 VALUES('two', 'x..xx', 19);\n  INSERT INTO t3 VALUES('two', 'x.x..', 20);\n  INSERT INTO t3 VALUES('two', 'x.x.x', 21);\n  INSERT INTO t3 VALUES('two', 'x.xx.', 22);\n  INSERT INTO t3 VALUES('two', 'x.xxx', 23);\n  INSERT INTO t3 VALUES('two', 'xx...', 24);\n  INSERT INTO t3 VALUES('two', 'xx..x', 25);\n  INSERT INTO t3 VALUES('two', 'xx.x.', 26);\n  INSERT INTO t3 VALUES('two', 'xx.xx', 27);\n  INSERT INTO t3 VALUES('two', 'xxx..', 28);\n  INSERT INTO t3 VALUES('two', 'xxx.x', 29);\n  INSERT INTO t3 VALUES('two', 'xxxx.', 30);\n  INSERT INTO t3 VALUES('two', 'xxxxx', 31);\n\n  INSERT INTO t3 SELECT * FROM t3;\n\n  CREATE INDEX i3 ON t3(a, b);\n  ANALYZE;\n\n  SELECT 'x' > '.';\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  CREATE TABLE t3(a TEXT, b TEXT COLLATE utf16_aligned, c);\n  INSERT INTO t3 VALUES('one', '.....', 0);\n  INSERT INTO t3 VALUES('one', '....x', 1);\n  INSERT INTO t3 VALUES('one', '...x.', 2);\n  INSERT INTO t3 VALUES('one', '...xx', 3);\n  INSERT INTO t3 VALUES('one', '..x..', 4);\n  INSERT INTO t3 VALUES('one', '..x.x', 5);\n  INSERT INTO t3 VALUES('one', '..xx.', 6);\n  INSERT INTO t3 VALUES('one', '..xxx', 7);\n  INSERT INTO t3 VALUES('one', '.x...', 8);\n  INSERT INTO t3 VALUES('one', '.x..x', 9);\n  INSERT INTO t3 VALUES('one', '.x.x.', 10);\n  INSERT INTO t3 VALUES('one', '.x.xx', 11);\n  INSERT INTO t3 VALUES('one', '.xx..', 12);\n  INSERT INTO t3 VALUES('one', '.xx.x', 13);\n  INSERT INTO t3 VALUES('one', '.xxx.', 14);\n  INSERT INTO t3 VALUES('one', '.xxxx', 15);\n\n  INSERT INTO t3 VALUES('two', 'x....', 16);\n  INSERT INTO t3 VALUES('two', 'x...x', 17);\n  INSERT INTO t3 VALUES('two', 'x..x.', 18);\n  INSERT INTO t3 VALUES('two', 'x..xx', 19);\n  INSERT INTO t3 VALUES('two', 'x.x..', 20);\n  INSERT INTO t3 VALUES('two', 'x.x.x', 21);\n  INSERT INTO t3 VALUES('two', 'x.xx.', 22);\n  INSERT INTO t3 VALUES('two', 'x.xxx', 23);\n  INSERT INTO t3 VALUES('two', 'xx...', 24);\n  INSERT INTO t3 VALUES('two', 'xx..x', 25);\n  INSERT INTO t3 VALUES('two', 'xx.x.', 26);\n  INSERT INTO t3 VALUES('two', 'xx.xx', 27);\n  INSERT INTO t3 VALUES('two', 'xxx..', 28);\n  INSERT INTO t3 VALUES('two', 'xxx.x', 29);\n  INSERT INTO t3 VALUES('two', 'xxxx.', 30);\n  INSERT INTO t3 VALUES('two', 'xxxxx', 31);\n\n  INSERT INTO t3 SELECT * FROM t3;\n\n  CREATE INDEX i3 ON t3(a, b);\n  ANALYZE;\n\n  SELECT 'x' > '.';\n")
			return
		}
		got := flatten(r)
		want := "1"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // "6.1"
		r = db.Query("EXPLAIN QUERY PLAN " + "\n    SELECT DISTINCT c FROM t3 WHERE b BETWEEN '.xx..' AND '.xxxx';\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "EXPLAIN QUERY PLAN "+"\n    SELECT DISTINCT c FROM t3 WHERE b BETWEEN '.xx..' AND '.xxxx';\n  ")
		}
	}
	// do_faultsim_test 6 -faults oom* -body {\n  db cache flush\n  db eval { SELECT DISTINCT c ...} -te... (unsupported command, not transpiled)
	{ // "7.1"
		_res = db.Exec("\n  CREATE TABLE x1(a INTEGER PRIMARY KEY, b);\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE x1(a INTEGER PRIMARY KEY, b);\n")
		}
	}
	// do_faultsim_test 7.2 -faults oom* -body {\n  execsql { SELECT * FROM x1 WHERE a = (SELECT 1...} -... (unsupported command, not transpiled)
	db.Close()
	db, err = frigolite.Open("")
	if err != nil { t.Fatal(err) }
	// proc definition (not transpiled)
	{ // "8.0"
		_res = db.Exec("\n  PRAGMA encoding = 'utf-16';\n  CREATE TABLE x2(x TEXT, y TEXT);\n  WITH data(i) AS (\n    SELECT 1 UNION ALL SELECT i+1 FROM data\n  )\n  INSERT INTO x2 SELECT isqrt(i), isqrt(i) FROM data LIMIT 400;\n  CREATE INDEX x2x ON x2(x);\n  CREATE INDEX x2y ON x2(y);\n  ANALYZE;\n  DELETE FROM x2;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  PRAGMA encoding = 'utf-16';\n  CREATE TABLE x2(x TEXT, y TEXT);\n  WITH data(i) AS (\n    SELECT 1 UNION ALL SELECT i+1 FROM data\n  )\n  INSERT INTO x2 SELECT isqrt(i), isqrt(i) FROM data LIMIT 400;\n  CREATE INDEX x2x ON x2(x);\n  CREATE INDEX x2y ON x2(y);\n  ANALYZE;\n  DELETE FROM x2;\n")
		}
	}
	// proc definition (not transpiled)
	// do_faultsim_test 8 -faults oom* -body {\n  execsql { SELECT * FROM x2 WHERE x = str('19')...} -te... (unsupported command, not transpiled)
}
