// Code generated by tcl2go; DO NOT EDIT.
package upfrom

import (
"github.com/pijalu/frigolite"
"strings"
"testing"
)

func Test_upfrom2(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result

	// set testdir: test directory (not used in Go test context)
	var testprefix = "upfrom2"
	_ = testprefix // suppress unused warning
	// foreach {tn wo} "\n  1 \"\"\n  2 \"WITHOUT ROWID\"\n"
	_items := tclSplitList("\n  1 \"\"\n  2 \"WITHOUT ROWID\"\n")
	for _idx := 0; _idx+2 <= len(_items); _idx += 2 {
		tn := _items[_idx+0]
		wo := _items[_idx+1]
		_ = _idx
			db.Close()
			db, err = frigolite.Open("")
			if err != nil { t.Fatal(err) }
			// eval [string map [list %WO% $wo %TN% $tn] {
  do_execsq...
		}
		db.Close()
		db, err = frigolite.Open("")
		if err != nil { t.Fatal(err) }
		{ // "3.0"
			_res = db.Exec("\n  CREATE TABLE data(x, y, z);\n  CREATE VIEW t1 AS SELECT * FROM data;\n  CREATE TRIGGER t1_insert INSTEAD OF INSERT ON t1 BEGIN\n    INSERT INTO data VALUES(new.x, new.y, new.z);\n  END;\n  CREATE TRIGGER t1_update INSTEAD OF UPDATE ON t1 BEGIN\n    INSERT INTO log VALUES(old.z || '->' || new.z);\n  END;\n\n  CREATE TABLE log(t TEXT);\n\n  INSERT INTO t1 VALUES(1, 'i',   'one');\n  INSERT INTO t1 VALUES(2, 'ii',  'two');\n  INSERT INTO t1 VALUES(3, 'iii', 'three');\n  INSERT INTO t1 VALUES(4, 'iv',  'four');\n")
			if _res.Error != nil {
				t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE data(x, y, z);\n  CREATE VIEW t1 AS SELECT * FROM data;\n  CREATE TRIGGER t1_insert INSTEAD OF INSERT ON t1 BEGIN\n    INSERT INTO data VALUES(new.x, new.y, new.z);\n  END;\n  CREATE TRIGGER t1_update INSTEAD OF UPDATE ON t1 BEGIN\n    INSERT INTO log VALUES(old.z || '->' || new.z);\n  END;\n\n  CREATE TABLE log(t TEXT);\n\n  INSERT INTO t1 VALUES(1, 'i',   'one');\n  INSERT INTO t1 VALUES(2, 'ii',  'two');\n  INSERT INTO t1 VALUES(3, 'iii', 'three');\n  INSERT INTO t1 VALUES(4, 'iv',  'four');\n")
			}
		}
		{ // "3.1"
			r = db.Query("\n  WITH input(k, v) AS (\n      VALUES(3, 'thirty'), (1, 'ten')\n  )\n  UPDATE t1 SET z=v FROM input WHERE x=k;\n")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  WITH input(k, v) AS (\n      VALUES(3, 'thirty'), (1, 'ten')\n  )\n  UPDATE t1 SET z=v FROM input WHERE x=k;\n")
			}
		}
		// foreach {tn sql} "\n  2 { \n    CREATE TABLE x1(a INT PRIMARY KEY, b, c) WITHOUT ROWID;\n  }\n  1 { \n    CREATE TABLE x1(a INTEGER PRIMARY KEY, b, c);\n  }\n  3 { \n    CREATE TABLE x1(a INT PRIMARY KEY, b, c);\n  }\n"
		_items := tclSplitList("\n  2 { \n    CREATE TABLE x1(a INT PRIMARY KEY, b, c) WITHOUT ROWID;\n  }\n  1 { \n    CREATE TABLE x1(a INTEGER PRIMARY KEY, b, c);\n  }\n  3 { \n    CREATE TABLE x1(a INT PRIMARY KEY, b, c);\n  }\n")
		for _idx := 0; _idx+2 <= len(_items); _idx += 2 {
			tn := _items[_idx+0]
			sql := _items[_idx+1]
			_ = _idx
				db.Close()
				db, err = frigolite.Open("")
				if err != nil { t.Fatal(err) }
				_res = db.Exec(sql)
				if _res.Error != nil {
					t.Errorf("exec error: %v\n  sql: %s", _res.Error, sql)
				}
				{ // "4." + tn + ".0"
					_res = db.Exec("\n    INSERT INTO x1 VALUES(1, 1, 1);\n    INSERT INTO x1 VALUES(2, 2, 2);\n    INSERT INTO x1 VALUES(3, 3, 3);\n    INSERT INTO x1 VALUES(4, 4, 4);\n    INSERT INTO x1 VALUES(5, 5, 5);\n    CREATE TABLE map(o, t);\n    INSERT INTO map VALUES(3, 30), (4, 40), (1, 10);\n  ")
					if _res.Error != nil {
						t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    INSERT INTO x1 VALUES(1, 1, 1);\n    INSERT INTO x1 VALUES(2, 2, 2);\n    INSERT INTO x1 VALUES(3, 3, 3);\n    INSERT INTO x1 VALUES(4, 4, 4);\n    INSERT INTO x1 VALUES(5, 5, 5);\n    CREATE TABLE map(o, t);\n    INSERT INTO map VALUES(3, 30), (4, 40), (1, 10);\n  ")
					}
				}
				{ // "4." + tn + ".1"
					r = db.Query("\n    UPDATE x1 SET a=t FROM map WHERE a=o;\n    SELECT * FROM x1 ORDER BY a;\n  ")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    UPDATE x1 SET a=t FROM map WHERE a=o;\n    SELECT * FROM x1 ORDER BY a;\n  ")
						return
					}
					got := flatten(r)
					want := "2 2 2   5 5 5   10 1 1  30 3 3  40 4 4"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
			}
			db.Close()
			db, err = frigolite.Open("")
			if err != nil { t.Fatal(err) }
			{ // "5.0"
				_res = db.Exec("\n  CREATE TABLE x1(a, b, c);\n  CREATE TABLE x2(a, b, c);\n")
				if _res.Error != nil {
					t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE x1(a, b, c);\n  CREATE TABLE x2(a, b, c);\n")
				}
			}
			// foreach {tn update nm} "\n  1 \"UPDATE x1 SET a=5 FROM x1\" x1\n  2 \"UPDATE x1 AS grapes SET a=5 FROM x1 AS grapes\" grapes\n  3 \"UPDATE x1 SET a=5 FROM x2, x1\" x1\n  4 \"UPDATE x1 AS grapes SET a=5 FROM x2, x1 AS grapes\" grapes\n"
			_items := tclSplitList("\n  1 \"UPDATE x1 SET a=5 FROM x1\" x1\n  2 \"UPDATE x1 AS grapes SET a=5 FROM x1 AS grapes\" grapes\n  3 \"UPDATE x1 SET a=5 FROM x2, x1\" x1\n  4 \"UPDATE x1 AS grapes SET a=5 FROM x2, x1 AS grapes\" grapes\n")
			for _idx := 0; _idx+3 <= len(_items); _idx += 3 {
				tn := _items[_idx+0]
				update := _items[_idx+1]
				nm := _items[_idx+2]
				_ = _idx
					{ // "5." + tn
						_res = db.Exec(update)
						if _res.Error == nil || !strings.Contains(_res.Error.Error(), "target object/alias may not appear in FROM clause: \" + nm + \"") {
							t.Errorf("expected error containing %q, got: %v\n  sql: %s", "target object/alias may not appear in FROM clause: \" + nm + \"", _res.Error, update)
						}
					}
				}
				db.Close()
				db, err = frigolite.Open("")
				if err != nil { t.Fatal(err) }
				{ // "6.0"
					_res = db.Exec("\n  CREATE TABLE t1(a); \n")
					if _res.Error != nil {
						t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE t1(a); \n")
					}
				}
				{ // "6.1"
					_res = db.Exec("\n  UPDATE t1 SET a = 1 FROM (\n      SELECT * FROM t1\n  )\n")
					if _res.Error != nil {
						t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  UPDATE t1 SET a = 1 FROM (\n      SELECT * FROM t1\n  )\n")
					}
				}
				{ // "6.2"
					_res = db.Exec("\n  UPDATE t1 SET a = 1 FROM (\n      SELECT * FROM t1 UNION ALL SELECT * FROM t1\n  )\n")
					if _res.Error != nil {
						t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  UPDATE t1 SET a = 1 FROM (\n      SELECT * FROM t1 UNION ALL SELECT * FROM t1\n  )\n")
					}
				}
				db.Close()
				db, err = frigolite.Open("")
				if err != nil { t.Fatal(err) }
				{ // "7.0"
					r = db.Query("\n  CREATE TABLE t1(a);\n  INSERT INTO t1(a) VALUES(11),(22),(33),(44),(55);\n  CREATE VIEW t2(b,c) AS SELECT a, COUNT(*) OVER () FROM t1;\n  CREATE TABLE t3(x,y);\n  CREATE TRIGGER t2r1 INSTEAD OF UPDATE ON t2 BEGIN\n    INSERT INTO t3(x,y) VALUES(new.b,new.c);\n  END;\n  SELECT * FROM t2;\n")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  CREATE TABLE t1(a);\n  INSERT INTO t1(a) VALUES(11),(22),(33),(44),(55);\n  CREATE VIEW t2(b,c) AS SELECT a, COUNT(*) OVER () FROM t1;\n  CREATE TABLE t3(x,y);\n  CREATE TRIGGER t2r1 INSTEAD OF UPDATE ON t2 BEGIN\n    INSERT INTO t3(x,y) VALUES(new.b,new.c);\n  END;\n  SELECT * FROM t2;\n")
						return
					}
					got := flatten(r)
					want := "11 5 22 5 33 5 44 5 55 5"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
				{ // "7.1"
					r = db.Query("\n  UPDATE t2 SET c=t1.a FROM t1 WHERE t2.b=t1.a;\n  SELECT * FROM t3;\n")
					if r.Error != nil {
						t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  UPDATE t2 SET c=t1.a FROM t1 WHERE t2.b=t1.a;\n  SELECT * FROM t3;\n")
						return
					}
					got := flatten(r)
					want := "11 11 22 22 33 33 44 44 55 55"
					if got != want {
						t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
					}
				}
}
