// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package sqllog

import (
"github.com/pijalu/frigolite"
"os"
"testing"
)

func Test_sqllog(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var testprefix string
	_ = testprefix // pre-declared from TCL source
	var fd string
	_ = fd // pre-declared from TCL source
	var txt string
	_ = txt // pre-declared from TCL source
	var env_SQLITE_SQLLOG_DIR string
	_ = env_SQLITE_SQLLOG_DIR // pre-declared from TCL source
	var a string
	_ = a // pre-declared from TCL source
	var b string
	_ = b // pre-declared from TCL source
	var env_SQLITE_SQLLOG_CONDITIONAL string
	_ = env_SQLITE_SQLLOG_CONDITIONAL // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source
	var f string
	_ = f // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	testprefix = "sqllog"
	_ = testprefix // suppress unused warning
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	// sqlite3_shutdown (unsupported command, not transpiled)
	env_SQLITE_SQLLOG_DIR = "pwd" // TCL namespace variable
	_ = env_SQLITE_SQLLOG_DIR // suppress unused warning
	// delete_all_sqllog_files (unsupported command, not transpiled)
	os.Remove("test.db")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	a = "a"
	_ = a // suppress unused warning
	b = "b"
	_ = b // suppress unused warning
	{ // "1.0"
		r = db.Query("\n  CREATE TABLE t1(x, y);\n  INSERT INTO t1 VALUES(1, 2);\n  INSERT INTO t1 VALUES($a, $b);\n  SELECT * FROM t1;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  CREATE TABLE t1(x, y);\n  INSERT INTO t1 VALUES(1, 2);\n  INSERT INTO t1 VALUES($a, $b);\n  SELECT * FROM t1;\n")
			return
		}
		got := flatten(r)
		want := "1 2 a b"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // do_test "1.1"
		// readfile [lindex [glob sqllog_*.sql] 0] (unsupported command, not transpiled)
	}
	{ // do_test "1.2"
		// file size [lindex [glob sqllog_*_0.db] 0]
	}
	{
		var _catchErr error
		_ = _catchErr // suppress unused warning
	}
	// sqlite3_shutdown (unsupported command, not transpiled)
	// delete_all_sqllog_files (unsupported command, not transpiled)
	os.Remove("test.db-sqllog")
	env_SQLITE_SQLLOG_CONDITIONAL = "1" // TCL namespace variable
	_ = env_SQLITE_SQLLOG_CONDITIONAL // suppress unused warning
	os.Remove("test.db")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	{ // "2.1"
		r = db.Query("\n  INSERT INTO t1 VALUES(4, 5);\n  SELECT * FROM t1;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  INSERT INTO t1 VALUES(4, 5);\n  SELECT * FROM t1;\n")
			return
		}
		got := flatten(r)
		want := "1 2 a b 4 5"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // do_test "2.2"
		tclGlob("-nocomplain")
	}
	// touch test.db-sqllog (unsupported command, not transpiled)
	os.Remove("test.db")
	db, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	{ // "2.3"
		r = db.Query("\n  INSERT INTO t1 VALUES(6, 7);\n  SELECT * FROM t1;\n")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n  INSERT INTO t1 VALUES(6, 7);\n  SELECT * FROM t1;\n")
			return
		}
		got := flatten(r)
		want := "1 2 a b 4 5 6 7"
		if got != want {
			t.Errorf("result mismatch\n  got:  [%s]\n  want: [%s]", got, want)
		}
	}
	{ // do_test "2.4"
		// readfile [lindex [glob sqllog_*.sql] 0] (unsupported command, not transpiled)
	}
	{
		var _catchErr error
		_ = _catchErr // suppress unused warning
	}
	// sqlite3_shutdown (unsupported command, not transpiled)
	// sqlite3_config_sqllog (unsupported command, not transpiled)
	// sqlite3_initialize (unsupported command, not transpiled)
}
