// Code generated by tcl2go; DO NOT EDIT.
package fts4growth

import (
"github.com/pijalu/frigolite"
"strconv"
"testing"
)

func Test_fts4growth2(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning

	// set testdir: test directory (not used in Go test context)
	var testprefix = "fts4growth2"
	_ = testprefix // suppress unused warning
	{ // "1.0"
		_res = db.Exec(" CREATE TABLE t1(docid, words); ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, " CREATE TABLE t1(docid, words); ")
		}
	}
	t.Errorf("TODO: %s not implemented in frigolite", "fts_kjv_genesis")
	// proc definition (not transpiled)
	// proc definition (not transpiled)
	{ // "1.1"
		_res = db.Exec("\n  CREATE VIRTUAL TABLE x1 USING fts4;\n  INSERT INTO x1(x1) VALUES('automerge=2');\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE VIRTUAL TABLE x1 USING fts4;\n  INSERT INTO x1(x1) VALUES('automerge=2');\n")
		}
	}
	{ // do_test "1.2"
		var i = "0"
		_ = i // suppress unused warning
		for func() bool { i_n, _i_e := strconv.Atoi(i); if _i_e != nil { return false }; return i_n < 40 }() {
			t.Errorf("TODO: %s not implemented in frigolite", "tt 0")
			t.Errorf("TODO: %s not implemented in frigolite", "tt 1")
			t.Errorf("TODO: %s not implemented in frigolite", "tt 2")
			t.Errorf("TODO: %s not implemented in frigolite", "tt 3")
			// incr i 1
			{
				_n, _err := strconv.Atoi(i)
				if _err == nil {
					i = strconv.Itoa(_n + 1)
				}
			}
		}
		r = db.Query(" \n    SELECT max(level) FROM x1_segdir; \n    SELECT count(*) FROM x1_segdir WHERE level=2;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " \n    SELECT max(level) FROM x1_segdir; \n    SELECT count(*) FROM x1_segdir WHERE level=2;\n  ")
		}
	}
	{ // do_test "1.3"
		var i = "0"
		_ = i // suppress unused warning
		for func() bool { i_n, _i_e := strconv.Atoi(i); if _i_e != nil { return false }; return i_n < 40 }() {
			t.Errorf("TODO: %s not implemented in frigolite", "tt 0")
			t.Errorf("TODO: %s not implemented in frigolite", "tt 1")
			t.Errorf("TODO: %s not implemented in frigolite", "tt 2")
			t.Errorf("TODO: %s not implemented in frigolite", "tt 3")
			// incr i 1
			{
				_n, _err := strconv.Atoi(i)
				if _err == nil {
					i = strconv.Itoa(_n + 1)
				}
			}
		}
		r = db.Query(" \n    SELECT max(level) FROM x1_segdir; \n    SELECT count(*) FROM x1_segdir WHERE level=2;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, " \n    SELECT max(level) FROM x1_segdir; \n    SELECT count(*) FROM x1_segdir WHERE level=2;\n  ")
		}
	}
	{ // "2.1"
		_res = db.Exec("\n  DELETE FROM t1 WHERE rowid>16;\n  DROP TABLE IF EXISTS x1;\n  CREATE VIRTUAL TABLE x1 USING fts4;\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  DELETE FROM t1 WHERE rowid>16;\n  DROP TABLE IF EXISTS x1;\n  CREATE VIRTUAL TABLE x1 USING fts4;\n")
		}
	}
	// proc definition (not transpiled)
	var tn = "0"
	_ = tn // suppress unused warning
	for func() bool { tn_n, _tn_e := strconv.Atoi(tn); if _tn_e != nil { return false }; return tn_n < 40 }() {
		{ // do_test "2.2." + tn
			var i = "0"
			_ = i // suppress unused warning
			for func() bool { i_n, _i_e := strconv.Atoi(i); if _i_e != nil { return false }; return i_n < 100 }() {
				t.Errorf("TODO: %s not implemented in frigolite", "tt 0")
				t.Errorf("TODO: %s not implemented in frigolite", "tt 1")
				t.Errorf("TODO: %s not implemented in frigolite", "tt 2")
				t.Errorf("TODO: %s not implemented in frigolite", "tt 3")
				// incr i 1
				{
					_n, _err := strconv.Atoi(i)
					if _err == nil {
						i = strconv.Itoa(_n + 1)
					}
				}
			}
			r = db.Query(" SELECT max(level) FROM x1_segdir ")
			if r.Error != nil {
				t.Errorf("query error: %v\n  sql: %s", r.Error, " SELECT max(level) FROM x1_segdir ")
			}
		}
		// incr tn 1
		{
			_n, _err := strconv.Atoi(tn)
			if _err == nil {
				tn = strconv.Itoa(_n + 1)
			}
		}
	}
}
