// Code generated by tcl2go; DO NOT EDIT.
//go:build testgen
// +build testgen

package schema

import (
"github.com/pijalu/frigolite"
"os"
"testing"
)

func Test_schema(t *testing.T) {
	if err := os.Chdir(t.TempDir()); err != nil { t.Fatal(err) }
	db, err := frigolite.Open("test.db")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	var _r string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning
	_ = _r   // suppress unused warning
	tcl_nullvalue = "{}" // default NULL rendering

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var STMT string
	_ = STMT // pre-declared from TCL source
	var sql string
	_ = sql // pre-declared from TCL source
	var rc string
	_ = rc // pre-declared from TCL source
	var S string
	_ = S // pre-declared from TCL source
	var Id_ string
	_ = Id_ // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source
	var DB string
	_ = DB // pre-declared from TCL source
	var args string
	_ = args // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	{ // "schema-1.1" (prepare-step internals; SQL side effects only)
		// prepared STMT: SELECT * FROM sqlite_master (bind/step emulation)
		_ = STMT // prepared statement handle
		_res = db.Exec("\n    CREATE TABLE abc(a, b, c);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE TABLE abc(a, b, c);\n  ")
		}
		_res = db.Exec("SELECT * FROM sqlite_master")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "SELECT * FROM sqlite_master")
		}
	}
	{ // "schema-1.2" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $STMT
	}
	{ // "schema-1.3" (prepare-step internals; SQL side effects only)
		// prepared STMT: SELECT * FROM sqlite_master (bind/step emulation)
		_ = STMT // prepared statement handle
		_res = db.Exec("\n    DROP TABLE abc;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    DROP TABLE abc;\n  ")
		}
		_res = db.Exec("SELECT * FROM sqlite_master")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "SELECT * FROM sqlite_master")
		}
	}
	{ // "schema-1.4" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $STMT
	}
	{ // "schema-2.1" (prepare-step internals; SQL side effects only)
		// prepared STMT: SELECT * FROM sqlite_master (bind/step emulation)
		_ = STMT // prepared statement handle
		_res = db.Exec("\n      CREATE VIEW v1 AS SELECT * FROM sqlite_master;\n    ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      CREATE VIEW v1 AS SELECT * FROM sqlite_master;\n    ")
		}
		_res = db.Exec("SELECT * FROM sqlite_master")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "SELECT * FROM sqlite_master")
		}
	}
	{ // "schema-2.2" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $STMT
	}
	{ // "schema-2.3" (prepare-step internals; SQL side effects only)
		// prepared STMT: SELECT * FROM sqlite_master (bind/step emulation)
		_ = STMT // prepared statement handle
		_res = db.Exec("\n      DROP VIEW v1;\n    ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      DROP VIEW v1;\n    ")
		}
		_res = db.Exec("SELECT * FROM sqlite_master")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "SELECT * FROM sqlite_master")
		}
	}
	{ // "schema-2.4" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $STMT
	}
	{ // "schema-3.1" (prepare-step internals; SQL side effects only)
		_res = db.Exec("\n      CREATE TABLE abc(a, b, c);\n    ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      CREATE TABLE abc(a, b, c);\n    ")
		}
		// prepared STMT: SELECT * FROM sqlite_master (bind/step emulation)
		_ = STMT // prepared statement handle
		_res = db.Exec("\n      CREATE TRIGGER abc_trig AFTER INSERT ON abc BEGIN\n        SELECT 1, 2, 3;\n      END;\n    ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      CREATE TRIGGER abc_trig AFTER INSERT ON abc BEGIN\n        SELECT 1, 2, 3;\n      END;\n    ")
		}
		_res = db.Exec("SELECT * FROM sqlite_master")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "SELECT * FROM sqlite_master")
		}
	}
	{ // "schema-3.2" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $STMT
	}
	{ // "schema-3.3" (prepare-step internals; SQL side effects only)
		// prepared STMT: SELECT * FROM sqlite_master (bind/step emulation)
		_ = STMT // prepared statement handle
		_res = db.Exec("\n      DROP TRIGGER abc_trig;\n    ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      DROP TRIGGER abc_trig;\n    ")
		}
		_res = db.Exec("SELECT * FROM sqlite_master")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "SELECT * FROM sqlite_master")
		}
	}
	{ // "schema-3.4" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $STMT
	}
	{ // "schema-4.1" (prepare-step internals; SQL side effects only)
		_res = db.Exec("\n    CREATE TABLE abc(a, b, c);\n  ")
		_ = _res // catchsql
		// prepared STMT: SELECT * FROM sqlite_master (bind/step emulation)
		_ = STMT // prepared statement handle
		_res = db.Exec("\n    CREATE INDEX abc_index ON abc(a);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE INDEX abc_index ON abc(a);\n  ")
		}
		_res = db.Exec("SELECT * FROM sqlite_master")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "SELECT * FROM sqlite_master")
		}
	}
	{ // "schema-4.2" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $STMT
	}
	{ // "schema-4.3" (prepare-step internals; SQL side effects only)
		// prepared STMT: SELECT * FROM sqlite_master (bind/step emulation)
		_ = STMT // prepared statement handle
		_res = db.Exec("\n    DROP INDEX abc_index;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    DROP INDEX abc_index;\n  ")
		}
		_res = db.Exec("SELECT * FROM sqlite_master")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "SELECT * FROM sqlite_master")
		}
	}
	{ // "schema-4.4" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $STMT
	}
	{ // "schema-5.1" (prepare-step internals; SQL side effects only)
		sql = "SELECT * FROM abc;"
		_ = sql // suppress unused warning
		// prepared STMT: $sql (bind/step emulation)
		_ = STMT // prepared statement handle
		_res = db.Exec("\n      ATTACH 'test2.db' AS aux;\n    ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      ATTACH 'test2.db' AS aux;\n    ")
		}
		_res = db.Exec("$sql")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "$sql")
		}
	}
	{ // do_test "schema-5.2"
		// sqlite3_reset $STMT
	}
	{ // "schema-5.3" (prepare-step internals; SQL side effects only)
		_res = db.Exec("\n      DETACH aux;\n    ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      DETACH aux;\n    ")
		}
		_res = db.Exec("$sql")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "$sql")
		}
	}
	{ // "schema-5.4" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $STMT
	}
	{ // "schema-6.1" (prepare-step internals; SQL side effects only)
		sql = "SELECT * FROM abc;"
		_ = sql // suppress unused warning
		// prepared STMT: $sql (bind/step emulation)
		_ = STMT // prepared statement handle
		// db function hello_function (variable-reader, inlined)
		db.RegisterFunction("hello_function", func(args []interface{}) (interface{}, error) { return nil, nil }, 0, -1)
		_res = db.Exec("$sql")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "$sql")
		}
	}
	{ // do_test "schema-6.2"
		// sqlite3_reset $STMT
	}
	{ // "schema-6.3" (prepare-step internals; SQL side effects only)
		// sqlite_delete_function $::DB hello_function (unsupported command, not transpiled)
		_res = db.Exec("$sql")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "$sql")
		}
	}
	{ // "schema-6.4" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $STMT
	}
	{ // "schema-7.1" (prepare-step internals; SQL side effects only)
		sql = "SELECT * FROM abc;"
		_ = sql // suppress unused warning
		// prepared STMT: $sql (bind/step emulation)
		_ = STMT // prepared statement handle
		// add_test_collate $::DB 1 1 1 (unsupported command, not transpiled)
		_res = db.Exec("$sql")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "$sql")
		}
	}
	{ // do_test "schema-7.2"
		// sqlite3_reset $STMT
	}
	{ // "schema-7.3" (prepare-step internals; SQL side effects only)
		// add_test_collate $::DB 0 0 0 (unsupported command, not transpiled)
		_res = db.Exec("$sql")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "$sql")
		}
	}
	{ // "schema-7.4" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $STMT
	}
	// proc definition (not transpiled)
	{ // "schema-8.1" (prepare-step internals; SQL side effects only)
		// prepared STMT: SELECT * FROM sqlite_master (bind/step emulation)
		_ = STMT // prepared statement handle
		_res = db.Exec("SELECT * FROM sqlite_master")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "SELECT * FROM sqlite_master")
		}
	}
	{ // "schema-8.2" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $STMT
	}
	{ // "schema-8.11" (prepare-step internals; SQL side effects only)
		// prepared STMT: SELECT * FROM sqlite_master (bind/step emulation)
		_ = STMT // prepared statement handle
		_res = db.Exec("SELECT * FROM sqlite_master")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "SELECT * FROM sqlite_master")
		}
	}
	{ // "schema-8.12" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $STMT
	}
	{ // do_test "schema-9.1"
		db2 = db // sqlite3 db2 test.db: alias to main in-memory db
		_ = db2
		_res = db.Exec("\n    DROP TABLE abc;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    DROP TABLE abc;\n  ")
		}
		_ = db2 // close db2: aliased to db, no-op
		_res = db.Exec("\n    SELECT * FROM abc;\n  ")
		_ = _res // catchsql
	}
	_res = db.Exec("\n  CREATE TABLE abc(a, b, c);\n")
	if _res.Error != nil {
		t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE abc(a, b, c);\n")
	}
	{ // do_test "schema-9.2"
		_res = db.Exec("\n      CREATE VIEW abcview AS SELECT * FROM abc;\n    ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      CREATE VIEW abcview AS SELECT * FROM abc;\n    ")
		}
		db2 = db // sqlite3 db2 test.db: alias to main in-memory db
		_ = db2
		_res = db.Exec("\n      DROP VIEW abcview;\n    ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n      DROP VIEW abcview;\n    ")
		}
		_ = db2 // close db2: aliased to db, no-op
		_res = db.Exec("\n      SELECT * FROM abcview;\n    ")
		_ = _res // catchsql
	}
	{ // "schema-10.1" (prepare-step internals; SQL side effects only)
		_res = db.Exec("\n    INSERT INTO abc VALUES(1, 2, 3);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    INSERT INTO abc VALUES(1, 2, 3);\n  ")
		}
		sql = "SELECT * FROM abc"
		_ = sql // suppress unused warning
		// prepared STMT: $sql (bind/step emulation)
		_ = STMT // prepared statement handle
		_res = db.Exec("$sql")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "$sql")
		}
	}
	{ // do_test "schema-10.2"
		_res = db.Exec("\n    CREATE TABLE t2(a, b, c);\n  ")
		_ = _res // catchsql
	}
	{ // "schema-10.3" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $STMT
	}
	{ // do_test "schema-10.4"
		db2 = db // sqlite3 db2 test.db: alias to main in-memory db
		_ = db2
		r = db.Query("\n    SELECT * FROM abc\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT * FROM abc\n  ")
		}
	}
	{ // do_test "schema-10.5"
		_ = db2 // close db2: aliased to db, no-op
	}
	{ // "schema-11.1" (prepare-step internals; SQL side effects only)
		// db function tstfunc (variable-reader, inlined)
		db.RegisterFunction("tstfunc", func(args []interface{}) (interface{}, error) { return nil, nil }, 0, -1)
		sql = "SELECT * FROM abc"
		_ = sql // suppress unused warning
		// prepared STMT: $sql (bind/step emulation)
		_ = STMT // prepared statement handle
		_res = db.Exec("$sql")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "$sql")
		}
	}
	{ // do_test "schema-11.2"
		// sqlite_delete_function $::DB tstfunc (unsupported command, not transpiled)
	}
	{ // do_test "schema-11.3"
	_ = rc // suppress unused warning
	_ = msg // suppress unused warning
		{ // catch block
			var _catchErr error
			// db function tstfunc (variable-reader, inlined)
			db.RegisterFunction("tstfunc", func(args []interface{}) (interface{}, error) { return nil, nil }, 0, -1)
			if _catchErr != nil {
				rc = "1"
				msg = _catchErr.Error()
			} else {
				rc = "0"
				msg = ""
			}
		}
		_list := tclList([]string{rc, msg})
		_ = _list
	}
	{ // "schema-11.4" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $STMT
	}
	{ // "schema-11.5" (prepare-step internals; SQL side effects only)
		// db collate tstcollate (not transpiled)
		sql = "SELECT * FROM abc"
		_ = sql // suppress unused warning
		// prepared STMT: $sql (bind/step emulation)
		_ = STMT // prepared statement handle
		_res = db.Exec("$sql")
		if _res.Error != nil {
			t.Errorf("prepared-statement exec error: %v\n  sql: %s", _res.Error, "$sql")
		}
	}
	{ // do_test "schema-11.6"
		db.UnregisterCollation("tstcollate")
	}
	{ // do_test "schema-11.7"
	_ = rc // suppress unused warning
	_ = msg // suppress unused warning
		{ // catch block
			var _catchErr error
			// db collate tstcollate (not transpiled)
			if _catchErr != nil {
				rc = "1"
				msg = _catchErr.Error()
			} else {
				rc = "0"
				msg = ""
			}
		}
		_list := tclList([]string{rc, msg})
		_ = _list
	}
	{ // "schema-11.8" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $STMT
	}
	{ // do_test "schema-12.1"
		_res = db.Exec("\n    BEGIN;\n    CREATE TABLE t3(a, b, c);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    BEGIN;\n    CREATE TABLE t3(a, b, c);\n  ")
		}
		// prepared STMT: CREATE TABLE t4(a,b,c) (bind/step emulation)
		_ = STMT // prepared statement handle
		_res = db.Exec("\n    ROLLBACK;\n    CREATE TABLE t4(a, b, c);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    ROLLBACK;\n    CREATE TABLE t4(a, b, c);\n  ")
		}
		_list := tclList([]string{"SQLITE_ROW", ""})
		_ = _list
	}
	{ // "schema-13.1" (prepare-step internals; SQL side effects only)
		_ = S // prepared statement handle
		// db function hello (variable-reader, inlined)
		db.RegisterFunction("hello", func(args []interface{}) (interface{}, error) { return nil, nil }, 0, -1)
		// db function hello (variable-reader, inlined)
		db.RegisterFunction("hello", func(args []interface{}) (interface{}, error) { return nil, nil }, 0, -1)
		// proc definition (not transpiled)
		// sqlite3_step $S (unknown prepared statement)
	}
	{ // "schema-13.2" (prepare-step internals; SQL side effects only)
		// sqlite3_step $S (unknown prepared statement)
	}
	{ // "schema-13.3" (prepare-step internals; SQL side effects only)
		// sqlite3_finalize $S
	}
}
