// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2026 Pierre Poissinger
//
// Package parse implements an LALR(1) SQL parser using go-lemon generated
// parse tables from SQLite's grammar.
//
// This file is the rule-dispatch hub. The go-lemon engine reduces each
// grammar rule to a rule number (an index into the shipped parse tables,
// sql_tables.go yyRuleInfoLhs/yyRuleInfoNRhs); handleRule looks that number
// up in ruleHandlers and runs the handler, which pops the RHS semantic
// values off the parser stack (getRHS) and returns the LHS semantic value.
// Rules absent from the map fall through to handleRuleFallback, which
// passes the first RHS value through unchanged.
//
// The handler FUNCTIONS live in the functional files parser_rules_*.go
// (statement dispatch, DDL, table constraints, SELECT, expressions,
// operators, window, DML, triggers, PRAGMA, name/list helpers); the rule
// NUMBER constants live in parser_ruleids.go. Adding a rule = one rid
// constant + one handler + one map entry (OCP).
//
// Note: rule 257 shares rule 255's handler (identical PRAGMA productions
// differing only in the EQ/LP spelling of the value).

package parse

// ruleHandlers dispatches each grammar rule number to its action handler.
// Keys are rid* constants defined in parser_ruleids.go.
var ruleHandlers = map[int]ruleHandler{
	ridExplainPlain:              ruleExplainPlain,
	ridExplainExplainQueryPlan:   ruleExplainExplainQueryPlan,
	ridCmdxCmd:                   ruleCmdxCmd,
	ridCmdBeginTranstypeTransOpt: ruleCmdBeginTranstypeTransOpt,
	ridTranstypeEmpty:            ruleTranstypeEmpty,
	ridCmdCommitEndTransOpt:      ruleCmdCommitEndTransOpt,
	ridCmdRollbackTransOpt:       ruleCmdRollbackTransOpt,
	ridCreateTableCreatekwTempTableIfnotexistsNmDbnm: ruleCreateTableCreatekwTempTableIfnotexistsNmDbnm,
	ridCreatekw:               ruleCreatekw,
	ridIfnotexists:            ruleIfnotexists,
	ridIfnotexistsIfNotExists: ruleIfnotexistsIfNotExists,
	ridTempTemp:               ruleTempTemp,
	ridTemp:                   ruleTemp,
	ridCreateTableArgsLpColumnlistConslistOptRpTableOptionSet: ruleCreateTableArgsLpColumnlistConslistOptRpTableOptionSet,
	ridCreateTableArgsAsSelect:                                ruleCreateTableArgsAsSelect,
	ridTableOptionSet:                                         ruleTableOptionSet,
	ridTableOptionSetList:                                     ruleTableOptionSetList,
	ridTableOptionWithoutNm:                                   ruleTableOptionWithoutNm,
	ridTableOptionNm:                                          ruleTableOptionNm,
	ridColumnnameNmTypemod:                                    ruleColumnnameNmTypemod,
	ridTypetoken:                                              ruleTypetoken,
	ridTypetokenTypenameLpSignedRp:                            ruleTypetokenTypenameLpSignedRp,
	ridTypetokenTypenameLpSignedCommaSignedRp:                 ruleTypetokenTypenameLpSignedCommaSignedRp,
	ridTypenameTypenameIdMultiWordTypeNames:                   ruleTypenameTypenameIdMultiWordTypeNames,
	ridCconsConstraintNm:                                      ruleCconsConstraintNm,
	ridCconsDefaultScantokTerm:                                ruleCconsDefaultScantokTerm,
	ridCconsDefaultLpExprRp:                                   ruleCconsDefaultLpExprRp,
	ridCconsDefaultPlusScantokTerm:                            ruleCconsDefaultPlusScantokTerm,
	ridCconsDefaultMinusScantokTerm:                           ruleCconsDefaultMinusScantokTerm,
	ridCconsDefaultScantokId:                                  ruleCconsDefaultScantokId,
	ridCconsNotNullOnconf:                                     ruleCconsNotNullOnconf,
	ridCconsPrimaryKeySortorderOnconfAutoinc:                  ruleCconsPrimaryKeySortorderOnconfAutoinc,
	ridCconsUniqueOnconf:                                      ruleCconsUniqueOnconf,
	ridCconsCheckLpExprRp:                                     ruleCconsCheckLpExprRp,
	ridCconsReferencesNmEidlistOptRefargs:                     ruleCconsReferencesNmEidlistOptRefargs,
	ridCconsDeferSubclause:                                    ruleCconsDeferSubclause,
	ridCconsCollateIds:                                        ruleCconsCollateIds,
	ridGeneratedLpExprRp:                                      ruleGeneratedLpExprRp,
	ridGeneratedLpExprRpId:                                    ruleGeneratedLpExprRpId,
	ridAutoinc:                                                ruleAutoinc,
	ridAutoincAutoincr:                                        ruleAutoincAutoincr,
	ridRefargsEmpty:                                           ruleRefargsEmpty,
	ridRefargsRefargsRefarg:                                   ruleRefargsRefargsRefarg,
	ridRefargMatchNm:                                          ruleRefargMatchNm,
	ridRefargOnInsertRefact:                                   ruleRefargOnInsertRefact,
	ridRefargOnDeleteRefact:                                   ruleRefargOnDeleteRefact,
	ridRefargOnUpdateRefact:                                   ruleRefargOnUpdateRefact,
	ridRefactSetNull:                                          ruleRefactSetNull,
	ridRefactSetDefault:                                       ruleRefactSetDefault,
	ridRefactCascade:                                          ruleRefactCascade,
	ridRefactRestrict:                                         ruleRefactRestrict,
	ridRefactNoAction:                                         ruleRefactNoAction,
	ridDeferSubclauseDeferrableInitDeferredPredOpt:            ruleDeferSubclauseDeferrableInitDeferredPredOpt,
	ridInitDeferredPredOptEmpty:                               ruleInitDeferredPredOptEmpty,
	ridInitDeferredPredOptInitiallyDeferred:                   ruleInitDeferredPredOptInitiallyDeferred,
	ridInitDeferredPredOptInitiallyImmediate:                  ruleInitDeferredPredOptInitiallyImmediate,
	ridConslistOptEmpty:                                       ruleConslistOptEmpty,
	ridTconscommaComma:                                        ruleTconscommaComma,
	ridTconsConstraintNm:                                      ruleTconsConstraintNm,
	ridTconsPrimaryKeyLpSortlistAutoincRpOnconf:               ruleTconsPrimaryKeyLpSortlistAutoincRpOnconf,
	ridTconsUniqueLpSortlistRpOnconf:                          ruleTconsUniqueLpSortlistRpOnconf,
	ridTconsCheckOnconf:                                       ruleTconsCheckOnconf,
	ridTconsForeignKey:                                        ruleTconsForeignKey,
	ridDeferSubclauseOpt:                                      ruleDeferSubclauseOpt,
	ridOnconf:                                                 ruleOnconf,
	ridOnconfOnConflictOrconf:                                 ruleOnconfOnConflictOrconf,
	ridOrconf:                                                 ruleOrconf,
	ridOrconfOrResolvel:                                       ruleOrconfOrResolvel,
	ridResolvelIgnore:                                         ruleResolvelIgnore,
	ridResolvelReplace:                                        ruleResolvelReplace,
	ridCmdDropTableIfexistsFullname:                           ruleCmdDropTableIfexistsFullname,
	ridIfexistsIfExists:                                       ruleIfexistsIfExists,
	ridIfexists:                                               ruleIfexists,
	ridCmdCreateView:                                          ruleCmdCreateView,
	ridCmdDropViewIfexistsFullname:                            ruleCmdDropViewIfexistsFullname,
	ridCmdSelect:                                              ruleCmdSelect,
	ridSelectWithWqlistSelectnowith:                           ruleSelectWithWqlistSelectnowith,
	ridSelectWithRecursiveWqlistSelectnowith:                  ruleSelectWithRecursiveWqlistSelectnowith,
	ridSelectSelectnowith:                                     ruleSelectSelectnowith,
	ridSelectnowithSelectnowithMultiselectOpOneselect:         ruleSelectnowithSelectnowithMultiselectOpOneselect,
	ridMultiselectOpUnion:                                     ruleMultiselectOpUnion,
	ridMultiselectOpUnionAll:                                  ruleMultiselectOpUnionAll,
	ridMultiselectOpExceptIntersect:                           ruleMultiselectOpExceptIntersect,
	ridOneselectCore:                                          ruleOneselectCore,
	ridOneselectCoreWindow:                                    ruleOneselectCoreWindow,
	ridValuesValuesLpNexprlistRp:                              ruleValuesValuesLpNexprlistRp,
	ridOneselectMvalues:                                       ruleOneselectMvalues,
	ridMvaluesValuesCommaLpNexprlistRp:                        ruleMvaluesValuesCommaLpNexprlistRp,
	ridMvaluesMvaluesCommaLpNexprlistRp:                       ruleMvaluesMvaluesCommaLpNexprlistRp,
	ridDistinctDistinct:                                       ruleDistinctDistinct,
	ridDistinctAll:                                            ruleDistinctAll,
	ridDistinct:                                               ruleDistinct,
	ridSelcollistSclpCommaScanptExprAs:                        ruleSelcollistSclpCommaScanptExprAs,
	ridSelcollistSclpScanptStar:                               ruleSelcollistSclpScanptStar,
	ridSelcollistSclpScanptNmDotStar:                          ruleSelcollistSclpScanptNmDotStar,
	ridAsAsNm:                                                 ruleAsAsNm,
	ridAs:                                                     ruleAs,
	ridFrom:                                                   ruleFrom,
	ridFromFromSeltablist:                                     ruleFromFromSeltablist,
	ridStlPrefixSeltablistJoinop:                              ruleStlPrefixSeltablistJoinop,
	ridStlPrefixEmpty:                                         ruleStlPrefixEmpty,
	ridSeltablistStlPrefixNmDbnmAsOnUsing:                     ruleSeltablistStlPrefixNmDbnmAsOnUsing,
	ridSeltablistStlPrefixNmDbnmAsIndexedByOnUsing:            ruleSeltablistStlPrefixNmDbnmAsIndexedByOnUsing,
	ridSeltablistStlPrefixNmDbnmLpExprlistRpAsOnUsing:         ruleSeltablistStlPrefixNmDbnmLpExprlistRpAsOnUsing,
	ridSeltablistStlPrefixLpSelectRpAsOnUsing:                 ruleSeltablistStlPrefixLpSelectRpAsOnUsing,
	ridSeltablistStlPrefixLpSeltablistRpAsOnUsing:             ruleSeltablistStlPrefixLpSeltablistRpAsOnUsing,
	ridDbnm:            ruleDbnm,
	ridDbnmDotNm:       ruleDbnmDotNm,
	ridFullnameNm:      ruleFullnameNm,
	ridFullnameNmDotNm: ruleFullnameNmDotNm,
	ridXfullnameNmDotNmSchemaQualifiedTableNameUsedBy: ruleXfullnameNmDotNmSchemaQualifiedTableNameUsedBy,
	ridXfullnameNmAsNm:                         ruleXfullnameNmAsNm,
	ridXfullnameNmDotNmAsNm:                    ruleXfullnameNmDotNmAsNm,
	ridJoinopCommaJoin:                         ruleJoinopCommaJoin,
	ridJoinopJoinKwJoin:                        ruleJoinopJoinKwJoin,
	ridJoinopJoinKwNmJoin:                      ruleJoinopJoinKwNmJoin,
	ridJoinopJoinKwNmNmJoin:                    ruleJoinopJoinKwNmNmJoin,
	ridOnUsingOnExpr:                           ruleOnUsingOnExpr,
	ridOnUsingUsing:                            ruleOnUsingUsing,
	ridOnUsing:                                 ruleOnUsing,
	ridScanpt:                                  ruleScanpt,
	ridIndexedByIndexedByNm:                    ruleIndexedByIndexedByNm,
	ridIndexedByNotIndexed:                     ruleIndexedByNotIndexed,
	ridOrderbyOpt:                              ruleOrderbyOpt,
	ridOrderbyOptOrderBySortlist:               ruleOrderbyOptOrderBySortlist,
	ridSortlistSortlistCommaExprSortorderNulls: ruleSortlistSortlistCommaExprSortorderNulls,
	ridSortlistExprSortorderNulls:              ruleSortlistExprSortorderNulls,
	ridSortorderAsc:                            ruleSortorderAsc,
	ridSortorderDesc:                           ruleSortorderDesc,
	ridSortorder:                               ruleSortorder,
	ridNullsNullsFirst:                         ruleNullsNullsFirst,
	ridNullsNullsLast:                          ruleNullsNullsLast,
	ridNullsEmpty:                              ruleNullsEmpty,
	ridGroupbyOpt:                              ruleGroupbyOpt,
	ridGroupbyOptGroupByNexprlist:              ruleGroupbyOptGroupByNexprlist,
	ridHavingOpt:                               ruleHavingOpt,
	ridHavingOptHavingExpr:                     ruleHavingOptHavingExpr,
	ridLimitOpt:                                ruleLimitOpt,
	ridLimitOptLimitExpr:                       ruleLimitOptLimitExpr,
	ridLimitOptLimitExprOffsetExpr:             ruleLimitOptLimitExprOffsetExpr,
	ridLimitOptLimitExprCommaExpr:              ruleLimitOptLimitExprCommaExpr,
	ridCmdWithDeleteFromXfullnameIndexedOptWhereOptRet: ruleCmdWithDeleteFromXfullnameIndexedOptWhereOptRet,
	ridWhereOpt:                                ruleWhereOpt,
	ridWhereOptWhereExpr:                       ruleWhereOptWhereExpr,
	ridWhereOptRet:                             ruleWhereOptRet,
	ridWhereOptRetWhereExpr:                    ruleWhereOptRetWhereExpr,
	ridWhereOptRetReturningSelcollist:          ruleWhereOptRetReturningSelcollist,
	ridWhereOptRetWhereExprReturningSelcollist: ruleWhereOptRetWhereExprReturningSelcollist,
	ridCmdUpdate:                               ruleCmdUpdate,
	ridSetlistSetlistCommaNmEqExpr:             ruleSetlistSetlistCommaNmEqExpr,
	ridSetlistNmEqExpr:                         ruleSetlistNmEqExpr,
	ridCmdWithInsertCmdIntoXfullnameIdlistOptSelectUpsert:  ruleCmdWithInsertCmdIntoXfullnameIdlistOptSelectUpsert,
	ridCmdInsertDefaultValues:                              ruleCmdInsertDefaultValues,
	ridUpsert:                                              ruleUpsert,
	ridUpsertReturningSelcollist:                           ruleUpsertReturningSelcollist,
	ridUpsertOnConflictLpSortlistRpWhereOpt:                ruleUpsertOnConflictLpSortlistRpWhereOpt,
	ridUpsertOnConflictLpSortlistRpWhereOptDoNothingUpsert: ruleUpsertOnConflictLpSortlistRpWhereOptDoNothingUpsert,
	ridUpsertOnConflictDoNothingReturning:                  ruleUpsertOnConflictDoNothingReturning,
	ridUpsertOnConflictDoUpdateSetSetlistWhereOptReturning: ruleUpsertOnConflictDoUpdateSetSetlistWhereOptReturning,
	ridReturningReturningSelcollist:                        ruleReturningReturningSelcollist,
	ridInsertCmdOrResolvel:                                 ruleInsertCmdOrResolvel,
	ridInsertCmdReplace:                                    ruleInsertCmdReplace,
	ridIdlistOpt:                                           ruleIdlistOpt,
	ridIdlistOptLpIdlistRp:                                 ruleIdlistOptLpIdlistRp,
	ridIdlistIdlistCommaNm:                                 ruleIdlistIdlistCommaNm,
	ridIdlistNm:                                            ruleIdlistNm,
	ridExprLpExprRp:                                        ruleExprLpExprRp,
	ridExprIdIndexedJoinKwColumnReference:                  ruleExprIdIndexedJoinKwColumnReference,
	ridExprNmDotNmSchemaTable:                              ruleExprNmDotNmSchemaTable,
	ridExprNmDotNmDotNmSchemaTableColumn:                   ruleExprNmDotNmDotNmSchemaTableColumn,
	ridTermNullFloatBlob:                                   ruleTermNullFloatBlob,
	ridTermString:                                          ruleTermString,
	ridTermInteger:                                         ruleTermInteger,
	ridExprVariable:                                        ruleExprVariable,
	ridExprExprCollateIdString:                             ruleExprExprCollateIdString,
	ridExprCastLpExprAsTypetokenRp:                         ruleExprCastLpExprAsTypetokenRp,
	ridExprFunc:                                            ruleExprFunc,
	ridExprFuncOrderBy:                                     ruleExprFuncOrderBy,
	ridExprFuncStar:                                        ruleExprFuncStar,
	ridExprFuncFilterOver:                                  ruleExprFuncFilterOver,
	ridExprFuncOrderByFilterOver:                           ruleExprFuncOrderByFilterOver,
	ridExprFuncStarFilterOver:                              ruleExprFuncStarFilterOver,
	ridExprLpExprlistCommaExprRpRowValueVector:             ruleExprLpExprlistCommaExprRpRowValueVector,
	ridExprExprAndExpr:                                     ruleExprExprAndExpr,
	ridExprExprOrExpr:                                      ruleExprExprOrExpr,
	ridExprExprLtGtGeLeExpr:                                ruleExprExprLtGtGeLeExpr,
	ridExprExprEqNeExpr:                                    ruleExprExprEqNeExpr,
	ridExprBitop:                                           ruleExprBitop,
	ridExprExprPlusMinusExpr:                               ruleExprExprPlusMinusExpr,
	ridExprExprStarSlashRemExpr:                            ruleExprExprStarSlashRemExpr,
	ridExprExprConcatExpr:                                  ruleExprExprConcatExpr,
	ridLikeopNot:                                           ruleLikeopNot,
	ridExprLikeop:                                          ruleExprLikeop,
	ridExprLikeopEscape:                                    ruleExprLikeopEscape,
	ridExprIsnullNotnull:                                   ruleExprIsnullNotnull,
	ridExprExprNotLikeopExprNotLikeNotGlob:                 ruleExprExprNotLikeopExprNotLikeNotGlob,
	ridExprExprIsExpr:                                      ruleExprExprIsExpr,
	ridExprExprIsNotExpr:                                   ruleExprExprIsNotExpr,
	ridExprExprIsNotDistinctFromExpr6RhsSymbols:            ruleExprExprIsNotDistinctFromExpr6RhsSymbols,
	ridExprExprIsDistinctFromExpr5RhsSymbols:               ruleExprExprIsDistinctFromExpr5RhsSymbols,
	ridExprNotExpr:                                         ruleExprNotExpr,
	ridExprBitnotExpr:                                      ruleExprBitnotExpr,
	ridExprPlusMinusExprUnary:                              ruleExprPlusMinusExprUnary,
	ridExprPtr:                                             ruleExprPtr,
	ridExprBetween:                                         ruleExprBetween,
	ridInOpIn:                                              ruleInOpIn,
	ridInOpNotIn:                                           ruleInOpNotIn,
	ridExprExprInOpLpExprlistRp:                            ruleExprExprInOpLpExprlistRp,
	ridExprLpSelectRp:                                      ruleExprLpSelectRp,
	ridExprExprInOpLpSelectRp:                              ruleExprExprInOpLpSelectRp,
	ridExprExprInOpNmDbnmParenExprlist:                     ruleExprExprInOpNmDbnmParenExprlist,
	ridExprExistsLpSelectRp:                                ruleExprExistsLpSelectRp,
	ridExprCase:                                            ruleExprCase,
	ridCaseExprlistCaseExprlistWhenExprThenExpr:            ruleCaseExprlistCaseExprlistWhenExprThenExpr,
	ridCaseExprlistWhenExprThenExpr:                        ruleCaseExprlistWhenExprThenExpr,
	ridCaseElseElseExpr:                                    ruleCaseElseElseExpr,
	ridCaseElse:                                            ruleCaseElse,
	ridCaseOperand:                                         ruleCaseOperand,
	ridExprlist:                                            ruleExprlist,
	ridNexprlistNexprlistCommaExpr:                         ruleNexprlistNexprlistCommaExpr,
	ridNexprlistExpr:                                       ruleNexprlistExpr,
	ridParenExprlist:                                       ruleParenExprlist,
	ridParenExprlistLpExprlistRp:                           ruleParenExprlistLpExprlistRp,
	ridCmdCreateIndex:                                      ruleCmdCreateIndex,
	ridEidlistOpt:                                          ruleEidlistOpt,
	ridEidlistOptLpEidlistRp:                               ruleEidlistOptLpEidlistRp,
	ridEidlistEidlistCommaNmCollateSortorder:               ruleEidlistEidlistCommaNmCollateSortorder,
	ridEidlistNmCollateSortorder:                           ruleEidlistNmCollateSortorder,
	ridCmdDropIndexIfexistsFullname:                        ruleCmdDropIndexIfexistsFullname,
	ridCmdVacuumIntoOpt:                                    ruleCmdVacuumIntoOpt,
	ridCmdVacuumNmVinto:                                    ruleCmdVacuumNmVinto,
	ridIntoOpt:                                             ruleIntoOpt,
	ridCmdPragmaNmDbnm:                                     ruleCmdPragmaNmDbnm,
	ridCmdPragmaNmDbnmPragmaValue:                          ruleCmdPragmaNmDbnmPragmaValue,
	ridCmdPragmaNmDbnmLpPragmaValueRp:                      ruleCmdPragmaNmDbnmLpPragmaValueRp,
	ridCmdPragmaNmDbnmEqMinusNum:                           ruleCmdPragmaNmDbnmEqMinusNum,
	ridCmdPragmaNmDbnmLpMinusNumRp:                         ruleCmdPragmaNmDbnmLpPragmaValueRp, // shared with rule 255 (identical action)
	ridMinusNumMinusNumber:                                 ruleMinusNumMinusNumber,
	ridCmdCreatekwTriggerDeclBeginTriggerCmdListEnd:        ruleCmdCreatekwTriggerDeclBeginTriggerCmdListEnd,
	ridTriggerDecl:                                         ruleTriggerDecl,
	ridTriggerCmdListTriggerCmdListTriggerCmdSemi:          ruleTriggerCmdListTriggerCmdListTriggerCmdSemi,
	ridTriggerCmdListTriggerCmdSemi:                        ruleTriggerCmdListTriggerCmdSemi,
	ridTriggerCmdUpdate:                                    ruleTriggerCmdUpdate,
	ridTriggerCmdInsert:                                    ruleTriggerCmdInsert,
	ridTriggerCmdDeleteFromXfullnameTridxbyWhereOptScanpt:  ruleTriggerCmdDeleteFromXfullnameTridxbyWhereOptScanpt,
	ridTriggerCmdScanptSelectScanpt:                        ruleTriggerCmdScanptSelectScanpt,
	ridExprRaiseLpIgnoreRp:                                 ruleExprRaiseLpIgnoreRp,
	ridExprRaise:                                           ruleExprRaise,
	ridRaisetypeRollback:                                   ruleRaisetypeRollback,
	ridRaisetypeAbort:                                      ruleRaisetypeAbort,
	ridRaisetypeFail:                                       ruleRaisetypeFail,
	ridCmdDropTriggerIfexistsFullname:                      ruleCmdDropTriggerIfexistsFullname,
	ridCmdAttachDatabaseKwOptExprAsExprKeyOpt:              ruleCmdAttachDatabaseKwOptExprAsExprKeyOpt,
	ridCmdDetachDatabaseKwOptExpr:                          ruleCmdDetachDatabaseKwOptExpr,
	ridCmdReindex:                                          ruleCmdReindex,
	ridCmdReindexNmDbnmReindexWithAnOptionalSchema:         ruleCmdReindexNmDbnmReindexWithAnOptionalSchema,
	ridCmdAnalyze:                                          ruleCmdAnalyze,
	ridCmdAnalyzeNmDbnm:                                    ruleCmdAnalyzeNmDbnm,
	ridCmdAlterTableFullnameRenameToNm:                     ruleCmdAlterTableFullnameRenameToNm,
	ridCmdAlterAddCarglist:                                 ruleCmdAlterAddCarglist,
	ridAlterAddAlterTableFullnameAddKwcolumnOptNmTypetoken: ruleAlterAddAlterTableFullnameAddKwcolumnOptNmTypetoken,
	ridCmdAlterTableFullnameDropKwcolumnOptNm:              ruleCmdAlterTableFullnameDropKwcolumnOptNm,
	ridCmdAlterTableFullnameRenameKwcolumnOptNmToNm:        ruleCmdAlterTableFullnameRenameKwcolumnOptNmToNm,
	ridCmdAlterDropConstraint:                              ruleCmdAlterDropConstraint,
	ridCmdAlterColumnDropNotNull:                           ruleCmdAlterColumnDropNotNull,
	ridCmdAlterColumnSetNotNull:                            ruleCmdAlterColumnSetNotNull,
	ridCmdAlterAddConstraintCheck:                          ruleCmdAlterAddConstraintCheck,
	ridCmdAlterTableFullnameAddCheckLpExprRpOnconf:         ruleCmdAlterTableFullnameAddCheckLpExprRpOnconf,
	ridCmdCreateVtab:                                       ruleCmdCreateVtab,
	ridCmdCreateVtabLpVtabarglistRp:                        ruleCmdCreateVtabLpVtabarglistRp,
	ridCreateVtab:                                          ruleCreateVtab,
	ridVtabargEmpty:                                        ruleVtabargEmpty,
	ridTokenIdASingleVirtualTableArgumentToken:             ruleTokenIdASingleVirtualTableArgumentToken,
	ridWithWithWqlist:                                      ruleWithWithWqlist,
	ridWithWithRecursiveWqlist:                             ruleWithWithRecursiveWqlist,
	ridWqasAs:                                              ruleWqasAs,
	ridWqitemWithnmEidlistOptWqasLpSelectRp:                ruleWqitemWithnmEidlistOptWqasLpSelectRp,
	ridWithnmNm:                                            ruleWithnmNm,
	ridWqlistWqitem:                                        ruleWqlistWqitem,
	ridWqlistListCommaWqitem:                               ruleWqlistListCommaWqitem,
	ridWindowdefnListWindowdefnListCommaWindowdefn:         ruleWindowdefnListWindowdefnListCommaWindowdefn,
	ridWindowdefnNmAsLpWindowRp:                            ruleWindowdefnNmAsLpWindowRp,
	ridWindowPartitionByNexprlistOrderbyOptFrameOpt:        ruleWindowPartitionByNexprlistOrderbyOptFrameOpt,
	ridWindowNmPartitionByNexprlistOrderbyOptFrameOpt:      ruleWindowNmPartitionByNexprlistOrderbyOptFrameOpt,
	ridWindowOrderBySortlistFrameOpt:                       ruleWindowOrderBySortlistFrameOpt,
	ridWindowNmOrderBySortlistFrameOpt:                     ruleWindowNmOrderBySortlistFrameOpt,
	ridWindowNmFrameOpt:                                    ruleWindowNmFrameOpt,
	ridFrameOpt:                                            ruleFrameOpt,
	ridFrameOptRangeOrRowsFrameBoundSFrameExcludeOpt:       ruleFrameOptRangeOrRowsFrameBoundSFrameExcludeOpt,
	ridFrameOptBetween:                                     ruleFrameOptBetween,
	ridRangeOrRowsRangeRowsGroups:                          ruleRangeOrRowsRangeRowsGroups,
	ridFrameBoundSFrameBound:                               ruleFrameBoundSFrameBound,
	ridFrameBoundSUnboundedPreceding:                       ruleFrameBoundSUnboundedPreceding,
	ridFrameBoundEFrameBound:                               ruleFrameBoundEFrameBound,
	ridFrameBoundEUnboundedFollowing:                       ruleFrameBoundEUnboundedFollowing,
	ridFrameBoundExprPrecedingFollowing:                    ruleFrameBoundExprPrecedingFollowing,
	ridFrameBoundCurrentRow:                                ruleFrameBoundCurrentRow,
	ridFrameExcludeOpt:                                     ruleFrameExcludeOpt,
	ridFrameExcludeOptExcludeFrameExclude:                  ruleFrameExcludeOptExcludeFrameExclude,
	ridFrameExcludeNoOthers:                                ruleFrameExcludeNoOthers,
	ridFrameExcludeCurrentRow:                              ruleFrameExcludeCurrentRow,
	ridFrameExcludeGroupTies:                               ruleFrameExcludeGroupTies,
	ridWindowClause:                                        ruleWindowClause,
	ridFilterOverFilterClauseOverClause:                    ruleFilterOverFilterClauseOverClause,
	ridFilterOverOverClause:                                ruleFilterOverOverClause,
	ridFilterOverFilterClause:                              ruleFilterOverFilterClause,
	ridOverClauseOverLpWindowRp:                            ruleOverClauseOverLpWindowRp,
	ridOverClauseOverNm:                                    ruleOverClauseOverNm,
	ridFilterClauseFilterLpWhereExprRp:                     ruleFilterClauseFilterLpWhereExprRp,
	ridInputCmdlist:                                        ruleInputCmdlist,
	ridCmdlistCmdlistEcmd:                                  ruleCmdlistCmdlistEcmd,
	ridCmdlistEcmd:                                         ruleCmdlistEcmd,
	ridEcmdSemi:                                            ruleEcmdSemi,
	ridEcmdCmdxSemi:                                        ruleEcmdCmdxSemi,
	ridEcmdExplainCmdxSemiExplain:                          ruleEcmdExplainCmdxSemiExplain,
	ridTransOpt:                                            ruleTransOpt,
	ridTransOptTransaction:                                 ruleTransOptTransaction,
	ridCmdCreateTableCreateTableArgs:                       ruleCmdCreateTableCreateTableArgs,
	ridTableOptionSetTableOption:                           ruleTableOptionSetTableOption,
	ridColumnlistColumnlistCommaColumnnameCarglist:         ruleColumnlistColumnlistCommaColumnnameCarglist,
	ridColumnlistColumnnameCarglist:                        ruleColumnlistColumnnameCarglist,
	ridNmIdIndexedJoinKw:                                   ruleNmIdIndexedJoinKw,
	ridNmString:                                            ruleNmString,
	ridTypetokenTypename:                                   ruleTypetokenTypename,
	ridTypenameIdString:                                    ruleTypenameIdString,
	ridCarglistCarglistCcons:                               ruleCarglistCarglistCcons,
	ridCarglist:                                            ruleCarglist,
	ridCconsAsGenerated:                                    ruleCconsAsGenerated,
	ridCconsGeneratedAlwaysAsGenerated:                     ruleCconsGeneratedAlwaysAsGenerated,
	ridCconsAsGeneratedAlt:                                 ruleCconsAsGeneratedAlt,
	ridConslistOptCommaConslist:                            ruleConslistOptCommaConslist,
	ridConslistListTconscommaTcons:                         ruleConslistListTconscommaTcons,
	ridConslistTcons:                                       ruleConslistTcons,
	ridTconscommaEmpty:                                     ruleTconscommaEmpty,
	ridResolvelRollbackAbortFail:                           ruleResolvelRollbackAbortFail,
	ridSelectnowithOneselect:                               ruleSelectnowithOneselect,
	ridOneselectValues:                                     ruleOneselectValues,
	ridAsIdString:                                          ruleAsIdString,
	ridReturningEmpty:                                      ruleReturningEmpty,
	ridExprTerm:                                            ruleExprTerm,
	ridLikeopKeywords:                                      ruleLikeopKeywords,
	ridExprlistExpr:                                        ruleExprlistExpr,
	ridPlusNumIntegerFloat:                                 rulePlusNumIntegerFloat,
	ridVtabarglistVtabarg:                                  ruleVtabarglistVtabarg,
	ridVtabarglistVtabarglistCommaVtabarg:                  ruleVtabarglistVtabarglistCommaVtabarg,
	ridVtabargVtabargToken:                                 ruleVtabargVtabargToken,
	ridWith:                                                ruleWith,
	ridWindowdefnListWindowdefn:                            ruleWindowdefnListWindowdefn,
	ridWindowFrameOpt:                                      ruleWindowFrameOpt,
}

// ruleHandler implements the action for a single grammar rule.
type ruleHandler func(ruleNo int, p *Parser) interface{}

// ruleDispatch is ruleHandlers in array form, built once at init: the
// parser reduces hundreds of times per statement and the hot path cannot
// afford a map lookup per reduce. The map above stays the readable,
// OCP-friendly source of truth (rid* keys); this slice is derived from it.
var ruleDispatch = func() []ruleHandler {
	d := make([]ruleHandler, len(yyRuleInfoNRhs))
	for no, h := range ruleHandlers {
		if no >= 0 && no < len(d) {
			d[no] = h
		}
	}
	return d
}()

// handleRule implements the action code for each grammar rule.
// Returns the semantic value for the LHS symbol.
func handleRule(ruleNo int, p *Parser, lookahead int, lookaheadToken interface{}) interface{} {
	if ruleNo >= 0 && ruleNo < len(ruleDispatch) {
		if h := ruleDispatch[ruleNo]; h != nil {
			return h(ruleNo, p)
		}
	}
	return handleRuleFallback(ruleNo, p)
}

func getRHS(p *Parser, ruleNo, n int) interface{} {
	t := p.tables
	size := -t.RuleInfoNRhs[ruleNo]
	return p.stack[p.pos-size+n].Minor
}

func handleRuleFallback(ruleNo int, p *Parser) interface{} {
	if p.pos >= 1 {
		t := p.tables
		if ruleNo < len(t.RuleInfoNRhs) && t.RuleInfoNRhs[ruleNo] != 0 {
			return getRHS(p, ruleNo, 1)
		}
	}
	return nil
}
