// Code generated by tcl2go; DO NOT EDIT.
package interrupt

import (
"github.com/pijalu/frigolite"
"strconv"
"testing"
)

func Test_interrupt(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	// set testdir: test directory (not used in Go test context)
	var DB = "sqlite3_connection_pointer db"
	_ = DB // suppress unused warning
	// proc definition (not transpiled)
	{ // do_test "interrupt-1.1"
		r = db.Query("\n    CREATE TABLE t1(a,b);\n    SELECT name FROM sqlite_master;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    CREATE TABLE t1(a,b);\n    SELECT name FROM sqlite_master;\n  ")
		}
	}
	t.Errorf("TODO: %s not implemented in frigolite", "interrupt_test interrupt-1.2 {DROP TABLE t1} {}")
	{ // do_test "interrupt-1.3"
		r = db.Query("\n    SELECT name FROM sqlite_master;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT name FROM sqlite_master;\n  ")
		}
	}
	_res = db.Exec("PRAGMA integrity_check")
	if _res.Error != nil { t.Errorf("integrity check: %v", _res.Error) }
	{ // do_test "interrrupt-2.1"
		r = db.Query("\n    BEGIN;\n    CREATE TABLE t1(a,b);\n    INSERT INTO t1 VALUES(1,randstr(300,400));\n    INSERT INTO t1 SELECT a+1, randstr(300,400) FROM t1;\n    INSERT INTO t1 SELECT a+2, a || '-' || b FROM t1;\n    INSERT INTO t1 SELECT a+4, a || '-' || b FROM t1;\n    INSERT INTO t1 SELECT a+8, a || '-' || b FROM t1;\n    INSERT INTO t1 SELECT a+16, a || '-' || b FROM t1;\n    INSERT INTO t1 SELECT a+32, a || '-' || b FROM t1;\n    COMMIT;\n    UPDATE t1 SET b=substr(b,-5,5);\n    SELECT count(*) from t1;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    BEGIN;\n    CREATE TABLE t1(a,b);\n    INSERT INTO t1 VALUES(1,randstr(300,400));\n    INSERT INTO t1 SELECT a+1, randstr(300,400) FROM t1;\n    INSERT INTO t1 SELECT a+2, a || '-' || b FROM t1;\n    INSERT INTO t1 SELECT a+4, a || '-' || b FROM t1;\n    INSERT INTO t1 SELECT a+8, a || '-' || b FROM t1;\n    INSERT INTO t1 SELECT a+16, a || '-' || b FROM t1;\n    INSERT INTO t1 SELECT a+32, a || '-' || b FROM t1;\n    COMMIT;\n    UPDATE t1 SET b=substr(b,-5,5);\n    SELECT count(*) from t1;\n  ")
		}
	}
	var origsize = "file size test.db"
	_ = origsize // suppress unused warning
	var cksum = "db eval {SELECT md5sum(a || b) FROM t1}"
	_ = cksum // suppress unused warning
	{ // do_test "interrupt-2.3"
		r = db.Query("\n    SELECT md5sum(a || b) FROM t1;\n  ")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "\n    SELECT md5sum(a || b) FROM t1;\n  ")
		}
	}
	_res = db.Exec("PRAGMA integrity_check")
	if _res.Error != nil { t.Errorf("integrity check: %v", _res.Error) }
	{ // do_test "interrupt-2.7"
		t.Errorf("TODO: %s not implemented in frigolite", "sqlite3_is_interrupted $DB")
	}
	_res = db.Exec("\n  CREATE TABLE t2(a,b,c);\n  INSERT INTO t2 SELECT round(a/10), randstr(50,80), randstr(50,60) FROM t1;\n")
	if _res.Error != nil {
		t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE t2(a,b,c);\n  INSERT INTO t2 SELECT round(a/10), randstr(50,80), randstr(50,60) FROM t1;\n")
	}
	var sql = "\n  SELECT max(min(b,c)), min(max(b,c)), a FROM t2 GROUP BY a ORDER BY a;\n"
	_ = sql // suppress unused warning
	var sqlite_interrupt_count = "1000000"
	_ = sqlite_interrupt_count // suppress unused warning
	_res = db.Exec(sql)
	if _res.Error != nil {
		t.Errorf("exec error: %v\n  sql: %s", _res.Error, sql)
	}
	var max_count = "1000000-$sqlite_interrupt_count"
	_ = max_count // suppress unused warning
	var i = "1"
	_ = i // suppress unused warning
	for func() bool { i_n, _i_e := strconv.Atoi(i); if _i_e != nil { return false }; max_count_n, _max_count_e := strconv.Atoi(max_count); if _max_count_e != nil { return false }; return i_n < max_count_n-5 }() {
		{ // do_test "interrupt-4." + i + ".1"
			var _sqlite_interrupt_count = _i // TCL namespace variable
			_ = _sqlite_interrupt_count // suppress unused warning
			_res = db.Exec(sql)
			_ = _res // catchsql
		}
		// incr i 1
		{
			_n, _err := strconv.Atoi(i)
			if _err == nil {
				i = strconv.Itoa(_n + 1)
			}
		}
	}
	if false {
		{ // do_test "interrupt-5.1"
			// proc definition (not transpiled)
			_res = db.Exec("\n    CREATE INDEX fake ON fake1(a COLLATE fake_collation, b, c DESC);\n  ")
			_ = _res // catchsql
		}
	}
}
