// Code generated by tcl2go; DO NOT EDIT.
package bindxfer

import (
"github.com/pijalu/frigolite"
"testing"
)

func Test_bindxfer(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var vals string
	_ = vals // pre-declared from TCL source
	var cols string
	_ = cols // pre-declared from TCL source
	var rc string
	_ = rc // pre-declared from TCL source
	var i string
	_ = i // pre-declared from TCL source
	var DB string
	_ = DB // pre-declared from TCL source
	var VM1 string
	_ = VM1 // pre-declared from TCL source
	var VM2 string
	_ = VM2 // pre-declared from TCL source
	var sqlite_static_bind_value string
	_ = sqlite_static_bind_value // pre-declared from TCL source
	var VALUES string
	_ = VALUES // pre-declared from TCL source
	var Id_ string
	_ = Id_ // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source
	var VALS string
	_ = VALS // pre-declared from TCL source
	var COLS string
	_ = COLS // pre-declared from TCL source
	var stmt string
	_ = stmt // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	// proc definition (not transpiled)
	{ // do_test "bindxfer-1.1"
		DB = "sqlite3_connection_pointer db"
		_ = DB // suppress unused warning
		_res = db.Exec("CREATE TABLE t1(a,b,c);")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "CREATE TABLE t1(a,b,c);")
		}
		VM1 = "sqlite3_prepare $DB {SELECT ?, ?, ?} -1 TAIL"
		_ = VM1 // suppress unused warning
	}
	{ // do_test "bindxfer-1.2"
		// sqlite3_bind_parameter_count $VM1 (unsupported command, not transpiled)
	}
	{ // do_test "bindxfer-1.3"
		VM2 = "sqlite3_prepare $DB {SELECT ?, ?, ?} -1 TAIL"
		_ = VM2 // suppress unused warning
	}
	{ // do_test "bindxfer-1.4"
		// sqlite3_bind_parameter_count $VM2 (unsupported command, not transpiled)
	}
	{ // do_test "bindxfer-1.5"
		// sqlite_bind $VM1 1 one normal (unsupported command, not transpiled)
		sqlite_static_bind_value = "two"
		_ = sqlite_static_bind_value // suppress unused warning
		// sqlite_bind $VM1 2 {} static (unsupported command, not transpiled)
		// sqlite_bind $VM1 3 {} null (unsupported command, not transpiled)
		// sqlite3_transfer_bindings $VM1 $VM2 (unsupported command, not transpiled)
		// sqlite_step $VM1 VALUES COLNAMES (unsupported command, not transpiled)
	}
	{ // do_test "bindxfer-1.6"
	}
	{ // do_test "bindxfer-1.7"
		// sqlite_step $VM2 VALUES COLNAMES (unsupported command, not transpiled)
	}
	{ // do_test "bindxfer-1.8"
	}
	{
		var _catchErr error
		_ = _catchErr // suppress unused warning
		// sqlite3_finalize $VM1 (unsupported command, not transpiled)
	}
	{
		var _catchErr error
		_ = _catchErr // suppress unused warning
		// sqlite3_finalize $VM2 (unsupported command, not transpiled)
	}
}
