// Code generated by tcl2go; DO NOT EDIT.
package vacuum

import (
"github.com/pijalu/frigolite"
"os"
"testing"
)

func Test_vacuum2(t *testing.T) {
	db, err := frigolite.Open("")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	var _res *frigolite.Result
	var r *frigolite.Result
	var msg string
	_ = msg // suppress unused warning
	_ = _res // suppress unused warning
	_ = r    // suppress unused warning

	var db1 *frigolite.DB
	_ = db1
	var db2 *frigolite.DB
	_ = db2
	var db3 *frigolite.DB
	_ = db3
	var db4 *frigolite.DB
	_ = db4
	var db5 *frigolite.DB
	_ = db5
	var db6 *frigolite.DB
	_ = db6
	var db7 *frigolite.DB
	_ = db7
	var db8 *frigolite.DB
	_ = db8
	var db9 *frigolite.DB
	_ = db9

	var testdir string
	_ = testdir // pre-declared from TCL source
	var testprefix string
	_ = testprefix // pre-declared from TCL source
	var pageSize string
	_ = pageSize // pre-declared from TCL source
	var cksum string
	_ = cksum // pre-declared from TCL source
	var res string
	_ = res // pre-declared from TCL source
	var res2 string
	_ = res2 // pre-declared from TCL source
	var Id_ string
	_ = Id_ // pre-declared from TCL source
	var argv0 string
	_ = argv0 // pre-declared from TCL source
	var a string
	_ = a // pre-declared from TCL source
	var lhs string
	_ = lhs // pre-declared from TCL source
	var rhs string
	_ = rhs // pre-declared from TCL source

	// set testdir: test directory (not used in Go test context)
	testprefix = "vacuum2"
	_ = testprefix // suppress unused warning
	// do_not_use_codec (unsupported command, not transpiled)
	if tclBool(AUTOVACUUM) {
		return
	}
	{ // do_test "vacuum2-1.1"
		_res = db.Exec("\n    CREATE TABLE t1(x INTEGER PRIMARY KEY AUTOINCREMENT, y);\n    DROP TABLE t1;\n    VACUUM;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE TABLE t1(x INTEGER PRIMARY KEY AUTOINCREMENT, y);\n    DROP TABLE t1;\n    VACUUM;\n  ")
		}
	}
	{ // do_test "vacuum2-2.1"
		_res = db.Exec("\n    CREATE TABLE t1(x);\n    CREATE TABLE t2(y);\n    INSERT INTO t1 VALUES(1);\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    CREATE TABLE t1(x);\n    CREATE TABLE t2(y);\n    INSERT INTO t1 VALUES(1);\n  ")
		}
		// hexio_get_int [hexio_read test.db 24 4] (unsupported command, not transpiled)
	}
	{ // do_test "vacuum2-2.2"
		_res = db.Exec("\n    VACUUM\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    VACUUM\n  ")
		}
		// hexio_get_int [hexio_read test.db 24 4] (unsupported command, not transpiled)
	}
	db2, err = frigolite.Open("test.db")
	if err != nil { t.Fatal(err) }
	pageSize = "db eval {pragma page_size}"
	_ = pageSize // suppress unused warning
	{ // do_test "vacuum2-3.1"
		_res = db.Exec("\n    INSERT INTO t1 VALUES('hello');\n    INSERT INTO t2 VALUES('out there');\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    INSERT INTO t1 VALUES('hello');\n    INSERT INTO t2 VALUES('out there');\n  ")
		}
		// expr [file size test.db]/$pageSize → "[file size test.db]/$pageSize"
	}
	cksum = "cksum"
	_ = cksum // suppress unused warning
	{ // do_test "vacuum2-3.2"
		// cksum db2 (unsupported command, not transpiled)
	}
	{ // do_test "vacuum2-3.4"
		// cksum db2 (unsupported command, not transpiled)
	}
	{ // do_test "vacuum2-3.5"
		// cksum (unsupported command, not transpiled)
	}
	{ // do_test "vacuum2-3.6"
		r = db.Query("PRAGMA integrity_check")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "PRAGMA integrity_check")
		}
	}
	{ // do_test "vacuum2-3.7"
		r = db.Query("PRAGMA integrity_check")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "PRAGMA integrity_check")
		}
	}
	{ // do_test "vacuum2-3.13"
		_res = db.Exec("\n    PRAGMA auto_vacuum=NONE;\n    VACUUM;\n  ")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n    PRAGMA auto_vacuum=NONE;\n    VACUUM;\n  ")
		}
		// expr [file size test.db]/$pageSize → "[file size test.db]/$pageSize"
	}
	{ // do_test "vacuum2-3.14"
		// cksum db2 (unsupported command, not transpiled)
	}
	{ // do_test "vacuum2-3.15"
		// cksum (unsupported command, not transpiled)
	}
	{ // do_test "vacuum2-3.16"
		r = db.Query("PRAGMA integrity_check")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "PRAGMA integrity_check")
		}
	}
	{ // do_test "vacuum2-3.17"
		r = db.Query("PRAGMA integrity_check")
		if r.Error != nil {
			t.Errorf("query error: %v\n  sql: %s", r.Error, "PRAGMA integrity_check")
		}
	}
	db2.Close()
	os.Remove("test.db")
	_dbtmp0, err := frigolite.Open("test.db")
	_ = _dbtmp0 // sqlite3 db connection
	if err != nil { t.Fatal(err) }
	{ // "vacuum2-5.1"
		_res = db.Exec("\n  CREATE TABLE t1(a PRIMARY KEY, b UNIQUE);\n  INSERT INTO t1 VALUES(1, randomblob(500));\n  INSERT INTO t1 SELECT a+1, randomblob(500) FROM t1;      -- 2\n  INSERT INTO t1 SELECT a+2, randomblob(500) FROM t1;      -- 4 \n  INSERT INTO t1 SELECT a+4, randomblob(500) FROM t1;      -- 8 \n  INSERT INTO t1 SELECT a+8, randomblob(500) FROM t1;      -- 16 \n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE t1(a PRIMARY KEY, b UNIQUE);\n  INSERT INTO t1 VALUES(1, randomblob(500));\n  INSERT INTO t1 SELECT a+1, randomblob(500) FROM t1;      -- 2\n  INSERT INTO t1 SELECT a+2, randomblob(500) FROM t1;      -- 4 \n  INSERT INTO t1 SELECT a+4, randomblob(500) FROM t1;      -- 8 \n  INSERT INTO t1 SELECT a+8, randomblob(500) FROM t1;      -- 16 \n")
		}
	}
	{ // do_test "vacuum2-5.2"
		_list := tclList([]string{"0", msg})
		_ = _list
	}
	{ // do_test "vacuum2-5.3"
		_list := tclList([]string{"0", msg})
		_ = _list
	}
	{ // do_test "vacuum2-5.4"
		res = ""
		_ = res // suppress unused warning
		res2 = ""
		_ = res2 // suppress unused warning
		_res = db.Exec("SELECT a, b FROM t1 WHERE a<=10")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "SELECT a, b FROM t1 WHERE a<=10")
		}
		res2 = tclListAppend(res2, res)
	}
	// proc definition (not transpiled)
	{ // "6.0"
		_res = db.Exec("\n  CREATE TABLE t6(x PRIMARY KEY COLLATE cmp, y) WITHOUT ROWID;\n  CREATE INDEX t6y ON t6(y);\n  INSERT INTO t6 VALUES('i', 'one');\n  INSERT INTO t6 VALUES('ii', 'one');\n  INSERT INTO t6 VALUES('iii', 'one');\n")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "\n  CREATE TABLE t6(x PRIMARY KEY COLLATE cmp, y) WITHOUT ROWID;\n  CREATE INDEX t6y ON t6(y);\n  INSERT INTO t6 VALUES('i', 'one');\n  INSERT INTO t6 VALUES('ii', 'one');\n  INSERT INTO t6 VALUES('iii', 'one');\n")
		}
	}
	_res = db.Exec("PRAGMA integrity_check")
	if _res.Error != nil { t.Errorf("integrity check: %v", _res.Error) }
	// proc definition (not transpiled)
	{ // "6.2"
		_res = db.Exec("VACUUM")
		if _res.Error != nil {
			t.Errorf("exec error: %v\n  sql: %s", _res.Error, "VACUUM")
		}
	}
	_res = db.Exec("PRAGMA integrity_check")
	if _res.Error != nil { t.Errorf("integrity check: %v", _res.Error) }
}
